"""Sillabus servis qatı — modulun YEGANƏ yazı/oxu giriş nöqtəsi.

View, API və management əmrləri buradan istifadə edir; modelə birbaşa
``status = ...`` yazan kod OLMAMALIDIR (state maşını
:mod:`apps.syllabus.state_machine`-dədir).
"""

from .coverage import (  # noqa: F401
    GROUP_CHAIR,
    GROUP_PROGRAM,
    coverage_breakdown,
    coverage_report,
    coverage_trend,
    has_review_scope,
    review_scope_queryset,
)
from .drafts import (  # noqa: F401
    SectionConflict,
    assess_split_is_valid,
    blank_section_data,
    copy_from_previous,
    create_draft,
    create_next_version,
    import_migrated_version,
    recompute_completion,
    refresh_pointers,
    resolve_pointer_versions,
    save_section,
    section_data_map,
    set_plan_hours,
)
from .offerings import (  # noqa: F401
    ACTION_STATES,
    STATE_APPROVED,
    STATE_ARCHIVED,
    STATE_DRAFT,
    STATE_MISSING,
    STATE_PENDING,
    STATE_REJECTED,
    STATE_REVISION,
    approved_version_for,
    offering_syllabus_state,
    syllabus_for_offering,
)
from .queries import (  # noqa: F401
    QUEUE_SORT_KEYS,
    audit_entries,
    list_syllabi,
    review_queue,
    status_counts,
    version_diff,
    version_timeline,
)
from .scoping import SyllabusActor, can_view, has_decision_scope, is_author, resolve_actor  # noqa: F401
from .versioning import (  # noqa: F401
    ESCALATION_CODE,
    STRUCTURAL_SECTIONS,
    classify,
    escalate_if_structural,
    structural_changes,
)
from .workflow import (  # noqa: F401
    approve,
    archive,
    available_actions,
    reject,
    request_revision,
    resume_editing,
    start_review,
    submit,
    withdraw,
)

__all__ = [
    "ACTION_STATES",
    "ESCALATION_CODE",
    "GROUP_CHAIR",
    "GROUP_PROGRAM",
    "QUEUE_SORT_KEYS",
    "STATE_APPROVED",
    "STATE_ARCHIVED",
    "STATE_DRAFT",
    "STATE_MISSING",
    "STATE_PENDING",
    "STATE_REJECTED",
    "STATE_REVISION",
    "STRUCTURAL_SECTIONS",
    "SectionConflict",
    "SyllabusActor",
    "approve",
    "approved_version_for",
    "archive",
    "audit_entries",
    "available_actions",
    "blank_section_data",
    "assess_split_is_valid",
    "can_view",
    "classify",
    "copy_from_previous",
    "coverage_breakdown",
    "coverage_report",
    "coverage_trend",
    "create_draft",
    "create_next_version",
    "escalate_if_structural",
    "has_decision_scope",
    "has_review_scope",
    "import_migrated_version",
    "is_author",
    "list_syllabi",
    "offering_syllabus_state",
    "recompute_completion",
    "reject",
    "request_revision",
    "resolve_actor",
    "resume_editing",
    "review_queue",
    "review_scope_queryset",
    "save_section",
    "section_data_map",
    "set_plan_hours",
    "start_review",
    "structural_changes",
    "status_counts",
    "submit",
    "syllabus_for_offering",
    "version_diff",
    "version_timeline",
    "withdraw",
]
