"""Sillabus servis qatı — modulun YEGANƏ yazı/oxu giriş nöqtəsi.

View, API və management əmrləri buradan istifadə edir; modelə birbaşa
``status = ...`` yazan kod OLMAMALIDIR (state maşını
:mod:`apps.syllabus.state_machine`-dədir).
"""

from . import reuse, reuse_rules, reuse_sync  # noqa: F401 — təkrar istifadə (bağla/kopyala/sinxron), 2026-10-08
from .coverage import (  # noqa: F401
    GROUP_CHAIR,
    GROUP_PROGRAM,
    coverage_breakdown,
    coverage_report,
    coverage_trend,
    has_review_scope,
    review_scope_queryset,
)
from .drafts import (  # noqa: F401
    SectionConflict,
    assess_split_is_valid,
    blank_section_data,
    copy_from_previous,
    create_draft,
    create_next_version,
    import_migrated_version,
    open_version_for,
    recompute_completion,
    refresh_pointers,
    resolve_pointer_versions,
    save_section,
    section_data_map,
)
from .offerings import (  # noqa: F401
    ACTION_STATES,
    STATE_APPROVED,
    STATE_ARCHIVED,
    STATE_DRAFT,
    STATE_MISSING,
    STATE_PENDING,
    STATE_REJECTED,
    STATE_REVISION,
    approved_version_for,
    offering_syllabus_state,
    preload_syllabus_for_offering,
    syllabus_for_offering,
    syllabus_for_offering_obj,
)
from .plan_hours import seed_week_hours, set_plan_hours  # noqa: F401
from .queries import (  # noqa: F401
    QUEUE_SORT_KEYS,
    audit_entries,
    has_broad_view_scope,
    list_syllabi,
    own_q,
    review_queue,
    status_counts,
    version_diff,
    version_timeline,
)
from .reuse import ReuseTarget  # noqa: F401
from .reuse_rules import hours_match, normalize_hours, reuse_origin, sibling_queryset  # noqa: F401
from .scoping import (  # noqa: F401
    SyllabusActor,
    can_view,
    has_decision_scope,
    has_escalated_decision_scope,
    is_author,
    is_self_authored_by_decider,
    resolve_actor,
)
from .section_shape import SectionShapeError, normalize_section_data  # noqa: F401
from .versioning import (  # noqa: F401
    ESCALATION_CODE,
    STRUCTURAL_SECTIONS,
    classify,
    escalate_if_structural,
    structural_changes,
)
from .workflow import (  # noqa: F401
    approve,
    archive,
    available_actions,
    reject,
    request_revision,
    resume_editing,
    start_review,
    submit,
    withdraw,
)

__all__ = [
    "ACTION_STATES",
    "ESCALATION_CODE",
    "GROUP_CHAIR",
    "GROUP_PROGRAM",
    "QUEUE_SORT_KEYS",
    "ReuseTarget",
    "STATE_APPROVED",
    "STATE_ARCHIVED",
    "STATE_DRAFT",
    "STATE_MISSING",
    "STATE_PENDING",
    "STATE_REJECTED",
    "STATE_REVISION",
    "STRUCTURAL_SECTIONS",
    "SectionConflict",
    "SectionShapeError",
    "SyllabusActor",
    "approve",
    "approved_version_for",
    "archive",
    "audit_entries",
    "available_actions",
    "blank_section_data",
    "assess_split_is_valid",
    "can_view",
    "classify",
    "copy_from_previous",
    "coverage_breakdown",
    "coverage_report",
    "coverage_trend",
    "create_draft",
    "create_next_version",
    "escalate_if_structural",
    "has_decision_scope",
    "has_escalated_decision_scope",
    "has_broad_view_scope",
    "has_review_scope",
    "hours_match",
    "import_migrated_version",
    "is_author",
    "is_self_authored_by_decider",
    "list_syllabi",
    "normalize_hours",
    "offering_syllabus_state",
    "open_version_for",
    "own_q",
    "recompute_completion",
    "reject",
    "request_revision",
    "resolve_actor",
    "resume_editing",
    "reuse",
    "reuse_origin",
    "reuse_rules",
    "reuse_sync",
    "review_queue",
    "review_scope_queryset",
    "save_section",
    "seed_week_hours",
    "section_data_map",
    "set_plan_hours",
    "sibling_queryset",
    "start_review",
    "structural_changes",
    "status_counts",
    "submit",
    "preload_syllabus_for_offering",
    "syllabus_for_offering",
    "syllabus_for_offering_obj",
    "version_diff",
    "version_timeline",
    "withdraw",
]
