# Generated by Django 5.2.8 on 2026-02-07 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Kurs İşi Adı"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                ("start_date", models.DateTimeField(verbose_name="Başlanğıc tarixi")),
                ("deadline", models.DateTimeField(verbose_name="Son tarix")),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Maksimum cəhd"
                    ),
                ),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Maksimum bal"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("inactive", "Deaktiv"),
                            ("archived", "Arxivləndi"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="student_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tələbələr",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs İşi",
                "verbose_name_plural": "Kurs İşləri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Cavab / İzahat")),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="projects/submissions/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("graded", "Qiymətləndirilib"),
                            ("rejected", "Rədd edilib"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "grade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_project_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="projects.project",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
