# Generated by Django 5.2.12 on 2026-03-24 09:11

import core.upload_security
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("start_date", models.DateTimeField(verbose_name="start_date")),
                ("deadline", models.DateTimeField(verbose_name="deadline")),
                ("max_attempts", models.PositiveIntegerField(default=1, verbose_name="max_attempts")),
                ("max_score", models.PositiveIntegerField(default=100, verbose_name="max_score")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("inactive", "inactive"), ("archived", "archived")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="student_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned_students",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(verbose_name="content")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="projects/submissions/",
                        validators=[core.upload_security.FileUploadValidator()],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "pending"), ("graded", "graded"), ("rejected", "rejected")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("grade", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("feedback", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_project_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="projects.project"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
