# Generated by Django 5.2.8 on 2026-03-01 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_grading_type_course_organization_id_and_more"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"], "verbose_name": "singular", "verbose_name_plural": "plural"},
        ),
        migrations.AlterModelOptions(
            name="projectsubmission",
            options={"ordering": ["-submitted_at"], "verbose_name": "singular", "verbose_name_plural": "plural"},
        ),
        migrations.AlterField(
            model_name="project",
            name="assigned_students",
            field=models.ManyToManyField(
                blank=True,
                related_name="student_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="assigned_students",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="courses.course",
                verbose_name="course",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="deadline",
            field=models.DateTimeField(verbose_name="deadline"),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="project",
            name="max_attempts",
            field=models.PositiveIntegerField(default=1, verbose_name="max_attempts"),
        ),
        migrations.AlterField(
            model_name="project",
            name="max_score",
            field=models.PositiveIntegerField(default=100, verbose_name="max_score"),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateTimeField(verbose_name="start_date"),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("active", "active"), ("inactive", "inactive"), ("archived", "archived")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=255, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="projectsubmission",
            name="content",
            field=models.TextField(verbose_name="content"),
        ),
        migrations.AlterField(
            model_name="projectsubmission",
            name="status",
            field=models.CharField(
                choices=[("pending", "pending"), ("graded", "graded"), ("rejected", "rejected")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
