# Generated by Django 5.2.8 on 2026-03-15 20:13

import core.upload_security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsubmission",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="projects/submissions/",
                validators=[core.upload_security.FileUploadValidator()],
            ),
        ),
    ]
