"""Dərs yükü servisləri — modulun YEGANƏ yazma/oxuma girişi."""

from .amendments import amendment_history, open_amendment
from .assignments import assign_teacher, balance_for_rows, remaining_hours, unassign
from .curriculum_import import chair_specialty_ids, curriculum_row_suggestions
from .distribution import confirm_distribution, distribution_readiness, sync_offerings
from .generation import generate_rows_from_plan, plan_preview
from .imports import ImportFileError, apply_import, build_mapping, parse_workbook
from .objections import (
    chair_objections,
    confirm_own_load,
    create_objection,
    ensure_can_object,
    is_load_confirmed,
    my_objections,
    resolve_objection,
)
from .overview import build_overview, load_band
from .people import (
    chair_teacher_memberships,
    ensure_assignable_teacher,
    is_assignable_teacher,
    resolve_chair,
    teacher_pool,
)
from .queries import (
    chair_tasks,
    serialize_rows,
    task_rows,
    teacher_load_panel,
    teacher_workload_rows,
    teacher_workload_summary,
    teacher_years,
)
from .reviews import (
    coordinator_specialty_ids,
    ensure_can_review_row,
    review_all,
    review_counts,
    review_queue,
    row_remarks,
    set_row_review,
)
from .scoping import (
    WorkloadActor,
    WorkloadDenied,
    can_distribute_chair,
    can_manage_chair,
    can_report,
    can_view_task,
    ensure_can_distribute,
    ensure_can_manage,
    ensure_can_view,
    manageable_chairs,
    resolve_actor,
)
from .tasks import (
    delete_row,
    find_task,
    get_or_create_task,
    list_years,
    normalize_academic_year,
    resolve_specialty_and_faculty,
    row_warnings,
    save_row,
)
from .workflow import (
    approve_slice,
    ensure_can_approve,
    ensure_can_submit,
    ensure_distribution_stage,
    ensure_reason,
    recompute_task_status,
    return_slice,
    slice_progress,
    submit_summary,
    submit_task,
    task_faculty_ids,
    unrouted_rows,
)

__all__ = [
    "ImportFileError",
    "WorkloadActor",
    "WorkloadDenied",
    "amendment_history",
    "apply_import",
    "approve_slice",
    "assign_teacher",
    "balance_for_rows",
    "build_mapping",
    "build_overview",
    "can_distribute_chair",
    "can_manage_chair",
    "can_report",
    "can_view_task",
    "chair_objections",
    "chair_specialty_ids",
    "chair_tasks",
    "chair_teacher_memberships",
    "confirm_distribution",
    "confirm_own_load",
    "coordinator_specialty_ids",
    "create_objection",
    "curriculum_row_suggestions",
    "delete_row",
    "distribution_readiness",
    "ensure_assignable_teacher",
    "ensure_can_approve",
    "ensure_can_distribute",
    "ensure_can_manage",
    "ensure_can_object",
    "ensure_can_review_row",
    "ensure_can_submit",
    "ensure_can_view",
    "ensure_distribution_stage",
    "ensure_reason",
    "find_task",
    "generate_rows_from_plan",
    "get_or_create_task",
    "is_assignable_teacher",
    "is_load_confirmed",
    "list_years",
    "load_band",
    "manageable_chairs",
    "my_objections",
    "normalize_academic_year",
    "open_amendment",
    "parse_workbook",
    "plan_preview",
    "recompute_task_status",
    "remaining_hours",
    "resolve_actor",
    "resolve_chair",
    "resolve_objection",
    "resolve_specialty_and_faculty",
    "return_slice",
    "review_all",
    "review_counts",
    "review_queue",
    "row_remarks",
    "row_warnings",
    "save_row",
    "serialize_rows",
    "set_row_review",
    "slice_progress",
    "submit_summary",
    "submit_task",
    "sync_offerings",
    "task_faculty_ids",
    "task_rows",
    "teacher_load_panel",
    "teacher_pool",
    "teacher_workload_rows",
    "teacher_workload_summary",
    "teacher_years",
    "unassign",
    "unrouted_rows",
]
