# Generated by Django 5.2.12 on 2026-03-24 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email OTP",
                "verbose_name_plural": "Email OTPs",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "requested_organization_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Təşkilat DB-də yoxdursa signup zamanı daxil edilən ad",
                        max_length=255,
                        verbose_name="Müraciət edilən təşkilat adı",
                    ),
                ),
                (
                    "requested_organization_message",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tələbənin təşkilata qoşulma üçün yazdığı qısa mesaj",
                        max_length=280,
                        verbose_name="Təşkilata müraciət mesajı",
                    ),
                ),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("university", "university"),
                            ("school", "school"),
                            ("course_center", "course_center"),
                            ("individual", "individual"),
                        ],
                        default="individual",
                        help_text="Hansı təşkilat tipində qeydiyyatdan keçdiniz",
                        max_length=20,
                        verbose_name="Təşkilat tipi",
                    ),
                ),
                ("country", models.CharField(blank=True, default="", max_length=100, verbose_name="Ölkə")),
                (
                    "student_university_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tələbə üçün universitet adı (əgər varsa)",
                        max_length=255,
                        verbose_name="Universitet adı",
                    ),
                ),
                (
                    "student_school_identifier",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tələbə üçün məktəb nömrəsi və ya rəsmi identifikator",
                        max_length=120,
                        verbose_name="Məktəb nömrəsi/identifikatoru",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Super Admin"),
                            ("org_owner", "Təşkilat Sahibi"),
                            ("org_admin", "Təşkilat Admini"),
                            ("member", "Üzv"),
                            ("hr", "HR"),
                            ("teacher", "Müəllim"),
                            ("assistant_teacher", "Müəllim Köməkçisi"),
                            ("lead_student", "Baş Tələbə"),
                            ("student", "Tələbə"),
                        ],
                        db_index=True,
                        default="member",
                        help_text="İstifadəçinin sistəmdəki rolu",
                        max_length=30,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, help_text="Profil şəkli", null=True, upload_to="avatars/", verbose_name="Avatar"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, help_text="Əlaqə nömrəsi", max_length=20, verbose_name="Telefon"),
                ),
                ("bio", models.TextField(blank=True, help_text="Qısa məlumat", verbose_name="Haqqında")),
                (
                    "supervisor_code",
                    models.CharField(
                        blank=True,
                        help_text="Admin/supervisor tərəfindən təyin edilir. User dəyişə bilməz.",
                        max_length=50,
                        verbose_name="Nəzarətçi kodu",
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, help_text="Şəhər və ya ünvan", max_length=100, verbose_name="Yer"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Yaradılma tarixi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Yenilənmə tarixi")),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="İstifadəçinin aid olduğu təşkilat",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="organizations.organization",
                        verbose_name="Təşkilat",
                    ),
                ),
                (
                    "requested_organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Signup zamanı seçilən, amma hələ qoşulmadığı təşkilat",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_members",
                        to="organizations.organization",
                        verbose_name="Müraciət edilən təşkilat",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="profile", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "İstifadəçi profili",
                "verbose_name_plural": "İstifadəçi profilləri",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["organization", "created_at"], name="accounts_us_organiz_b2bf44_idx"),
                    models.Index(fields=["role"], name="accounts_us_role_e16858_idx"),
                    models.Index(fields=["requested_organization"], name="accounts_us_request_9a72ac_idx"),
                ],
            },
        ),
    ]
