# Generated by Django 5.2.8 on 2026-02-13 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("university", "University"),
                            ("school", "School"),
                            ("course_center", "Course Center"),
                            ("individual", "Individual"),
                        ],
                        default="individual",
                        help_text="Hansı təşkilat tipində qeydiyyatdan keçdiniz",
                        max_length=20,
                        verbose_name="Təşkilat tipi",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Profil şəkli",
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Əlaqə nömrəsi",
                        max_length=20,
                        verbose_name="Telefon",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Qısa məlumat", verbose_name="Haqqında"
                    ),
                ),
                (
                    "supervisor_code",
                    models.CharField(
                        blank=True,
                        help_text="Admin/supervisor tərəfindən təyin edilir. User dəyişə bilməz.",
                        max_length=50,
                        verbose_name="Nəzarətçi kodu",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Şəhər və ya ünvan",
                        max_length=100,
                        verbose_name="Yer",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə tarixi"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "İstifadəçi profili",
                "verbose_name_plural": "İstifadəçi profilləri",
                "ordering": ["-created_at"],
            },
        ),
    ]
