# Generated by Django 5.2.12 on 2026-03-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Müəllim və ya işçinin departamenti/kafedrası",
                max_length=255,
                verbose_name="Departament / Kafedra",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="staff_position",
            field=models.CharField(
                blank=True,
                default="",
                help_text="İşçinin vəzifəsi (yalnız staff üçün)",
                max_length=255,
                verbose_name="Vəzifə",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="student_group_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tələbənin qrup nömrəsi və ya sinif qrupu",
                max_length=100,
                verbose_name="Qrup / Sinif",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="student_specialization",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tələbənin ixtisası və ya fakültəsi",
                max_length=255,
                verbose_name="İxtisas / Fakültə",
            ),
        ),
    ]
