# Generated by Django 5.2.8 on 2026-02-14 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="İstifadəçinin aid olduğu təşkilat",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="organizations.organization",
                verbose_name="Təşkilat",
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["organization", "created_at"],
                name="accounts_us_organiz_b2bf44_idx",
            ),
        ),
    ]
