# Generated by Django 5.2.12 on 2026-04-05 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_emailotp_email(apps, schema_editor):
    EmailOTP = apps.get_model("accounts", "EmailOTP")
    for otp in EmailOTP.objects.select_related("user").filter(email="").exclude(user__isnull=True):
        otp.email = (getattr(otp.user, "email", "") or "").strip().lower()
        otp.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_persona_profile_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emailotp",
            name="attempts_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="emailotp",
            name="email",
            field=models.EmailField(blank=True, db_index=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="emailotp",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailotp",
            name="otp_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="emailotp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("signup", "Signup verification"),
                    ("login", "Login verification"),
                    ("password_reset", "Password reset"),
                    ("admin_login", "Admin login"),
                ],
                db_index=True,
                default="signup",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="code",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_otps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="emailotp",
            index=models.Index(fields=["email", "purpose", "created_at"], name="accounts_em_email_c46531_idx"),
        ),
        migrations.AddIndex(
            model_name="emailotp",
            index=models.Index(fields=["user", "purpose", "created_at"], name="accounts_em_user_id_1533d7_idx"),
        ),
        migrations.RunPython(backfill_emailotp_email, migrations.RunPython.noop),
    ]
