# Generated by Django 5.2.8 on 2026-02-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Ölkə"),
        ),
    ]
