# Generated by Django 5.2.13 on 2026-04-11 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_emailotp_attempts_count_emailotp_email_and_more"),
        ("organizations", "0004_expand_rls_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Hesabın silinmə tarixi", null=True, verbose_name="Silinmə tarixi"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, help_text="Hesab silinibsə True", verbose_name="Silinib"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["is_deleted", "deleted_at"], name="accounts_us_is_dele_9bf4cd_idx"),
        ),
    ]
