# Generated by Django 5.2.8 on 2026-02-14 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_country'),
        ('organizations', '0002_organization_country_organization_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('org_owner', 'Təşkilat Sahibi'), ('org_admin', 'Təşkilat Admini'), ('teacher', 'Müəllim'), ('assistant_teacher', 'Müəllim Köməkçisi'), ('lead_student', 'Baş Tələbə'), ('student', 'Tələbə')], db_index=True, default='student', help_text='İstifadəçinin sistəmdəki rolu', max_length=30, verbose_name='Rol'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='accounts_us_role_e16858_idx'),
        ),
    ]
