# Generated by Django 5.2.8 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_role_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="student_school_identifier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tələbə üçün məktəb nömrəsi və ya rəsmi identifikator",
                max_length=120,
                verbose_name="Məktəb nömrəsi/identifikatoru",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="student_university_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tələbə üçün universitet adı (əgər varsa)",
                max_length=255,
                verbose_name="Universitet adı",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("org_owner", "Təşkilat Sahibi"),
                    ("org_admin", "Təşkilat Admini"),
                    ("member", "Üzv"),
                    ("hr", "HR"),
                    ("teacher", "Müəllim"),
                    ("assistant_teacher", "Müəllim Köməkçisi"),
                    ("lead_student", "Baş Tələbə"),
                    ("student", "Tələbə"),
                ],
                db_index=True,
                default="member",
                help_text="İstifadəçinin sistəmdəki rolu",
                max_length=30,
                verbose_name="Rol",
            ),
        ),
    ]
