# Generated by Django 5.2.8 on 2026-02-19 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_student_references_and_hr_role"),
        ("organizations", "0005_seed_additional_azerbaijan_universities"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="requested_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Signup zamanı seçilən, amma hələ qoşulmadığı təşkilat",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_members",
                to="organizations.organization",
                verbose_name="Müraciət edilən təşkilat",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="requested_organization_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Təşkilat DB-də yoxdursa signup zamanı daxil edilən ad",
                max_length=255,
                verbose_name="Müraciət edilən təşkilat adı",
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["requested_organization"], name="accounts_us_request_9a72ac_idx"),
        ),
    ]
