# Generated by Django 5.2.15 on 2026-07-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_userprofile_role_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_verified",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="İlk girişdə OTP ilə təsdiqləndikdən sonra True; parol bərpası üçün istifadə olunur.",
                verbose_name="Email təsdiqlənib",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="password_change_required",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="İlk girişdə istifadəçi öz parolunu qurana qədər True qalır.",
                verbose_name="Parol dəyişməlidir",
            ),
        ),
    ]
