# Generated by Django 5.2.15 on 2026-07-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_userprofile_email_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_manage_exam_rooms",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Superadmin verir: imtahan zalı və kompüter/MAC qeydlərini idarə etmək icazəsi.",
                verbose_name="Zal idarəçisi",
            ),
        ),
    ]
