# Generated by Django 5.2.8 on 2026-03-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_userprofile_requested_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("university", "university"),
                    ("school", "school"),
                    ("course_center", "course_center"),
                    ("individual", "individual"),
                ],
                default="individual",
                help_text="Hansı təşkilat tipində qeydiyyatdan keçdiniz",
                max_length=20,
                verbose_name="Təşkilat tipi",
            ),
        ),
    ]
