# Generated by Django 5.2.8 on 2026-03-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_userprofile_organization_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="requested_organization_message",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tələbənin təşkilata qoşulma üçün yazdığı qısa mesaj",
                max_length=280,
                verbose_name="Təşkilata müraciət mesajı",
            ),
        ),
    ]
