# Generated by Django 5.2.13 on 2026-07-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("org_owner", "Təşkilat Sahibi"),
                    ("org_admin", "Təşkilat Admini"),
                    ("member", "Üzv"),
                    ("hr", "HR"),
                    ("exam_center_head", "İmtahan Mərkəzi Rəhbəri"),
                    ("exam_center_staff", "İmtahan Mərkəzi İşçisi"),
                    ("exam_center", "İmtahan Mərkəzi"),
                    ("ikt_rehber", "İKT Rəhbəri"),
                    ("teacher", "Müəllim"),
                    ("assistant_teacher", "Müəllim Köməkçisi"),
                    ("lead_student", "Baş Tələbə"),
                    ("student", "Tələbə"),
                ],
                db_index=True,
                default="member",
                help_text="Denormalizə keş — əsl rol Membership.role-dadır",
                max_length=30,
                verbose_name="Rol",
            ),
        ),
    ]
