# Generated by Django 5.2.15 on 2026-07-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "superadmin"),
                    ("org_owner", "org_owner"),
                    ("org_admin", "org_admin"),
                    ("member", "member"),
                    ("hr", "hr"),
                    ("exam_center_head", "exam_center_head"),
                    ("exam_center_staff", "exam_center_staff"),
                    ("exam_center", "exam_center"),
                    ("ikt_rehber", "ikt_rehber"),
                    ("teacher", "teacher"),
                    ("assistant_teacher", "assistant_teacher"),
                    ("lead_student", "lead_student"),
                    ("student", "student"),
                ],
                db_index=True,
                default="member",
                help_text="Denormalizə keş — əsl rol Membership.role-dadır",
                max_length=30,
                verbose_name="Rol",
            ),
        ),
    ]
