# Generated by Django 5.2.13 on 2026-08-14 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_userprofile_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="academic_degree",
            field=models.CharField(
                blank=True,
                choices=[("phd", "Fəlsəfə doktoru (PhD)"), ("dsc", "Elmlər doktoru")],
                default="",
                help_text="Fəlsəfə doktoru (PhD) və ya elmlər doktoru",
                max_length=30,
                verbose_name="Elmi dərəcə",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="academic_title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assistant", "Assistent"),
                    ("teacher", "Müəllim"),
                    ("senior_teacher", "Baş müəllim"),
                    ("docent", "Dosent"),
                    ("professor", "Professor"),
                ],
                default="",
                help_text="Müəllim/akademik heyət üçün: assistent → professor",
                max_length=30,
                verbose_name="Elmi ad / vəzifə",
            ),
        ),
        migrations.CreateModel(
            name="AcademicProfileItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("subject", "Tədris etdiyi fənn"),
                            ("certificate", "Sertifikat"),
                            ("publication", "Məqalə"),
                            ("conference", "Konfrans materialı"),
                        ],
                        max_length=20,
                        verbose_name="Növ",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlıq")),
                (
                    "detail",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Jurnal/konfrans adı, verən qurum, kafedra və s.",
                        max_length=255,
                        verbose_name="Ətraflı",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="İl")),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="DOI / sertifikat / nəşr keçidi (http-https)",
                        max_length=300,
                        verbose_name="Keçid",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Akademik fəaliyyət qeydi",
                "verbose_name_plural": "Akademik fəaliyyət qeydləri",
                "ordering": ["kind", "-year", "-id"],
                "indexes": [models.Index(fields=["user", "kind"], name="accounts_ac_user_id_a0af9f_idx")],
            },
        ),
    ]
