# Generated by Django 5.2.13 on 2026-08-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_userprofile_academic_degree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_secondary",
            field=models.CharField(
                blank=True,
                default="",
                help_text="İkinci əlaqə nömrəsi. Nömrələr yalnız əməkdaş səviyyəli baxanlara göstərilir.",
                max_length=20,
                verbose_name="Əlavə telefon",
            ),
        ),
    ]
