# Generated by Django 5.2.17 on 2026-08-25 11:17

"""UserProfile.fin — şəxsiyyət vəsiqəsi FİN kodu (idxal/uzlaşdırma açarı).

Ops qeydi: böyük production ``accounts_userprofile`` cədvəlində unikal index
qurulması cədvəli kilidləyir; EMSArena-nın cari miqyasında bu əhəmiyyətsizdir.
Geri dönüş = adi ``RemoveField``; data migration, trigger, RLS dəyişikliyi yoxdur —
yalnız SQLite-a məxsus schema-repair var: table remake 0013-ün raw canonical
indeksini itirdiyi üçün RunPython onu hər iki istiqamətdə bərpa edir.
"""

from django.db import migrations, models

import core.validators

STUDENT_INDEX = "accounts_student_ident_canon_uniq"


def reinstall_sqlite_student_index(_apps, schema_editor):
    """SQLite-də ``AddField(unique=True)`` cədvəli yenidən qurur (``_remake_table``)
    və 0013-ün raw canonical indeksini (``accounts_student_ident_canon_uniq``)
    itirir; onu eynilə bərpa et. PostgreSQL-də ``ALTER TABLE`` indeksə
    toxunmur — heç nə etmə."""
    if schema_editor.connection.vendor != "sqlite":
        return
    quote = schema_editor.quote_name
    identifier = quote("institutional_identifier")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"DROP INDEX IF EXISTS {quote(STUDENT_INDEX)}")
        cursor.execute(
            f"CREATE UNIQUE INDEX {quote(STUDENT_INDEX)} "
            f"ON {quote('accounts_userprofile')} "
            f"({quote('organization_id')}, LOWER(TRIM({identifier}))) "
            f"WHERE {quote('organization_id')} IS NOT NULL "
            f"AND TRIM({identifier}) <> ''"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_identity_staging_and_canonical_guards"),
    ]

    operations = [
        # Geriyə miqrasiyada RemoveField-in remake-i indeksi yenidən itirir;
        # bu no-op-un reverse-i backward istiqamətdə SONDA işləyib onu bərpa edir.
        migrations.RunPython(migrations.RunPython.noop, reinstall_sqlite_student_index),
        migrations.AddField(
            model_name="userprofile",
            name="fin",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Şəxsiyyət vəsiqəsi FİN kodu (7 simvol, A-Z0-9) — idxal/uzlaşdırma açarı.",
                max_length=7,
                null=True,
                unique=True,
                validators=[core.validators.validate_fin],
                verbose_name="FİN",
            ),
        ),
        migrations.RunPython(reinstall_sqlite_student_index, migrations.RunPython.noop),
    ]
