# Generated by Django 5.2.17 on 2026-08-26 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

#: 0013-ün qurduğu raw kanonik indeks — SQLite ``AddField`` cədvəli yenidən
#: qurduğu (``_remake_table``) üçün bu miqrasiyada da itir və bərpa olunmalıdır
#: (eyni resept 0014-dədir).
STUDENT_INDEX = "accounts_student_ident_canon_uniq"


def reinstall_sqlite_student_index(_apps, schema_editor):
    """SQLite-də itən 0013 indeksini eynilə bərpa et; PostgreSQL-də no-op."""

    if schema_editor.connection.vendor != "sqlite":
        return
    quote = schema_editor.quote_name
    identifier = quote("institutional_identifier")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"DROP INDEX IF EXISTS {quote(STUDENT_INDEX)}")
        cursor.execute(
            f"CREATE UNIQUE INDEX {quote(STUDENT_INDEX)} "
            f"ON {quote('accounts_userprofile')} "
            f"({quote('organization_id')}, LOWER(TRIM({identifier}))) "
            f"WHERE {quote('organization_id')} IS NOT NULL "
            f"AND TRIM({identifier}) <> ''"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_userprofile_fin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Geriyə miqrasiyada RemoveField remake-i indeksi yenidən itirir;
        # bu no-op-un reverse-i backward istiqamətdə SONDA onu bərpa edir.
        migrations.RunPython(migrations.RunPython.noop, reinstall_sqlite_student_index),
        migrations.AddField(
            model_name="userprofile",
            name="block_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="RİM operatorunun yazdığı səbəb",
                max_length=300,
                verbose_name="Bloklanma səbəbi",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="blocked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Bloklanma tarixi"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="blocked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Hesabı bloklayan RİM operatoru",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rim_blocked_profiles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Bloklayan",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Hesabı soft-delete edən RİM operatoru",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rim_deleted_profiles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Silən",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="deletion_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="RİM operatorunun yazdığı səbəb",
                max_length=300,
                verbose_name="Silinmə səbəbi",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="patronymic",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Ad+soyad eyni olan hesabları ayırd etmək üçün (RİM axtarışı).",
                max_length=100,
                verbose_name="Ata adı",
            ),
        ),
        migrations.RunPython(reinstall_sqlite_student_index, migrations.RunPython.noop),
    ]
