# Generated by Django 5.2.17 on 2026-08-30 05:26

"""UserProfile.gender + UserProfile.birth_date — kataloq demoqrafiya filtrləri.

Niyə: müəllim/tələbə kataloqu «cinsə görə» və «yaşa görə» filtr tələb edir,
hədəfdə isə belə sütun yox idi.  Hər ikisi fail-closed sentinel ilə gəlir —
``gender='unspecified'`` və ``birth_date IS NULL``: mənbədə dəyər yoxdursa və
ya pozuqdursa təxmin EDİLMİR (bax ``legacy_import.services.legacy_demographics``).

Ops qeydi: iki ``AddField`` + iki adi B-tree indeks; PostgreSQL-də
``ALTER TABLE ... ADD COLUMN`` sabit default ilə cədvəli yenidən yazmır.
``0013``-ün ``accounts_reject_active_staged_profile_trg`` trigger-i bu sətirlərə
də dəyir, amma yalnız ``access_state`` keçidini və staged↔is_active
uyğunluğunu yoxlayır — bu iki sütunun yazılması onun üçün no-op-dur (mövcud
``patronymic``/``fin`` idxal yazıları ilə eyni yol).  Geri dönüş = adi
``RemoveField``; data migration, RLS və ya trigger dəyişikliyi yoxdur.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_userprofile_access_state_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                default=None,
                help_text="Yaş filtri üçün; pozuq və ya qeyri-müəyyən mənbə dəyəri NULL qalır.",
                null=True,
                verbose_name="Doğum tarixi",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("unspecified", "Təyin edilməyib"), ("male", "Kişi"), ("female", "Qadın")],
                db_index=True,
                default="unspecified",
                help_text="Mənbədə göstərilməyibsə «təyin edilməyib» qalır — təxmin edilmir.",
                max_length=16,
                verbose_name="Cins",
            ),
        ),
    ]
