# Generated by Django 5.2.17 on 2026-09-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_student_reinstatement_identity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountactivationevidence",
            name="reason_code",
            field=models.CharField(
                choices=[
                    ("institution_registry_match", "Institution registry match"),
                    ("manual_registry_verification", "Manual registry verification"),
                    ("signed_authoritative_export", "Signed authoritative export"),
                    ("student_reinstatement_order", "Student reinstatement order"),
                ],
                editable=False,
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="accountrestoreevidence",
            name="reason_code",
            field=models.CharField(
                choices=[
                    ("institution_registry_match", "Institution registry match"),
                    ("manual_registry_verification", "Manual registry verification"),
                    ("signed_authoritative_export", "Signed authoritative export"),
                    ("student_reinstatement_order", "Student reinstatement order"),
                ],
                editable=False,
                max_length=64,
            ),
        ),
    ]
