# Generated by Django 5.2.17 on 2026-09-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_drop_duplicate_profile_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="citizenship",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="Vətəndaşlıq"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="id_document_number",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="Vəsiqə nömrəsi"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="id_document_series",
            field=models.CharField(blank=True, default="", max_length=8, verbose_name="Vəsiqə seriyası"),
        ),
    ]
