# Generated by Django 5.2.17 on 2026-09-30 22:02

import apps.accounts.academic_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_atis_admission_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicprofileitem",
            name="attachment",
            field=models.FileField(
                blank=True,
                default="",
                max_length=255,
                upload_to=apps.accounts.academic_models.academic_attachment_upload_to,
                verbose_name="Qoşma fayl",
            ),
        ),
        migrations.AddField(
            model_name="academicprofileitem",
            name="attachment_name",
            field=models.CharField(blank=True, default="", max_length=160, verbose_name="Qoşmanın adı"),
        ),
        migrations.AddField(
            model_name="academicprofileitem",
            name="attachment_size",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Qoşmanın ölçüsü (bayt)"),
        ),
        migrations.AddField(
            model_name="academicprofileitem",
            name="attachment_thumb",
            field=models.FileField(
                blank=True,
                default="",
                max_length=255,
                upload_to=apps.accounts.academic_models.academic_attachment_upload_to,
                verbose_name="Qoşma önizləməsi",
            ),
        ),
        migrations.AlterField(
            model_name="academicprofileitem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("subject", "Tədris etdiyi fənn"),
                    ("education", "Təhsil / dərəcə"),
                    ("experience", "Peşəkar təcrübə"),
                    ("publication", "Məqalə"),
                    ("book", "Kitab / dərslik"),
                    ("conference", "Konfrans materialı"),
                    ("project", "Elmi layihə / qrant"),
                    ("patent", "Patent"),
                    ("certificate", "Sertifikat"),
                    ("award", "Mükafat / təltif"),
                ],
                max_length=20,
                verbose_name="Növ",
            ),
        ),
    ]
