# Generated by Django 5.2.17 on 2026-10-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_academic_item_kinds_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="grades_notice_pending",
            field=models.BooleanField(
                default=False,
                help_text="Parol bərpasından sonra ilk girişdə köçürülmüş ballar barədə xəbərdarlıq göstərilsin.",
                verbose_name="Bal xəbərdarlığı gözləyir",
            ),
        ),
    ]
