# Generated by Django 5.2.17 on 2026-10-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_userprofile_grades_notice_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="block_contact_code",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="Müraciət ünvanı (kod)"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="block_contact_note",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Girişdə tələbəyə görünür: otaq, telefon, iş saatı və s.",
                max_length=200,
                verbose_name="Tələbəyə qeyd",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="block_reason_code",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="Dayandırma səbəbi (kod)"),
        ),
    ]
