# Generated by Django 5.2.17 on 2026-10-05 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_identity_email_lookup_index"),
        ("organizations", "0057_capacity_drop_unused_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Tutum testi 2026-10-05: yalnız indekslər silinir. Django-nun FK `db_index`
    # dəyişikliyi FK məhdudiyyətini silib yenidən əlavə edir (bütün cədvəl yoxlaması) —
    # bu lazımsızdır, ona görə DB tərəfi xam DROP INDEX, state tərəfi isə avtomatik
    # əməliyyatlardır.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "accounts_us_organiz_b2bf44_idx";\nDROP INDEX IF EXISTS "accounts_us_is_dele_9bf4cd_idx";\nDROP INDEX IF EXISTS "accounts_userprofile_access_state_9809a4fd";\nDROP INDEX IF EXISTS "accounts_userprofile_access_state_9809a4fd_like";\nDROP INDEX IF EXISTS "accounts_userprofile_birth_date_dea1576d";\nDROP INDEX IF EXISTS "accounts_userprofile_blocked_by_id_38d2d2cb";\nDROP INDEX IF EXISTS "accounts_userprofile_can_manage_exam_rooms_f414b0f0";\nDROP INDEX IF EXISTS "accounts_userprofile_deleted_by_id_5a5faf03";\nDROP INDEX IF EXISTS "accounts_userprofile_email_verified_6177a7ac";\nDROP INDEX IF EXISTS "accounts_userprofile_gender_43f4d4d1";\nDROP INDEX IF EXISTS "accounts_userprofile_gender_43f4d4d1_like";\nDROP INDEX IF EXISTS "accounts_userprofile_is_deleted_41d04cc3";\nDROP INDEX IF EXISTS "accounts_userprofile_password_change_required_18b62271";\nDROP INDEX IF EXISTS "accounts_userprofile_patronymic_1f8a80e9";\nDROP INDEX IF EXISTS "accounts_userprofile_patronymic_1f8a80e9_like";\nDROP INDEX IF EXISTS "accounts_userprofile_requested_organization_id_14043874";\nDROP INDEX IF EXISTS "accounts_userprofile_role_f557a06b";\nDROP INDEX IF EXISTS "accounts_userprofile_role_f557a06b_like";',
                    reverse_sql="CREATE INDEX IF NOT EXISTS accounts_us_organiz_b2bf44_idx ON public.accounts_userprofile USING btree (organization_id, created_at);\nCREATE INDEX IF NOT EXISTS accounts_us_is_dele_9bf4cd_idx ON public.accounts_userprofile USING btree (is_deleted, deleted_at);\nCREATE INDEX IF NOT EXISTS accounts_userprofile_access_state_9809a4fd ON public.accounts_userprofile USING btree (access_state);\nCREATE INDEX IF NOT EXISTS accounts_userprofile_access_state_9809a4fd_like ON public.accounts_userprofile USING btree (access_state varchar_pattern_ops);\nCREATE INDEX IF NOT EXISTS accounts_userprofile_birth_date_dea1576d ON public.accounts_userprofile USING btree (birth_date);\nCREATE INDEX IF NOT EXISTS accounts_userprofile_blocked_by_id_38d2d2cb ON public.accounts_userprofile USING btree (blocked_by_id);\nCREATE INDEX IF NOT EXISTS accounts_userprofile_can_manage_exam_rooms_f414b0f0 ON public.accounts_userprofile USING btree (can_manage_exam_rooms);\nCREATE INDEX IF NOT EXISTS accounts_userprofile_deleted_by_id_5a5faf03 ON public.accounts_userprofile USING btree (deleted_by_id);\nCREATE INDEX IF NOT EXISTS accounts_userprofile_email_verified_6177a7ac ON public.accounts_userprofile USING btree (email_verified);\nCREATE INDEX IF NOT EXISTS accounts_userprofile_gender_43f4d4d1 ON public.accounts_userprofile USING btree (gender);\nCREATE INDEX IF NOT EXISTS accounts_userprofile_gender_43f4d4d1_like ON public.accounts_userprofile USING btree (gender varchar_pattern_ops);\nCREATE INDEX IF NOT EXISTS accounts_userprofile_is_deleted_41d04cc3 ON public.accounts_userprofile USING btree (is_deleted);\nCREATE INDEX IF NOT EXISTS accounts_userprofile_password_change_required_18b62271 ON public.accounts_userprofile USING btree (password_change_required);\nCREATE INDEX IF NOT EXISTS accounts_userprofile_patronymic_1f8a80e9 ON public.accounts_userprofile USING btree (patronymic);\nCREATE INDEX IF NOT EXISTS accounts_userprofile_patronymic_1f8a80e9_like ON public.accounts_userprofile USING btree (patronymic varchar_pattern_ops);\nCREATE INDEX IF NOT EXISTS accounts_userprofile_requested_organization_id_14043874 ON public.accounts_userprofile USING btree (requested_organization_id);\nCREATE INDEX IF NOT EXISTS accounts_userprofile_role_f557a06b ON public.accounts_userprofile USING btree (role);\nCREATE INDEX IF NOT EXISTS accounts_userprofile_role_f557a06b_like ON public.accounts_userprofile USING btree (role varchar_pattern_ops);",
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name="userprofile",
                    name="accounts_us_organiz_b2bf44_idx",
                ),
                migrations.RemoveIndex(
                    model_name="userprofile",
                    name="accounts_us_is_dele_9bf4cd_idx",
                ),
                migrations.AlterField(
                    model_name="userprofile",
                    name="access_state",
                    field=models.CharField(
                        choices=[
                            ("active", "Aktiv giriş"),
                            ("staged", "Mərhələlənmiş (giriş bağlıdır)"),
                            ("archived", "Arxiv — məzun/xaric (giriş bağlıdır)"),
                        ],
                        default="active",
                        help_text="Legacy import staged qalır; məzun/xaric archived olur (giriş bağlı, data qalır).",
                        max_length=16,
                        verbose_name="Giriş vəziyyəti",
                    ),
                ),
                migrations.AlterField(
                    model_name="userprofile",
                    name="birth_date",
                    field=models.DateField(
                        blank=True,
                        default=None,
                        help_text="Yaş filtri üçün; pozuq və ya qeyri-müəyyən mənbə dəyəri NULL qalır.",
                        null=True,
                        verbose_name="Doğum tarixi",
                    ),
                ),
                migrations.AlterField(
                    model_name="userprofile",
                    name="blocked_by",
                    field=models.ForeignKey(
                        blank=True,
                        db_index=False,
                        help_text="Hesabı bloklayan RİM operatoru",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rim_blocked_profiles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bloklayan",
                    ),
                ),
                migrations.AlterField(
                    model_name="userprofile",
                    name="can_manage_exam_rooms",
                    field=models.BooleanField(
                        default=False,
                        help_text="Superadmin verir: imtahan zalı və kompüter/MAC qeydlərini idarə etmək icazəsi.",
                        verbose_name="Zal idarəçisi",
                    ),
                ),
                migrations.AlterField(
                    model_name="userprofile",
                    name="deleted_by",
                    field=models.ForeignKey(
                        blank=True,
                        db_index=False,
                        help_text="Hesabı soft-delete edən RİM operatoru",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rim_deleted_profiles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Silən",
                    ),
                ),
                migrations.AlterField(
                    model_name="userprofile",
                    name="email_verified",
                    field=models.BooleanField(
                        default=False,
                        help_text="İlk girişdə OTP ilə təsdiqləndikdən sonra True; parol bərpası üçün istifadə olunur.",
                        verbose_name="Email təsdiqlənib",
                    ),
                ),
                migrations.AlterField(
                    model_name="userprofile",
                    name="gender",
                    field=models.CharField(
                        choices=[("unspecified", "Təyin edilməyib"), ("male", "Kişi"), ("female", "Qadın")],
                        default="unspecified",
                        help_text="Mənbədə göstərilməyibsə «təyin edilməyib» qalır — təxmin edilmir.",
                        max_length=16,
                        verbose_name="Cins",
                    ),
                ),
                migrations.AlterField(
                    model_name="userprofile",
                    name="is_deleted",
                    field=models.BooleanField(default=False, help_text="Hesab silinibsə True", verbose_name="Silinib"),
                ),
                migrations.AlterField(
                    model_name="userprofile",
                    name="password_change_required",
                    field=models.BooleanField(
                        default=False,
                        help_text="İlk girişdə istifadəçi öz parolunu qurana qədər True qalır.",
                        verbose_name="Parol dəyişməlidir",
                    ),
                ),
                migrations.AlterField(
                    model_name="userprofile",
                    name="patronymic",
                    field=models.CharField(
                        blank=True,
                        default="",
                        help_text="Ad+soyad eyni olan hesabları ayırd etmək üçün (RİM axtarışı).",
                        max_length=100,
                        verbose_name="Ata adı",
                    ),
                ),
                migrations.AlterField(
                    model_name="userprofile",
                    name="requested_organization",
                    field=models.ForeignKey(
                        blank=True,
                        db_index=False,
                        help_text="Signup zamanı seçilən, amma hələ qoşulmadığı təşkilat",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_members",
                        to="organizations.organization",
                        verbose_name="Müraciət edilən təşkilat",
                    ),
                ),
                migrations.AlterField(
                    model_name="userprofile",
                    name="role",
                    field=models.CharField(
                        choices=[
                            ("superadmin", "superadmin"),
                            ("org_owner", "org_owner"),
                            ("org_admin", "org_admin"),
                            ("member", "member"),
                            ("hr", "hr"),
                            ("exam_center_head", "exam_center_head"),
                            ("exam_center_staff", "exam_center_staff"),
                            ("exam_center", "exam_center"),
                            ("ikt_rehber", "ikt_rehber"),
                            ("rim_staff", "rim_staff"),
                            ("teacher", "teacher"),
                            ("assistant_teacher", "assistant_teacher"),
                            ("lead_student", "lead_student"),
                            ("student", "student"),
                        ],
                        default="member",
                        help_text="Denormalizə keş — əsl rol Membership.role-dadır",
                        max_length=30,
                        verbose_name="Rol",
                    ),
                ),
            ],
        ),
    ]
