# Generated by Django 5.2.8 on 2026-01-26 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectsubmission",
            options={"ordering": ["-submitted_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="projectsubmission",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateTimeField(verbose_name="Başlanğıc tarixi"),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Aktiv"),
                    ("inactive", "Deaktiv"),
                    ("archived", "Arxivləndi"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectsubmission",
            name="content",
            field=models.TextField(verbose_name="Cavab / İzahat"),
        ),
        migrations.AlterField(
            model_name="projectsubmission",
            name="feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="projectsubmission",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="projects/submissions/"
            ),
        ),
        migrations.AlterField(
            model_name="projectsubmission",
            name="grade",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="projectsubmission",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_project_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projectsubmission",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="projectsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Gözləyir"),
                    ("graded", "Qiymətləndirilib"),
                    ("rejected", "Rədd edilib"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectsubmission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
