"""Final imtahan mərkəzi xidmət paketi — FASAD.

Zal/oturum idarəsi, tələbə biletləri, PIN təhlükəsizliyi, presence və
monitor snapshot-ları. Kənar istehlakçılar yalnız bu fasaddan istifadə
etməlidir (AGENTS §1/§5 pattern-i).
"""

from .cabinet import student_final_exam_context
from .entry import (
    ENTRY_SESSION_KEY,
    ERROR_INVALID,
    ERROR_LOCKED,
    ERROR_NO_ACTIVE_SESSION,
    ERROR_RATE_LIMITED,
    attach_ticket_to_room_sitting,
    claim_student_pin_entry,
    claim_ticket_pin_entry,
    clear_entry_session,
    ensure_open_room_sitting,
    ensure_pin_ticket,
    entry_session_matches,
    entry_session_values_match,
    entry_ticket_id,
    final_attempt_entry_session_valid,
    store_entry_session,
    validate_entry,
)
from .events import (
    broadcast_to_staff,
    broadcast_to_students,
    notify_ticket,
    staff_group,
    students_group,
    ticket_group,
)
from .history import session_history
from .monitor import (
    room_live_sessions,
    room_monitor_snapshot,
    session_list_annotations,
    session_monitor_snapshot,
)
from .permissions import (
    can_manage_final_center,
    can_supervise_session,
    can_supervise_session_ws,
    can_view_final_history,
    ensure_can_manage_final_center,
    ensure_can_supervise_session,
    ensure_can_view_final_history,
    ensure_ticket_owner,
    sessions_visible_to,
    supervised_sessions_q,
    user_is_org_member,
    user_supervises_final_sessions,
)
from .pins import (
    decrypt_ticket_pin,
    generate_pin_value,
    revoke_ticket_pin,
    set_ticket_pin,
    student_visible_pin,
    verify_ticket_pin,
)
from .presence import (
    HEARTBEAT_INTERVAL_SECONDS,
    PRESENCE_TTL_SECONDS,
    connected_count,
    drop_presence,
    presence_map,
    touch_presence,
    touch_ticket_last_seen,
)
from .reminders import notify_upcoming_final_exams
from .reports import filter_sessions, filter_tickets
from .room_admin import RoomAdminError, add_computer, bulk_add_computers, delete_room, update_computer
from .sessions import (
    RoomSessionStateError,
    auto_close_stale_room_sessions,
    cancel_session,
    end_room,
    open_entry,
    start_room,
    validate_session_plan,
)
from .tickets import (
    TicketStateError,
    assign_students,
    begin_attempt_for_ticket,
    enter_waiting,
    readmit_student,
    regenerate_pin,
    remove_student,
    resolve_ticket_language,
    set_ready,
    set_seat,
    student_cancel_waiting,
    sync_ticket_completion,
    transition_ticket,
)

__all__ = [
    "ENTRY_SESSION_KEY",
    "ERROR_INVALID",
    "ERROR_LOCKED",
    "ERROR_NO_ACTIVE_SESSION",
    "ERROR_RATE_LIMITED",
    "attach_ticket_to_room_sitting",
    "claim_student_pin_entry",
    "claim_ticket_pin_entry",
    "ensure_open_room_sitting",
    "ensure_pin_ticket",
    "HEARTBEAT_INTERVAL_SECONDS",
    "PRESENCE_TTL_SECONDS",
    "RoomAdminError",
    "RoomSessionStateError",
    "TicketStateError",
    "add_computer",
    "assign_students",
    "begin_attempt_for_ticket",
    "bulk_add_computers",
    "delete_room",
    "broadcast_to_staff",
    "broadcast_to_students",
    "can_manage_final_center",
    "can_supervise_session",
    "can_supervise_session_ws",
    "can_view_final_history",
    "auto_close_stale_room_sessions",
    "cancel_session",
    "clear_entry_session",
    "connected_count",
    "decrypt_ticket_pin",
    "drop_presence",
    "end_room",
    "ensure_can_manage_final_center",
    "ensure_can_supervise_session",
    "ensure_can_view_final_history",
    "ensure_ticket_owner",
    "enter_waiting",
    "entry_session_matches",
    "entry_session_values_match",
    "entry_ticket_id",
    "filter_sessions",
    "filter_tickets",
    "final_attempt_entry_session_valid",
    "generate_pin_value",
    "notify_ticket",
    "notify_upcoming_final_exams",
    "open_entry",
    "presence_map",
    "readmit_student",
    "regenerate_pin",
    "remove_student",
    "resolve_ticket_language",
    "revoke_ticket_pin",
    "room_live_sessions",
    "room_monitor_snapshot",
    "session_history",
    "session_list_annotations",
    "session_monitor_snapshot",
    "sessions_visible_to",
    "set_ready",
    "set_seat",
    "set_ticket_pin",
    "staff_group",
    "start_room",
    "store_entry_session",
    "student_cancel_waiting",
    "student_final_exam_context",
    "student_visible_pin",
    "students_group",
    "supervised_sessions_q",
    "sync_ticket_completion",
    "ticket_group",
    "touch_presence",
    "touch_ticket_last_seen",
    "transition_ticket",
    "update_computer",
    "user_is_org_member",
    "user_supervises_final_sessions",
    "validate_entry",
    "validate_session_plan",
    "verify_ticket_pin",
]
