"""Registrar models paketi (U14 bölgüsü) — sxem dəyişikliyi YOXDUR.

Köhnə tək ``models.py`` iki məntiqi modula bölünüb; bütün ictimai adlar burada
re-eksport olunur, ona görə ``from apps.registrar.models import X`` toxunulmaz
işləyir (migrasiyalar da dəyişməz qalır).
"""

from .academic import (
    AcademicStatus,
    CourseOffering,
    Curriculum,
    CurriculumSubject,
    DegreeLevel,
    Enrollment,
    EnrollmentKind,
    GroupElectiveChoice,
    Program,
    ScheduleSlot,
    SlotKind,
    StudentAcademicRecord,
    Subject,
    WeekType,
)
from .grading import (
    ApprovalStatus,
    AssessmentComponent,
    AssessmentScheme,
    AttendanceStatus,
    ComponentKind,
    ComponentScore,
    CourseWork,
    CriterionScore,
    FinalGrade,
    Lesson,
    LessonKind,
    LessonMark,
    ResitReason,
    ResitRecord,
    ResitStatus,
    Rubric,
    RubricCriterion,
    SelfWorkMark,
    SelfWorkTopic,
)

__all__ = [
    "AcademicStatus",
    "ApprovalStatus",
    "AssessmentComponent",
    "AssessmentScheme",
    "AttendanceStatus",
    "ComponentKind",
    "ComponentScore",
    "CourseWork",
    "CriterionScore",
    "CourseOffering",
    "Curriculum",
    "CurriculumSubject",
    "DegreeLevel",
    "Enrollment",
    "EnrollmentKind",
    "FinalGrade",
    "GroupElectiveChoice",
    "Lesson",
    "LessonKind",
    "LessonMark",
    "Program",
    "ResitReason",
    "ResitRecord",
    "ResitStatus",
    "Rubric",
    "RubricCriterion",
    "ScheduleSlot",
    "SelfWorkMark",
    "SelfWorkTopic",
    "SlotKind",
    "StudentAcademicRecord",
    "Subject",
    "WeekType",
]
