# Generated by Django 5.2.17 on 2026-10-06 17:04

import apps.announcements.models
import core.upload_security
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0005_reopened_event_kind"),
        ("organizations", "0057_capacity_drop_unused_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("summary", models.CharField(blank=True, default="", max_length=300)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "Ümumi"),
                            ("academic", "Tədris"),
                            ("exam", "İmtahan"),
                            ("event", "Tədbir"),
                            ("urgent", "Təcili"),
                        ],
                        default="general",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(choices=[(0, "Adi"), (1, "Yüksək"), (2, "Kritik")], default=0),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Qaralama"), ("published", "Dərc olunub"), ("archived", "Arxiv")],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("publish_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("deadline_at", models.DateTimeField(blank=True, null=True)),
                ("show_as_popup", models.BooleanField(default=False)),
                ("audience_families", models.JSONField(blank=True, default=list)),
                ("audience_units", models.JSONField(blank=True, default=list)),
                (
                    "apply_mode",
                    models.CharField(
                        choices=[
                            ("none", "Müraciət yoxdur"),
                            ("internal", "Daxili müraciət (Müraciətlər modulu)"),
                            ("url", "Keçid (link)"),
                        ],
                        default="none",
                        max_length=12,
                    ),
                ),
                ("apply_url", models.CharField(blank=True, default="", max_length=500)),
                ("apply_label", models.CharField(blank=True, default="", max_length=60)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "apply_kind",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="applications.applicationkind",
                    ),
                ),
                (
                    "apply_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="applications.applicationunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "elan",
                "verbose_name_plural": "elanlar",
                "ordering": ["-is_pinned", "-publish_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementAttachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=apps.announcements.models.announcement_attachment_path,
                        validators=[
                            core.upload_security.FileUploadValidator(
                                allowed_extensions={
                                    ".docx",
                                    ".jpeg",
                                    ".jpg",
                                    ".pdf",
                                    ".png",
                                    ".pptx",
                                    ".webp",
                                    ".xlsx",
                                },
                                max_size_mb=10,
                            )
                        ],
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, default="", max_length=120)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="announcements.announcement",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="organizations.organization"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "elan sənədi",
                "verbose_name_plural": "elan sənədləri",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementReceipt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("popup_seen_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("application_id", models.UUIDField(blank=True, null=True)),
                ("application_number", models.CharField(blank=True, default="", max_length=20)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="announcements.announcement",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="organizations.organization"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "elan qəbzi",
                "verbose_name_plural": "elan qəbzləri",
            },
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(fields=["organization", "status", "-publish_at"], name="ann_org_status_pub"),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(fields=["organization", "deadline_at"], name="ann_org_deadline"),
        ),
        migrations.AddConstraint(
            model_name="announcement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expires_at__isnull", True),
                    ("publish_at__isnull", True),
                    ("expires_at__gt", models.F("publish_at")),
                    _connector="OR",
                ),
                name="ann_window_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="announcement",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "published", "archived"])), name="ann_status_valid"
            ),
        ),
        migrations.AddIndex(
            model_name="announcementreceipt",
            index=models.Index(fields=["organization", "user"], name="ann_receipt_org_user"),
        ),
        migrations.AddConstraint(
            model_name="announcementreceipt",
            constraint=models.UniqueConstraint(fields=("announcement", "user"), name="ann_receipt_once"),
        ),
    ]
