# Generated by Django 5.2.17 on 2026-10-06 20:01
"""Elanın yumşaq silinməsi: ``is_deleted`` / ``deleted_at`` / ``deleted_by``.

RLS: ``0002_rls_announcements`` siyasəti yalnız ``organization_id``-yə baxır və cədvəl
səviyyəsindədir — yeni sütunlar onu dəyişmir (ADD COLUMN siyasəti saxlayır). ``is_deleted``
``db_default=False`` ilə gəlir: köhnə kod (rolling deploy) sütunsuz INSERT etsə də sətir
«silinməmiş» sayılır; mövcud sətirlər üçün cədvəlin yenidən yazılması lazım deyil.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0003_seed_manage_permission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="is_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddConstraint(
            model_name="announcement",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_deleted", False), ("deleted_at__isnull", False), _connector="OR"),
                name="ann_deleted_has_time",
            ),
        ),
    ]
