# Generated by Django 5.2.15 on 2026-07-04 10:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0013_alter_orgunit_unit_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=255)),
                (
                    "degree_level",
                    models.CharField(
                        choices=[("bachelor", "Bachelor"), ("master", "Master"), ("phd", "PhD")],
                        default="bachelor",
                        max_length=16,
                    ),
                ),
                ("ects_total", models.PositiveIntegerField(default=240, help_text="Proqramın tam ECTS kredit yükü.")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "specialty_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="İxtisas (OrgUnit: specialty) — iyerarxiya bağlantısı.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programs",
                        to="organizations.orgunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "program",
                "verbose_name_plural": "programs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("admission_year", models.PositiveIntegerField(help_text="Qəbul ili (məs. 2024).")),
                ("name", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curricula",
                        to="organizations.organization",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="curricula", to="registrar.program"
                    ),
                ),
            ],
            options={
                "verbose_name": "curriculum",
                "verbose_name_plural": "curricula",
                "ordering": ["-admission_year", "program__name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=255)),
                ("ects", models.PositiveSmallIntegerField(default=5, help_text="Fənnin ECTS kredit dəyəri.")),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "subject",
                "verbose_name_plural": "subjects",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CurriculumSubject",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("semester_number", models.PositiveSmallIntegerField(help_text="Neçənci semestr (1..N).")),
                ("is_elective", models.BooleanField(db_index=True, default=False)),
                (
                    "elective_group",
                    models.CharField(
                        blank=True,
                        help_text="Seçmə blok adı (eyni blokun sətirləri eyni dəyəri daşıyır).",
                        max_length=50,
                    ),
                ),
                (
                    "required_choices",
                    models.PositiveSmallIntegerField(default=1, help_text="Seçmə blokdan neçə fənn seçilməlidir."),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rows", to="registrar.curriculum"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_subjects",
                        to="organizations.organization",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_rows",
                        to="registrar.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "curriculum subject",
                "verbose_name_plural": "curriculum subjects",
                "ordering": ["curriculum", "semester_number", "order"],
            },
        ),
        migrations.AddConstraint(
            model_name="program",
            constraint=models.UniqueConstraint(fields=("organization", "code"), name="uniq_program_code_per_org"),
        ),
        migrations.AddConstraint(
            model_name="curriculum",
            constraint=models.UniqueConstraint(
                fields=("organization", "program", "admission_year"), name="uniq_curriculum_program_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(fields=("organization", "code"), name="uniq_subject_code_per_org"),
        ),
        migrations.AddIndex(
            model_name="curriculumsubject",
            index=models.Index(fields=["curriculum", "semester_number"], name="registrar_c_curricu_d66d74_idx"),
        ),
        migrations.AddIndex(
            model_name="curriculumsubject",
            index=models.Index(fields=["curriculum", "elective_group"], name="registrar_c_curricu_d5ed14_idx"),
        ),
        migrations.AddConstraint(
            model_name="curriculumsubject",
            constraint=models.UniqueConstraint(
                fields=("organization", "curriculum", "subject", "semester_number"),
                name="uniq_curriculum_subject_semester",
            ),
        ),
    ]
