# Generated by Django 5.2.15 on 2026-07-04 11:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("organizations", "0013_alter_orgunit_unit_type"),
        ("registrar", "0002_rls_policies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseOffering",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="LMS kursu (fənn içi = mövzular/resurslar) — opsional.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offerings",
                        to="courses.course",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bu bölmənin/qrupun dərsi (boşdursa — bütün ixtisas üçün).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_offerings",
                        to="organizations.orgunit",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_offerings",
                        to="organizations.organization",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offerings",
                        to="organizations.academicperiod",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="offerings", to="registrar.subject"
                    ),
                ),
            ],
            options={
                "verbose_name": "course offering",
                "verbose_name_plural": "course offerings",
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[("mandatory", "Mandatory"), ("elective", "Elective"), ("retake", "Retake")],
                        default="mandatory",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("enrolled", "Enrolled"), ("completed", "Completed"), ("dropped", "Dropped")],
                        db_index=True,
                        default="enrolled",
                        max_length=16,
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="registrar.courseoffering",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "enrollment",
                "verbose_name_plural": "enrollments",
            },
        ),
        migrations.CreateModel(
            name="GroupElectiveChoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "elective_group",
                    models.CharField(help_text="CurriculumSubject.elective_group blok adı.", max_length=50),
                ),
                (
                    "chosen_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_elective_choices",
                        to="registrar.subject",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="group_elective_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_elective_choices",
                        to="organizations.orgunit",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_elective_choices",
                        to="organizations.organization",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_elective_choices",
                        to="organizations.academicperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "group elective choice",
                "verbose_name_plural": "group elective choices",
            },
        ),
        migrations.CreateModel(
            name="StudentAcademicRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("admission_year", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_records",
                        to="registrar.curriculum",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tələbənin qrupu (bölmə/sektor OrgUnit: group).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_records",
                        to="organizations.orgunit",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_records",
                        to="organizations.organization",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_records",
                        to="registrar.program",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "student academic record",
                "verbose_name_plural": "student academic records",
            },
        ),
        migrations.AddIndex(
            model_name="courseoffering",
            index=models.Index(fields=["organization", "period"], name="registrar_c_organiz_8c8ef4_idx"),
        ),
        migrations.AddConstraint(
            model_name="courseoffering",
            constraint=models.UniqueConstraint(
                fields=("organization", "subject", "period", "group"), name="uniq_offering_subject_period_group"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["organization", "student"], name="registrar_e_organiz_06332c_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["offering", "status"], name="registrar_e_offerin_315790_idx"),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("organization", "student", "offering"), name="uniq_student_offering"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupelectivechoice",
            constraint=models.UniqueConstraint(
                fields=("organization", "group", "period", "elective_group"), name="uniq_group_elective_block"
            ),
        ),
        migrations.AddIndex(
            model_name="studentacademicrecord",
            index=models.Index(fields=["organization", "group"], name="registrar_s_organiz_53ed8c_idx"),
        ),
        migrations.AddConstraint(
            model_name="studentacademicrecord",
            constraint=models.UniqueConstraint(
                fields=("organization", "student", "program"), name="uniq_student_program"
            ),
        ),
    ]
