# Generated by Django 5.2.15 on 2026-07-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0004_rls_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseoffering",
            name="lesson_hours",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Semestrdə fənnin tam dərs (kontakt) saatı — qayıb limiti üçün baza."
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="absence_hours",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Bu fənn üzrə toplanmış üzrsüz qayıb saatı (qayıb limiti üçün)."
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="absence_limit_percent",
            field=models.PositiveSmallIntegerField(
                default=25, help_text="Üzrsüz qayıb həddi (dərs saatının %-i); keçilərsə imtahana buraxılmır."
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="ects_total",
            field=models.PositiveIntegerField(
                default=240, help_text="Məzuniyyət üçün tələb olunan tam ECTS kredit yükü (Boloniya)."
            ),
        ),
    ]
