# Generated by Django 5.2.15 on 2026-07-04 13:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0013_alter_orgunit_unit_type"),
        ("registrar", "0005_courseoffering_lesson_hours_enrollment_absence_hours_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="courseoffering",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                help_text="Fənni tədris edən müəllim (elektron jurnal sahibi).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taught_offerings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AssessmentScheme",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "pass_threshold",
                    models.PositiveSmallIntegerField(default=51, help_text="Keçid üçün minimum ümumi bal (adətən 51)."),
                ),
                (
                    "min_final_exam_score",
                    models.PositiveSmallIntegerField(
                        default=17, help_text="Yekun imtahandan keçid üçün minimum bal (kəsilmə qaydası)."
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, help_text="Yekunlaşdırılıb — bal redaktəsi bağlıdır."),
                ),
                (
                    "offering",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_scheme",
                        to="registrar.courseoffering",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_schemes",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "assessment scheme",
                "verbose_name_plural": "assessment schemes",
            },
        ),
        migrations.CreateModel(
            name="GradeComponent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("name", models.CharField(help_text="Komponentin adı (məs. Seminar, Sərbəst iş).", max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("seminar", "Seminar"),
                            ("lab", "Laboratory"),
                            ("independent", "Independent work"),
                            ("colloquium", "Colloquium"),
                            ("attendance", "Attendance"),
                            ("final_exam", "Final exam"),
                            ("other", "Other"),
                        ],
                        default="seminar",
                        max_length=16,
                    ),
                ),
                (
                    "max_score",
                    models.PositiveSmallIntegerField(default=10, help_text="Bu komponentin maksimum balı (çəkisi)."),
                ),
                (
                    "is_final_exam",
                    models.BooleanField(
                        default=False, help_text="Yekun imtahan komponenti (minimum-hədd qaydası buna tətbiq olunur)."
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_components",
                        to="organizations.organization",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="registrar.assessmentscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "grade component",
                "verbose_name_plural": "grade components",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ComponentScore",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Daxil edilmiş bal (0 .. max_score).",
                        max_digits=6,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_scores",
                        to="registrar.enrollment",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_scores",
                        to="organizations.organization",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="registrar.gradecomponent",
                    ),
                ),
            ],
            options={
                "verbose_name": "component score",
                "verbose_name_plural": "component scores",
                "indexes": [models.Index(fields=["organization", "enrollment"], name="registrar_c_organiz_587067_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("enrollment", "component"), name="uniq_enrollment_component_score")
                ],
            },
        ),
    ]
