# Generated by Django 5.2.15 on 2026-07-04 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0013_alter_orgunit_unit_type"),
        ("registrar", "0007_rls_gradebook"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gradecomponent",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="gradecomponent",
            name="scheme",
        ),
        migrations.RemoveField(
            model_name="assessmentscheme",
            name="min_final_exam_score",
        ),
        migrations.RemoveField(
            model_name="assessmentscheme",
            name="pass_threshold",
        ),
        migrations.AddField(
            model_name="assessmentscheme",
            name="entry_score_max",
            field=models.PositiveSmallIntegerField(
                default=50, help_text="Semestr 'giriş balı' tavanı (Boloniya ≈50; qalan 50 yekun imtahan)."
            ),
        ),
        migrations.AlterField(
            model_name="assessmentscheme",
            name="is_published",
            field=models.BooleanField(default=False, help_text="Yekunlaşdırılıb — jurnal redaktəsi bağlıdır."),
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField(help_text="Dərsin keçirildiyi tarix.")),
                (
                    "kind",
                    models.CharField(
                        choices=[("lecture", "Lecture"), ("seminar", "Seminar"), ("lab", "Laboratory")],
                        default="lecture",
                        max_length=16,
                    ),
                ),
                ("topic", models.CharField(blank=True, help_text="Mövzu (opsional).", max_length=255)),
                (
                    "hours",
                    models.PositiveSmallIntegerField(
                        default=2, help_text="Bu dərsin akademik saatı (qayıb hesabı üçün)."
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="registrar.courseoffering",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "lesson",
                "verbose_name_plural": "lessons",
                "ordering": ["date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonMark",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("present", "Present"), ("absent", "Absent")], default="present", max_length=12
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Seminar/lab balı (opsional).", max_digits=5, null=True
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_marks",
                        to="registrar.enrollment",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="marks", to="registrar.lesson"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_marks",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "lesson mark",
                "verbose_name_plural": "lesson marks",
            },
        ),
        migrations.DeleteModel(
            name="ComponentScore",
        ),
        migrations.DeleteModel(
            name="GradeComponent",
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["organization", "offering", "date"], name="registrar_l_organiz_7c6e08_idx"),
        ),
        migrations.AddIndex(
            model_name="lessonmark",
            index=models.Index(fields=["organization", "enrollment"], name="registrar_l_organiz_f4590b_idx"),
        ),
        migrations.AddConstraint(
            model_name="lessonmark",
            constraint=models.UniqueConstraint(fields=("lesson", "enrollment"), name="uniq_lesson_enrollment_mark"),
        ),
    ]
