# Generated by Django 5.2.15 on 2026-07-04 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0013_alter_orgunit_unit_type"),
        ("registrar", "0009_rls_journal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleSlot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("weekday", models.PositiveSmallIntegerField(help_text="Həftənin günü (1=Bazar ertəsi … 7=Bazar).")),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("room", models.CharField(blank=True, help_text="Auditoriya (opsional).", max_length=64)),
                (
                    "week_type",
                    models.CharField(
                        choices=[("all", "Every week"), ("odd", "Odd weeks"), ("even", "Even weeks")],
                        default="all",
                        max_length=8,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_slots",
                        to="registrar.courseoffering",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_slots",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "schedule slot",
                "verbose_name_plural": "schedule slots",
                "ordering": ["weekday", "start_time"],
                "indexes": [
                    models.Index(fields=["organization", "offering", "weekday"], name="registrar_s_organiz_f12378_idx")
                ],
            },
        ),
    ]
