# Generated by Django 5.2.15 on 2026-07-04 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0013_alter_orgunit_unit_type"),
        ("registrar", "0011_rls_scheduleslot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentscheme",
            name="min_final_exam_score",
            field=models.PositiveSmallIntegerField(
                default=17, help_text="Yekun imtahandan keçid üçün minimum bal (kəsilmə qaydası)."
            ),
        ),
        migrations.AddField(
            model_name="assessmentscheme",
            name="pass_threshold",
            field=models.PositiveSmallIntegerField(
                default=51, help_text="Keçid üçün minimum ümumi bal (giriş + imtahan, adətən 51)."
            ),
        ),
        migrations.CreateModel(
            name="FinalGrade",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "exam_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Yekun imtahan balı (≈max 50).", max_digits=5, null=True
                    ),
                ),
                ("is_published", models.BooleanField(default=False, help_text="Nəticə rəsmiləşdirilib.")),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_grade",
                        to="registrar.enrollment",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_grades",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "final grade",
                "verbose_name_plural": "final grades",
                "indexes": [models.Index(fields=["organization", "enrollment"], name="registrar_f_organiz_1ee27f_idx")],
            },
        ),
        migrations.CreateModel(
            name="ResitRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("absence", "Barred by absence"),
                            ("total", "Total below pass mark"),
                            ("exam", "Exam below minimum"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("eligible", "Eligible"), ("completed", "Completed")],
                        default="eligible",
                        max_length=12,
                    ),
                ),
                (
                    "resit_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Təkrar imtahan balı.", max_digits=5, null=True
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resit_records",
                        to="registrar.enrollment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resits",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "resit record",
                "verbose_name_plural": "resit records",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["organization", "enrollment"], name="registrar_r_organiz_957295_idx")],
                "constraints": [models.UniqueConstraint(fields=("enrollment",), name="uniq_resit_per_enrollment")],
            },
        ),
    ]
