# Generated by Django 5.2.15 on 2026-07-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0013_rls_finals"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentacademicrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("enrolled", "Enrolled"),
                    ("academic_leave", "Academic leave"),
                    ("expelled", "Expelled"),
                    ("graduated", "Graduated"),
                ],
                db_index=True,
                default="enrolled",
                help_text="Akademik status (qeydiyyatlı / akademik məzuniyyət / xaric / məzun).",
                max_length=20,
            ),
        ),
    ]
