# Generated by Django 5.2.15 on 2026-07-04 19:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0013_alter_orgunit_unit_type"),
        ("registrar", "0014_studentacademicrecord_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentComponent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "name",
                    models.CharField(
                        help_text="Komponent adı (məs. Seminar, Kollokvium 1, SDF, Layihə).", max_length=100
                    ),
                ),
                (
                    "max_score",
                    models.PositiveSmallIntegerField(
                        default=10, help_text="Bu komponentin giriş balına maksimum töhfəsi."
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_components",
                        to="registrar.courseoffering",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_components",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "assessment component",
                "verbose_name_plural": "assessment components",
                "ordering": ["offering", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ComponentScore",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("score", models.DecimalField(decimal_places=2, default=0, help_text="Komponent balı.", max_digits=5)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="registrar.assessmentcomponent",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_scores",
                        to="registrar.enrollment",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_scores",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "component score",
                "verbose_name_plural": "component scores",
            },
        ),
        migrations.AddIndex(
            model_name="assessmentcomponent",
            index=models.Index(fields=["organization", "offering"], name="registrar_a_organiz_ad70cd_idx"),
        ),
        migrations.AddConstraint(
            model_name="assessmentcomponent",
            constraint=models.UniqueConstraint(fields=("offering", "name"), name="uniq_component_offering_name"),
        ),
        migrations.AddIndex(
            model_name="componentscore",
            index=models.Index(fields=["organization", "enrollment"], name="registrar_c_organiz_587067_idx"),
        ),
        migrations.AddConstraint(
            model_name="componentscore",
            constraint=models.UniqueConstraint(
                fields=("component", "enrollment"), name="uniq_component_enrollment_score"
            ),
        ),
    ]
