# Generated by Django 5.2.15 on 2026-07-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0017_assessmentscheme_approval_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalgrade",
            name="bonus",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Bonus (+) / cərimə (−) düzəlişi — ümumi bala əlavə olunur.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="finalgrade",
            name="comment",
            field=models.CharField(
                blank=True, help_text="Müəllimin yekun rəyi — tələbəyə görünür (opsional).", max_length=500
            ),
        ),
    ]
