# Generated by Django 5.2.15 on 2026-07-05 11:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0014_academicperiod_exam_session_end_and_more"),
        ("registrar", "0018_finalgrade_bonus_finalgrade_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rubric",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Rubrik adı (məs. Layihə təqdimatı).", max_length=150)),
                ("description", models.CharField(blank=True, default="", max_length=300)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rubrics",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "rubric",
                "verbose_name_plural": "rubrics",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="assessmentcomponent",
            name="rubric",
            field=models.ForeignKey(
                blank=True,
                help_text="Qoşulubsa, bu komponent meyar-meyar (rubrik ilə) qiymətləndirilir (U22).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="components",
                to="registrar.rubric",
            ),
        ),
        migrations.CreateModel(
            name="RubricCriterion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("max_points", models.PositiveSmallIntegerField(default=5, help_text="Bu meyar üzrə maksimum bal.")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rubric_criteria",
                        to="organizations.organization",
                    ),
                ),
                (
                    "rubric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="criteria", to="registrar.rubric"
                    ),
                ),
            ],
            options={
                "verbose_name": "rubric criterion",
                "verbose_name_plural": "rubric criteria",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CriterionScore",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("points", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterion_scores",
                        to="registrar.enrollment",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterion_scores",
                        to="organizations.organization",
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="registrar.rubriccriterion",
                    ),
                ),
            ],
            options={
                "verbose_name": "criterion score",
                "verbose_name_plural": "criterion scores",
            },
        ),
        migrations.AddConstraint(
            model_name="rubric",
            constraint=models.UniqueConstraint(fields=("organization", "name"), name="uniq_rubric_org_name"),
        ),
        migrations.AddIndex(
            model_name="rubriccriterion",
            index=models.Index(fields=["organization", "rubric"], name="registrar_r_organiz_b9fe30_idx"),
        ),
        migrations.AddConstraint(
            model_name="rubriccriterion",
            constraint=models.UniqueConstraint(fields=("rubric", "name"), name="uniq_criterion_rubric_name"),
        ),
        migrations.AddIndex(
            model_name="criterionscore",
            index=models.Index(fields=["organization", "enrollment"], name="registrar_c_organiz_bf53cf_idx"),
        ),
        migrations.AddConstraint(
            model_name="criterionscore",
            constraint=models.UniqueConstraint(
                fields=("criterion", "enrollment"), name="uniq_criterion_enrollment_score"
            ),
        ),
    ]
