# Generated by Django 5.2.15 on 2026-07-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0020_rls_rubrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleslot",
            name="kind",
            field=models.CharField(
                choices=[("lecture", "Lecture"), ("seminar", "Seminar"), ("lab", "Laboratory")],
                default="lecture",
                help_text="Dərs növü (mühazirə/məşğələ/laboratoriya) — cədvəl rəng kodu.",
                max_length=16,
            ),
        ),
    ]
