# Generated by Django 5.2.15 on 2026-07-12 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0023_grade_event_append_only"),
        ("registrar", "0021_scheduleslot_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentcomponent",
            name="held_on",
            field=models.DateField(
                blank=True, help_text="Keçirilmə tarixi (kollokvium üçün — tələbə tarixçəsində göstərilir).", null=True
            ),
        ),
        migrations.AddField(
            model_name="assessmentcomponent",
            name="kind",
            field=models.CharField(
                choices=[("generic", "Generic"), ("kollokvium", "Kollokvium"), ("self_work", "Independent work")],
                db_index=True,
                default="generic",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="start_time",
            field=models.TimeField(
                blank=True, help_text="Dərs saatı (cədvəl slotundan seçilir — opsional).", null=True
            ),
        ),
        migrations.CreateModel(
            name="SelfWorkTopic",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("title", models.CharField(max_length=255)),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="self_work_topics",
                        to="registrar.courseoffering",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="self_work_topics",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "independent work topic",
                "verbose_name_plural": "independent work topics",
                "ordering": ["offering", "order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SelfWorkMark",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("done", models.BooleanField(default=False)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="self_work_marks",
                        to="registrar.enrollment",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="self_work_marks",
                        to="organizations.organization",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="marks", to="registrar.selfworktopic"
                    ),
                ),
            ],
            options={
                "verbose_name": "independent work mark",
                "verbose_name_plural": "independent work marks",
            },
        ),
        migrations.CreateModel(
            name="CourseWork",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("topic", models.CharField(help_text="Kurs işinin mövzusu.", max_length=255)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Bal (0-100).", max_digits=5, null=True
                    ),
                ),
                ("submitted_on", models.DateField(blank=True, help_text="Təhvil tarixi.", null=True)),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_work",
                        to="registrar.enrollment",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_works",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "course work",
                "verbose_name_plural": "course works",
                "indexes": [models.Index(fields=["organization", "enrollment"], name="registrar_c_organiz_66198e_idx")],
            },
        ),
        migrations.AddIndex(
            model_name="selfworktopic",
            index=models.Index(fields=["organization", "offering"], name="registrar_s_organiz_e4ddf1_idx"),
        ),
        migrations.AddIndex(
            model_name="selfworkmark",
            index=models.Index(fields=["organization", "enrollment"], name="registrar_s_organiz_a748c6_idx"),
        ),
        migrations.AddConstraint(
            model_name="selfworkmark",
            constraint=models.UniqueConstraint(fields=("topic", "enrollment"), name="uniq_selfwork_topic_enrollment"),
        ),
    ]
