# Generated by Django 5.2.13 on 2026-07-15 17:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0023_grade_event_append_only"),
        ("registrar", "0024_journal_mark_immutability_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KollokviumWindow",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("k_index", models.PositiveSmallIntegerField(verbose_name="kollokvium indeksi (0=K1)")),
                ("opens_on", models.DateField(verbose_name="açılış tarixi")),
                ("closes_on", models.DateField(verbose_name="bağlanış tarixi")),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kollokvium_windows",
                        to="organizations.organization",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kollokvium_windows",
                        to="organizations.academicperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kollokvium pəncərəsi",
                "verbose_name_plural": "Kollokvium pəncərələri",
                "ordering": ["period", "k_index"],
            },
        ),
        migrations.CreateModel(
            name="KollokviumExtraGrant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("organization", "Bütün universitet"),
                            ("faculty", "Fakültə"),
                            ("department", "Kafedra"),
                        ],
                        max_length=16,
                    ),
                ),
                ("extra_days", models.PositiveSmallIntegerField(default=0)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kollokvium_extra_grants",
                        to="organizations.orgunit",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kollokvium_extra_grants",
                        to="organizations.organization",
                    ),
                ),
                (
                    "window",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_grants",
                        to="registrar.kollokviumwindow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kollokvium əlavə gün",
                "verbose_name_plural": "Kollokvium əlavə günlər",
            },
        ),
        migrations.AddIndex(
            model_name="kollokviumwindow",
            index=models.Index(fields=["organization", "period"], name="registrar_k_organiz_735911_idx"),
        ),
        migrations.AddConstraint(
            model_name="kollokviumwindow",
            constraint=models.UniqueConstraint(
                fields=("organization", "period", "k_index"), name="uniq_kollokvium_window"
            ),
        ),
        migrations.AddIndex(
            model_name="kollokviumextragrant",
            index=models.Index(fields=["organization", "window"], name="registrar_k_organiz_dae964_idx"),
        ),
        migrations.AddConstraint(
            model_name="kollokviumextragrant",
            constraint=models.UniqueConstraint(
                fields=("window", "scope", "org_unit"), name="uniq_kollokvium_extra_grant"
            ),
        ),
    ]
