# Generated by Django 5.2.13 on 2026-07-19 00:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.registrar.models.corrections
import core.upload_security


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0025_rls_org_functional_indexes"),
        ("registrar", "0026_rls_kollokvium_window"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonmark",
            name="status",
            field=models.CharField(
                choices=[("present", "Present"), ("absent", "Absent"), ("excused", "Excused absence")],
                default="present",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="JournalCorrection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("field", models.CharField(choices=[("attendance", "Attendance"), ("score", "Score")], max_length=12)),
                ("old_status", models.CharField(blank=True, default="", max_length=12)),
                ("new_status", models.CharField(blank=True, default="", max_length=12)),
                ("old_score", models.IntegerField(blank=True, null=True)),
                ("new_score", models.IntegerField(blank=True, null=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("medical", "Medical certificate"),
                            ("official", "Official leave / permission"),
                            ("technical", "Data-entry error"),
                            ("appeal", "Appeal decision"),
                            ("other", "Other (see note)"),
                        ],
                        max_length=12,
                    ),
                ),
                ("note", models.TextField(help_text="Düzəlişin izahı — tələbə və müəllim görür (məcburi).")),
                (
                    "document",
                    models.FileField(
                        help_text="Əsas sənəd — yalnız PDF (məcburi).",
                        upload_to=apps.registrar.models.corrections.correction_document_path,
                        validators=[
                            core.upload_security.FileUploadValidator(allowed_extensions={".pdf"}, max_size_mb=10)
                        ],
                    ),
                ),
                ("corrected_by_name", models.CharField(editable=False, max_length=200)),
                (
                    "corrected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson_mark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrections",
                        to="registrar.lessonmark",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_corrections",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "journal correction",
                "verbose_name_plural": "journal corrections",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["organization", "lesson_mark"], name="registrar_j_organiz_79256b_idx"),
                    models.Index(fields=["organization", "-created_at"], name="registrar_j_organiz_30205b_idx"),
                ],
            },
        ),
    ]
