# Generated by Django 5.2.15 on 2026-07-20 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0028_rls_journal_correction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                help_text="Bu dərsi keçən müəllim — fənn 2 müəllim arasında bölünübsə (məs. mühazirə bir müəllim, seminar başqa). Boşdursa açılışın (CourseOffering) müəllimi götürülür.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taught_lessons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
