# Generated by Django 5.2.15 on 2026-07-20 23:31

import apps.registrar.models.corrections
import core.upload_security
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0026_seed_ikt_rehber_role"),
        ("registrar", "0029_lesson_instructor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonCorrection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("old_date", models.DateField(blank=True, null=True)),
                ("new_date", models.DateField(blank=True, null=True)),
                (
                    "old_kind",
                    models.CharField(
                        blank=True,
                        choices=[("lecture", "Lecture"), ("seminar", "Seminar"), ("lab", "Laboratory")],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "new_kind",
                    models.CharField(
                        blank=True,
                        choices=[("lecture", "Lecture"), ("seminar", "Seminar"), ("lab", "Laboratory")],
                        default="",
                        max_length=16,
                    ),
                ),
                ("old_hours", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("new_hours", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("old_time", models.CharField(blank=True, default="", max_length=32)),
                ("new_time", models.CharField(blank=True, default="", max_length=32)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("medical", "Medical certificate"),
                            ("official", "Official leave / permission"),
                            ("technical", "Data-entry error"),
                            ("appeal", "Appeal decision"),
                            ("other", "Other (see note)"),
                        ],
                        max_length=12,
                    ),
                ),
                ("note", models.TextField(help_text="Düzəlişin izahı (məcburi).")),
                (
                    "document",
                    models.FileField(
                        help_text="Əsas sənəd — yalnız PDF (məcburi).",
                        upload_to=apps.registrar.models.corrections.lesson_correction_document_path,
                        validators=[
                            core.upload_security.FileUploadValidator(allowed_extensions={".pdf"}, max_size_mb=10)
                        ],
                    ),
                ),
                ("corrected_by_name", models.CharField(editable=False, max_length=200)),
                (
                    "corrected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lesson_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="corrections", to="registrar.lesson"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_corrections",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "lesson correction",
                "verbose_name_plural": "lesson corrections",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["organization", "lesson"], name="registrar_l_organiz_7ae64c_idx"),
                    models.Index(fields=["organization", "-created_at"], name="registrar_l_organiz_5e1298_idx"),
                ],
            },
        ),
    ]
