# Generated by Django 5.2.15 on 2026-07-21 00:34

import apps.registrar.models.corrections
import core.upload_security
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0026_seed_ikt_rehber_role"),
        ("registrar", "0031_rls_lesson_correction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseWorkCorrection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("old_score", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("new_score", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("old_topic", models.CharField(blank=True, default="", max_length=255)),
                ("new_topic", models.CharField(blank=True, default="", max_length=255)),
                ("old_date", models.DateField(blank=True, null=True)),
                ("new_date", models.DateField(blank=True, null=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("medical", "Medical certificate"),
                            ("official", "Official leave / permission"),
                            ("technical", "Data-entry error"),
                            ("appeal", "Appeal decision"),
                            ("other", "Other (see note)"),
                        ],
                        max_length=12,
                    ),
                ),
                ("note", models.TextField(help_text="Düzəlişin izahı (məcburi).")),
                (
                    "document",
                    models.FileField(
                        help_text="Əsas sənəd — yalnız PDF (məcburi).",
                        upload_to=apps.registrar.models.corrections.coursework_correction_document_path,
                        validators=[
                            core.upload_security.FileUploadValidator(allowed_extensions={".pdf"}, max_size_mb=10)
                        ],
                    ),
                ),
                ("corrected_by_name", models.CharField(editable=False, max_length=200)),
                (
                    "corrected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coursework_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coursework_corrections",
                        to="registrar.enrollment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coursework_corrections",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "course-work correction",
                "verbose_name_plural": "course-work corrections",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["organization", "enrollment"], name="registrar_c_organiz_adc860_idx"),
                    models.Index(fields=["organization", "-created_at"], name="registrar_c_organiz_c121db_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SelfWorkCorrection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("old_done", models.BooleanField(default=False)),
                ("new_done", models.BooleanField(default=False)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("medical", "Medical certificate"),
                            ("official", "Official leave / permission"),
                            ("technical", "Data-entry error"),
                            ("appeal", "Appeal decision"),
                            ("other", "Other (see note)"),
                        ],
                        max_length=12,
                    ),
                ),
                ("note", models.TextField(help_text="Düzəlişin izahı (məcburi).")),
                (
                    "document",
                    models.FileField(
                        help_text="Əsas sənəd — yalnız PDF (məcburi).",
                        upload_to=apps.registrar.models.corrections.selfwork_correction_document_path,
                        validators=[
                            core.upload_security.FileUploadValidator(allowed_extensions={".pdf"}, max_size_mb=10)
                        ],
                    ),
                ),
                ("corrected_by_name", models.CharField(editable=False, max_length=200)),
                (
                    "corrected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selfwork_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selfwork_corrections",
                        to="registrar.enrollment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selfwork_corrections",
                        to="organizations.organization",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrections",
                        to="registrar.selfworktopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "self-work correction",
                "verbose_name_plural": "self-work corrections",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["organization", "topic", "enrollment"], name="registrar_s_organiz_ab8d29_idx"),
                    models.Index(fields=["organization", "-created_at"], name="registrar_s_organiz_71fb60_idx"),
                ],
            },
        ),
    ]
