# Generated by Django 5.2.15 on 2026-07-21 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0036_lessoncorrection_new_instructor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessoncorrection",
            name="is_deletion",
            field=models.BooleanField(default=False, help_text="Bu qeyd dərsin silinməsidir (redaktə deyil)."),
        ),
        migrations.AddField(
            model_name="lessoncorrection",
            name="lesson_label",
            field=models.CharField(blank=True, default="", help_text="Silinmə üçün dərs snapshotu.", max_length=120),
        ),
        migrations.AlterField(
            model_name="lessoncorrection",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrections",
                to="registrar.lesson",
            ),
        ),
    ]
