# Generated by Django 5.2.15 on 2026-07-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0037_lessoncorrection_is_deletion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalcorrection",
            name="created_mark",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
