# Generated by Django 5.2.16 on 2026-08-22 22:47

import django.db.models.deletion
from django.db import migrations, models

_TRIGGER_SQL = r"""
CREATE OR REPLACE FUNCTION public.registrar_validate_enrollment_supersession()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $function$
DECLARE
    successor RECORD;
    source_offering RECORD;
BEGIN
    IF NEW.superseded_by_id IS NOT NULL THEN
        IF NEW.id = NEW.superseded_by_id THEN
            RAISE EXCEPTION 'enrollment cannot supersede itself'
                USING ERRCODE = '23514';
        END IF;

        SELECT e.organization_id, e.student_id, o.subject_id, o.period_id
          INTO successor
          FROM public.registrar_enrollment e
          JOIN public.registrar_courseoffering o ON o.id = e.offering_id
         WHERE e.id = NEW.superseded_by_id;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'successor enrollment does not exist or is outside tenant scope'
                USING ERRCODE = '23514';
        END IF;

        SELECT o.subject_id, o.period_id
          INTO source_offering
          FROM public.registrar_courseoffering o
         WHERE o.id = NEW.offering_id;

        IF successor.organization_id IS DISTINCT FROM NEW.organization_id
           OR successor.student_id IS DISTINCT FROM NEW.student_id
           OR successor.subject_id IS DISTINCT FROM source_offering.subject_id
           OR successor.period_id IS DISTINCT FROM source_offering.period_id THEN
            RAISE EXCEPTION
                'successor must have the same organization, student, subject and period'
                USING ERRCODE = '23514';
        END IF;

        IF EXISTS (
            WITH RECURSIVE successor_chain AS (
                SELECT e.id, e.superseded_by_id, ARRAY[e.id]::uuid[] AS path
                  FROM public.registrar_enrollment e
                 WHERE e.id = NEW.superseded_by_id
                UNION ALL
                SELECT e.id, e.superseded_by_id, chain.path || e.id
                  FROM public.registrar_enrollment e
                  JOIN successor_chain chain ON e.id = chain.superseded_by_id
                 WHERE NOT e.id = ANY(chain.path)
            )
            SELECT 1 FROM successor_chain WHERE id = NEW.id
        ) THEN
            RAISE EXCEPTION 'enrollment supersession cycle is not allowed'
                USING ERRCODE = '23514';
        END IF;
    END IF;

    -- Protect existing inbound links when a successor row is raw-updated.
    IF EXISTS (
        SELECT 1
          FROM public.registrar_enrollment predecessor
          JOIN public.registrar_courseoffering predecessor_offering
            ON predecessor_offering.id = predecessor.offering_id
          JOIN public.registrar_courseoffering new_offering
            ON new_offering.id = NEW.offering_id
         WHERE predecessor.superseded_by_id = NEW.id
           AND (
               predecessor.organization_id IS DISTINCT FROM NEW.organization_id
               OR predecessor.student_id IS DISTINCT FROM NEW.student_id
               OR predecessor_offering.subject_id IS DISTINCT FROM new_offering.subject_id
               OR predecessor_offering.period_id IS DISTINCT FROM new_offering.period_id
           )
    ) THEN
        RAISE EXCEPTION
            'successor update would break enrollment supersession integrity'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS registrar_enrollment_supersession_guard
    ON public.registrar_enrollment;
CREATE TRIGGER registrar_enrollment_supersession_guard
BEFORE INSERT OR UPDATE ON public.registrar_enrollment
FOR EACH ROW EXECUTE FUNCTION public.registrar_validate_enrollment_supersession();
"""

_DROP_TRIGGER_SQL = r"""
DROP TRIGGER IF EXISTS registrar_enrollment_supersession_guard
    ON public.registrar_enrollment;
DROP FUNCTION IF EXISTS public.registrar_validate_enrollment_supersession();
"""


def _install_postgres_guard(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(_TRIGGER_SQL)


def _remove_postgres_guard(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(_DROP_TRIGGER_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0038_journalcorrection_created_mark"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Qrup köçürməsində bu qeydiyyatı əvəz edən cari qeydiyyat.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="superseded_enrollments",
                to="registrar.enrollment",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.CheckConstraint(
                condition=models.Q(("superseded_by__isnull", True), ("status", "dropped"), _connector="OR"),
                name="superseded_enrollment_is_dropped",
            ),
        ),
        migrations.RunPython(_install_postgres_guard, _remove_postgres_guard),
    ]
