# Generated by Django 5.2.17 on 2026-08-26 08:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0030_journal_close_permission"),
        ("registrar", "0045_reference_identity_and_group_transfer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentscheme",
            name="returned_reason",
            field=models.TextField(blank=True, help_text="LEGACY: geri qaytarılma səbəbi (köhnə təsdiq zənciri)."),
        ),
        migrations.CreateModel(
            name="JournalCloseNotice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("organization", "Bütün universitet"),
                            ("faculty", "Fakültə"),
                            ("department", "Kafedra"),
                        ],
                        default="organization",
                        max_length=16,
                    ),
                ),
                (
                    "closes_on",
                    models.DateField(
                        help_text="Bu tarixdən SONRA jurnala yazmaq olmayacaq (tarix özü daxildir).",
                        verbose_name="bağlanma tarixi",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        help_text="Standart mətn əvəzinə göstəriləcək öz mətniniz (opsional).",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fakültə/kafedra əhatəsi üçün bölmə; org əhatəsində boşdur.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_close_notices",
                        to="organizations.orgunit",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_close_notices",
                        to="organizations.organization",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_close_notices",
                        to="organizations.academicperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jurnal bağlanma xəbərdarlığı",
                "verbose_name_plural": "Jurnal bağlanma xəbərdarlıqları",
                "ordering": ["-closes_on"],
                "indexes": [models.Index(fields=["organization", "period"], name="registrar_j_organiz_249780_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "period", "scope", "org_unit"), name="uniq_journal_close_notice_unit"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("scope", "organization")),
                        fields=("organization", "period"),
                        name="uniq_journal_close_notice_org",
                    ),
                ],
            },
        ),
    ]
