# Generated by Django 5.2.17 on 2026-08-26 09:50

import apps.registrar.models.exam_score_entry
import core.upload_security
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0031_seed_exam_score_entry_permission"),
        ("registrar", "0048_reset_intermediate_approval_states"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamScoreEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[("initial", "Initial entry"), ("correction", "Documented change")],
                        default="initial",
                        max_length=12,
                    ),
                ),
                ("old_score", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("new_score", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("medical", "Medical certificate"),
                            ("official", "Official leave / permission"),
                            ("technical", "Data-entry error"),
                            ("appeal", "Appeal decision"),
                            ("other", "Other (see note)"),
                        ],
                        help_text="Dəyişiklik səbəbi — yalnız sonrakı düzəlişdə məcburi.",
                        max_length=12,
                    ),
                ),
                ("note", models.TextField(blank=True, help_text="Mətn qeydi (ilkin daxiletmədə opsional).")),
                (
                    "evidence",
                    models.FileField(
                        blank=True,
                        help_text="İmtahan vərəqinin şəkli / PDF-i — ilkin daxiletmədə opsional, düzəlişdə məcburi.",
                        upload_to=apps.registrar.models.exam_score_entry.exam_score_evidence_path,
                        validators=[
                            core.upload_security.FileUploadValidator(
                                allowed_extensions={".heic", ".heif", ".jpeg", ".jpg", ".pdf", ".png", ".webp"},
                                max_size_mb=10,
                            )
                        ],
                    ),
                ),
                ("entered_by_name", models.CharField(editable=False, max_length=200)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_score_entries",
                        to="registrar.enrollment",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_score_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_score_entries",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "exam score entry",
                "verbose_name_plural": "exam score entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["organization", "enrollment"], name="registrar_e_organiz_bf528a_idx"),
                    models.Index(fields=["organization", "-created_at"], name="registrar_e_organiz_8391db_idx"),
                ],
            },
        ),
    ]
