# Generated by Django 5.2.17 on 2026-08-26 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0062_question_bank_subject_kind_teacher"),
        ("registrar", "0050_rls_exam_score_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="room",
            field=models.ForeignKey(
                blank=True,
                help_text="Dərsin keçirildiyi otaq (opsional). Korpus otağın öz 'building' sahəsindədir.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="exams.examroom",
            ),
        ),
    ]
