# Generated by Django 5.2.13 on 2026-08-27 19:28

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

_TABLES = (
    "registrar_legacygradefact",
    "registrar_legacygradereview",
)

_FORWARD_SQL = r"""
CREATE OR REPLACE FUNCTION public.registrar_guard_legacy_grade_append_only()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
DECLARE
    has_rows boolean;
BEGIN
    IF TG_OP = 'TRUNCATE' THEN
        IF COALESCE((SELECT usesuper FROM pg_user WHERE usename = session_user), false) THEN
            RETURN NULL;
        END IF;
        EXECUTE format(
            'SELECT EXISTS (SELECT 1 FROM %%I.%%I)',
            TG_TABLE_SCHEMA,
            TG_TABLE_NAME
        ) INTO has_rows;
        IF NOT has_rows THEN
            RETURN NULL;
        END IF;
    END IF;
    RAISE EXCEPTION 'registrar legacy grade evidence is append-only: %%', TG_OP
        USING ERRCODE = '23514';
END;
$function$;

CREATE OR REPLACE FUNCTION public.registrar_guard_legacy_grade_fact_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
BEGIN
    IF NEW.requires_exam_center_review IS DISTINCT FROM true THEN
        RAISE EXCEPTION 'legacy grade fact requires exam-center review'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.enrollment_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
          FROM public.registrar_enrollment enrollment
         WHERE enrollment.id = NEW.enrollment_id
           AND enrollment.organization_id = NEW.organization_id
    ) THEN
        RAISE EXCEPTION 'legacy grade fact enrollment must belong to the same organization'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.registrar_guard_legacy_grade_review_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM public.registrar_legacygradefact fact
         WHERE fact.id = NEW.fact_id
           AND fact.organization_id = NEW.organization_id
    ) THEN
        RAISE EXCEPTION 'legacy grade review fact must belong to the same organization'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.reviewed_by_id IS NULL OR NOT public.registrar_actor_can_write_for_organization(
        NEW.organization_id,
        NEW.reviewed_by_id
    ) THEN
        RAISE EXCEPTION 'legacy grade reviewer is not authorized for the organization'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION public.registrar_guard_legacy_grade_append_only() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.registrar_guard_legacy_grade_fact_insert() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.registrar_guard_legacy_grade_review_insert() FROM PUBLIC;
"""

_REVERSE_SQL = r"""
DROP FUNCTION IF EXISTS public.registrar_guard_legacy_grade_review_insert();
DROP FUNCTION IF EXISTS public.registrar_guard_legacy_grade_fact_insert();
DROP FUNCTION IF EXISTS public.registrar_guard_legacy_grade_append_only();
"""


def _apply_security(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(_FORWARD_SQL)
    for table in _TABLES:
        schema_editor.execute(f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY")
        schema_editor.execute(f"ALTER TABLE public.{table} FORCE ROW LEVEL SECURITY")
        schema_editor.execute(f"DROP POLICY IF EXISTS rls_tenant_isolation ON public.{table}")
        schema_editor.execute(f"""
            CREATE POLICY rls_tenant_isolation ON public.{table}
            USING (
                current_setting('app.bypass_rls', true) = 'on'
                OR organization_id::text = NULLIF(current_setting('app.current_org_id', true), '')
            )
            WITH CHECK (
                current_setting('app.bypass_rls', true) = 'on'
                OR organization_id::text = NULLIF(current_setting('app.current_org_id', true), '')
            )
            """)
        schema_editor.execute(
            f"CREATE TRIGGER registrar_legacy_grade_append_only_update "
            f"BEFORE UPDATE ON public.{table} FOR EACH ROW "
            "EXECUTE FUNCTION public.registrar_guard_legacy_grade_append_only()"
        )
        schema_editor.execute(
            f"CREATE TRIGGER registrar_legacy_grade_append_only_delete "
            f"BEFORE DELETE ON public.{table} FOR EACH ROW "
            "EXECUTE FUNCTION public.registrar_guard_legacy_grade_append_only()"
        )
        schema_editor.execute(
            f"CREATE TRIGGER registrar_legacy_grade_append_only_truncate "
            f"BEFORE TRUNCATE ON public.{table} FOR EACH STATEMENT "
            "EXECUTE FUNCTION public.registrar_guard_legacy_grade_append_only()"
        )
    schema_editor.execute(
        "CREATE TRIGGER registrar_legacy_grade_fact_insert "
        "BEFORE INSERT ON public.registrar_legacygradefact FOR EACH ROW "
        "EXECUTE FUNCTION public.registrar_guard_legacy_grade_fact_insert()"
    )
    schema_editor.execute(
        "CREATE TRIGGER registrar_legacy_grade_review_insert "
        "BEFORE INSERT ON public.registrar_legacygradereview FOR EACH ROW "
        "EXECUTE FUNCTION public.registrar_guard_legacy_grade_review_insert()"
    )


def _revert_security(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "DROP TRIGGER IF EXISTS registrar_legacy_grade_fact_insert ON public.registrar_legacygradefact"
    )
    schema_editor.execute(
        "DROP TRIGGER IF EXISTS registrar_legacy_grade_review_insert ON public.registrar_legacygradereview"
    )
    for table in reversed(_TABLES):
        for suffix in ("update", "delete", "truncate"):
            schema_editor.execute(
                f"DROP TRIGGER IF EXISTS registrar_legacy_grade_append_only_{suffix} ON public.{table}"
            )
        schema_editor.execute(f"DROP POLICY IF EXISTS rls_tenant_isolation ON public.{table}")
        schema_editor.execute(f"ALTER TABLE public.{table} NO FORCE ROW LEVEL SECURITY")
        schema_editor.execute(f"ALTER TABLE public.{table} DISABLE ROW LEVEL SECURITY")
    schema_editor.execute(_REVERSE_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0032_seed_alumni_role"),
        ("registrar", "0051_lesson_room"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyGradeFact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "source_system",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[a-z0-9][a-z0-9._-]{0,63}\\Z", "Dəyər təhlükəsiz token formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                (
                    "source_table",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[a-z0-9][a-z0-9._-]{0,63}\\Z", "Dəyər təhlükəsiz token formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                ("source_pk", models.PositiveBigIntegerField()),
                (
                    "source_snapshot_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[0-9a-f]{64}\\Z", "SHA-256 lowercase hex formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                (
                    "source_row_hash",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[0-9a-f]{64}\\Z", "SHA-256 lowercase hex formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                (
                    "materialization_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[0-9a-f]{64}\\Z", "SHA-256 lowercase hex formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                (
                    "transform_version",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[a-z0-9][a-z0-9._-]{0,63}\\Z", "Dəyər təhlükəsiz token formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                (
                    "evidence_kind",
                    models.CharField(
                        choices=[
                            ("summary", "Legacy summary"),
                            ("exam", "Legacy exam"),
                            ("resit", "Legacy resit"),
                            ("other", "Other legacy grade code"),
                        ],
                        max_length=16,
                    ),
                ),
                ("score_code", models.CharField(blank=True, default="", max_length=16)),
                ("is_archive", models.BooleanField(default=False)),
                (
                    "mapping_status",
                    models.CharField(
                        choices=[
                            ("linked", "Linked"),
                            ("group_mismatch", "Historical group mismatch"),
                            ("discarded_source", "Discarded legacy journal"),
                            ("unresolved", "Unresolved"),
                            ("conflict", "Conflicting source rows"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "mapping_issue_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[a-z0-9][a-z0-9._-]{0,63}\\Z", "Dəyər təhlükəsiz token formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                ("source_student_ref", models.CharField(blank=True, default="", max_length=64)),
                ("source_journal_ref", models.CharField(blank=True, default="", max_length=255)),
                ("source_lesson_ref", models.CharField(blank=True, default="", max_length=64)),
                ("source_group_ref", models.CharField(blank=True, default="", max_length=64)),
                ("source_enrollment_ref", models.CharField(blank=True, default="", max_length=320)),
                ("entry_score_text", models.CharField(blank=True, default="", max_length=64)),
                ("exam_score_text", models.CharField(blank=True, default="", max_length=64)),
                ("resit_score_text", models.CharField(blank=True, default="", max_length=64)),
                ("final_score_text", models.CharField(blank=True, default="", max_length=64)),
                ("raw_score_text", models.CharField(blank=True, default="", max_length=64)),
                ("entry_score", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("exam_score", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("resit_score", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("final_score", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("legacy_kesr", models.IntegerField(blank=True, null=True)),
                ("legacy_level", models.IntegerField(blank=True, null=True)),
                ("legacy_guzest_girish_text", models.CharField(blank=True, default="", max_length=64)),
                ("legacy_guzest_artim_text", models.CharField(blank=True, default="", max_length=64)),
                ("requires_exam_center_review", models.BooleanField(default=True, editable=False)),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Həll olunubsa cari qeydiyyat; tapılmasa xam fakt yenə saxlanır.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_grade_facts",
                        to="registrar.enrollment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_grade_facts",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "legacy grade fact",
                "verbose_name_plural": "legacy grade facts",
                "ordering": ["source_table", "source_pk"],
            },
        ),
        migrations.CreateModel(
            name="LegacyGradeReview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("disputed", "Disputed"),
                            ("correction_required", "Correction required"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[a-z0-9][a-z0-9._-]{0,63}\\Z", "Dəyər təhlükəsiz token formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "evidence_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[0-9a-f]{64}\\Z", "SHA-256 lowercase hex formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                ("reviewed_by_name", models.CharField(editable=False, max_length=200)),
                (
                    "fact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="registrar.legacygradefact",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_grade_reviews",
                        to="organizations.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_grade_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "legacy grade review",
                "verbose_name_plural": "legacy grade reviews",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="legacygradefact",
            index=models.Index(fields=["organization", "enrollment"], name="reg_legacy_grade_org_enroll"),
        ),
        migrations.AddIndex(
            model_name="legacygradefact",
            index=models.Index(fields=["organization", "mapping_status"], name="reg_legacy_grade_org_map"),
        ),
        migrations.AddConstraint(
            model_name="legacygradefact",
            constraint=models.UniqueConstraint(
                fields=("organization", "source_system", "source_table", "source_pk"),
                name="registrar_legacy_grade_source_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacygradefact",
            constraint=models.CheckConstraint(
                condition=models.Q(("requires_exam_center_review", True)), name="registrar_legacy_grade_review_required"
            ),
        ),
        migrations.AddIndex(
            model_name="legacygradereview",
            index=models.Index(fields=["organization", "fact", "created_at"], name="reg_legacy_review_fact_time"),
        ),
        migrations.RunPython(_apply_security, _revert_security),
    ]
