# Generated by Django 5.2.17 on 2026-08-28 22:09

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

_FORWARD_SQL = r"""
CREATE OR REPLACE FUNCTION public.registrar_actor_can_import_legacy_grade(
    target_organization uuid,
    target_user bigint
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
    SELECT EXISTS (
        SELECT 1
          FROM public.organizations_organization organization
          JOIN public.auth_user actor
            ON actor.id = organization.owner_id
           AND actor.is_active
         WHERE organization.id = target_organization
           AND organization.is_active
           AND organization.owner_id = target_user
    ) OR EXISTS (
        SELECT 1
          FROM public.auth_user actor
          JOIN public.organizations_organization organization
            ON organization.id = target_organization
           AND organization.is_active
         WHERE actor.id = target_user
           AND actor.is_active
           AND actor.is_superuser
    );
$function$;

CREATE OR REPLACE FUNCTION public.registrar_guard_legacy_grade_artifact_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
DECLARE
    session_actor bigint;
BEGIN
    IF NEW.requires_exam_center_review IS DISTINCT FROM true THEN
        RAISE EXCEPTION 'legacy grade artifact requires exam-center review'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.source_system IS DISTINCT FROM 'myedu_mariadb'
       OR NEW.source_table IS DISTINCT FROM 'balvereqi_logs'
       OR NEW.artifact_kind IS DISTINCT FROM 'score_sheet_export' THEN
        RAISE EXCEPTION 'legacy grade artifact source contract is invalid'
            USING ERRCODE = '23514';
    END IF;
    IF COALESCE(NEW.source_owner_ref, '') = ''
       OR COALESCE(NEW.source_journal_ref, '') = ''
       OR COALESCE(NEW.source_exported_at_text, '') = ''
       OR NEW.payload_size_bytes <= 0
       OR OCTET_LENGTH(NEW.payload_zlib) <= 0 THEN
        RAISE EXCEPTION 'legacy grade artifact payload metadata is incomplete'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.source_row_hash !~ '^[0-9a-f]{64}$'
       OR NEW.materialization_digest !~ '^[0-9a-f]{64}$'
       OR NEW.source_snapshot_sha256 !~ '^[0-9a-f]{64}$'
       OR NEW.payload_sha256 !~ '^[0-9a-f]{64}$' THEN
        RAISE EXCEPTION 'legacy grade artifact digest is invalid'
            USING ERRCODE = '23514';
    END IF;
    IF current_setting('app.bypass_rls', true) IS DISTINCT FROM 'on' THEN
        BEGIN
            session_actor := NULLIF(current_setting('app.current_user_id', true), '')::bigint;
        EXCEPTION WHEN invalid_text_representation THEN
            session_actor := NULL;
        END;
        IF session_actor IS NULL OR NOT public.registrar_actor_can_import_legacy_grade(
            NEW.organization_id,
            session_actor
        ) THEN
            RAISE EXCEPTION 'legacy grade artifact import actor is not authorized'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$function$;

ALTER TABLE public.registrar_legacygradeartifact ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registrar_legacygradeartifact FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_tenant_isolation ON public.registrar_legacygradeartifact;
CREATE POLICY rls_tenant_isolation ON public.registrar_legacygradeartifact
USING (
    current_setting('app.bypass_rls', true) = 'on'
    OR organization_id::text = NULLIF(current_setting('app.current_org_id', true), '')
)
WITH CHECK (
    current_setting('app.bypass_rls', true) = 'on'
    OR organization_id::text = NULLIF(current_setting('app.current_org_id', true), '')
);

CREATE TRIGGER registrar_legacy_grade_artifact_append_only_update
BEFORE UPDATE ON public.registrar_legacygradeartifact FOR EACH ROW
EXECUTE FUNCTION public.registrar_guard_legacy_grade_append_only();
CREATE TRIGGER registrar_legacy_grade_artifact_append_only_delete
BEFORE DELETE ON public.registrar_legacygradeartifact FOR EACH ROW
EXECUTE FUNCTION public.registrar_guard_legacy_grade_append_only();
CREATE TRIGGER registrar_legacy_grade_artifact_append_only_truncate
BEFORE TRUNCATE ON public.registrar_legacygradeartifact FOR EACH STATEMENT
EXECUTE FUNCTION public.registrar_guard_legacy_grade_append_only();
CREATE TRIGGER registrar_legacy_grade_artifact_insert
BEFORE INSERT ON public.registrar_legacygradeartifact FOR EACH ROW
EXECUTE FUNCTION public.registrar_guard_legacy_grade_artifact_insert();

REVOKE ALL ON FUNCTION public.registrar_actor_can_import_legacy_grade(uuid, bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.registrar_guard_legacy_grade_artifact_insert() FROM PUBLIC;
"""

_REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS registrar_legacy_grade_artifact_insert
    ON public.registrar_legacygradeartifact;
DROP TRIGGER IF EXISTS registrar_legacy_grade_artifact_append_only_update
    ON public.registrar_legacygradeartifact;
DROP TRIGGER IF EXISTS registrar_legacy_grade_artifact_append_only_delete
    ON public.registrar_legacygradeartifact;
DROP TRIGGER IF EXISTS registrar_legacy_grade_artifact_append_only_truncate
    ON public.registrar_legacygradeartifact;
DROP POLICY IF EXISTS rls_tenant_isolation ON public.registrar_legacygradeartifact;
ALTER TABLE public.registrar_legacygradeartifact NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.registrar_legacygradeartifact DISABLE ROW LEVEL SECURITY;
DROP FUNCTION IF EXISTS public.registrar_guard_legacy_grade_artifact_insert();

CREATE OR REPLACE FUNCTION public.registrar_actor_can_import_legacy_grade(
    target_organization uuid,
    target_user bigint
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
    SELECT EXISTS (
        SELECT 1
          FROM public.organizations_membership membership
          JOIN public.organizations_organization organization
            ON organization.id = membership.organization_id
           AND organization.is_active
          JOIN public.organizations_role role
            ON role.id = membership.role_id
           AND role.organization_id = target_organization
           AND role.is_active
          JOIN public.auth_user actor
            ON actor.id = membership.user_id
           AND actor.is_active
         WHERE membership.organization_id = target_organization
           AND membership.user_id = target_user
           AND membership.is_active
           AND (
               COALESCE(role.permissions, '[]'::jsonb) ? '*'
               OR COALESCE(role.permissions, '[]'::jsonb) ? 'member.invite'
               OR COALESCE(role.permissions, '[]'::jsonb) ? 'member.*'
           )
    ) OR EXISTS (
        SELECT 1
          FROM public.organizations_organization organization
          JOIN public.auth_user actor
            ON actor.id = organization.owner_id
           AND actor.is_active
         WHERE organization.id = target_organization
           AND organization.is_active
           AND organization.owner_id = target_user
    ) OR EXISTS (
        SELECT 1
          FROM public.auth_user actor
          JOIN public.organizations_organization organization
            ON organization.id = target_organization
           AND organization.is_active
         WHERE actor.id = target_user
           AND actor.is_active
           AND actor.is_superuser
    );
$function$;

REVOKE ALL ON FUNCTION public.registrar_actor_can_import_legacy_grade(uuid, bigint) FROM PUBLIC;
"""


def _forward_security(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(_FORWARD_SQL)


def _reverse_security(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(_REVERSE_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0032_seed_alumni_role"),
        ("registrar", "0053_legacy_grade_write_authorization"),
    ]

    operations = [
        migrations.AddField(
            model_name="legacygradefact",
            name="legacy_attempt_type",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="legacygradefact",
            name="legacy_recorded_at_text",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="legacygradefact",
            name="evidence_kind",
            field=models.CharField(
                choices=[
                    ("summary", "Legacy summary"),
                    ("exam", "Legacy exam"),
                    ("resit", "Legacy resit"),
                    ("exam_entry_exit", "Legacy exam entry/exit attempt"),
                    ("other", "Other legacy grade code"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="LegacyGradeArtifact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "source_system",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[a-z0-9][a-z0-9._-]{0,63}\\Z", "Dəyər təhlükəsiz token formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                (
                    "source_table",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[a-z0-9][a-z0-9._-]{0,63}\\Z", "Dəyər təhlükəsiz token formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                ("source_pk", models.PositiveBigIntegerField()),
                (
                    "source_snapshot_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[0-9a-f]{64}\\Z", "SHA-256 lowercase hex formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                (
                    "source_row_hash",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[0-9a-f]{64}\\Z", "SHA-256 lowercase hex formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                (
                    "materialization_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[0-9a-f]{64}\\Z", "SHA-256 lowercase hex formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                (
                    "transform_version",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[a-z0-9][a-z0-9._-]{0,63}\\Z", "Dəyər təhlükəsiz token formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                (
                    "artifact_kind",
                    models.CharField(choices=[("score_sheet_export", "Legacy score-sheet export")], max_length=32),
                ),
                ("source_owner_ref", models.CharField(blank=True, default="", max_length=64)),
                ("source_journal_ref", models.CharField(blank=True, default="", max_length=255)),
                ("source_exported_at_text", models.CharField(blank=True, default="", max_length=64)),
                (
                    "payload_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[0-9a-f]{64}\\Z", "SHA-256 lowercase hex formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                ("payload_size_bytes", models.PositiveBigIntegerField()),
                ("payload_zlib", models.BinaryField()),
                ("requires_exam_center_review", models.BooleanField(default=True, editable=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_grade_artifacts",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "legacy grade artifact",
                "verbose_name_plural": "legacy grade artifacts",
                "ordering": ["source_table", "source_pk"],
                "indexes": [
                    models.Index(fields=["organization", "source_journal_ref"], name="reg_legacy_art_org_journal")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "source_system", "source_table", "source_pk"),
                        name="registrar_legacy_grade_artifact_source_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("requires_exam_center_review", True)),
                        name="registrar_legacy_artifact_review_required",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("payload_size_bytes__gt", 0)),
                        name="registrar_legacy_artifact_payload_nonempty",
                    ),
                ],
            },
        ),
        migrations.RunPython(_forward_security, _reverse_security),
    ]
