# Generated by Django 5.2.13 on 2026-08-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0056_enrollment_guest_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentacademicrecord",
            name="national_athlete_exemption",
            field=models.BooleanField(
                db_default=False,
                db_index=True,
                default=False,
                help_text="Milli yığma komandanın üzvü olan idmançı-tələbə — 25% qayıb həddi imtahana buraxılışı ləğv etmir (bal yenə real qayıba görə hesablanır).",
            ),
        ),
        migrations.AddField(
            model_name="studentacademicrecord",
            name="national_athlete_exemption_note",
            field=models.CharField(
                blank=True,
                db_default="",
                help_text="İstisnanın rəsmi əsası (Kollegiya qərarının nömrəsi/tarixi) — audit üçün.",
                max_length=255,
            ),
        ),
    ]
