"""Fənnin başqa müəllimə təhvili — ``TeachingHandover`` + RLS + eyni-tenant qoruyucusu.

Üç qat:

1. **Cədvəl** — təhvil hadisəsi (kimdən, kimə, niyə, kim etdi, geri qaytarılıbmı).
2. **RLS** — birbaşa ``organization_id`` izolyasiyası (0050 naxışı).
3. **DB qoruyucusu** — ``registrar_handover_same_org_guard``: təhvil qeydinin
   açılışı öz təşkilatına aid olmalıdır. Mövcud ``registrar_guard_same_org_fk``
   funksiyası təkrar işlədilir (yeni funksiya yaradılmır).
"""

# Generated by Django 5.2.15 on 2026-08-30 23:52

import apps.registrar.reference_identity
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


_BYPASS_EXPR = "current_setting('app.bypass_rls', true) = 'on'"
_CURRENT_ORG = "NULLIF(current_setting('app.current_org_id', true), '')"
_ORG_EXPR = f"organization_id::text = {_CURRENT_ORG}"
_TABLE = "registrar_teachinghandover"


def _apply(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        f"""
ALTER TABLE {_TABLE} ENABLE ROW LEVEL SECURITY;
ALTER TABLE {_TABLE} FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_tenant_isolation ON {_TABLE};
CREATE POLICY rls_tenant_isolation ON {_TABLE}
    USING ({_BYPASS_EXPR} OR {_ORG_EXPR})
    WITH CHECK ({_BYPASS_EXPR} OR {_ORG_EXPR});
"""
    )
    schema_editor.execute(f"DROP TRIGGER IF EXISTS registrar_handover_same_org_guard ON public.{_TABLE}")
    schema_editor.execute(
        f"CREATE TRIGGER registrar_handover_same_org_guard "
        f"BEFORE INSERT OR UPDATE OF offering_id, organization_id ON public.{_TABLE} "
        f"FOR EACH ROW EXECUTE FUNCTION public.registrar_guard_same_org_fk("
        f"'offering_id', 'registrar_courseoffering', 'handover offering')"
    )


def _revert(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(f"DROP TRIGGER IF EXISTS registrar_handover_same_org_guard ON public.{_TABLE}")
    schema_editor.execute(
        f"""
DROP POLICY IF EXISTS rls_tenant_isolation ON {_TABLE};
ALTER TABLE {_TABLE} NO FORCE ROW LEVEL SECURITY;
ALTER TABLE {_TABLE} DISABLE ROW LEVEL SECURITY;
"""
    )


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0032_seed_alumni_role"),
        ("registrar", "0057_student_record_athlete_exemption"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeachingHandover",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("from_instructor_name", models.CharField(blank=True, max_length=255)),
                ("to_instructor_name", models.CharField(blank=True, max_length=255)),
                ("reason", models.TextField(help_text="Təhvilin səbəbi — MƏCBURİDİR (audit sualının cavabı).")),
                ("reverted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("revert_reason", models.TextField(blank=True)),
                ("notified", models.BooleanField(default=False)),
                (
                    "from_instructor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Təhvildən ƏVVƏLKİ müəllim (boş ola bilər — açılış müəllimsiz idi).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handovers_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        help_text="Təhvil verilən dərs açılışı (fənn × semestr × qrup).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handovers",
                        to="registrar.courseoffering",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_handovers",
                        to="organizations.organization",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Təhvili aparan aktor (RİM / dekan / kafedra müdiri).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teaching_handovers_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reverted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teaching_handovers_reverted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_instructor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Təhvildən SONRAKI müəllim.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handovers_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "fənn təhvili qeydi",
                "verbose_name_plural": "fənn təhvili qeydləri",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "offering", "-created_at"], name="registrar_t_organiz_2a561f_idx"
                    ),
                    models.Index(fields=["organization", "from_instructor"], name="registrar_t_organiz_e5a910_idx"),
                    models.Index(fields=["organization", "to_instructor"], name="registrar_t_organiz_8d7ed5_idx"),
                ],
            },
            bases=(apps.registrar.reference_identity.ReferenceIdentityValidationMixin, models.Model),
        ),
        migrations.RunPython(_apply, _revert),
    ]
