# Generated by Django 5.2.17 on 2026-08-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0058_teaching_handover"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="is_legacy_synthesised",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Bu dərs köhnə sistemin dərs cədvəlində yoxdur — mövcud bal/davamiyyət xanalarının (ay, gün, saat) açarından bərpa olunub. Xananın dəyəri mənbədəndir.",
            ),
        ),
    ]
