# Generated by Django 5.2.13 on 2026-08-31 05:30
"""Üzrlü qayıb sənədləri (``allowed_qb``) — append-only tenant sübutu.

Sxem qatı ilə yanaşı DB qatı da qorunur (0052 ilə eyni ruh): tenant RLS,
DELETE/TRUNCATE tam qadağan, UPDATE isə YALNIZ boş ``document`` sahəsinə fayl
qoşulması üçün açıqdır — qalan hər sütun dəyişməz olmalıdır.  Beləliklə sahib
faylları köhnə serverdən gətirəndə qoşa bilir, amma heç bir köhnə dəyər (tarix,
izah, tələbə, mənbə möhürləri) nə əl ilə, nə xam SQL ilə dəyişdirilə bilmir.
"""

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.registrar.models.legacy_excuse
import core.upload_security

_TABLE = "registrar_legacyexcusedocument"

_FORWARD_SQL = r"""
CREATE OR REPLACE FUNCTION public.registrar_guard_legacy_excuse_append_only()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
DECLARE
    has_rows boolean;
BEGIN
    IF TG_OP = 'TRUNCATE' THEN
        IF COALESCE((SELECT usesuper FROM pg_user WHERE usename = session_user), false) THEN
            RETURN NULL;
        END IF;
        EXECUTE format(
            'SELECT EXISTS (SELECT 1 FROM %%I.%%I)',
            TG_TABLE_SCHEMA,
            TG_TABLE_NAME
        ) INTO has_rows;
        IF NOT has_rows THEN
            RETURN NULL;
        END IF;
    END IF;
    RAISE EXCEPTION 'registrar legacy excuse evidence is append-only: %%', TG_OP
        USING ERRCODE = '23514';
END;
$function$;

CREATE OR REPLACE FUNCTION public.registrar_guard_legacy_excuse_attach_only()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
BEGIN
    -- Faylın qoşulmasından başqa hər şey dəyişməz: ``document`` və
    -- ``updated_at``-dan savayı BÜTÜN sütunlar eyni qalmalıdır.
    IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.organization_id IS DISTINCT FROM OLD.organization_id
       OR NEW.student_id IS DISTINCT FROM OLD.student_id
       OR NEW.source_system IS DISTINCT FROM OLD.source_system
       OR NEW.source_table IS DISTINCT FROM OLD.source_table
       OR NEW.source_pk IS DISTINCT FROM OLD.source_pk
       OR NEW.source_snapshot_sha256 IS DISTINCT FROM OLD.source_snapshot_sha256
       OR NEW.source_row_hash IS DISTINCT FROM OLD.source_row_hash
       OR NEW.materialization_digest IS DISTINCT FROM OLD.materialization_digest
       OR NEW.transform_version IS DISTINCT FROM OLD.transform_version
       OR NEW.mapping_status IS DISTINCT FROM OLD.mapping_status
       OR NEW.source_student_ref IS DISTINCT FROM OLD.source_student_ref
       OR NEW.source_owner_ref IS DISTINCT FROM OLD.source_owner_ref
       OR NEW.source_batch_ref IS DISTINCT FROM OLD.source_batch_ref
       OR NEW.starts_on IS DISTINCT FROM OLD.starts_on
       OR NEW.ends_on IS DISTINCT FROM OLD.ends_on
       OR NEW.source_window_text IS DISTINCT FROM OLD.source_window_text
       OR NEW.source_recorded_at_text IS DISTINCT FROM OLD.source_recorded_at_text
       OR NEW.note IS DISTINCT FROM OLD.note
       OR NEW.document_name IS DISTINCT FROM OLD.document_name
       OR NEW.created_at IS DISTINCT FROM OLD.created_at
    THEN
        RAISE EXCEPTION 'registrar legacy excuse evidence is append-only: UPDATE'
            USING ERRCODE = '23514';
    END IF;
    IF COALESCE(OLD.document, '') <> '' THEN
        RAISE EXCEPTION 'an attached legacy excuse document cannot be replaced'
            USING ERRCODE = '23514';
    END IF;
    IF COALESCE(NEW.document, '') = '' THEN
        RAISE EXCEPTION 'registrar legacy excuse evidence is append-only: UPDATE'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION public.registrar_guard_legacy_excuse_append_only() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.registrar_guard_legacy_excuse_attach_only() FROM PUBLIC;
"""

_REVERSE_SQL = r"""
DROP FUNCTION IF EXISTS public.registrar_guard_legacy_excuse_attach_only();
DROP FUNCTION IF EXISTS public.registrar_guard_legacy_excuse_append_only();
"""


def _apply_security(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(_FORWARD_SQL)
    schema_editor.execute(f"ALTER TABLE public.{_TABLE} ENABLE ROW LEVEL SECURITY")
    schema_editor.execute(f"ALTER TABLE public.{_TABLE} FORCE ROW LEVEL SECURITY")
    schema_editor.execute(f"DROP POLICY IF EXISTS rls_tenant_isolation ON public.{_TABLE}")
    schema_editor.execute(f"""
        CREATE POLICY rls_tenant_isolation ON public.{_TABLE}
        USING (
            current_setting('app.bypass_rls', true) = 'on'
            OR organization_id::text = NULLIF(current_setting('app.current_org_id', true), '')
        )
        WITH CHECK (
            current_setting('app.bypass_rls', true) = 'on'
            OR organization_id::text = NULLIF(current_setting('app.current_org_id', true), '')
        )
        """)
    schema_editor.execute(
        f"CREATE TRIGGER registrar_legacy_excuse_append_only_delete "
        f"BEFORE DELETE ON public.{_TABLE} FOR EACH ROW "
        "EXECUTE FUNCTION public.registrar_guard_legacy_excuse_append_only()"
    )
    schema_editor.execute(
        f"CREATE TRIGGER registrar_legacy_excuse_append_only_truncate "
        f"BEFORE TRUNCATE ON public.{_TABLE} FOR EACH STATEMENT "
        "EXECUTE FUNCTION public.registrar_guard_legacy_excuse_append_only()"
    )
    schema_editor.execute(
        f"CREATE TRIGGER registrar_legacy_excuse_attach_only_update "
        f"BEFORE UPDATE ON public.{_TABLE} FOR EACH ROW "
        "EXECUTE FUNCTION public.registrar_guard_legacy_excuse_attach_only()"
    )


def _revert_security(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for name in (
        "registrar_legacy_excuse_attach_only_update",
        "registrar_legacy_excuse_append_only_truncate",
        "registrar_legacy_excuse_append_only_delete",
    ):
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {name} ON public.{_TABLE}")
    schema_editor.execute(f"DROP POLICY IF EXISTS rls_tenant_isolation ON public.{_TABLE}")
    schema_editor.execute(f"ALTER TABLE public.{_TABLE} NO FORCE ROW LEVEL SECURITY")
    schema_editor.execute(f"ALTER TABLE public.{_TABLE} DISABLE ROW LEVEL SECURITY")
    schema_editor.execute(_REVERSE_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0032_seed_alumni_role"),
        ("registrar", "0059_lesson_legacy_synthesised_marker"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyExcuseDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "source_system",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[a-z0-9][a-z0-9._-]{0,63}\\Z", "Dəyər təhlükəsiz token formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                (
                    "source_table",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[a-z0-9][a-z0-9._-]{0,63}\\Z", "Dəyər təhlükəsiz token formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                ("source_pk", models.PositiveBigIntegerField()),
                (
                    "source_snapshot_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[0-9a-f]{64}\\Z", "SHA-256 lowercase hex formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                (
                    "source_row_hash",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[0-9a-f]{64}\\Z", "SHA-256 lowercase hex formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                (
                    "materialization_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[0-9a-f]{64}\\Z", "SHA-256 lowercase hex formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                (
                    "transform_version",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[a-z0-9][a-z0-9._-]{0,63}\\Z", "Dəyər təhlükəsiz token formatında olmalıdır."
                            )
                        ],
                    ),
                ),
                (
                    "mapping_status",
                    models.CharField(
                        choices=[
                            ("linked", "Bağlanıb"),
                            ("student_unresolved", "Tələbə tapılmadı"),
                            ("window_invalid", "Yararsız tarix aralığı"),
                        ],
                        max_length=24,
                    ),
                ),
                ("source_student_ref", models.CharField(blank=True, default="", max_length=64)),
                ("source_owner_ref", models.CharField(blank=True, default="", max_length=64)),
                ("source_batch_ref", models.CharField(blank=True, default="", max_length=32)),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("source_window_text", models.CharField(blank=True, default="", max_length=64)),
                ("source_recorded_at_text", models.CharField(blank=True, default="", max_length=32)),
                ("note", models.TextField(blank=True, default="", help_text="Köhnə sistemdəki izah (``desc``).")),
                ("document_name", models.CharField(blank=True, default="", max_length=64)),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        default="",
                        help_text="Boşdur: sənəd köhnə sistemdədir, sonradan qoşula bilər.",
                        upload_to=apps.registrar.models.legacy_excuse.legacy_excuse_document_path,
                        validators=[
                            core.upload_security.FileUploadValidator(
                                allowed_extensions={".docx", ".jfif", ".jpeg", ".jpg", ".pdf", ".png"}, max_size_mb=25
                            )
                        ],
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_excuse_documents",
                        to="organizations.organization",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_excuse_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "üzrlü qayıb sənədi",
                "verbose_name_plural": "üzrlü qayıb sənədləri",
                "ordering": ["source_table", "source_pk"],
                "indexes": [
                    models.Index(fields=["organization", "student"], name="reg_legacy_excuse_org_std"),
                    models.Index(fields=["organization", "starts_on"], name="reg_legacy_excuse_org_start"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "source_system", "source_table", "source_pk"),
                        name="registrar_legacy_excuse_source_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("ends_on__isnull", True), ("starts_on__isnull", True)),
                            models.Q(
                                ("ends_on__gte", models.F("starts_on")),
                                ("ends_on__isnull", False),
                                ("starts_on__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="registrar_legacy_excuse_window_ordered",
                    ),
                ],
            },
        ),
        migrations.RunPython(_apply_security, _revert_security),
    ]
