"""İKİNCİ rəsmi şifr sütunu — əvvəlki nəsil ixtisas təsnifatı üçün.

Niyə İKİ sütun, niyə biri digərini əvəz etmir
---------------------------------------------
Azərbaycanda ixtisas təsnifatı 2024-cü ildə tam dəyişdi (NK 503, 02.12.2024;
NK 109, 17.04.2026 düzəlişi). Köhnə nəsil ``050XXX``/``060XXX`` şifrləri 7
rəqəmli ``6XXXXXX``/``7XXXXXX`` şifrləri ilə əvəz olundu — AMMA uyğunluq
bire-bir DEYİL:

* ixtisas LƏĞV olunub → köhnə şifr var, yenisi YOXDUR (``050401`` «Dünya
  iqtisadiyyatı», ``050645`` «Poliqrafiya mühəndisliyi», ``060411`` «Kommersiya»);
* ixtisas YENİDİR → yeni şifr var, köhnəsi YOXDUR (``6006017`` «İnformasiya
  təhlükəsizliyi», ``6004001`` «Beynəlxalq ticarət və logistika»);
* ixtisas BÖLÜNÜB (``050810`` «Turizm və otelçilik» → ``6008007`` + ``6008008``).

Yəni tək sütunda saxlamaq məlumat İTİRİR. Üstəlik hazırda oxuyan tələbələrin
diplom və arayışlarında məhz KÖHNƏ şifr yazılıb — onu silmək sənədlə bazanı
ziddiyyətə salardı. Sahibin tələbəsi də açıqdır: «yeni və köhnə kodlar var,
bunları da əlavə et» → hər ikisi saxlanılır və hər ikisi göstərilir.

Niyə ayrı CƏDVƏL deyil
----------------------
Alternativ (b) — köhnə şifri ayrı cədvəldə saxlamaq — 1:1 atribut cütü üçün
JOIN, RLS policy miqrasiyası və hər oxu səthində ``select_related`` tələb
edərdi. ``Program`` tenant başına ~100 sətirlik kiçik kataloqdur; kardinallıq
heç bir yerdə 1-dən çox olmur. Ona görə (a): ikinci sütun.

``code`` (daxili ``MYEDU-*`` açarı) YENƏ toxunulmur — ``apps/legacy_import``
onu ``TargetRef.key`` və ``program_pk_index()`` açarı kimi işlədir (bax
0055-in izahı).

RLS: yeni cədvəl/əlaqə yoxdur, yalnız mövcud ``registrar_program`` cədvəlinə
sütun — ayrıca policy miqrasiyası tələb olunmur.
"""

# Generated by Django 5.2.13 on 2026-08-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0060_legacy_excuse_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="legacy_official_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ƏVVƏLKİ nəsil rəsmi ixtisas şifri (050XXX bakalavr, 060XXX magistratura). Köhnə tələbələrin diplom və arayışlarında yazılan şifrdir — saxlanılır və göstərilir. İxtisas yalnız 2024 təsnifatında varsa BOŞ qalır.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="official_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="CARİ rəsmi dövlət ixtisas şifri (NK 503/2024; 7 rəqəm — 6XXXXXX bakalavr, 7XXXXXX magistratura). İxtisas yeni təsnifatda ləğv olunubsa BOŞ qalır. Unikal DEYİL: bir şifr bir neçə proqrama (magistr ixtisaslaşmaları, AZ/EN bölmələri, əyani/qiyabi formalar) aid ola bilər.",
                max_length=32,
            ),
        ),
    ]
