# Generated by Django 5.2.13 on 2026-08-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0061_program_legacy_official_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="legacygradereview",
            name="category_codes",
            field=models.CharField(blank=True, default="", editable=False, max_length=255),
        ),
    ]
