"""Kataloq arxiv qatı + ixtisas/fənn metadatası (dizayn handoff Mərhələ 1).

Ekran 03 «İxtisaslar» və ekran 04 «Fənn kataloqu» üçün:

* ``Program.education_form`` — əyani / qiyabi / distant;
* ``Subject.kind`` — kataloq təsnifatı, ``Subject.chair_unit`` — aparan kafedra;
* hər ikisinə ARXİV qatı (``is_archived`` + səbəb + aktor + timestamp).

SİLMƏ YOXDUR (handoff §8 qayda 5): arxivlənmiş yazının qiymət/jurnal/sillabus
tarixçəsi olduğu kimi qalır. ``is_active`` sahəsinə TOXUNULMUR — o «cari
semestrdə istifadədədir» mənasını daşıyır və köçürmə xətti ona söykənir.

RLS: yeni cədvəl yoxdur (yalnız sütun), ona görə əlavə policy tələb olunmur —
``registrar_program`` / ``registrar_subject`` policy-ləri dəyişməz qalır.
"""

# Generated by Django 5.2.17 on 2026-09-03 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0038_seed_teaching_office_roles"),
        ("registrar", "0063_selfwork_enrollment_done_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_archived",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="archived_reason",
            field=models.TextField(blank=True, help_text="Arxivləmə səbəbi (≥20 simvol)."),
        ),
        migrations.AddField(
            model_name="program",
            name="education_form",
            field=models.CharField(
                choices=[("full_time", "Əyani"), ("part_time", "Qiyabi"), ("distance", "Distant")],
                db_index=True,
                default="full_time",
                help_text="Təhsil forması (əyani/qiyabi/distant).",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="is_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Arxivlənmiş yazı reyestrdə süzülür; əlaqəli tarixçə saxlanılır.",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_archived",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="archived_reason",
            field=models.TextField(blank=True, help_text="Arxivləmə səbəbi (≥20 simvol)."),
        ),
        migrations.AddField(
            model_name="subject",
            name="chair_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Fənni aparan kafedra (OrgUnit: chair/department).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_subjects",
                to="organizations.orgunit",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="is_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Arxivlənmiş yazı reyestrdə süzülür; əlaqəli tarixçə saxlanılır.",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="kind",
            field=models.CharField(
                choices=[
                    ("core", "İxtisas fənni"),
                    ("general", "Ümumi fənn"),
                    ("elective", "Seçmə fənn"),
                    ("practice", "Təcrübə"),
                ],
                db_index=True,
                default="core",
                help_text="Fənn növü (ixtisas/ümumi/seçmə/təcrübə).",
                max_length=16,
            ),
        ),
    ]
