# Generated by Django 5.2.17 on 2026-09-06 23:51

import apps.registrar.models.guest_document
import core.upload_security
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0047_program_coordinator_group_grants"),
        ("registrar", "0068_admission_fields_db_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestRosterDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "document",
                    models.FileField(
                        help_text="Təqdimat / sərəncam — alt qrupdan əlavənin əsası (məcburi).",
                        upload_to=apps.registrar.models.guest_document.guest_document_path,
                        validators=[
                            core.upload_security.FileUploadValidator(
                                allowed_extensions={".heic", ".heif", ".jpeg", ".jpg", ".pdf", ".png", ".webp"},
                                max_size_mb=10,
                            )
                        ],
                    ),
                ),
                ("note", models.CharField(blank=True, help_text="Qısa qeyd (məs. sərəncam №).", max_length=255)),
                ("uploaded_by_name", models.CharField(editable=False, max_length=200)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_documents",
                        to="registrar.enrollment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_roster_documents",
                        to="organizations.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guest_roster_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "guest roster document",
                "verbose_name_plural": "guest roster documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "enrollment", "-created_at"], name="registrar_g_organiz_8a5d37_idx"
                    )
                ],
            },
        ),
    ]
