# Generated by Django 5.2.17 on 2026-09-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0078_exam_score_sheet_invigilator"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentacademicrecord",
            name="admission_channel",
            field=models.CharField(
                blank=True,
                choices=[("dim", "DİM vasitəsilə"), ("exam_free", "İmtahansız qəbul")],
                db_default="",
                db_index=True,
                default="",
                help_text="Qəbul xətti (ATİS): DİM imtahanı ilə / imtahansız.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="studentacademicrecord",
            name="admission_extra",
            field=models.JSONField(
                blank=True,
                db_default=models.Value("{}", output_field=models.JSONField()),
                default=dict,
                help_text="ATİS-in digər sütunları (açar → dəyər).",
            ),
        ),
        migrations.AddField(
            model_name="studentacademicrecord",
            name="admission_note",
            field=models.TextField(blank=True, db_default="", default="", help_text="ATİS «QEYD»."),
        ),
        migrations.AddField(
            model_name="studentacademicrecord",
            name="admission_status",
            field=models.CharField(
                choices=[
                    ("admitted", "Qəbul edildi"),
                    ("deferred", "Möhlətlə qəbul edildi"),
                    ("privileged", "Güzəştli qəbul edildi"),
                    ("social_ttk", "Sosial TTK ilə qəbul edildi"),
                    ("standard_ttk", "Standart TTK ilə qəbul edildi"),
                ],
                db_default="admitted",
                db_index=True,
                default="admitted",
                help_text="Qəbulun növü (ATİS STATUS): adi / möhlətlə / güzəştli / TTK.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="studentacademicrecord",
            name="admission_tour",
            field=models.CharField(
                blank=True,
                choices=[("first", "I tur"), ("second", "II tur")],
                db_default="",
                default="",
                help_text="Qəbul turu.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="studentacademicrecord",
            name="admitted_at",
            field=models.DateTimeField(blank=True, help_text="Qəbul tarixi (ATİS).", null=True),
        ),
        migrations.AddField(
            model_name="studentacademicrecord",
            name="applied_at",
            field=models.DateTimeField(blank=True, help_text="Müraciət tarixi (ATİS).", null=True),
        ),
        migrations.AddField(
            model_name="studentacademicrecord",
            name="instruction_language",
            field=models.CharField(
                blank=True,
                choices=[("az", "Azərbaycan dili"), ("en", "İngilis dili"), ("ru", "Rus dili"), ("de", "Alman dili")],
                db_default="",
                db_index=True,
                default="",
                help_text="Tədris dili (ATİS) — qrup təyin olunmamış tələbə də süzülsün.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="studentacademicrecord",
            name="tuition_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, help_text="İllik təhsil haqqı (AZN), ATİS.", max_digits=10, null=True
            ),
        ),
    ]
