# Generated by Django 5.2.17 on 2026-09-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0079_atis_admission_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="off_schedule_reason",
            field=models.CharField(
                blank=True, default="", help_text="Cədvəldən kənar dərsin səbəbi (boş = cədvəl üzrə).", max_length=255
            ),
        ),
    ]
