# Generated by Django 5.2.17 on 2026-10-05 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0057_capacity_drop_unused_indexes"),
        ("registrar", "0084_journal_mark_window_from_settings"),
    ]

    # Tutum testi 2026-10-05: yalnız indekslər silinir. Django-nun FK `db_index`
    # dəyişikliyi FK məhdudiyyətini silib yenidən əlavə edir (bütün cədvəl yoxlaması) —
    # bu lazımsızdır, ona görə DB tərəfi xam DROP INDEX, state tərəfi isə avtomatik
    # əməliyyatlardır.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "registrar_studentacademicrecord_admission_channel_d405cb05";\nDROP INDEX IF EXISTS "registrar_studentacademicrecord_admission_channel_d405cb05_like";\nDROP INDEX IF EXISTS "registrar_studentacademicrecord_admission_status_a4f33b8c";\nDROP INDEX IF EXISTS "registrar_studentacademicrecord_admission_status_a4f33b8c_like";\nDROP INDEX IF EXISTS "registrar_studentacademicrecord_atis_id_7b33be31";\nDROP INDEX IF EXISTS "registrar_studentacademicrecord_atis_id_7b33be31_like";\nDROP INDEX IF EXISTS "registrar_studentacademicrecord_education_form_029ce217";\nDROP INDEX IF EXISTS "registrar_studentacademicrecord_education_form_029ce217_like";\nDROP INDEX IF EXISTS "registrar_studentacademicrecord_funding_type_2d15ad4a";\nDROP INDEX IF EXISTS "registrar_studentacademicrecord_funding_type_2d15ad4a_like";\nDROP INDEX IF EXISTS "registrar_studentacademi_instruction_language_0bbdd09e_like";\nDROP INDEX IF EXISTS "registrar_studentacademicrecord_instruction_language_0bbdd09e";\nDROP INDEX IF EXISTS "registrar_studentacademicrecord_is_active_92a5d75b";\nDROP INDEX IF EXISTS "registrar_studentacademicrecord_organization_id_df8da9ee";\nDROP INDEX IF EXISTS "registrar_studentacademicrecord_status_0cd4cf73";\nDROP INDEX IF EXISTS "registrar_studentacademicrecord_status_0cd4cf73_like";',
                    reverse_sql="CREATE INDEX IF NOT EXISTS registrar_studentacademicrecord_admission_channel_d405cb05 ON public.registrar_studentacademicrecord USING btree (admission_channel);\nCREATE INDEX IF NOT EXISTS registrar_studentacademicrecord_admission_channel_d405cb05_like ON public.registrar_studentacademicrecord USING btree (admission_channel varchar_pattern_ops);\nCREATE INDEX IF NOT EXISTS registrar_studentacademicrecord_admission_status_a4f33b8c ON public.registrar_studentacademicrecord USING btree (admission_status);\nCREATE INDEX IF NOT EXISTS registrar_studentacademicrecord_admission_status_a4f33b8c_like ON public.registrar_studentacademicrecord USING btree (admission_status varchar_pattern_ops);\nCREATE INDEX IF NOT EXISTS registrar_studentacademicrecord_atis_id_7b33be31 ON public.registrar_studentacademicrecord USING btree (atis_id);\nCREATE INDEX IF NOT EXISTS registrar_studentacademicrecord_atis_id_7b33be31_like ON public.registrar_studentacademicrecord USING btree (atis_id varchar_pattern_ops);\nCREATE INDEX IF NOT EXISTS registrar_studentacademicrecord_education_form_029ce217 ON public.registrar_studentacademicrecord USING btree (education_form);\nCREATE INDEX IF NOT EXISTS registrar_studentacademicrecord_education_form_029ce217_like ON public.registrar_studentacademicrecord USING btree (education_form varchar_pattern_ops);\nCREATE INDEX IF NOT EXISTS registrar_studentacademicrecord_funding_type_2d15ad4a ON public.registrar_studentacademicrecord USING btree (funding_type);\nCREATE INDEX IF NOT EXISTS registrar_studentacademicrecord_funding_type_2d15ad4a_like ON public.registrar_studentacademicrecord USING btree (funding_type varchar_pattern_ops);\nCREATE INDEX IF NOT EXISTS registrar_studentacademi_instruction_language_0bbdd09e_like ON public.registrar_studentacademicrecord USING btree (instruction_language varchar_pattern_ops);\nCREATE INDEX IF NOT EXISTS registrar_studentacademicrecord_instruction_language_0bbdd09e ON public.registrar_studentacademicrecord USING btree (instruction_language);\nCREATE INDEX IF NOT EXISTS registrar_studentacademicrecord_is_active_92a5d75b ON public.registrar_studentacademicrecord USING btree (is_active);\nCREATE INDEX IF NOT EXISTS registrar_studentacademicrecord_organization_id_df8da9ee ON public.registrar_studentacademicrecord USING btree (organization_id);\nCREATE INDEX IF NOT EXISTS registrar_studentacademicrecord_status_0cd4cf73 ON public.registrar_studentacademicrecord USING btree (status);\nCREATE INDEX IF NOT EXISTS registrar_studentacademicrecord_status_0cd4cf73_like ON public.registrar_studentacademicrecord USING btree (status varchar_pattern_ops);",
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="studentacademicrecord",
                    name="admission_channel",
                    field=models.CharField(
                        blank=True,
                        choices=[("dim", "DİM vasitəsilə"), ("exam_free", "İmtahansız qəbul")],
                        db_default="",
                        default="",
                        help_text="Qəbul xətti (ATİS): DİM imtahanı ilə / imtahansız.",
                        max_length=16,
                    ),
                ),
                migrations.AlterField(
                    model_name="studentacademicrecord",
                    name="admission_status",
                    field=models.CharField(
                        choices=[
                            ("admitted", "Qəbul edildi"),
                            ("deferred", "Möhlətlə qəbul edildi"),
                            ("privileged", "Güzəştli qəbul edildi"),
                            ("social_ttk", "Sosial TTK ilə qəbul edildi"),
                            ("standard_ttk", "Standart TTK ilə qəbul edildi"),
                        ],
                        db_default="admitted",
                        default="admitted",
                        help_text="Qəbulun növü (ATİS STATUS): adi / möhlətlə / güzəştli / TTK.",
                        max_length=16,
                    ),
                ),
                migrations.AlterField(
                    model_name="studentacademicrecord",
                    name="atis_id",
                    field=models.CharField(
                        blank=True,
                        db_default="",
                        default="",
                        help_text="ATİS qəbul siyahısındakı sətir nömrəsi/identifikatoru.",
                        max_length=64,
                    ),
                ),
                migrations.AlterField(
                    model_name="studentacademicrecord",
                    name="education_form",
                    field=models.CharField(
                        choices=[("full_time", "Əyani"), ("part_time", "Qiyabi"), ("distance", "Distant")],
                        db_default="full_time",
                        default="full_time",
                        help_text="Tələbənin təhsil forması (ixtisasın default formasından fərqlənə bilər).",
                        max_length=16,
                    ),
                ),
                migrations.AlterField(
                    model_name="studentacademicrecord",
                    name="funding_type",
                    field=models.CharField(
                        choices=[("state", "Dövlət sifarişi"), ("paid", "Ödənişli")],
                        db_default="paid",
                        default="paid",
                        help_text="Maliyyələşmə mənbəyi (dövlət sifarişi / ödənişli).",
                        max_length=16,
                    ),
                ),
                migrations.AlterField(
                    model_name="studentacademicrecord",
                    name="instruction_language",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("az", "Azərbaycan dili"),
                            ("en", "İngilis dili"),
                            ("ru", "Rus dili"),
                            ("de", "Alman dili"),
                        ],
                        db_default="",
                        default="",
                        help_text="Tədris dili (ATİS) — qrup təyin olunmamış tələbə də süzülsün.",
                        max_length=8,
                    ),
                ),
                migrations.AlterField(
                    model_name="studentacademicrecord",
                    name="is_active",
                    field=models.BooleanField(default=True),
                ),
                migrations.AlterField(
                    model_name="studentacademicrecord",
                    name="organization",
                    field=models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_records",
                        to="organizations.organization",
                    ),
                ),
                migrations.AlterField(
                    model_name="studentacademicrecord",
                    name="status",
                    field=models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("academic_leave", "Academic leave"),
                            ("expelled", "Expelled"),
                            ("graduated", "Graduated"),
                        ],
                        default="enrolled",
                        help_text="Akademik status (qeydiyyatlı / akademik məzuniyyət / xaric / məzun).",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
