# Generated by Django 5.2.17 on 2026-09-25 01:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0053_rim_full_permissions"),
        ("registrar", "0079_atis_admission_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=160)),
                ("scope", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qaralama"),
                            ("queued", "Növbədə"),
                            ("running", "İşləyir"),
                            ("done", "Hazırdır"),
                            ("failed", "Uğursuz"),
                            ("published", "Dərc edilib"),
                            ("discarded", "Ləğv edilib"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("seed", models.PositiveIntegerField(default=1)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("priorities", models.JSONField(blank=True, default=dict)),
                ("kpis", models.JSONField(blank=True, default=dict)),
                ("progress", models.JSONField(blank=True, default=dict)),
                ("log", models.JSONField(blank=True, default=list)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_runs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_runs",
                        to="organizations.academicperiod",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reruns",
                        to="timetable.timetablerun",
                    ),
                ),
            ],
            options={
                "verbose_name": "cədvəl işləməsi",
                "verbose_name_plural": "cədvəl işləmələri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimetableDraftSlot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_key", models.CharField(db_index=True, max_length=160)),
                ("kind", models.CharField(max_length=16)),
                ("weekday", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("pair", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("week_type", models.CharField(default="all", max_length=8)),
                ("is_biweekly", models.BooleanField(default=False)),
                ("room", models.CharField(blank=True, max_length=64)),
                ("room_ref", models.CharField(blank=True, max_length=64)),
                ("locked", models.BooleanField(default=False)),
                ("is_manual", models.BooleanField(default=False)),
                ("penalty", models.IntegerField(default=0)),
                ("reason_code", models.CharField(blank=True, max_length=32)),
                ("reason", models.TextField(blank=True)),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_draft_slots",
                        to="registrar.courseoffering",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_draft_slots",
                        to="organizations.organization",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="slots", to="timetable.timetablerun"
                    ),
                ),
            ],
            options={
                "verbose_name": "qaralama slot",
                "verbose_name_plural": "qaralama slotlar",
                "ordering": ["weekday", "pair", "event_key"],
            },
        ),
        migrations.CreateModel(
            name="GroupTimePolicy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("level", models.CharField(blank=True, max_length=16)),
                ("bands", models.JSONField(blank=True, default=list)),
                ("weekdays", models.JSONField(blank=True, default=list)),
                ("max_pairs_per_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_excluded", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_policies",
                        to="organizations.orgunit",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_group_policies",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "qrup növbə siyasəti",
                "verbose_name_plural": "qrup növbə siyasətləri",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("group__isnull", False)),
                        fields=("organization", "group"),
                        name="uniq_timetable_policy_group",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("group__isnull", True)),
                        fields=("organization", "level"),
                        name="uniq_timetable_policy_level",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TeacherAvailability",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("grid", models.JSONField(blank=True, default=dict)),
                ("max_pairs_per_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_days_per_week", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("priority", models.PositiveSmallIntegerField(default=1)),
                ("subject_priorities", models.JSONField(blank=True, default=dict)),
                ("note", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_availabilities",
                        to="organizations.organization",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_availabilities",
                        to="organizations.academicperiod",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_availabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "müəllim əlçatanlığı",
                "verbose_name_plural": "müəllim əlçatanlıqları",
                "indexes": [models.Index(fields=["organization", "period"], name="timetable_t_organiz_19f502_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "teacher", "period"), name="uniq_timetable_availability_teacher_period"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("priority__gte", 1), ("priority__lte", 5)),
                        name="timetable_availability_priority_1_5",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="timetablerun",
            index=models.Index(fields=["organization", "period", "status"], name="timetable_t_organiz_3e818b_idx"),
        ),
        migrations.AddIndex(
            model_name="timetabledraftslot",
            index=models.Index(fields=["run", "weekday", "pair"], name="timetable_t_run_id_ac2d4b_idx"),
        ),
        migrations.AddIndex(
            model_name="timetabledraftslot",
            index=models.Index(fields=["run", "offering"], name="timetable_t_run_id_bbd33d_idx"),
        ),
    ]
