# Generated by Django 5.2.14 on 2026-05-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="contactmessage",
            new_name="contact_con_created_00b9df_idx",
            old_name="contact_con_created_idx",
        ),
        migrations.RenameIndex(
            model_name="contactmessage",
            new_name="contact_con_is_hand_01c13a_idx",
            old_name="contact_con_handled_idx",
        ),
    ]
