# Generated by Django 5.2.8 on 2025-12-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liveExam", "0003_livesession_current_question_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livesession",
            name="question_limit",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="livesession",
            name="selected_question_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
