# Generated by Django 5.2.8 on 2025-12-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liveExam", "0004_livesession_question_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveanswer",
            name="choice_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="liveanswer",
            name="choice_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
