# Generated by Django 5.2.12 on 2026-03-24 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Kurs Adı")),
                ("description", models.TextField(blank=True, verbose_name="Kurs Təsviri")),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True, verbose_name="URL Slug")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft (yayımlanmayıb)"),
                            ("published", "Yayımlandı"),
                            ("archived", "Arxivləndi"),
                        ],
                        default="draft",
                        help_text="Draft: tələbələr görmə, Published: görsün",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="course_covers/%Y/%m/", verbose_name="Kurs Şəkli"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Yaradılma Tarixi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Yenilənmə Tarixi")),
                (
                    "grading_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Faiz (0-100)"),
                            ("letter", "Hərf (A, B, C, D, F)"),
                            ("pass_fail", "Keç/Qal"),
                            ("points", "Xal sistemi"),
                        ],
                        default="percentage",
                        help_text="Kursun qiymətləndirmə metodunu seçin",
                        max_length=20,
                        verbose_name="Qiymətləndirmə Tipi",
                    ),
                ),
                (
                    "passing_grade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum keçid balı (məs: 50.00)",
                        max_digits=5,
                        null=True,
                        verbose_name="Keçid Qiyməti",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON formatında əlavə tənzimləmələr",
                        verbose_name="Əlavə Parametrlər",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Kursun aid olduğu təşkilat",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="organizations.organization",
                        verbose_name="Təşkilat",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Kursun sahibi olan müəllim",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taught_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Müəllif (Müəllim)",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        help_text="Kursun aid olduğu akademik dövr (semestr, trisemestr, və s.)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="organizations.academicperiod",
                        verbose_name="Akademik Dövr",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Kursun aid olduğu kafedra və ya şöbə",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="organizations.orgunit",
                        verbose_name="Kafedra/Şöbə",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs",
                "verbose_name_plural": "Kurslar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Məs: Qrup A, Lab 1, Praktikum 2", max_length=100, verbose_name="Qrup Adı"
                    ),
                ),
                (
                    "schedule",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON: {'day': 'Monday', 'time': '10:00', 'room': '301'}",
                        verbose_name="Cədvəl",
                    ),
                ),
                (
                    "max_students",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Bu qrupa daxil ola biləcək maksimum tələbə sayı",
                        verbose_name="Maksimum Tələbə Sayı",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Yaradılma Tarixi")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_groups",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bu qrupu tədris edən müəllim/asistant",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instructed_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Qrup Müəllimi",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="course_group_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Qrup Üzvləri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs Qrupu",
                "verbose_name_plural": "Kurs Qrupları",
            },
        ),
        migrations.CreateModel(
            name="CourseInstructor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("primary", "Əsas Müəllim"), ("assistant", "Asistant"), ("guest", "Qonaq Müəllim")],
                        default="assistant",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON: {'can_grade': true, 'can_edit': false, ...}",
                        verbose_name="Səlahiyyətlər",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Əlavə Edilmə Tarixi")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructors",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Müəllim/Asistant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs Müəllimi",
                "verbose_name_plural": "Kurs Müəllimləri",
            },
        ),
        migrations.CreateModel(
            name="CourseMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("teacher", "Müəllim"), ("assistant", "Asistant"), ("student", "Tələbə")],
                        default="student",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        blank=True,
                        help_text='Məs: "875i", "842A1". Tələbəyə aid qrup.',
                        max_length=100,
                        verbose_name="Qrup Adı (isteğe bağlı)",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True, verbose_name="Qoşulma Tarixi")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs Üzvü",
                "verbose_name_plural": "Kurs Üzvləri",
            },
        ),
        migrations.CreateModel(
            name="CourseTopic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Mövzu Adı")),
                ("description", models.TextField(blank=True, verbose_name="Mövzu Təsviri")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, help_text="1, 2, 3, ... (hansı mövzu əvvəl göstərilsin)", verbose_name="Sıra Nömrəsi"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Yaradılma Tarixi")),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Bu mövzu hansı kursa aiddir",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs Mövzusu",
                "verbose_name_plural": "Kurs Mövzuları",
                "ordering": ["course", "order"],
            },
        ),
        migrations.CreateModel(
            name="CourseResource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Resurs Başlığı")),
                ("description", models.TextField(blank=True, verbose_name="Açıqlama")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("file", "Fayl (PDF, ZIP, və s.)"),
                            ("link", "Xarici Link"),
                            ("document", "Sənəd"),
                            ("video", "Video"),
                        ],
                        default="file",
                        max_length=20,
                        verbose_name="Resurs Tipi",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Fayl yükləyin (PDF, ZIP, IMG, və s.)",
                        null=True,
                        upload_to="course_resources/%Y/%m/",
                        verbose_name="Fayl",
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, help_text="Məs: https://docs.python.org", verbose_name="URL Linki"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Yaradılma Tarixi")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bu resurs hansı mövzuya aid (boş olabilər - kurs səviyyəsində)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="courses.coursetopic",
                        verbose_name="Mövzu (isteğe bağlı)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs Resursu",
                "verbose_name_plural": "Kurs Resursları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["owner", "-created_at"], name="courses_cou_owner_i_e2e8dd_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["status"], name="courses_cou_status_158bbf_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["slug"], name="courses_cou_slug_2e551f_idx"),
        ),
        migrations.AddIndex(
            model_name="coursegroup",
            index=models.Index(fields=["course"], name="courses_cou_course__225864_idx"),
        ),
        migrations.AddIndex(
            model_name="coursegroup",
            index=models.Index(fields=["instructor"], name="courses_cou_instruc_f2ed74_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="coursegroup",
            unique_together={("course", "name")},
        ),
        migrations.AddIndex(
            model_name="courseinstructor",
            index=models.Index(fields=["course", "role"], name="courses_cou_course__13a825_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="courseinstructor",
            unique_together={("course", "user")},
        ),
        migrations.AddIndex(
            model_name="coursemembership",
            index=models.Index(fields=["course", "role"], name="courses_cou_course__076371_idx"),
        ),
        migrations.AddIndex(
            model_name="coursemembership",
            index=models.Index(fields=["course", "group_name"], name="courses_cou_course__44546e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="coursemembership",
            unique_together={("course", "user")},
        ),
        migrations.AddIndex(
            model_name="coursetopic",
            index=models.Index(fields=["course", "order"], name="courses_cou_course__0e20e3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="coursetopic",
            unique_together={("course", "order")},
        ),
        migrations.AddIndex(
            model_name="courseresource",
            index=models.Index(fields=["course", "topic"], name="courses_cou_course__c30055_idx"),
        ),
    ]
