# Generated by Django 5.2.8 on 2026-02-13 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="grading_type",
            field=models.CharField(
                choices=[
                    ("percentage", "Faiz (0-100)"),
                    ("letter", "Hərf (A, B, C, D, F)"),
                    ("pass_fail", "Keç/Qal"),
                    ("points", "Xal sistemi"),
                ],
                default="percentage",
                help_text="Kursun qiymətləndirmə metodunu seçin",
                max_length=20,
                verbose_name="Qiymətləndirmə Tipi",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="organization_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Gələcəkdə organizations.Organization FK olacaq",
                null=True,
                verbose_name="Təşkilat ID",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="passing_grade",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum keçid balı (məs: 50.00)",
                max_digits=5,
                null=True,
                verbose_name="Keçid Qiyməti",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="period_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Placeholder - gələcək AcademicPeriod FK",
                null=True,
                verbose_name="Akademik Dövr ID",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON formatında əlavə tənzimləmələr",
                verbose_name="Əlavə Parametrlər",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="unit_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Placeholder - gələcək OrgUnit FK",
                null=True,
                verbose_name="Kafedra/Şöbə ID",
            ),
        ),
        migrations.CreateModel(
            name="CourseGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Məs: Qrup A, Lab 1, Praktikum 2",
                        max_length=100,
                        verbose_name="Qrup Adı",
                    ),
                ),
                (
                    "schedule",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON: {'day': 'Monday', 'time': '10:00', 'room': '301'}",
                        verbose_name="Cədvəl",
                    ),
                ),
                (
                    "max_students",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Bu qrupa daxil ola biləcək maksimum tələbə sayı",
                        verbose_name="Maksimum Tələbə Sayı",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_groups",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bu qrupu tədris edən müəllim/asistant",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instructed_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Qrup Müəllimi",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="course_group_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Qrup Üzvləri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs Qrupu",
                "verbose_name_plural": "Kurs Qrupları",
                "indexes": [
                    models.Index(
                        fields=["course"], name="courses_cou_course__225864_idx"
                    ),
                    models.Index(
                        fields=["instructor"], name="courses_cou_instruc_f2ed74_idx"
                    ),
                ],
                "unique_together": {("course", "name")},
            },
        ),
        migrations.CreateModel(
            name="CourseInstructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Əsas Müəllim"),
                            ("assistant", "Asistant"),
                            ("guest", "Qonaq Müəllim"),
                        ],
                        default="assistant",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON: {'can_grade': true, 'can_edit': false, ...}",
                        verbose_name="Səlahiyyətlər",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Əlavə Edilmə Tarixi"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructors",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Müəllim/Asistant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs Müəllimi",
                "verbose_name_plural": "Kurs Müəllimləri",
                "indexes": [
                    models.Index(
                        fields=["course", "role"], name="courses_cou_course__13a825_idx"
                    )
                ],
                "unique_together": {("course", "user")},
            },
        ),
    ]
