# Generated by Django 5.2.8 on 2026-03-17 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_organization_non_nullable'),
        ('organizations', '0006_alter_academicperiod_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='period_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='unit_id',
        ),
        migrations.AddField(
            model_name='course',
            name='period',
            field=models.ForeignKey(blank=True, help_text='Kursun aid olduğu akademik dövr (semestr, trisemestr, və s.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='organizations.academicperiod', verbose_name='Akademik Dövr'),
        ),
        migrations.AddField(
            model_name='course',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Kursun aid olduğu kafedra və ya şöbə', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='organizations.orgunit', verbose_name='Kafedra/Şöbə'),
        ),
    ]
