# Generated by Django 5.2.17 on 2026-09-25 06:13

import apps.subject_folder.models.paths
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0054_seed_quality_control_roles"),
        ("registrar", "0080_lesson_off_schedule_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectFolder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Qaralama"), ("active", "Aktiv"), ("archived", "Arxivlənib")],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "syllabus_ref",
                    models.UUIDField(
                        blank=True,
                        help_text="Mövzuların son sinxron olunduğu TƏSDİQLƏNMİŞ sillabus versiyasının id-si (məlumat üçün).",
                        null=True,
                    ),
                ),
                (
                    "selfwork_option",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sillabusun sərbəst iş strukturu (1x10 / 2x5 / 10x1); boş = sillabus yoxdur.",
                        max_length=8,
                    ),
                ),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_folders",
                        to="organizations.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subject_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        help_text="Semestr. Boşdursa qovluq istənilən semestrin açılışına təyin oluna bilər.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subject_folders",
                        to="organizations.academicperiod",
                    ),
                ),
                (
                    "source_folder",
                    models.ForeignKey(
                        blank=True,
                        help_text="Keçən semestrdən köçürülübsə mənbə qovluq.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_folders",
                        to="subject_folder.subjectfolder",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subject_folders",
                        to="registrar.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "fənn qovluğu",
                "verbose_name_plural": "fənn qovluqları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FolderTopic",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("week_no", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("syllabus", "Sillabusdan"), ("custom", "Müəllimin mövzusu")],
                        default="custom",
                        max_length=16,
                    ),
                ),
                ("syllabus_uid", models.CharField(blank=True, max_length=40, null=True)),
                ("syllabus_title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False, help_text="Sillabusdan çıxıb, amma bağlı materialı var — silinmir, gizlədilir."
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_folder_topics",
                        to="organizations.organization",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="subject_folder.subjectfolder",
                    ),
                ),
            ],
            options={
                "verbose_name": "qovluq mövzusu",
                "verbose_name_plural": "qovluq mövzuları",
                "ordering": ["folder", "order", "week_no", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="FolderTask",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(choices=[("selfwork", "Sərbəst iş"), ("homework", "Ev tapşırığı")], max_length=16),
                ),
                ("title", models.CharField(max_length=255)),
                ("instructions", models.TextField(blank=True)),
                (
                    "slot_index",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Sərbəst iş slotunun nömrəsi (1-dən). Ev tapşırığında boşdur.", null=True
                    ),
                ),
                (
                    "max_points",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Sərbəst iş slotunun maksimal balı (sillabus strukturundan). Ev tapşırığında boşdur.",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "syllabus_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sillabusdakı sərbəst iş mövzusu (sinxron üçün).",
                        max_length=255,
                    ),
                ),
                (
                    "allowed_extensions",
                    models.JSONField(
                        blank=True, default=list, help_text="İcazəli fayl uzantıları; boş = modulun standart siyahısı."
                    ),
                ),
                ("max_file_mb", models.PositiveSmallIntegerField(default=20)),
                ("max_files", models.PositiveSmallIntegerField(default=5)),
                ("allow_text_answer", models.BooleanField(default=True)),
                ("allow_files", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Sillabus strukturu dəyişib və ya müəllim gizlədib — göndərişləri olan tapşırıq SİLİNMİR.",
                    ),
                ),
                ("lineage_key", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_folder_tasks",
                        to="organizations.organization",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="subject_folder.foldertopic",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="subject_folder.subjectfolder",
                    ),
                ),
            ],
            options={
                "verbose_name": "tapşırıq",
                "verbose_name_plural": "tapşırıqlar",
                "ordering": ["folder", "kind", "slot_index", "order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="FolderMaterial",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("file", "Fayl"),
                            ("image", "Şəkil"),
                            ("code", "Kod nümunəsi"),
                            ("link", "Keçid"),
                            ("video_link", "Video keçidi"),
                            ("note", "Qeyd"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, max_length=255, upload_to=apps.subject_folder.models.paths.material_file_path
                    ),
                ),
                ("original_name", models.CharField(blank=True, default="", max_length=255)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, default="", max_length=120)),
                ("sha256", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("url", models.URLField(blank=True, default="", max_length=1000)),
                ("code_text", models.TextField(blank=True, default="")),
                (
                    "code_language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("python", "Python"),
                            ("java", "Java"),
                            ("c", "C"),
                            ("cpp", "C++"),
                            ("csharp", "C#"),
                            ("javascript", "JavaScript"),
                            ("typescript", "TypeScript"),
                            ("sql", "SQL"),
                            ("html", "HTML"),
                            ("css", "CSS"),
                            ("php", "PHP"),
                            ("go", "Go"),
                            ("rust", "Rust"),
                            ("kotlin", "Kotlin"),
                            ("swift", "Swift"),
                            ("r", "R"),
                            ("matlab", "MATLAB"),
                            ("bash", "Bash"),
                            ("other", "Digər"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                (
                    "is_archived",
                    models.BooleanField(default=False, help_text="Silinmiş (gizlədilmiş) material — data saxlanılır."),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_folder_materials",
                        to="organizations.organization",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="subject_folder.foldertopic",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="subject_folder.subjectfolder",
                    ),
                ),
            ],
            options={
                "verbose_name": "tədris materialı",
                "verbose_name_plural": "tədris materialları",
                "ordering": ["folder", "topic", "order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="FolderAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("assigned_at", models.DateTimeField()),
                (
                    "syllabus_version_ref",
                    models.UUIDField(
                        blank=True,
                        help_text="Təyin anında açılışın TƏSDİQLƏNMİŞ sillabus versiyası (snapshot).",
                        null=True,
                    ),
                ),
                (
                    "selfwork_option",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Təyin anında açılışın sillabusundakı sərbəst iş strukturu.",
                        max_length=8,
                    ),
                ),
                (
                    "grades_selfwork",
                    models.BooleanField(
                        default=True,
                        help_text="Bu təyinat açılışın sərbəst işini qiymətləndirirmi (açılış üzrə yalnız biri).",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("unassigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subject_folder_assignments",
                        to="registrar.courseoffering",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_folder_assignments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "unassigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="subject_folder.subjectfolder",
                    ),
                ),
            ],
            options={
                "verbose_name": "qovluq təyinatı",
                "verbose_name_plural": "qovluq təyinatları",
                "ordering": ["folder", "assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[("selfwork", "Sərbəst iş"), ("homework", "Ev tapşırığı")],
                        help_text="Tapşırığın növü (snapshot).",
                        max_length=16,
                    ),
                ),
                ("attempt_no", models.PositiveSmallIntegerField(default=1)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qaralama"),
                            ("submitted", "Yoxlanılır"),
                            ("returned", "Yenidən işləməyə qaytarılıb"),
                            ("accepted", "Qəbul edilib"),
                            ("checked", "Yoxlanılıb"),
                            ("rejected", "Rədd edilib"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("text_answer", models.TextField(blank=True, default="")),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("is_late", models.BooleanField(default=False)),
                ("reviewer_name", models.CharField(blank=True, default="", max_length=200)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, default="")),
                (
                    "reject_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("late", "Son tarixdən sonra göndərilib"),
                            ("plagiarism", "Plagiat / köçürülmüş iş"),
                            ("off_topic", "Mövzuya uyğun deyil"),
                            ("other", "Digər səbəb"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("points", models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ("points_max", models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                (
                    "journal_sync_status",
                    models.CharField(
                        choices=[
                            ("none", "Tətbiq olunmur"),
                            ("pending", "Jurnala ötürülməsi gözlənilir"),
                            ("synced", "Jurnala düşüb"),
                            ("blocked", "Jurnal qəbul etmədi"),
                        ],
                        db_index=True,
                        default="none",
                        max_length=16,
                    ),
                ),
                ("journal_sync_message", models.CharField(blank=True, default="", max_length=500)),
                ("journal_synced_at", models.DateTimeField(blank=True, null=True)),
                ("journal_sync_attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "content_sha256",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Normallaşdırılmış mətn + fayl heşləri.",
                        max_length=64,
                    ),
                ),
                (
                    "plagiarism_status",
                    models.CharField(
                        choices=[
                            ("pending", "Yoxlama gözlənilir"),
                            ("done", "Yoxlanılıb"),
                            ("skipped", "Yoxlanıla bilən mətn yoxdur"),
                            ("failed", "Yoxlama alınmadı"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("similarity_max", models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ("plagiarism_flagged", models.BooleanField(db_index=True, default=False)),
                ("teacher_notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="subject_folder.folderassignment",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subject_folder_submissions",
                        to="registrar.enrollment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_folder_submissions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subject_folder_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="subject_folder.foldertask",
                    ),
                ),
            ],
            options={
                "verbose_name": "göndəriş",
                "verbose_name_plural": "göndərişlər",
                "ordering": ["-submitted_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SimilarityMatch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("score", models.DecimalField(decimal_places=3, max_digits=4)),
                (
                    "method",
                    models.CharField(choices=[("exact", "Eyni məzmun"), ("shingle", "Mətn oxşarlığı")], max_length=16),
                ),
                ("is_flagged", models.BooleanField(db_index=True, default=False)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("dismiss_note", models.CharField(blank=True, default="", max_length=500)),
                (
                    "dismissed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_folder_similarity_matches",
                        to="organizations.organization",
                    ),
                ),
                (
                    "submission_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_as_a",
                        to="subject_folder.submission",
                    ),
                ),
                (
                    "submission_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_as_b",
                        to="subject_folder.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "oxşarlıq uyğunluğu",
                "verbose_name_plural": "oxşarlıq uyğunluqları",
                "ordering": ["-score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("draft_saved", "Qaralama saxlanıldı"),
                            ("submitted", "Göndərildi"),
                            ("resubmitted", "Yenidən göndərildi"),
                            ("file_removed", "Fayl silindi"),
                            ("returned", "Rəylə qaytarıldı"),
                            ("accepted", "Qəbul edildi"),
                            ("checked", "Yoxlanıldı"),
                            ("rejected", "Rədd edildi"),
                            ("reopened", "Rədd ləğv edildi"),
                            ("journal_synced", "Jurnala düşdü"),
                            ("journal_pending", "Jurnala ötürülmə gözləyir"),
                            ("journal_blocked", "Jurnal qəbul etmədi"),
                            ("plagiarism_flagged", "Oxşarlıq aşkarlandı"),
                        ],
                        max_length=24,
                    ),
                ),
                ("actor_name", models.CharField(blank=True, default="", max_length=200)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_folder_submission_events",
                        to="organizations.organization",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="subject_folder.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "göndəriş hadisəsi",
                "verbose_name_plural": "göndəriş hadisələri",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionFile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "file",
                    models.FileField(max_length=255, upload_to=apps.subject_folder.models.paths.submission_file_path),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, default="", max_length=120)),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_folder_submission_files",
                        to="organizations.organization",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="files",
                        to="subject_folder.submission",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "göndəriş faylı",
                "verbose_name_plural": "göndəriş faylları",
                "ordering": ["submission", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionFingerprint",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Yoxlama gözlənilir"),
                            ("done", "Yoxlanılıb"),
                            ("skipped", "Yoxlanıla bilən mətn yoxdur"),
                            ("failed", "Yoxlama alınmadı"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, default="", help_text="Normallaşdırılmış (kiçik hərf, işarəsiz) mətn."
                    ),
                ),
                ("text_sha256", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("shingle_count", models.PositiveIntegerField(default=0)),
                ("minhash", models.JSONField(blank=True, default=list)),
                ("file_hashes", models.JSONField(blank=True, default=list, help_text="Faylların sha256 siyahısı.")),
                ("extracted_chars", models.PositiveIntegerField(default=0)),
                (
                    "skipped_files",
                    models.JSONField(blank=True, default=list, help_text="Mətni çıxarılmayan fayllar və səbəbi."),
                ),
                ("error", models.CharField(blank=True, default="", max_length=500)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_folder_fingerprints",
                        to="organizations.organization",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fingerprint",
                        to="subject_folder.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "göndəriş barmaq izi",
                "verbose_name_plural": "göndəriş barmaq izləri",
            },
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "file",
                    models.FileField(max_length=255, upload_to=apps.subject_folder.models.paths.task_attachment_path),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, default="", max_length=120)),
                ("sha256", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_folder_task_attachments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="subject_folder.foldertask",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "tapşırıq qoşması",
                "verbose_name_plural": "tapşırıq qoşmaları",
                "ordering": ["task", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskDeadline",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("opens_at", models.DateTimeField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "late_policy",
                    models.CharField(
                        choices=[("none", "Son tarixdən sonra qəbul edilmir"), ("allow", "Gecikmə ilə qəbul edilir")],
                        default="none",
                        max_length=8,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deadlines",
                        to="subject_folder.folderassignment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_folder_deadlines",
                        to="organizations.organization",
                    ),
                ),
                (
                    "set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deadlines",
                        to="subject_folder.foldertask",
                    ),
                ),
            ],
            options={
                "verbose_name": "tapşırıq son tarixi",
                "verbose_name_plural": "tapşırıq son tarixləri",
            },
        ),
        migrations.AddIndex(
            model_name="subjectfolder",
            index=models.Index(fields=["organization", "owner", "status"], name="sf_folder_org_owner_status"),
        ),
        migrations.AddIndex(
            model_name="subjectfolder",
            index=models.Index(fields=["organization", "subject", "period"], name="sf_folder_org_subject_period"),
        ),
        migrations.AddConstraint(
            model_name="subjectfolder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("period__isnull", False)),
                fields=("organization", "subject", "owner", "period"),
                name="sf_folder_uniq_subject_owner_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectfolder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("period__isnull", True)),
                fields=("organization", "subject", "owner"),
                name="sf_folder_uniq_subject_owner_noperiod",
            ),
        ),
        migrations.AddIndex(
            model_name="foldertopic",
            index=models.Index(fields=["organization", "folder", "order"], name="sf_topic_org_folder_order"),
        ),
        migrations.AddConstraint(
            model_name="foldertopic",
            constraint=models.UniqueConstraint(
                condition=models.Q(("syllabus_uid__isnull", False)),
                fields=("folder", "syllabus_uid"),
                name="sf_topic_uniq_syllabus_uid",
            ),
        ),
        migrations.AddConstraint(
            model_name="foldertopic",
            constraint=models.CheckConstraint(
                condition=models.Q(("source", "custom"), ("syllabus_uid__isnull", False), _connector="OR"),
                name="sf_topic_syllabus_has_uid",
            ),
        ),
        migrations.AddIndex(
            model_name="foldertask",
            index=models.Index(fields=["organization", "folder", "kind"], name="sf_task_org_folder_kind"),
        ),
        migrations.AddConstraint(
            model_name="foldertask",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False), ("kind", "selfwork")),
                fields=("folder", "slot_index"),
                name="sf_task_uniq_active_selfwork_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="foldertask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind", "selfwork"),
                        ("max_points__gt", 0),
                        ("max_points__isnull", False),
                        ("max_points__lte", 10),
                        ("slot_index__gte", 1),
                        ("slot_index__isnull", False),
                    ),
                    models.Q(("kind", "homework"), ("max_points__isnull", True), ("slot_index__isnull", True)),
                    _connector="OR",
                ),
                name="sf_task_kind_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="foldertask",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_files__gte", 1)), name="sf_task_max_files_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="foldertask",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_file_mb__gte", 1)), name="sf_task_max_file_mb_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="foldermaterial",
            index=models.Index(
                fields=["organization", "folder", "topic", "order"], name="sf_material_org_folder_topic"
            ),
        ),
        migrations.AddIndex(
            model_name="foldermaterial",
            index=models.Index(fields=["folder", "is_published", "is_archived"], name="sf_material_visibility"),
        ),
        migrations.AddConstraint(
            model_name="foldermaterial",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind__in", ["file", "image"]), _negated=True),
                    models.Q(("file", ""), _negated=True),
                    _connector="OR",
                ),
                name="sf_material_file_kinds_have_file",
            ),
        ),
        migrations.AddConstraint(
            model_name="foldermaterial",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind__in", ["link", "video_link"]), _negated=True),
                    models.Q(("url", ""), _negated=True),
                    _connector="OR",
                ),
                name="sf_material_link_kinds_have_url",
            ),
        ),
        migrations.AddConstraint(
            model_name="foldermaterial",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "code"), _negated=True),
                    models.Q(("code_text", ""), _negated=True),
                    _connector="OR",
                ),
                name="sf_material_code_has_text",
            ),
        ),
        migrations.AddIndex(
            model_name="folderassignment",
            index=models.Index(fields=["organization", "offering", "is_active"], name="sf_assignment_org_offering"),
        ),
        migrations.AddConstraint(
            model_name="folderassignment",
            constraint=models.UniqueConstraint(
                fields=("folder", "offering"), name="sf_assignment_uniq_folder_offering"
            ),
        ),
        migrations.AddConstraint(
            model_name="folderassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("grades_selfwork", True), ("is_active", True)),
                fields=("offering",),
                name="sf_assignment_one_selfwork_grader",
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["organization", "assignment", "status"], name="sf_sub_org_assignment_status"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["organization", "task", "status"], name="sf_sub_org_task_status"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["enrollment", "kind", "status"], name="sf_sub_enrollment_kind_status"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["organization", "student", "-submitted_at"], name="sf_sub_org_student"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["organization", "journal_sync_status"], name="sf_sub_org_journal_sync"),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                fields=("task", "enrollment", "attempt_no"), name="sf_submission_uniq_attempt"
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("task", "enrollment"),
                name="sf_submission_one_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["accepted", "checked", "rejected"])),
                fields=("task", "enrollment"),
                name="sf_submission_one_final",
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_no__gte", 1)), name="sf_submission_attempt_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.CheckConstraint(
                condition=models.Q(("points__isnull", True), ("status", "accepted"), _connector="OR"),
                name="sf_submission_points_only_when_accepted",
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "accepted"), _negated=True),
                    models.Q(("kind", "selfwork"), ("points__isnull", False), ("points_max__isnull", False)),
                    _connector="OR",
                ),
                name="sf_submission_accepted_is_scored_selfwork",
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("points__isnull", True),
                    models.Q(("points_max__isnull", False), ("points__gt", 0), ("points__lte", models.F("points_max"))),
                    _connector="OR",
                ),
                name="sf_submission_points_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.CheckConstraint(
                condition=models.Q(("points_max__isnull", True), ("points_max__lte", 10), _connector="OR"),
                name="sf_submission_points_max_cap",
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "checked"), _negated=True), ("kind", "homework"), _connector="OR"
                ),
                name="sf_submission_checked_is_homework",
            ),
        ),
        migrations.AddIndex(
            model_name="similaritymatch",
            index=models.Index(fields=["organization", "is_flagged"], name="sf_match_org_flagged"),
        ),
        migrations.AddIndex(
            model_name="similaritymatch",
            index=models.Index(fields=["submission_b"], name="sf_match_sub_b"),
        ),
        migrations.AddConstraint(
            model_name="similaritymatch",
            constraint=models.UniqueConstraint(fields=("submission_a", "submission_b"), name="sf_match_uniq_pair"),
        ),
        migrations.AddConstraint(
            model_name="similaritymatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("submission_a__lt", models.F("submission_b"))), name="sf_match_canonical_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="similaritymatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", 0), ("score__lte", 1)), name="sf_match_score_range"
            ),
        ),
        migrations.AddIndex(
            model_name="submissionevent",
            index=models.Index(fields=["organization", "submission", "created_at"], name="sf_event_org_sub"),
        ),
        migrations.AddIndex(
            model_name="submissionfile",
            index=models.Index(fields=["organization", "sha256"], name="sf_subfile_org_sha"),
        ),
        migrations.AddIndex(
            model_name="submissionfingerprint",
            index=models.Index(fields=["organization", "text_sha256"], name="sf_fp_org_text_sha"),
        ),
        migrations.AddIndex(
            model_name="taskattachment",
            index=models.Index(fields=["organization", "task"], name="sf_attachment_org_task"),
        ),
        migrations.AddIndex(
            model_name="taskdeadline",
            index=models.Index(fields=["organization", "task"], name="sf_deadline_org_task"),
        ),
        migrations.AddConstraint(
            model_name="taskdeadline",
            constraint=models.UniqueConstraint(fields=("assignment", "task"), name="sf_deadline_uniq_assignment_task"),
        ),
        migrations.AddConstraint(
            model_name="taskdeadline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("opens_at__isnull", True),
                    ("due_at__isnull", True),
                    ("opens_at__lt", models.F("due_at")),
                    _connector="OR",
                ),
                name="sf_deadline_opens_before_due",
            ),
        ),
    ]
