#!/usr/bin/env python3
"""Atomically refresh Nginx's trusted Cloudflare network list.

The effective client IP may only come from ``CF-Connecting-IP`` when the TCP
peer is an official Cloudflare address.  Fetching and validating the two
official lists during a Cloudflare-mode deploy avoids trusting arbitrary proxy
headers or silently running with an empty allowlist.
"""

from __future__ import annotations

import argparse
import ipaddress
import os
import tempfile
import urllib.request
from pathlib import Path

IPV4_URL = "https://www.cloudflare.com/ips-v4/"
IPV6_URL = "https://www.cloudflare.com/ips-v6/"
MIN_IPV4_NETWORKS = 10
MIN_IPV6_NETWORKS = 5


def _download(url: str, *, timeout: float) -> str:
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "EMSArena-deploy/1.0"},
        method="GET",
    )
    with urllib.request.urlopen(request, timeout=timeout) as response:  # noqa: S310 - fixed HTTPS URLs
        if response.status != 200:
            raise RuntimeError(f"{url} returned HTTP {response.status}")
        return response.read(64 * 1024).decode("ascii", errors="strict")


Network = ipaddress.IPv4Network | ipaddress.IPv6Network


def _parse_networks(text: str, *, version: int) -> list[Network]:
    networks: list[Network] = []
    seen: set[str] = set()
    for token in text.split():
        network = ipaddress.ip_network(token, strict=True)
        if network.version != version:
            raise ValueError(f"expected IPv{version} CIDR, received {network}")
        canonical = str(network)
        if canonical not in seen:
            seen.add(canonical)
            networks.append(network)
    minimum = MIN_IPV4_NETWORKS if version == 4 else MIN_IPV6_NETWORKS
    if len(networks) < minimum:
        raise ValueError(f"Cloudflare IPv{version} list unexpectedly contains only {len(networks)} networks")
    return networks


def fetch_networks(*, timeout: float = 15.0) -> list[Network]:
    ipv4 = _parse_networks(_download(IPV4_URL, timeout=timeout), version=4)
    ipv6 = _parse_networks(_download(IPV6_URL, timeout=timeout), version=6)
    return [*ipv4, *ipv6]


def render_nginx(networks: list[Network]) -> str:
    lines = [
        "# Generated by scripts/deploy/sync_cloudflare_networks.py.",
        "# Source: Cloudflare official IPv4/IPv6 endpoint lists.",
    ]
    lines.extend(f"set_real_ip_from {network};" for network in networks)
    lines.extend(["", "real_ip_header CF-Connecting-IP;", "real_ip_recursive on;", ""])
    return "\n".join(lines)


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent, text=True)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary_name, 0o644)
        os.replace(temporary_name, path)
    except BaseException:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--timeout", type=float, default=15.0)
    args = parser.parse_args()

    networks = fetch_networks(timeout=args.timeout)
    atomic_write(args.output, render_nginx(networks))
    print(f"Wrote {len(networks)} validated Cloudflare networks to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
