# Generated by Django 5.2.12 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_category_options_category_name_az_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="view_count",
            field=models.PositiveBigIntegerField(db_index=True, default=0),
        ),
    ]
