# Generated by Django 5.2.8 on 2026-02-07 23:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import exams.models
import exams.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_answer",
                    models.TextField(blank=True, verbose_name="Yazılı cavab"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Düzgündür?"),
                ),
                (
                    "teacher_score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Bu suala verilən bal. (məs: 0–10 və ya 0–20 və s.)",
                        null=True,
                        verbose_name="Müəllim balı (sual üzrə)",
                    ),
                ),
                (
                    "teacher_feedback",
                    models.TextField(
                        blank=True, verbose_name="Müəllim rəyi (sual üzrə)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("has_paint", models.BooleanField(default=False)),
                (
                    "paint_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="exam_paints/%Y/%m/"
                    ),
                ),
                ("paint_updated_at", models.DateTimeField(blank=True, null=True)),
                ("paint_data_url", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Sual cavabı",
                "verbose_name_plural": "Sual cavabları",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Blok adı")),
                ("description", models.TextField(blank=True, verbose_name="Qısa izah")),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("test", "Test imtahanı"),
                            ("written", "Yazılı / praktiki"),
                        ],
                        default="test",
                        max_length=20,
                        verbose_name="İmtahan tipi",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="İmtahan bu tarixdən əvvəl başlamaq olmaz. Boş saxlasanız, hər zaman başlamaq olar.",
                        null=True,
                        verbose_name="Başlama tarixi və vaxtı",
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="İmtahan bu tarixdən sonra başlamaq olmaz. Boş saxlasanız, son tarix olmaz.",
                        null=True,
                        verbose_name="Bitmə tarixi və vaxtı",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Əgər söndürsəniz, tələbələr bu imtahanı görə bilməyəcək.",
                        verbose_name="Aktivdir?",
                    ),
                ),
                (
                    "total_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Məs: 30. Boş saxlasanız, ümumi vaxt limiti olmayacaq.",
                        null=True,
                        verbose_name="Ümumi imtahan müddəti (dəqiqə)",
                    ),
                ),
                (
                    "default_question_time_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Məs: 60. Boş saxlasanız, sual basisində vaxt limiti olmayacaq.",
                        null=True,
                        verbose_name="Hər sual üçün default vaxt (saniyə)",
                    ),
                ),
                (
                    "max_attempts_per_user",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Məs: 1, 2, 3... Boş saxlasanız, attempts limitsiz olacaq.",
                        null=True,
                        verbose_name="Bir istifadəçi üçün maksimum cəhd sayı",
                    ),
                ),
                (
                    "random_question_count",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Əgər 0 olarsa, bütün suallar düşür. Əgər rəqəm yazılarsa (məs: 7), bloklardan qarışıq şəkildə cəmi o qədər sual seçilir.",
                        verbose_name="Tələbəyə göstəriləcək sual sayı",
                    ),
                ),
                ("default_question_points", models.PositiveIntegerField(default=1)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Aktivdirsə, imtahan tələbə siyahısı məhdudiyyəti olmadan görünə bilər.",
                        verbose_name="Hamı üçün açıqdır?",
                    ),
                ),
                (
                    "access_code",
                    models.CharField(
                        blank=True,
                        help_text="İstəyə görə əlavə təhlükəsizlik üçün 6 rəqəmli kod.",
                        max_length=6,
                        verbose_name="İmtahan kodu (6 rəqəm)",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enable_paint",
                    models.BooleanField(
                        default=False,
                        help_text="Aktiv edilsə, tələbə cavabı paint ilə çəkib göndərə bilər.",
                        verbose_name="Paint cavabı aktiv olsun",
                    ),
                ),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Yalnız bu istifadəçilər imtahanı görə / başlaya bilsin (qrupdan əlavə olaraq).",
                        related_name="allowed_exams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İcazəli tələbələr (fərdi)",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Müəllif",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exams",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
            ],
            options={
                "verbose_name": "İmtahan bloku",
                "verbose_name_plural": "İmtahan blokları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamAnswerFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="exam_uploads/",
                        validators=[
                            exams.validators.validate_file_extension,
                            exams.validators.validate_file_size,
                            exams.validators.validate_zip_contents,
                        ],
                        verbose_name="Fayl",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yüklənmə tarixi"
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="exams.examanswer",
                        verbose_name="Cavab",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checked_by_teacher",
                    models.BooleanField(
                        default=False, verbose_name="Müəllim tərəfindən yoxlanılıb?"
                    ),
                ),
                (
                    "teacher_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Yoxlanma tarixi"
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Eyni user üçün 1, 2, 3 və s.",
                        verbose_name="Cəhd nömrəsi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft (yarımçıq saxlanılıb)"),
                            ("in_progress", "Davam edir"),
                            ("submitted", "Təslim edilib"),
                            ("expired", "Vaxt bitib"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Faktiki davametmə müddəti (saniyə)",
                    ),
                ),
                ("correct_count", models.PositiveIntegerField(default=0)),
                ("wrong_count", models.PositiveIntegerField(default=0)),
                (
                    "teacher_score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="0–100 arası bal.",
                        null=True,
                        verbose_name="Müəllimin verdiyi bal (%)",
                    ),
                ),
                (
                    "teacher_feedback",
                    models.TextField(blank=True, verbose_name="Müəllimin rəyi"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="exams.exam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "İmtahan cəhdi",
                "verbose_name_plural": "İmtahan cəhdləri",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="examanswer",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="exams.examattempt",
            ),
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.PositiveIntegerField(default=1)),
                (
                    "fingerprint",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("text", models.TextField(verbose_name="Sual mətni")),
                (
                    "correct_answer",
                    models.TextField(
                        blank=True,
                        verbose_name="Düzgün cavab / ideal cavab (yazılı üçün)",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Sıra")),
                (
                    "answer_mode",
                    models.CharField(
                        choices=[
                            ("single", "Tək düzgün cavab"),
                            ("multiple", "Birdən çox düzgün cavab"),
                        ],
                        default="single",
                        help_text="Yalnız test imtahanları üçün mənalıdır.",
                        max_length=20,
                        verbose_name="Cavab rejimi",
                    ),
                ),
                (
                    "time_limit_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Boş saxlasanız, Exam.default_question_time_seconds istifadə olunacaq.",
                        null=True,
                        verbose_name="Bu sual üçün vaxt limiti (saniyə)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=exams.models.question_media_path,
                        verbose_name="Sual şəkli (optional)",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=exams.models.question_media_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp4", "webm", "mov"]
                            ),
                            exams.models.validate_video_size,
                        ],
                        verbose_name="Sual videosu (optional)",
                    ),
                ),
                (
                    "enable_paint",
                    models.BooleanField(
                        default=False,
                        help_text="Yalnız yazılı imtahanda tələbə cavab üçün çəkim (paint) edə bilsin.",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.exam",
                        verbose_name="İmtahan bloku",
                    ),
                ),
            ],
            options={
                "verbose_name": "İmtahan sualı",
                "verbose_name_plural": "İmtahan sualları",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="examanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="exams.examquestion",
            ),
        ),
        migrations.CreateModel(
            name="ExamQuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=255, verbose_name="Variant mətni"),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False, verbose_name="Düzgün variantdır?"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="exams.examquestion",
                        verbose_name="Sual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sual variantı",
                "verbose_name_plural": "Sual variantları",
            },
        ),
        migrations.AddField(
            model_name="examanswer",
            name="selected_options",
            field=models.ManyToManyField(
                blank=True,
                related_name="selected_in_answers",
                to="exams.examquestionoption",
                verbose_name="Seçilmiş variantlar",
            ),
        ),
        migrations.CreateModel(
            name="QuestionBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Blok adı")),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Sıra")),
                (
                    "time_limit_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Bu blokdakı sualları həll etmək üçün ayrılan vaxt. Boş olsa, limit yoxdur.",
                        null=True,
                        verbose_name="Blok vaxtı (dəqiqə)",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_blocks",
                        to="exams.exam",
                        verbose_name="İmtahan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sual Bloku",
                "verbose_name_plural": "Sual Blokları",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="examquestion",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="exams.questionblock",
                verbose_name="Sual Bloku",
            ),
        ),
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Qrup adı / nömrəsi"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="student_groups_as_student",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tələbələr",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Müəllim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tələbə qrupu",
                "verbose_name_plural": "Tələbə qrupları",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="allowed_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Bu qruplardakı bütün tələbələr imtahana giriş icazəsi alır.",
                related_name="exams",
                to="exams.studentgroup",
                verbose_name="İcazəli qruplar",
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["user", "exam", "status"], name="exams_exama_user_id_6ce609_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["user", "exam", "-started_at"],
                name="exams_exama_user_id_bf4f2e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examanswer",
            unique_together={("attempt", "question")},
        ),
        migrations.AlterUniqueTogether(
            name="studentgroup",
            unique_together={("teacher", "name")},
        ),
    ]
