# Generated by Django 5.2.8 on 2025-12-15 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_exam_access_code_exam_allowed_users_exam_is_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="random_question_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Əgər 0 olarsa, bütün suallar düşür. Əgər rəqəm yazılarsa (məs: 7), bloklardan qarışıq şəkildə cəmi o qədər sual seçilir.",
                verbose_name="Tələbəyə göstəriləcək sual sayı",
            ),
        ),
        migrations.CreateModel(
            name="QuestionBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Blok adı")),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Sıra")),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_blocks",
                        to="blog.exam",
                        verbose_name="İmtahan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sual Bloku",
                "verbose_name_plural": "Sual Blokları",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="examquestion",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="blog.questionblock",
                verbose_name="Sual Bloku",
            ),
        ),
    ]
