# Generated by Django 5.2.8 on 2025-12-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_exam_random_question_count_questionblock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionblock",
            name="time_limit_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Bu blokdakı sualları həll etmək üçün ayrılan vaxt. Boş olsa, limit yoxdur.",
                null=True,
                verbose_name="Blok vaxtı (dəqiqə)",
            ),
        ),
    ]
