# Generated by Django 5.2.8 on 2026-01-04 21:25

import blog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0022_emailotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="examquestion",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=blog.models.question_media_path,
                verbose_name="Sual şəkli (optional)",
            ),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=blog.models.question_media_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "webm", "mov"]
                    ),
                    blog.models.validate_video_size,
                ],
                verbose_name="Sual videosu (optional)",
            ),
        ),
    ]
