# Generated by Django 5.2.8 on 2026-01-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0023_examquestion_image_examquestion_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="examquestion",
            name="enable_paint",
            field=models.BooleanField(default=False),
        ),
    ]
