# Generated by Django 5.2.8 on 2026-01-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0024_examquestion_enable_paint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examquestion",
            name="enable_paint",
            field=models.BooleanField(
                default=False,
                help_text="Yalnız yazılı imtahanda tələbə cavab üçün çəkim (paint) edə bilsin.",
            ),
        ),
    ]
