# Generated by Django 5.2.8 on 2026-01-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0027_alter_examattempt_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="end_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="İmtahan bu tarixdən sonra başlamaq olmaz. Boş saxlasanız, son tarix olmaz.",
                null=True,
                verbose_name="Bitmə tarixi və vaxtı",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="start_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="İmtahan bu tarixdən əvvəl başlamaq olmaz. Boş saxlasanız, hər zaman başlamaq olar.",
                null=True,
                verbose_name="Başlama tarixi və vaxtı",
            ),
        ),
    ]
