# Generated by Django 5.2.8 on 2026-01-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0028_exam_end_datetime_exam_start_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="enable_paint",
            field=models.BooleanField(
                default=False,
                help_text="Aktiv edilsə, tələbə cavabı paint ilə çəkib göndərə bilər.",
                verbose_name="Paint cavabı aktiv olsun",
            ),
        ),
    ]
