# Generated by Django 5.2.8 on 2026-01-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0029_exam_enable_paint"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="paint_disabled_override",
            field=models.BooleanField(default=False),
        ),
    ]
