# Generated by Django 5.2.8 on 2026-01-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0030_exam_paint_disabled_override"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="paint_disabled_override",
        ),
        migrations.AddField(
            model_name="examquestion",
            name="paint_force_disable",
            field=models.BooleanField(default=False),
        ),
    ]
