# Generated by Django 5.2.8 on 2026-01-16 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0031_remove_exam_paint_disabled_override_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examquestion",
            name="paint_force_disable",
        ),
    ]
