# Generated by Django 5.2.8 on 2026-01-30 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0032_remove_examquestion_paint_force_disable"),
        ("courses", "0004_remove_course_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exams",
                to="courses.course",
                verbose_name="Kurs",
            ),
        ),
    ]
