# Generated by Django 5.2.8 on 2026-02-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0033_exam_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
