# Generated by Django 5.2.8 on 2026-02-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0034_examattempt_checked_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examattempt",
            name="checked_at",
        ),
        migrations.AddField(
            model_name="examattempt",
            name="teacher_checked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Yoxlanma tarixi"
            ),
        ),
    ]
