# Generated by Django 5.2.8 on 2026-01-16 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Kurs adı")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Kurs təsviri"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=220, unique=True, verbose_name="URL slug"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft (yayımlanmayıb)"),
                            ("published", "Yayımlandı"),
                            ("archived", "Arxivləndi"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="course_covers/%Y/%m/",
                        verbose_name="Kurs şəkli",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə tarixi"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Müəllif (Müəllim)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs",
                "verbose_name_plural": "Kurslar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseGradePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=40,
                        max_digits=5,
                        verbose_name="İmtahan çəkisi (%)",
                    ),
                ),
                (
                    "lab_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=30,
                        max_digits=5,
                        verbose_name="Lab çəkisi (%)",
                    ),
                ),
                (
                    "freework_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=5,
                        verbose_name="Sərbəst iş çəkisi (%)",
                    ),
                ),
                (
                    "coursework_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        max_digits=5,
                        verbose_name="Kurs işi çəkisi (%)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_policy",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs Qiymətləndirmə Siyasəti",
                "verbose_name_plural": "Kurs Qiymətləndirmə Siyasətləri",
            },
        ),
        migrations.CreateModel(
            name="CourseMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("teacher", "Müəllim"),
                            ("assistant", "Asistant"),
                            ("student", "Tələbə"),
                        ],
                        default="student",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Qrup adı (optional)"
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Qoşulma tarixi"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs üzvü",
                "verbose_name_plural": "Kurs üzvləri",
            },
        ),
        migrations.CreateModel(
            name="CourseSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name='Bölmə adı (məs: "Həftə 1: Giriş")'
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Bölmə təsviri"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="Sıra nömrəsi"),
                ),
                (
                    "unlock_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bu tarixdən sonra açılacaq"
                    ),
                ),
                (
                    "lock_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Bu tarixdən sonra bağlanacaq",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "prerequisite_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_sections",
                        to="courses.coursesection",
                        verbose_name="Əvvəlcə tamamlanmalı bölmə",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs bölməsi",
                "verbose_name_plural": "Kurs bölmələri",
                "ordering": ["course", "order"],
            },
        ),
        migrations.CreateModel(
            name="CourseResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Resurs başlığı"),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("article", "Məqalə"),
                            ("book", "Kitab"),
                            ("video", "Video"),
                            ("website", "Vebsayt"),
                            ("dataset", "Məlumat Seti"),
                        ],
                        max_length=20,
                        verbose_name="Resurs tipi",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Müəllif"
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True, verbose_name="İl")),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "doi",
                    models.CharField(blank=True, max_length=255, verbose_name="DOI"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Təsviri")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="course_resources/%Y/%m/",
                        verbose_name="Fayl yüklə",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Zəruri mi?"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="courses.coursesection",
                        verbose_name="Bölmə (optional)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs Resursu",
                "verbose_name_plural": "Kurs Resursları",
                "ordering": ["course", "order"],
            },
        ),
        migrations.CreateModel(
            name="CourseContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Məzmun başlığı"),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("pdf", "PDF Sənəd"),
                            ("ppt", "PowerPoint"),
                            ("link", "Xarici Link"),
                            ("text", "Mətn / HTML"),
                            ("file", "Fayl"),
                        ],
                        max_length=20,
                        verbose_name="Məzmun tipi",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıqlama")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="course_content/%Y/%m/",
                        verbose_name="Fayl",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, verbose_name="URL (YouTube, Vimeo, və s.)"
                    ),
                ),
                (
                    "text_content",
                    models.TextField(blank=True, verbose_name="Mətn məzmunu"),
                ),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Sıra")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Müddət (dəqiqə) - video üçün",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="courses.coursesection",
                        verbose_name="Bölmə",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs məzmunu",
                "verbose_name_plural": "Kurs məzmunları",
                "ordering": ["section", "order"],
            },
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["owner", "-created_at"], name="courses_cou_owner_i_e2e8dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["status"], name="courses_cou_status_158bbf_idx"),
        ),
        migrations.AddIndex(
            model_name="coursemembership",
            index=models.Index(
                fields=["course", "role"], name="courses_cou_course__076371_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coursemembership",
            unique_together={("course", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="coursesection",
            unique_together={("course", "order")},
        ),
    ]
