# Generated by Django 5.2.8 on 2026-01-16 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Mövzu Adı")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Mövzu Təsviri"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="1, 2, 3, ... (hansı mövzu əvvəl göstərilsin)",
                        verbose_name="Sıra Nömrəsi",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs Mövzusu",
                "verbose_name_plural": "Kurs Mövzuları",
                "ordering": ["course", "order"],
            },
        ),
        migrations.RemoveField(
            model_name="coursecontent",
            name="section",
        ),
        migrations.RemoveField(
            model_name="coursegradepolicy",
            name="course",
        ),
        migrations.AlterUniqueTogether(
            name="coursesection",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="coursesection",
            name="course",
        ),
        migrations.RemoveField(
            model_name="coursesection",
            name="prerequisite_section",
        ),
        migrations.RemoveField(
            model_name="courseresource",
            name="section",
        ),
        migrations.AlterModelOptions(
            name="coursemembership",
            options={
                "verbose_name": "Kurs Üzvü",
                "verbose_name_plural": "Kurs Üzvləri",
            },
        ),
        migrations.AlterModelOptions(
            name="courseresource",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Kurs Resursu",
                "verbose_name_plural": "Kurs Resursları",
            },
        ),
        migrations.RemoveField(
            model_name="courseresource",
            name="author",
        ),
        migrations.RemoveField(
            model_name="courseresource",
            name="doi",
        ),
        migrations.RemoveField(
            model_name="courseresource",
            name="is_required",
        ),
        migrations.RemoveField(
            model_name="courseresource",
            name="order",
        ),
        migrations.RemoveField(
            model_name="courseresource",
            name="year",
        ),
        migrations.AlterField(
            model_name="course",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="course_covers/%Y/%m/",
                verbose_name="Kurs Şəkli",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yaradılma Tarixi"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, verbose_name="Kurs Təsviri"),
        ),
        migrations.AlterField(
            model_name="course",
            name="owner",
            field=models.ForeignKey(
                help_text="Kursun sahibi olan müəllim",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taught_courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Müəllif (Müəllim)",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="URL Slug"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft (yayımlanmayıb)"),
                    ("published", "Yayımlandı"),
                    ("archived", "Arxivləndi"),
                ],
                default="draft",
                help_text="Draft: tələbələr görmə, Published: görsün",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Kurs Adı"),
        ),
        migrations.AlterField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Yenilənmə Tarixi"),
        ),
        migrations.AlterField(
            model_name="coursemembership",
            name="group_name",
            field=models.CharField(
                blank=True,
                help_text='Məs: "875i", "842A1". Tələbəyə aid qrup.',
                max_length=100,
                verbose_name="Qrup Adı (isteğe bağlı)",
            ),
        ),
        migrations.AlterField(
            model_name="coursemembership",
            name="joined_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Qoşulma Tarixi"
            ),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yaradılma Tarixi"
            ),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="description",
            field=models.TextField(blank=True, verbose_name="Açıqlama"),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Fayl yükləyin (PDF, ZIP, IMG, və s.)",
                null=True,
                upload_to="course_resources/%Y/%m/",
                verbose_name="Fayl",
            ),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("file", "Fayl (PDF, ZIP, və s.)"),
                    ("link", "Xarici Link"),
                    ("document", "Sənəd"),
                    ("video", "Video"),
                ],
                default="file",
                max_length=20,
                verbose_name="Resurs Tipi",
            ),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Resurs Başlığı"),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Məs: https://docs.python.org",
                verbose_name="URL Linki",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["slug"], name="courses_cou_slug_2e551f_idx"),
        ),
        migrations.AddIndex(
            model_name="coursemembership",
            index=models.Index(
                fields=["course", "group_name"], name="courses_cou_course__44546e_idx"
            ),
        ),
        migrations.AddField(
            model_name="coursetopic",
            name="course",
            field=models.ForeignKey(
                help_text="Bu mövzu hansı kursa aiddir",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="courses.course",
                verbose_name="Kurs",
            ),
        ),
        migrations.AddField(
            model_name="courseresource",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                help_text="Bu resurs hansı mövzuya aid (boş olabilər - kurs səviyyəsində)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resources",
                to="courses.coursetopic",
                verbose_name="Mövzu (isteğe bağlı)",
            ),
        ),
        migrations.AddIndex(
            model_name="courseresource",
            index=models.Index(
                fields=["course", "topic"], name="courses_cou_course__c30055_idx"
            ),
        ),
        migrations.DeleteModel(
            name="CourseContent",
        ),
        migrations.DeleteModel(
            name="CourseGradePolicy",
        ),
        migrations.DeleteModel(
            name="CourseSection",
        ),
        migrations.AddIndex(
            model_name="coursetopic",
            index=models.Index(
                fields=["course", "order"], name="courses_cou_course__0e20e3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coursetopic",
            unique_together={("course", "order")},
        ),
    ]
