# Generated by Django 5.2.8 on 2026-01-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0032_remove_examquestion_paint_force_disable"),
        ("courses", "0002_coursetopic_remove_coursecontent_section_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses",
                to="blog.studentgroup",
                verbose_name="Kursa əlavə olunan qruplar",
            ),
        ),
    ]
