# Generated by Django 5.2.8 on 2026-01-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="groups",
        ),
    ]
