# Generated by Django 5.2.8 on 2026-01-19 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0004_remove_course_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Sərəbəst İş Adı"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Təsvir"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deadline", models.DateTimeField(verbose_name="Müddət")),
                (
                    "max_attempts",
                    models.IntegerField(default=3, verbose_name="Maksimum Cəhdlər"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("closed", "Bağlı"),
                            ("archived", "Arxivlənmiş"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "target_groups",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="Hədəf Qrupları",
                    ),
                ),
                (
                    "target_users",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="Hədəf Tələbələri",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="courses.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sərəbəst İş",
                "verbose_name_plural": "Sərəbəst İşlər",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_answer",
                    models.TextField(blank=True, null=True, verbose_name="Mətn Cavabı"),
                ),
                ("attempt_number", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qaralama"),
                            ("submitted", "Göndərildi"),
                            ("graded", "Qiymətləndirildi"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True, verbose_name="Bal")),
                (
                    "max_score",
                    models.FloatField(default=100, verbose_name="Maksimum Bal"),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="Rəy"),
                ),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="assignments.courseassignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sərəbəst İş Cavabı",
                "verbose_name_plural": "Sərəbəst İş Cavabları",
                "ordering": ["-created_at"],
                "unique_together": {("assignment", "student", "attempt_number")},
            },
        ),
        migrations.CreateModel(
            name="SubmissionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="assignments/%Y/%m/%d/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="assignments.assignmentsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cavab Faylı",
                "verbose_name_plural": "Cavab Faylları",
            },
        ),
    ]
