# Generated by Django 5.2.8 on 2026-01-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseassignment",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Başlama Tarixi"
            ),
        ),
        migrations.AlterField(
            model_name="courseassignment",
            name="deadline",
            field=models.DateTimeField(verbose_name="Bitmə Tarixi"),
        ),
    ]
