# Generated by Django 5.2.8 on 2026-01-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_courseassignment_start_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignmentsubmission",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Cavab",
                "verbose_name_plural": "Cavablar",
            },
        ),
        migrations.AlterModelOptions(
            name="courseassignment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Sərbəst İş",
                "verbose_name_plural": "Sərbəst İşlər",
            },
        ),
        migrations.AlterModelOptions(
            name="submissionfile",
            options={"verbose_name": "Fayl", "verbose_name_plural": "Fayllar"},
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="max_score",
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="text_answer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="courseassignment",
            name="deadline",
            field=models.DateTimeField(verbose_name="Son Tarix"),
        ),
        migrations.AlterField(
            model_name="courseassignment",
            name="target_groups",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="courseassignment",
            name="target_users",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="courseassignment",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Sərbəst İş Adı"),
        ),
    ]
