# Generated by Django 5.2.8 on 2026-01-20 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_alter_assignmentsubmission_options_and_more"),
        ("courses", "0004_remove_course_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="assignments.courseassignment",
                verbose_name="Sərbəst İş",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="attempt_number",
            field=models.PositiveIntegerField(default=1, verbose_name="Cəhd nömrəsi"),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="feedback",
            field=models.TextField(blank=True, null=True, verbose_name="Feedback"),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Qiymətləndirən",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="max_score",
            field=models.FloatField(default=100, verbose_name="Maksimum bal"),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="score",
            field=models.FloatField(blank=True, null=True, verbose_name="Bal"),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Tələbə",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="text_answer",
            field=models.TextField(blank=True, null=True, verbose_name="Mətn cavab"),
        ),
        migrations.AlterField(
            model_name="courseassignment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="courses.course",
                verbose_name="Kurs",
            ),
        ),
        migrations.AlterField(
            model_name="courseassignment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Yaradan",
            ),
        ),
        migrations.AlterField(
            model_name="courseassignment",
            name="max_attempts",
            field=models.PositiveIntegerField(default=3, verbose_name="Maksimum cəhd"),
        ),
        migrations.AlterField(
            model_name="submissionfile",
            name="file",
            field=models.FileField(
                upload_to="assignments/%Y/%m/%d/", verbose_name="Fayl"
            ),
        ),
        migrations.AlterField(
            model_name="submissionfile",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="assignments.assignmentsubmission",
                verbose_name="Cavab",
            ),
        ),
    ]
