# Generated by Django 5.2.8 on 2026-01-20 20:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0004_alter_assignmentsubmission_assignment_and_more"),
        ("courses", "0004_remove_course_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseassignment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="courseassignment",
            name="created_by",
        ),
        migrations.AlterModelOptions(
            name="assignmentsubmission",
            options={
                "ordering": ["-submitted_at"],
                "verbose_name": "Cavab",
                "verbose_name_plural": "Cavablar",
            },
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="Cavab"),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="assignments/submissions/",
                verbose_name="Fayl",
            ),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="grade",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Qiymət",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="feedback",
            field=models.TextField(blank=True, null=True, verbose_name="Rəy"),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Gözləyir"),
                    ("graded", "Qiymətləndirilib"),
                    ("rejected", "Rədd edilib"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="submitted_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Başlıq")),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                ("deadline", models.DateTimeField(verbose_name="Son tarix")),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Maksimum cəhd"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("inactive", "Deaktiv"),
                            ("archived", "Arxivləndi"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="student_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tələbələr",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sərbəst İş",
                "verbose_name_plural": "Sərbəst İşlər",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="assignmentsubmission",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="assignments.assignment",
                verbose_name="Tapşırıq",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignmentsubmission",
            unique_together={("assignment", "student", "submitted_at")},
        ),
        migrations.DeleteModel(
            name="SubmissionFile",
        ),
        migrations.DeleteModel(
            name="CourseAssignment",
        ),
        migrations.RemoveField(
            model_name="assignmentsubmission",
            name="attempt_number",
        ),
        migrations.RemoveField(
            model_name="assignmentsubmission",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="assignmentsubmission",
            name="max_score",
        ),
        migrations.RemoveField(
            model_name="assignmentsubmission",
            name="score",
        ),
        migrations.RemoveField(
            model_name="assignmentsubmission",
            name="text_answer",
        ),
        migrations.RemoveField(
            model_name="assignmentsubmission",
            name="updated_at",
        ),
    ]
