# Generated by Django 5.2.8 on 2026-01-20 20:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0005_remove_courseassignment_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Tələbələr bu tarixdən sonra cavab verə bilər",
                verbose_name="Başlanğıc tarixi",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="content",
            field=models.TextField(default="", verbose_name="Cavab"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="feedback",
            field=models.TextField(blank=True, default="", verbose_name="Rəy"),
            preserve_default=False,
        ),
    ]
