# Generated by Django 5.2.17 on 2026-09-25 01:00

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0053_rim_full_permissions"),
        ("registrar", "0079_atis_admission_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyCampaign",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Qaralama"), ("open", "Açıq"), ("closed", "Bağlı")],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("opens_on", models.DateField(blank=True, null=True)),
                ("closes_on", models.DateField(blank=True, null=True)),
                ("mandatory", models.BooleanField(default=True)),
                ("grace_until", models.DateField(blank=True, null=True)),
                (
                    "min_group_size",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(3),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "opened_via",
                    models.CharField(
                        choices=[("journal_close", "Jurnal bağlanması"), ("manual", "Əl ilə")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_campaigns",
                        to="organizations.organization",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="survey_campaigns",
                        to="organizations.academicperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "sorğu kampaniyası",
                "verbose_name_plural": "sorğu kampaniyaları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.SlugField(max_length=64)),
                ("section", models.CharField(choices=[("teacher", "Müəllim"), ("general", "Ümumi")], max_length=16)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("likert5", "Razılıq şkalası (1–5)"),
                            ("scale10", "Bal şkalası (1–10)"),
                            ("text", "Sərbəst mətn"),
                        ],
                        max_length=16,
                    ),
                ),
                ("text", models.TextField()),
                ("help_text", models.CharField(blank=True, max_length=300)),
                ("required", models.BooleanField(default=True)),
                ("in_index", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="organizations.organization"
                    ),
                ),
            ],
            options={
                "verbose_name": "sorğu sualı",
                "verbose_name_plural": "sorğu sualları",
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("scope", models.CharField(choices=[("teacher", "Müəllim"), ("general", "Ümumi")], max_length=16)),
                ("course_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="surveys.surveycampaign",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="organizations.orgunit",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="organizations.orgunit",
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="registrar.courseoffering",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="organizations.organization"
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="registrar.program",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="registrar.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="organizations.orgunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "anonim cavab",
                "verbose_name_plural": "anonim cavablar",
            },
        ),
        migrations.CreateModel(
            name="SurveyAnswer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("score", models.SmallIntegerField(blank=True, null=True)),
                ("text", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="organizations.organization"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="surveys.surveyquestion"
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="surveys.surveyresponse"
                    ),
                ),
            ],
            options={
                "verbose_name": "sorğu cavabı",
                "verbose_name_plural": "sorğu cavabları",
            },
        ),
        migrations.CreateModel(
            name="SurveyTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_templates",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "sorğu şablonu",
                "verbose_name_plural": "sorğu şablonları",
                "ordering": ["-is_default", "name", "-version"],
            },
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="surveys.surveytemplate"
            ),
        ),
        migrations.AddField(
            model_name="surveycampaign",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="campaigns", to="surveys.surveytemplate"
            ),
        ),
        migrations.CreateModel(
            name="SurveyReceipt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("scope", models.CharField(choices=[("teacher", "Müəllim"), ("general", "Ümumi")], max_length=16)),
                ("completed_on", models.DateField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="surveys.surveycampaign",
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="registrar.courseoffering",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="organizations.organization"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="organizations.orgunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "sorğu qəbzi",
                "verbose_name_plural": "sorğu qəbzləri",
                "indexes": [models.Index(fields=["campaign", "scope"], name="surveys_receipt_camp_scope")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("scope", "teacher")),
                        fields=("campaign", "student", "offering", "teacher"),
                        name="surveys_receipt_teacher_once",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("scope", "general")),
                        fields=("campaign", "student"),
                        name="surveys_receipt_general_once",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("offering__isnull", False), ("scope", "teacher"), ("teacher__isnull", False)),
                            models.Q(("offering__isnull", True), ("scope", "general"), ("teacher__isnull", True)),
                            _connector="OR",
                        ),
                        name="surveys_receipt_scope_shape",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(fields=["campaign", "scope"], name="surveys_resp_camp_scope"),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(fields=["campaign", "teacher"], name="surveys_resp_camp_teacher"),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(fields=["campaign", "teacher_department"], name="surveys_resp_camp_dept"),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(fields=["campaign", "faculty"], name="surveys_resp_camp_faculty"),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(fields=["campaign", "subject"], name="surveys_resp_camp_subject"),
        ),
        migrations.AddConstraint(
            model_name="surveyresponse",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("offering__isnull", True), ("scope", "general"), ("teacher__isnull", True)),
                    ("scope", "teacher"),
                    _connector="OR",
                ),
                name="surveys_response_general_shape",
            ),
        ),
        migrations.AddIndex(
            model_name="surveyanswer",
            index=models.Index(fields=["question", "score"], name="surveys_answer_q_score"),
        ),
        migrations.AddConstraint(
            model_name="surveyanswer",
            constraint=models.UniqueConstraint(fields=("response", "question"), name="surveys_answer_once"),
        ),
        migrations.AddConstraint(
            model_name="surveyanswer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("score__isnull", True), models.Q(("score__gte", 1), ("score__lte", 10)), _connector="OR"
                ),
                name="surveys_answer_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="surveytemplate",
            constraint=models.UniqueConstraint(
                fields=("organization", "name", "version"), name="surveys_template_name_version_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveytemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)), fields=("organization",), name="surveys_template_one_default"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyquestion",
            constraint=models.UniqueConstraint(fields=("template", "code"), name="surveys_question_code_uniq"),
        ),
        migrations.AddConstraint(
            model_name="surveycampaign",
            constraint=models.UniqueConstraint(fields=("organization", "period"), name="surveys_campaign_period_uniq"),
        ),
        migrations.AddConstraint(
            model_name="surveycampaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_group_size__gte", 3)), name="surveys_campaign_min_group_floor"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveycampaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closes_on__isnull", True),
                    ("opens_on__isnull", True),
                    ("closes_on__gte", models.F("opens_on")),
                    _connector="OR",
                ),
                name="surveys_campaign_dates_ordered",
            ),
        ),
    ]
