# Generated by Django 5.2.13 on 2026-07-12 17:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0023_grade_event_append_only"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Məlumat"),
                            ("low", "Aşağı"),
                            ("medium", "Orta"),
                            ("high", "Yüksək"),
                            ("critical", "Kritik"),
                        ],
                        default="medium",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Açıq"),
                            ("acknowledged", "Qəbul edilib"),
                            ("investigating", "Araşdırılır"),
                            ("monitoring", "İzlənilir"),
                            ("resolved", "Həll olunub"),
                            ("silenced", "Səssizləşdirilib"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("source", models.CharField(default="alertmanager", max_length=32)),
                ("service", models.CharField(blank=True, max_length=100)),
                ("alert_rule", models.CharField(blank=True, db_index=True, max_length=150)),
                ("environment", models.CharField(default="production", max_length=32)),
                ("fingerprint", models.CharField(db_index=True, max_length=128)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("labels", models.JSONField(blank=True, default=dict)),
                ("annotations", models.JSONField(blank=True, default=dict)),
                ("delivery_log", models.JSONField(blank=True, default=list)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitoring_incidents_acknowledged",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitoring_incidents_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitoring_incidents_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_failed", "Uğursuz giriş"),
                            ("login_brute_force", "Brute-force nümunəsi"),
                            ("superadmin_login", "Superadmin girişi"),
                            ("superadmin_login_failed", "Superadmin uğursuz girişi"),
                            ("unauthorized_monitoring", "İcazəsiz monitorinq cəhdi"),
                            ("permission_denied_spike", "İcazə rədd sıçrayışı"),
                            ("rate_limit", "Rate-limit hadisəsi"),
                            ("exam_pin_abuse", "İmtahan PIN sui-istifadəsi"),
                            ("config_change", "Kritik konfiqurasiya dəyişikliyi"),
                            ("other", "Digər"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Məlumat"),
                            ("low", "Aşağı"),
                            ("medium", "Orta"),
                            ("high", "Yüksək"),
                            ("critical", "Kritik"),
                        ],
                        default="low",
                        max_length=16,
                    ),
                ),
                ("source_service", models.CharField(default="django", max_length=64)),
                ("username_hint", models.CharField(blank=True, max_length=150)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("request_info", models.JSONField(blank=True, default=dict)),
                ("message", models.CharField(blank=True, max_length=500)),
                ("count", models.PositiveIntegerField(default=1)),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="monitoring.incident"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.organization",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitoring_security_events_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitoring_security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(fields=["fingerprint", "status"], name="monitoring__fingerp_2962d4_idx"),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(fields=["severity", "-started_at"], name="monitoring__severit_833c39_idx"),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(fields=["event_type", "-last_seen_at"], name="monitoring__event_t_aae880_idx"),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(fields=["ip_address", "event_type"], name="monitoring__ip_addr_443d27_idx"),
        ),
    ]
