# Generated by Django 5.2.8 on 2026-03-15 20:13

import core.upload_security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0002_alter_labassignment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lab",
            name="teacher_files",
            field=models.FileField(
                blank=True,
                help_text="PDF, ZIP, DOC və s.",
                null=True,
                upload_to="labs/teacher_files/%Y/%m/",
                validators=[core.upload_security.FileUploadValidator()],
                verbose_name="Müəllim faylı",
            ),
        ),
        migrations.AlterField(
            model_name="labanswer",
            name="answer_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="labs/answers/%Y/%m/",
                validators=[core.upload_security.FileUploadValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="labquestion",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="labs/questions/%Y/%m/",
                validators=[core.upload_security.FileUploadValidator()],
                verbose_name="Əlavə fayl",
            ),
        ),
    ]
