# Generated by Django 5.2.17 on 2026-09-02 06:03

import apps.applications.models.events
import core.upload_security
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0032_seed_alumni_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationCounter",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="application_counter",
                        serialize=False,
                        to="organizations.organization",
                    ),
                ),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "müraciət nömrə sayğacı",
                "verbose_name_plural": "müraciət nömrə sayğacları",
            },
        ),
        migrations.CreateModel(
            name="ApplicationKind",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.SlugField(max_length=40)),
                ("label", models.CharField(max_length=160)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "allowed_sender_families",
                    models.JSONField(
                        blank=True, default=list, help_text="SenderFamily dəyərləri: student / teacher / staff."
                    ),
                ),
                (
                    "route_overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{'student': 'koordinator', …} — ailəyə görə fərqli şöbə kodu.",
                    ),
                ),
                ("sla_days", models.PositiveSmallIntegerField(default=5)),
                ("badge_palette", models.CharField(default="neutral", max_length=20)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_kinds",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "müraciət növü",
                "verbose_name_plural": "müraciət növləri",
                "ordering": ["organization", "order", "label"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("number", models.CharField(db_index=True, max_length=20)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "sender_family",
                    models.CharField(
                        choices=[("student", "Tələbə"), ("teacher", "Müəllim"), ("staff", "Əməkdaş")], max_length=16
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Yeni"),
                            ("in_review", "Baxılır"),
                            ("assigned", "Təyin edilib"),
                            ("forwarded", "Yönləndirilib"),
                            ("waiting_info", "Məlumat gözlənilir"),
                            ("returned", "Düzəliş üçün qaytarılıb"),
                            ("resolved", "Həll olunub"),
                            ("rejected", "Rədd edilib"),
                            ("closed", "Bağlanıb"),
                            ("cancelled", "Ləğv edilib"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("sla_due_on", models.DateField(blank=True, db_index=True, null=True)),
                ("submitted_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_scope_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cari şöbənin aidiyyət bölməsi; mərkəzi şöbədə NULL.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications_at_unit",
                        to="organizations.orgunit",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="organizations.organization",
                    ),
                ),
                (
                    "sender_scope_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Göndərənin öz bölməsi (tələbə: qrup, müəllim: kafedra).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications_sent",
                        to="organizations.orgunit",
                    ),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="applications.applicationkind",
                    ),
                ),
            ],
            options={
                "verbose_name": "müraciət",
                "verbose_name_plural": "müraciətlər",
                "ordering": ["-last_activity_at", "-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationUnit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.SlugField(max_length=40)),
                ("name", models.CharField(max_length=160)),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", help_text="Yönləndirmə dialoqunda göstərilən qısa izah.", max_length=255
                    ),
                ),
                (
                    "handler_role_names",
                    models.JSONField(
                        blank=True, default=list, help_text="Bu şöbəni emal edən Role.name siyahısı (məs. ['dean'])."
                    ),
                ),
                (
                    "resolve_by",
                    models.CharField(
                        choices=[
                            ("organization", "Bütün təşkilat (mərkəzi şöbə)"),
                            ("faculty", "Göndərənin fakültəsi"),
                            ("chair", "Göndərənin kafedrası"),
                            ("specialty", "Göndərənin ixtisası"),
                        ],
                        default="organization",
                        help_text="Müraciət göndərənin hansı əcdad bölməsinə bağlanır.",
                        max_length=20,
                    ),
                ),
                ("default_sla_days", models.PositiveSmallIntegerField(default=5)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_units",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "müraciət şöbəsi",
                "verbose_name_plural": "müraciət şöbələri",
                "ordering": ["organization", "order", "name"],
            },
        ),
        migrations.AddField(
            model_name="applicationkind",
            name="target_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="kinds", to="applications.applicationunit"
            ),
        ),
        migrations.CreateModel(
            name="ApplicationEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("submitted", "Göndərildi"),
                            ("seen", "Baxışa götürüldü"),
                            ("comment", "Qeyd"),
                            ("assigned", "Məsul şəxsə təyin edildi"),
                            ("info_requested", "Əlavə məlumat istənildi"),
                            ("info_provided", "Əlavə məlumat verildi"),
                            ("forwarded", "Başqa şöbəyə yönləndirildi"),
                            ("returned", "Düzəliş üçün qaytarıldı"),
                            ("resubmitted", "Düzəlişdən sonra yenidən göndərildi"),
                            ("resolved", "Həll olundu"),
                            ("rejected", "Rədd edildi"),
                            ("closed", "Bağlandı"),
                            ("cancelled", "Ləğv edildi"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actor_name", models.CharField(blank=True, default="", editable=False, max_length=200)),
                ("actor_role_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("submitted", "Yeni"),
                            ("in_review", "Baxılır"),
                            ("assigned", "Təyin edilib"),
                            ("forwarded", "Yönləndirilib"),
                            ("waiting_info", "Məlumat gözlənilir"),
                            ("returned", "Düzəliş üçün qaytarılıb"),
                            ("resolved", "Həll olunub"),
                            ("rejected", "Rədd edilib"),
                            ("closed", "Bağlanıb"),
                            ("cancelled", "Ləğv edilib"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("submitted", "Yeni"),
                            ("in_review", "Baxılır"),
                            ("assigned", "Təyin edilib"),
                            ("forwarded", "Yönləndirilib"),
                            ("waiting_info", "Məlumat gözlənilir"),
                            ("returned", "Düzəliş üçün qaytarılıb"),
                            ("resolved", "Həll olunub"),
                            ("rejected", "Rədd edilib"),
                            ("closed", "Bağlanıb"),
                            ("cancelled", "Ləğv edilib"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False, help_text="Yalnız emalçılar görür — müraciət sahibinə göstərilmir."
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="applications.application",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_events",
                        to="organizations.organization",
                    ),
                ),
                (
                    "from_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_from",
                        to="applications.applicationunit",
                    ),
                ),
                (
                    "to_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_to",
                        to="applications.applicationunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "müraciət hadisəsi",
                "verbose_name_plural": "müraciət hadisələri",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="current_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_applications",
                to="applications.applicationunit",
            ),
        ),
        migrations.CreateModel(
            name="ApplicationWatch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watches",
                        to="applications.application",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_watches",
                        to="organizations.organization",
                    ),
                ),
                (
                    "scope_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_watches",
                        to="organizations.orgunit",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watches",
                        to="applications.applicationunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "müraciət izləməsi",
                "verbose_name_plural": "müraciət izləmələri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationAttachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.applications.models.events.application_attachment_path,
                        validators=[
                            core.upload_security.FileUploadValidator(
                                allowed_extensions={".docx", ".jpeg", ".jpg", ".pdf", ".png"}, max_size_mb=10
                            )
                        ],
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, default="", max_length=120)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="applications.application",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_attachments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="applications.applicationevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "müraciət sənədi",
                "verbose_name_plural": "müraciət sənədləri",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["organization", "application"], name="application_organiz_de7002_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="applicationunit",
            index=models.Index(fields=["organization", "is_active"], name="application_organiz_b341ba_idx"),
        ),
        migrations.AddConstraint(
            model_name="applicationunit",
            constraint=models.UniqueConstraint(fields=("organization", "code"), name="uniq_application_unit_code"),
        ),
        migrations.AddIndex(
            model_name="applicationkind",
            index=models.Index(fields=["organization", "is_active"], name="application_organiz_3abace_idx"),
        ),
        migrations.AddConstraint(
            model_name="applicationkind",
            constraint=models.UniqueConstraint(fields=("organization", "code"), name="uniq_application_kind_code"),
        ),
        migrations.AddIndex(
            model_name="applicationevent",
            index=models.Index(
                fields=["organization", "application", "created_at"], name="application_organiz_5f8ad5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["organization", "status"], name="application_organiz_6c3f01_idx"),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["organization", "created_by", "-submitted_at"], name="application_organiz_2dd0e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["organization", "current_unit", "status"], name="application_organiz_c33799_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["organization", "current_scope_unit"], name="application_organiz_7c631a_idx"),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(fields=("organization", "number"), name="uniq_application_number"),
        ),
        migrations.AddIndex(
            model_name="applicationwatch",
            index=models.Index(fields=["organization", "unit"], name="application_organiz_541d3f_idx"),
        ),
        migrations.AddConstraint(
            model_name="applicationwatch",
            constraint=models.UniqueConstraint(fields=("application", "unit"), name="uniq_application_watch"),
        ),
    ]
