# Generated by Django 5.2.17 on 2026-09-06 21:16

import apps.applications.models.events
import core.upload_security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_seed_permissions_and_catalog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationattachment",
            name="file",
            field=models.FileField(
                upload_to=apps.applications.models.events.application_attachment_path,
                validators=[
                    core.upload_security.FileUploadValidator(
                        allowed_extensions={".docx", ".jpeg", ".jpg", ".pdf", ".png", ".webp", ".zip"}, max_size_mb=10
                    )
                ],
            ),
        ),
    ]
