# Generated by Django 5.2.17 on 2026-09-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_alter_applicationattachment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("submitted", "Göndərildi"),
                    ("seen", "Baxışa götürüldü"),
                    ("comment", "Qeyd"),
                    ("assigned", "Məsul şəxsə təyin edildi"),
                    ("info_requested", "Əlavə məlumat istənildi"),
                    ("info_provided", "Əlavə məlumat verildi"),
                    ("forwarded", "Başqa şöbəyə yönləndirildi"),
                    ("returned", "Düzəliş üçün qaytarıldı"),
                    ("resubmitted", "Düzəlişdən sonra yenidən göndərildi"),
                    ("resolved", "Həll olundu"),
                    ("reopened", "Cavabdan razı qalmadı — yenidən baxışa göndərdi"),
                    ("rejected", "Rədd edildi"),
                    ("closed", "Bağlandı"),
                    ("cancelled", "Ləğv edildi"),
                ],
                max_length=20,
            ),
        ),
    ]
