# Generated by Django 5.2.12 on 2026-03-24 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("homework", "homework"),
                            ("quiz", "quiz"),
                            ("lab", "lab"),
                            ("midterm", "midterm"),
                            ("final", "final"),
                            ("project", "project"),
                        ],
                        default="homework",
                        max_length=20,
                        verbose_name="assignment_type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("instructions", models.TextField(blank=True, verbose_name="instructions")),
                (
                    "max_score",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=6, verbose_name="max_score"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, default=1.0, help_text="weight_ratio", max_digits=5, verbose_name="weight"
                    ),
                ),
                ("start_date", models.DateTimeField(help_text="start_date_for_submission", verbose_name="start_date")),
                ("due_date", models.DateTimeField(blank=True, null=True, verbose_name="due_date")),
                ("allow_late", models.BooleanField(default=False, verbose_name="allow_late_submission")),
                (
                    "late_penalty_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="late_penalty_description",
                        max_digits=5,
                        verbose_name="late_penalty_per_day",
                    ),
                ),
                ("max_attempts", models.PositiveIntegerField(default=1, verbose_name="max_attempts")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("published", "published"),
                            ("active", "active"),
                            ("inactive", "inactive"),
                            ("archived", "archived"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="student_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="students",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created_by",
                    ),
                ),
            ],
            options={
                "verbose_name": "verbose_name",
                "verbose_name_plural": "verbose_name_plural",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("deadline", "deadline"),
                            ("submission", "submission"),
                            ("grade", "grade"),
                            ("system", "system"),
                        ],
                        default="system",
                        max_length=20,
                        verbose_name="notification_type",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="is_read")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("link", models.URLField(blank=True, null=True, verbose_name="link")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "verbose_name",
                "verbose_name_plural": "verbose_name_plural",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "is_read"], name="assignments_user_id_52bdf7_idx"),
                    models.Index(fields=["user", "-created_at"], name="assignments_user_id_72f361_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempt_number", models.PositiveIntegerField(default=1, verbose_name="attempt_number")),
                ("content", models.TextField(blank=True, verbose_name="content")),
                (
                    "files",
                    models.JSONField(
                        blank=True, default=list, help_text="files_json_format", verbose_name="uploaded_files"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True, verbose_name="submitted_at")),
                ("is_late", models.BooleanField(default=False, verbose_name="is_late")),
                ("late_days", models.IntegerField(default=0, verbose_name="late_days")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "submitted"),
                            ("grading", "grading"),
                            ("graded", "graded"),
                            ("returned", "returned"),
                        ],
                        default="submitted",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "grade",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="grade"),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="feedback")),
                ("graded_at", models.DateTimeField(blank=True, null=True, verbose_name="graded_at")),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="assignments.assignment",
                        verbose_name="assignment",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="graded_by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="student",
                    ),
                ),
            ],
            options={
                "verbose_name": "verbose_name",
                "verbose_name_plural": "verbose_name_plural",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(fields=["assignment", "user"], name="assignments_assignm_fdd7af_idx"),
                    models.Index(fields=["status"], name="assignments_status_d82c9c_idx"),
                ],
            },
        ),
    ]
