# Generated by Django 5.2.8 on 2026-02-07 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Başlıq")),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="Tələbələr bu tarixdən sonra cavab verə bilər",
                        verbose_name="Başlanğıc tarixi",
                    ),
                ),
                ("deadline", models.DateTimeField(verbose_name="Son tarix")),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Maksimum cəhd"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("inactive", "Deaktiv"),
                            ("archived", "Arxivləndi"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="student_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tələbələr",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sərbəst İş",
                "verbose_name_plural": "Sərbəst İşlər",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Cavab")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="assignments/submissions/",
                        verbose_name="Fayl",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("graded", "Qiymətləndirilib"),
                            ("rejected", "Rədd edilib"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "grade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Qiymət",
                    ),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="Rəy")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="assignments.assignment",
                        verbose_name="Tapşırıq",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Qiymətləndirən",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tələbə",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cavab",
                "verbose_name_plural": "Cavablar",
                "ordering": ["-submitted_at"],
                "unique_together": {("assignment", "student", "submitted_at")},
            },
        ),
    ]
