# Generated by Django 5.2.8 on 2026-02-13 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="deadline",
        ),
        migrations.AddField(
            model_name="assignment",
            name="allow_late",
            field=models.BooleanField(
                default=False, verbose_name="Gecikmiş Təslimatı İcazə Ver"
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Yaradan",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Son Tarix"),
        ),
        migrations.AddField(
            model_name="assignment",
            name="instructions",
            field=models.TextField(blank=True, verbose_name="Təlimatlar"),
        ),
        migrations.AddField(
            model_name="assignment",
            name="late_penalty_per_day",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Hər gün üçün çıxılacaq bal faizi (məs: 10.00 = 10%)",
                max_digits=5,
                verbose_name="Gecikmiş Cərimə (gün başına)",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="max_score",
            field=models.DecimalField(
                decimal_places=2,
                default=100.0,
                max_digits=6,
                verbose_name="Maksimum Bal",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="type",
            field=models.CharField(
                choices=[
                    ("homework", "Ev Tapşırığı"),
                    ("quiz", "Kviz"),
                    ("lab", "Laboratoriya"),
                    ("midterm", "Midterm İmtahan"),
                    ("final", "Final İmtahan"),
                    ("project", "Layihə"),
                ],
                default="homework",
                max_length=20,
                verbose_name="Tapşırıq Tipi",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Ümumi qiymətdə çəkisi (məs: 0.1 = 10%)",
                max_digits=5,
                verbose_name="Çəki/Əhəmiyyət",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="max_attempts",
            field=models.PositiveIntegerField(default=1, verbose_name="Maksimum cəhd"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Qaralama"),
                    ("published", "Yayımlandı"),
                    ("archived", "Arxivləndi"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Başlıq")),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("deadline", "Son Tarix Xatırlatması"),
                            ("submission", "Yeni Təslimat"),
                            ("grade", "Qiymət Verildi"),
                            ("system", "Sistem Bildirişi"),
                        ],
                        default="system",
                        max_length=20,
                        verbose_name="Bildiriş Tipi",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Oxunub?")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                ("link", models.URLField(blank=True, null=True, verbose_name="Link")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildiriş",
                "verbose_name_plural": "Bildirişlər",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(default=1, verbose_name="Cəhd Nömrəsi"),
                ),
                ("content", models.TextField(blank=True, verbose_name="Cavab Mətni")),
                (
                    "files",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON siyahısı: [{name, path, size}]",
                        verbose_name="Yüklənmiş Fayllar",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Təslim Tarixi"
                    ),
                ),
                (
                    "is_late",
                    models.BooleanField(default=False, verbose_name="Gecikib?"),
                ),
                (
                    "late_days",
                    models.IntegerField(default=0, verbose_name="Gecikən Gün Sayı"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Təslim Edilib"),
                            ("grading", "Qiymətləndiriliir"),
                            ("graded", "Qiymətləndirilib"),
                            ("returned", "Qaytarılıb"),
                        ],
                        default="submitted",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "grade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Qiymət",
                    ),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="Rəy")),
                (
                    "graded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Qiymətləndirmə Tarixi"
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="assignments.assignment",
                        verbose_name="Tapşırıq",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Qiymətləndirən",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tələbə",
                    ),
                ),
            ],
            options={
                "verbose_name": "Təslimat",
                "verbose_name_plural": "Təslimatlar",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.DeleteModel(
            name="AssignmentSubmission",
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="assignments_user_id_52bdf7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "-created_at"], name="assignments_user_id_72f361_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["assignment", "user"], name="assignments_assignm_fdd7af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["status"], name="assignments_status_d82c9c_idx"),
        ),
    ]
