# Generated by Django 5.2.8 on 2026-03-01 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_remove_assignment_deadline_assignment_allow_late_and_more"),
        ("courses", "0002_course_grading_type_course_organization_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "verbose_name",
                "verbose_name_plural": "verbose_name_plural",
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "verbose_name",
                "verbose_name_plural": "verbose_name_plural",
            },
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={
                "ordering": ["-submitted_at"],
                "verbose_name": "verbose_name",
                "verbose_name_plural": "verbose_name_plural",
            },
        ),
        migrations.AlterField(
            model_name="assignment",
            name="allow_late",
            field=models.BooleanField(default=False, verbose_name="allow_late_submission"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="assigned_students",
            field=models.ManyToManyField(
                blank=True, related_name="student_assignments", to=settings.AUTH_USER_MODEL, verbose_name="students"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="courses.course",
                verbose_name="course",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created_by",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="due_date"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="instructions",
            field=models.TextField(blank=True, verbose_name="instructions"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="late_penalty_per_day",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="late_penalty_description",
                max_digits=5,
                verbose_name="late_penalty_per_day",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="max_attempts",
            field=models.PositiveIntegerField(default=1, verbose_name="max_attempts"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="max_score",
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6, verbose_name="max_score"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="start_date",
            field=models.DateTimeField(help_text="start_date_for_submission", verbose_name="start_date"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("published", "published"),
                    ("active", "active"),
                    ("inactive", "inactive"),
                    ("archived", "archived"),
                ],
                default="draft",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="title",
            field=models.CharField(max_length=255, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="type",
            field=models.CharField(
                choices=[
                    ("homework", "homework"),
                    ("quiz", "quiz"),
                    ("lab", "lab"),
                    ("midterm", "midterm"),
                    ("final", "final"),
                    ("project", "project"),
                ],
                default="homework",
                max_length=20,
                verbose_name="assignment_type",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, default=1.0, help_text="weight_ratio", max_digits=5, verbose_name="weight"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="is_read"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="link"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(verbose_name="message"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=255, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("deadline", "deadline"),
                    ("submission", "submission"),
                    ("grade", "grade"),
                    ("system", "system"),
                ],
                default="system",
                max_length=20,
                verbose_name="notification_type",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="assignments.assignment",
                verbose_name="assignment",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="attempt_number",
            field=models.PositiveIntegerField(default=1, verbose_name="attempt_number"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="content",
            field=models.TextField(blank=True, verbose_name="content"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="feedback",
            field=models.TextField(blank=True, verbose_name="feedback"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="files",
            field=models.JSONField(
                blank=True, default=list, help_text="files_json_format", verbose_name="uploaded_files"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="grade",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="grade"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="graded_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="graded_at"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="graded_by",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="is_late",
            field=models.BooleanField(default=False, verbose_name="is_late"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="late_days",
            field=models.IntegerField(default=0, verbose_name="late_days"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "submitted"),
                    ("grading", "grading"),
                    ("graded", "graded"),
                    ("returned", "returned"),
                ],
                default="submitted",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="submitted_at"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="student",
            ),
        ),
    ]
