# Generated by Django 5.2.8 on 2026-03-04 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("organizations", "0006_alter_academicperiod_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["resource_type", "resource_id"], name="audit_audit_resourc_2a3aef_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["request_id"], name="audit_audit_request_06fe30_idx"),
        ),
    ]
