# Generated by Django 5.2.15 on 2026-06-15 23:07

import apps.trial_exams.models
import core.upload_security
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialExamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject_name', models.CharField(max_length=150, verbose_name='Fənnin adı')),
                ('note', models.TextField(blank=True, max_length=2000, verbose_name='Qeyd')),
                ('questions_file', models.FileField(upload_to=apps.trial_exams.models.trial_questions_upload_path, validators=[core.upload_security.FileUploadValidator(allowed_extensions={'.pdf'})], verbose_name='Suallar (PDF)')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Orijinal fayl adı')),
                ('status', models.CharField(choices=[('pending', 'Gözləyir'), ('processing', 'Hazırlanır'), ('added', 'Sistemə əlavə olundu'), ('rejected', 'Rədd edildi')], db_index=True, default='pending', max_length=16, verbose_name='Status')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP ünvan')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('is_handled', models.BooleanField(default=False, verbose_name='Cavablandırılıb')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Göndərilmə tarixi')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cavab tarixi')),
                ('reply_body', models.TextField(blank=True, max_length=10000, verbose_name='Cavab mətni')),
                ('reply_from', models.CharField(blank=True, choices=[('info', 'info@emsarena.com'), ('support', 'support@emsarena.com')], max_length=16, verbose_name='Hansı maildən')),
                ('reply_delivery_status', models.CharField(blank=True, choices=[('pending', 'Göndərilir'), ('sent', 'Göndərildi'), ('failed', 'Göndərilmədi'), ('recorded', 'Qeyd edildi')], max_length=16, verbose_name='Cavab email statusu')),
                ('reply_delivery_error', models.CharField(blank=True, max_length=500, verbose_name='Cavab email xətası')),
                ('reply_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Cavab göndərilmə tarixi')),
                ('reply_sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_exam_replies', to=settings.AUTH_USER_MODEL, verbose_name='Cavab verən admin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_exam_requests', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Sınaq imtahanı sorğusu',
                'verbose_name_plural': 'Sınaq imtahanı sorğuları',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at'], name='trial_exams_created_6f7f34_idx'), models.Index(fields=['status', '-created_at'], name='trial_exams_status_0806d1_idx'), models.Index(fields=['is_handled', '-created_at'], name='trial_exams_is_hand_263044_idx')],
            },
        ),
    ]
