# Generated by Django 5.2.12 on 2026-03-24 09:11

import apps.exams.domain.access_policy
import apps.exams.domain.grading
import apps.exams.models
import apps.exams.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text_answer", models.TextField(blank=True, verbose_name="text_answer")),
                ("is_correct", models.BooleanField(default=False, verbose_name="is_correct")),
                (
                    "teacher_score",
                    models.PositiveIntegerField(
                        blank=True, help_text="teacher_score", null=True, verbose_name="teacher_score"
                    ),
                ),
                ("teacher_feedback", models.TextField(blank=True, verbose_name="teacher_feedback")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("has_paint", models.BooleanField(default=False)),
                ("paint_image", models.ImageField(blank=True, null=True, upload_to="exam_paints/%Y/%m/")),
                ("paint_updated_at", models.DateTimeField(blank=True, null=True)),
                ("paint_data_url", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
            },
            bases=(apps.exams.domain.grading.AnswerGradingMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("test", "test"), ("written", "written")],
                        default="test",
                        max_length=20,
                        verbose_name="exam_type",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        blank=True, help_text="start_datetime", null=True, verbose_name="start_datetime"
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(blank=True, help_text="end_datetime", null=True, verbose_name="end_datetime"),
                ),
                ("is_active", models.BooleanField(default=False, help_text="is_active", verbose_name="is_active")),
                (
                    "total_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="total_duration_minutes", null=True, verbose_name="total_duration_minutes"
                    ),
                ),
                (
                    "default_question_time_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="default_question_time_seconds",
                        null=True,
                        verbose_name="default_question_time_seconds",
                    ),
                ),
                (
                    "max_attempts_per_user",
                    models.PositiveIntegerField(
                        blank=True, help_text="max_attempts_per_user", null=True, verbose_name="max_attempts_per_user"
                    ),
                ),
                (
                    "random_question_count",
                    models.PositiveIntegerField(
                        default=10, help_text="random_question_count", verbose_name="random_question_count"
                    ),
                ),
                ("default_question_points", models.PositiveIntegerField(default=1)),
                (
                    "exam_type_extended",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("quiz", "quiz"),
                            ("midterm", "midterm"),
                            ("final", "final"),
                            ("placement", "placement"),
                            ("practice", "practice"),
                        ],
                        help_text="exam_type_extended",
                        max_length=20,
                        null=True,
                        verbose_name="exam_type_extended",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("online", "online"), ("offline", "offline"), ("hybrid", "hybrid")],
                        default="online",
                        max_length=20,
                        verbose_name="mode",
                    ),
                ),
                (
                    "proctoring_level",
                    models.CharField(
                        choices=[("none", "none"), ("basic", "basic"), ("strict", "strict")],
                        default="none",
                        max_length=20,
                        verbose_name="proctoring_level",
                    ),
                ),
                ("settings", models.JSONField(blank=True, default=dict, help_text="settings", verbose_name="settings")),
                ("is_public", models.BooleanField(default=True, help_text="is_public", verbose_name="is_public")),
                (
                    "access_code",
                    models.CharField(blank=True, help_text="access_code", max_length=6, verbose_name="access_code"),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enable_paint",
                    models.BooleanField(default=False, help_text="enable_paint", verbose_name="enable_paint"),
                ),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="allowed_users",
                        related_name="allowed_exams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="allowed_users",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exams",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="organization",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["-created_at"],
            },
            bases=(apps.exams.domain.access_policy.ExamAccessPolicyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ExamAnswerFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    models.FileField(
                        upload_to="exam_uploads/",
                        validators=[
                            apps.exams.validators.validate_file_extension,
                            apps.exams.validators.validate_file_size,
                            apps.exams.validators.validate_zip_contents,
                        ],
                        verbose_name="file",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="uploaded_at")),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="exams.examanswer",
                        verbose_name="answer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("checked_by_teacher", models.BooleanField(default=False, verbose_name="checked_by_teacher")),
                ("teacher_checked_at", models.DateTimeField(blank=True, null=True, verbose_name="teacher_checked_at")),
                (
                    "attempt_number",
                    models.PositiveIntegerField(default=1, help_text="attempt_number", verbose_name="attempt_number"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("in_progress", "in_progress"),
                            ("submitted", "submitted"),
                            ("expired", "expired"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="duration_seconds"),
                ),
                ("correct_count", models.PositiveIntegerField(default=0)),
                ("wrong_count", models.PositiveIntegerField(default=0)),
                (
                    "teacher_score",
                    models.PositiveIntegerField(
                        blank=True, help_text="teacher_score", null=True, verbose_name="teacher_score"
                    ),
                ),
                ("teacher_feedback", models.TextField(blank=True, verbose_name="teacher_feedback")),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="exams.exam"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["-started_at"],
            },
            bases=(apps.exams.domain.grading.AttemptGradingMixin, models.Model),
        ),
        migrations.AddField(
            model_name="examanswer",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="exams.examattempt"
            ),
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("points", models.PositiveIntegerField(default=1)),
                ("fingerprint", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "easy"), ("medium", "medium"), ("hard", "hard")],
                        default="medium",
                        max_length=20,
                        verbose_name="difficulty",
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list, help_text="tags", verbose_name="tags")),
                ("explanation", models.TextField(blank=True, help_text="explanation", verbose_name="explanation")),
                (
                    "usage_count",
                    models.PositiveIntegerField(default=0, help_text="usage_count", verbose_name="usage_count"),
                ),
                ("text", models.TextField(verbose_name="text")),
                ("correct_answer", models.TextField(blank=True, verbose_name="correct_answer")),
                ("order", models.PositiveIntegerField(default=1, verbose_name="order")),
                (
                    "answer_mode",
                    models.CharField(
                        choices=[("single", "single"), ("multiple", "multiple")],
                        default="single",
                        help_text="answer_mode",
                        max_length=20,
                        verbose_name="answer_mode",
                    ),
                ),
                (
                    "time_limit_seconds",
                    models.PositiveIntegerField(
                        blank=True, help_text="time_limit_seconds", null=True, verbose_name="time_limit_seconds"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=apps.exams.models.question_media_path, verbose_name="image"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.exams.models.question_media_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(allowed_extensions=["mp4", "webm", "mov"]),
                            apps.exams.models.validate_video_size,
                        ],
                        verbose_name="video",
                    ),
                ),
                ("enable_paint", models.BooleanField(default=False, help_text="enable_paint")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="is_active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.exam",
                        verbose_name="exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="examanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="exams.examquestion"
            ),
        ),
        migrations.CreateModel(
            name="ExamQuestionOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("E", "E")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="text")),
                ("is_correct", models.BooleanField(default=False, verbose_name="is_correct")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="exams.examquestion",
                        verbose_name="question",
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
            },
        ),
        migrations.AddField(
            model_name="examanswer",
            name="selected_options",
            field=models.ManyToManyField(
                blank=True,
                related_name="selected_in_answers",
                to="exams.examquestionoption",
                verbose_name="selected_options",
            ),
        ),
        migrations.CreateModel(
            name="ProctoringLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("tab_switch", "tab_switch"),
                            ("copy_paste", "copy_paste"),
                            ("right_click", "right_click"),
                            ("fullscreen_exit", "fullscreen_exit"),
                            ("focus_loss", "focus_loss"),
                            ("browser_console", "browser_console"),
                            ("screenshot_attempt", "screenshot_attempt"),
                            ("multiple_windows", "multiple_windows"),
                            ("suspicious_activity", "suspicious_activity"),
                            ("network_disconnect", "network_disconnect"),
                            ("other", "other"),
                        ],
                        max_length=50,
                        verbose_name="event_type",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="timestamp")),
                ("details", models.JSONField(blank=True, default=dict, help_text="details", verbose_name="details")),
                (
                    "exam_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proctoring_logs",
                        to="exams.examattempt",
                        verbose_name="exam_attempt",
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("subject", models.CharField(blank=True, help_text="subject", max_length=100, verbose_name="subject")),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("university", "university"),
                            ("school", "school"),
                            ("course_center", "course_center"),
                            ("individual", "individual"),
                        ],
                        default="individual",
                        max_length=50,
                        verbose_name="organization_type",
                    ),
                ),
                ("is_shared", models.BooleanField(default=False, help_text="is_shared", verbose_name="is_shared")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="is_active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated_at")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_banks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created_by",
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="examquestion",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                help_text="bank",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_questions",
                to="exams.questionbank",
                verbose_name="bank",
            ),
        ),
        migrations.CreateModel(
            name="QuestionBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("order", models.PositiveIntegerField(default=1, verbose_name="order")),
                (
                    "time_limit_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="time_limit_minutes", null=True, verbose_name="time_limit_minutes"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_blocks",
                        to="exams.exam",
                        verbose_name="exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="examquestion",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="exams.questionblock",
                verbose_name="block",
            ),
        ),
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_groups",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="student_groups_as_student",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="students",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="teacher",
                    ),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="student_groups_as_teacher",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="teachers",
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="allowed_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="allowed_groups",
                related_name="exams",
                to="exams.studentgroup",
                verbose_name="allowed_groups",
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(fields=["user", "exam", "status"], name="exams_exama_user_id_6ce609_idx"),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(fields=["user", "exam", "-started_at"], name="exams_exama_user_id_bf4f2e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="examanswer",
            unique_together={("attempt", "question")},
        ),
        migrations.AddIndex(
            model_name="proctoringlog",
            index=models.Index(fields=["exam_attempt", "-timestamp"], name="exams_proct_exam_at_76f1af_idx"),
        ),
        migrations.AddIndex(
            model_name="proctoringlog",
            index=models.Index(fields=["event_type"], name="exams_proct_event_t_d8a785_idx"),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(fields=["created_by", "-created_at"], name="exams_quest_created_b2b8da_idx"),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(fields=["is_active", "is_shared"], name="exams_quest_is_acti_1cb61b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="studentgroup",
            unique_together={("organization", "teacher", "name")},
        ),
    ]
