# Generated by Django 5.2.8 on 2026-02-13 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="exam_type_extended",
            field=models.CharField(
                blank=True,
                choices=[
                    ("quiz", "Kviz"),
                    ("midterm", "Midterm İmtahan"),
                    ("final", "Final İmtahan"),
                    ("placement", "Yerləşdirmə İmtahanı"),
                    ("practice", "Məşq İmtahanı"),
                ],
                help_text="Əlavə imtahan tipləri",
                max_length=20,
                null=True,
                verbose_name="İmtahan tipi (genişləndirilmiş)",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="mode",
            field=models.CharField(
                choices=[
                    ("online", "Onlayn"),
                    ("offline", "Oflayn"),
                    ("hybrid", "Hibrid"),
                ],
                default="online",
                max_length=20,
                verbose_name="İmtahan rejimi",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="organization_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Gələcəkdə organizations.Organization FK olacaq",
                null=True,
                verbose_name="Təşkilat ID",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="proctoring_level",
            field=models.CharField(
                choices=[
                    ("none", "Nəzarət Yoxdur"),
                    ("basic", "Əsas Nəzarət"),
                    ("strict", "Sərt Nəzarət"),
                ],
                default="none",
                max_length=20,
                verbose_name="Nəzarət səviyyəsi",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON formatında əlavə tənzimləmələr",
                verbose_name="Əlavə Parametrlər",
            ),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Asan"), ("medium", "Orta"), ("hard", "Çətin")],
                default="medium",
                max_length=20,
                verbose_name="Çətinlik Səviyyəsi",
            ),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="explanation",
            field=models.TextField(
                blank=True,
                help_text="Sualın həlli və ya izahatı",
                verbose_name="İzahat",
            ),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON siyahısı: ['algebra', 'equations', ...]",
                verbose_name="Etiketlər",
            ),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="usage_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Bu sual neçə dəfə istifadə olunub",
                verbose_name="İstifadə Sayı",
            ),
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Sual Bankı Adı"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Məs: Riyaziyyat, Fizika, Proqramlaşdırma",
                        max_length=100,
                        verbose_name="Fənn/Mövzu",
                    ),
                ),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("university", "Universitet"),
                            ("school", "Məktəb"),
                            ("course_center", "Kurs Mərkəzi"),
                            ("individual", "Fərdi"),
                        ],
                        default="individual",
                        max_length=50,
                        verbose_name="Təşkilat Tipi",
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        help_text="Digər istifadəçilər istifadə edə bilər",
                        verbose_name="Paylaşılıb?",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Aktivdir?"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_banks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sual Bankı",
                "verbose_name_plural": "Sual Bankları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="examquestion",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                help_text="Bu sual hansı sual bankından götürülüb",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_questions",
                to="exams.questionbank",
                verbose_name="Sual Bankı",
            ),
        ),
        migrations.CreateModel(
            name="ProctoringLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("tab_switch", "Tab Dəyişməsi"),
                            ("copy_paste", "Kopyala-Yapışdır"),
                            ("right_click", "Sağ Klik"),
                            ("fullscreen_exit", "Tam Ekrandan Çıxış"),
                            ("focus_loss", "Fokus İtkisi"),
                            ("browser_console", "Developer Console"),
                            ("screenshot_attempt", "Ekran Görüntüsü Cəhdi"),
                            ("multiple_windows", "Çoxlu Pəncərə"),
                            ("suspicious_activity", "Şübhəli Fəaliyyət"),
                            ("network_disconnect", "Şəbəkə Kəsilməsi"),
                            ("other", "Digər"),
                        ],
                        max_length=50,
                        verbose_name="Hadisə Tipi",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vaxt"),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON: {ip, browser, location, ...}",
                        verbose_name="Təfərrüatlar",
                    ),
                ),
                (
                    "exam_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proctoring_logs",
                        to="exams.examattempt",
                        verbose_name="İmtahan Cəhdi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proktoring Qeydi",
                "verbose_name_plural": "Proktoring Qeydləri",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["exam_attempt", "-timestamp"],
                        name="exams_proct_exam_at_76f1af_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="exams_proct_event_t_d8a785_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="exams_quest_created_b2b8da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["is_active", "is_shared"], name="exams_quest_is_acti_1cb61b_idx"
            ),
        ),
    ]
