# Generated by Django 5.2.8 on 2026-02-19

import django.db.models.deletion
from django.db import migrations, models


def backfill_student_group_organization(apps, schema_editor):
    StudentGroup = apps.get_model("exams", "StudentGroup")
    UserProfile = apps.get_model("accounts", "UserProfile")

    profile_map = {profile.user_id: profile.organization_id for profile in UserProfile.objects.all()}

    for group in StudentGroup.objects.all():
        organization_id = profile_map.get(group.teacher_id)
        if organization_id:
            group.organization_id = organization_id
            group.save(update_fields=["organization"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_student_references_and_hr_role"),
        ("organizations", "0004_country_institution"),
        ("exams", "0002_exam_exam_type_extended_exam_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroup",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_groups",
                to="organizations.organization",
                verbose_name="Təşkilat",
            ),
        ),
        migrations.RunPython(backfill_student_group_organization, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="studentgroup",
            unique_together={("organization", "teacher", "name")},
        ),
    ]
