# Generated by Django 5.2.13 on 2026-04-12 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_questionblock_enable_paint_examquestion_disable_paint"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="AI funksiyalarını bütün platforma üzrə aktiv/deaktiv et."
                    ),
                ),
                (
                    "rate_limit",
                    models.CharField(
                        default="100/1h",
                        help_text='Hər istifadəçi üçün AI sorğu limiti.  Format: "say/müddət" (məs. "100/1h").',
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Format: "100/1h", "50/30m", "200/1d"', regex="^\\d+/\\d*[smhd]$"
                            )
                        ],
                    ),
                ),
                (
                    "summary_model",
                    models.CharField(
                        choices=[
                            ("gemini-2.5-flash", "Gemini 2.5 Flash (orta keyfiyyət, ucuz)"),
                            ("gemini-2.5-flash-lite", "Gemini 2.5 Flash Lite (sürətli, ən ucuz)"),
                            ("gemini-2.5-pro", "Gemini 2.5 Pro (yüksək keyfiyyət, bahalı)"),
                        ],
                        default="gemini-2.5-flash",
                        help_text="Statistika xülasəsi üçün istifadə olunan model.",
                        max_length=50,
                    ),
                ),
                (
                    "grading_model",
                    models.CharField(
                        choices=[
                            ("gemini-2.5-flash", "Gemini 2.5 Flash (orta keyfiyyət, ucuz)"),
                            ("gemini-2.5-flash-lite", "Gemini 2.5 Flash Lite (sürətli, ən ucuz)"),
                            ("gemini-2.5-pro", "Gemini 2.5 Pro (yüksək keyfiyyət, bahalı)"),
                        ],
                        default="gemini-2.5-flash-lite",
                        help_text="Yazılı cavab qiymətləndirmə üçün istifadə olunan model.",
                        max_length=50,
                    ),
                ),
                (
                    "monthly_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Aylıq AI büdcəsi ($). Yalnız məlumat məqsədlidir.",
                        max_digits=6,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Configuration",
                "verbose_name_plural": "AI Configuration",
            },
        ),
    ]
