# Generated by Django 5.2.8 on 2026-02-19

from django.conf import settings
from django.db import migrations, models


def backfill_group_teachers(apps, schema_editor):
    StudentGroup = apps.get_model("exams", "StudentGroup")
    for group in StudentGroup.objects.exclude(teacher_id__isnull=True):
        group.teachers.add(group.teacher_id)


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_studentgroup_organization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroup",
            name="teachers",
            field=models.ManyToManyField(
                blank=True,
                related_name="student_groups_as_teacher",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Təyin olunmuş müəllimlər",
            ),
        ),
        migrations.RunPython(backfill_group_teachers, migrations.RunPython.noop),
    ]
