# Generated by Django 5.2.13 on 2026-04-12 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_aiconfiguration'),
        ('organizations', '0004_expand_rls_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='supervision_extra_chances',
            field=models.PositiveIntegerField(default=0, verbose_name='supervision_extra_chances'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='supervision_status',
            field=models.CharField(choices=[('active', 'active'), ('warned', 'warned'), ('locked', 'locked'), ('removed', 'removed'), ('resumed', 'resumed')], default='active', max_length=20, verbose_name='supervision_status'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='supervision_violation_count',
            field=models.PositiveIntegerField(default=0, verbose_name='supervision_violation_count'),
        ),
        migrations.CreateModel(
            name='ExamSupervisionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='enabled', verbose_name='enabled')),
                ('template', models.CharField(choices=[('custom', 'custom'), ('light', 'light'), ('medium', 'medium'), ('strict', 'strict')], default='custom', max_length=20, verbose_name='template')),
                ('force_fullscreen', models.BooleanField(default=True, help_text='force_fullscreen', verbose_name='force_fullscreen')),
                ('grace_period_seconds', models.PositiveIntegerField(default=15, help_text='grace_period_seconds', verbose_name='grace_period_seconds')),
                ('max_fullscreen_violations', models.PositiveIntegerField(default=3, help_text='max_fullscreen_violations', verbose_name='max_fullscreen_violations')),
                ('detect_tab_switch', models.BooleanField(default=True, help_text='detect_tab_switch', verbose_name='detect_tab_switch')),
                ('block_copy_paste', models.BooleanField(default=True, help_text='block_copy_paste', verbose_name='block_copy_paste')),
                ('disable_right_click', models.BooleanField(default=True, help_text='disable_right_click', verbose_name='disable_right_click')),
                ('disable_text_selection', models.BooleanField(default=False, help_text='disable_text_selection', verbose_name='disable_text_selection')),
                ('restrict_keyboard_shortcuts', models.BooleanField(default=True, help_text='restrict_keyboard_shortcuts', verbose_name='restrict_keyboard_shortcuts')),
                ('violation_action', models.CharField(choices=[('auto_submit', 'auto_submit'), ('lock_exam', 'lock_exam'), ('remove_student', 'remove_student'), ('mark_suspicious', 'mark_suspicious')], default='lock_exam', help_text='violation_action', max_length=20, verbose_name='violation_action')),
                ('recovery_policy', models.CharField(choices=[('no_second_chance', 'no_second_chance'), ('one_extra_chance', 'one_extra_chance'), ('teacher_controlled', 'teacher_controlled')], default='teacher_controlled', help_text='recovery_policy', max_length=20, verbose_name='recovery_policy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_config', to='exams.exam', verbose_name='exam')),
            ],
            options={
                'verbose_name': 'singular',
                'verbose_name_plural': 'plural',
            },
        ),
        migrations.CreateModel(
            name='SupervisionIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('fullscreen_exited', 'fullscreen_exited'), ('fullscreen_restored', 'fullscreen_restored'), ('tab_switched', 'tab_switched'), ('window_blurred', 'window_blurred'), ('window_focused', 'window_focused'), ('copy_attempt', 'copy_attempt'), ('paste_attempt', 'paste_attempt'), ('cut_attempt', 'cut_attempt'), ('right_click_attempt', 'right_click_attempt'), ('keyboard_shortcut', 'keyboard_shortcut'), ('text_select_attempt', 'text_select_attempt'), ('suspicious_repeated', 'suspicious_repeated'), ('grace_period_expired', 'grace_period_expired'), ('auto_locked', 'auto_locked'), ('auto_submitted', 'auto_submitted'), ('teacher_resumed', 'teacher_resumed'), ('teacher_granted_chance', 'teacher_granted_chance'), ('exam_started_supervised', 'exam_started_supervised'), ('student_acknowledged', 'student_acknowledged')], max_length=30, verbose_name='event_type')),
                ('severity', models.CharField(choices=[('info', 'info'), ('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')], default='medium', max_length=10, verbose_name='severity')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='metadata', verbose_name='metadata')),
                ('violation_count_at_time', models.PositiveIntegerField(default=0, verbose_name='violation_count_at_time')),
                ('teacher_action', models.CharField(blank=True, default='', max_length=100, verbose_name='teacher_action')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_incidents', to='exams.examattempt', verbose_name='attempt')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_incidents', to='exams.exam', verbose_name='exam')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_incidents', to='organizations.organization', verbose_name='organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_incidents', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'verbose_name': 'singular',
                'verbose_name_plural': 'plural',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['attempt', '-timestamp'], name='exams_super_attempt_6c8795_idx'), models.Index(fields=['organization', '-timestamp'], name='exams_super_organiz_413f14_idx'), models.Index(fields=['exam', '-timestamp'], name='exams_super_exam_id_b3121a_idx'), models.Index(fields=['student', '-timestamp'], name='exams_super_student_34affa_idx'), models.Index(fields=['event_type'], name='exams_super_event_t_f8c193_idx'), models.Index(fields=['severity'], name='exams_super_severit_e94589_idx')],
            },
        ),
    ]
