# Generated by Django 5.2.8 on 2026-03-01 12:06

import apps.exams.models
import apps.exams.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_grading_type_course_organization_id_and_more"),
        ("exams", "0004_studentgroup_teachers"),
        ("organizations", "0006_alter_academicperiod_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exam",
            options={"ordering": ["-created_at"], "verbose_name": "singular", "verbose_name_plural": "plural"},
        ),
        migrations.AlterModelOptions(
            name="examanswer",
            options={"verbose_name": "singular", "verbose_name_plural": "plural"},
        ),
        migrations.AlterModelOptions(
            name="examattempt",
            options={"ordering": ["-started_at"], "verbose_name": "singular", "verbose_name_plural": "plural"},
        ),
        migrations.AlterModelOptions(
            name="examquestion",
            options={"ordering": ["order", "id"], "verbose_name": "singular", "verbose_name_plural": "plural"},
        ),
        migrations.AlterModelOptions(
            name="examquestionoption",
            options={"verbose_name": "singular", "verbose_name_plural": "plural"},
        ),
        migrations.AlterModelOptions(
            name="proctoringlog",
            options={"ordering": ["-timestamp"], "verbose_name": "singular", "verbose_name_plural": "plural"},
        ),
        migrations.AlterModelOptions(
            name="questionbank",
            options={"ordering": ["-created_at"], "verbose_name": "singular", "verbose_name_plural": "plural"},
        ),
        migrations.AlterModelOptions(
            name="questionblock",
            options={"ordering": ["order", "id"], "verbose_name": "singular", "verbose_name_plural": "plural"},
        ),
        migrations.AlterModelOptions(
            name="studentgroup",
            options={"ordering": ["name"], "verbose_name": "singular", "verbose_name_plural": "plural"},
        ),
        migrations.AlterField(
            model_name="exam",
            name="access_code",
            field=models.CharField(blank=True, help_text="access_code", max_length=6, verbose_name="access_code"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="allowed_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="allowed_groups",
                related_name="exams",
                to="exams.studentgroup",
                verbose_name="allowed_groups",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="allowed_users",
                related_name="allowed_exams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="allowed_users",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exams",
                to="courses.course",
                verbose_name="course",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="default_question_time_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="default_question_time_seconds",
                null=True,
                verbose_name="default_question_time_seconds",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="enable_paint",
            field=models.BooleanField(default=False, help_text="enable_paint", verbose_name="enable_paint"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="end_datetime",
            field=models.DateTimeField(blank=True, help_text="end_datetime", null=True, verbose_name="end_datetime"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="exam_type",
            field=models.CharField(
                choices=[("test", "test"), ("written", "written")],
                default="test",
                max_length=20,
                verbose_name="exam_type",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="exam_type_extended",
            field=models.CharField(
                blank=True,
                choices=[
                    ("quiz", "quiz"),
                    ("midterm", "midterm"),
                    ("final", "final"),
                    ("placement", "placement"),
                    ("practice", "practice"),
                ],
                help_text="exam_type_extended",
                max_length=20,
                null=True,
                verbose_name="exam_type_extended",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="is_active",
            field=models.BooleanField(default=False, help_text="is_active", verbose_name="is_active"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="is_public",
            field=models.BooleanField(default=True, help_text="is_public", verbose_name="is_public"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="max_attempts_per_user",
            field=models.PositiveIntegerField(
                blank=True, help_text="max_attempts_per_user", null=True, verbose_name="max_attempts_per_user"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="mode",
            field=models.CharField(
                choices=[("online", "online"), ("offline", "offline"), ("hybrid", "hybrid")],
                default="online",
                max_length=20,
                verbose_name="mode",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="organization_id",
            field=models.IntegerField(
                blank=True, db_index=True, help_text="organization_id", null=True, verbose_name="organization_id"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="proctoring_level",
            field=models.CharField(
                choices=[("none", "none"), ("basic", "basic"), ("strict", "strict")],
                default="none",
                max_length=20,
                verbose_name="proctoring_level",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="random_question_count",
            field=models.PositiveIntegerField(
                default=10, help_text="random_question_count", verbose_name="random_question_count"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="settings",
            field=models.JSONField(blank=True, default=dict, help_text="settings", verbose_name="settings"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="start_datetime",
            field=models.DateTimeField(
                blank=True, help_text="start_datetime", null=True, verbose_name="start_datetime"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="title",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="total_duration_minutes",
            field=models.PositiveIntegerField(
                blank=True, help_text="total_duration_minutes", null=True, verbose_name="total_duration_minutes"
            ),
        ),
        migrations.AlterField(
            model_name="examanswer",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="is_correct"),
        ),
        migrations.AlterField(
            model_name="examanswer",
            name="selected_options",
            field=models.ManyToManyField(
                blank=True,
                related_name="selected_in_answers",
                to="exams.examquestionoption",
                verbose_name="selected_options",
            ),
        ),
        migrations.AlterField(
            model_name="examanswer",
            name="teacher_feedback",
            field=models.TextField(blank=True, verbose_name="teacher_feedback"),
        ),
        migrations.AlterField(
            model_name="examanswer",
            name="teacher_score",
            field=models.PositiveIntegerField(
                blank=True, help_text="teacher_score", null=True, verbose_name="teacher_score"
            ),
        ),
        migrations.AlterField(
            model_name="examanswer",
            name="text_answer",
            field=models.TextField(blank=True, verbose_name="text_answer"),
        ),
        migrations.AlterField(
            model_name="examanswerfile",
            name="answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="exams.examanswer",
                verbose_name="answer",
            ),
        ),
        migrations.AlterField(
            model_name="examanswerfile",
            name="file",
            field=models.FileField(
                upload_to="exam_uploads/",
                validators=[
                    apps.exams.validators.validate_file_extension,
                    apps.exams.validators.validate_file_size,
                    apps.exams.validators.validate_zip_contents,
                ],
                verbose_name="file",
            ),
        ),
        migrations.AlterField(
            model_name="examanswerfile",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="uploaded_at"),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="attempt_number",
            field=models.PositiveIntegerField(default=1, help_text="attempt_number", verbose_name="attempt_number"),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="checked_by_teacher",
            field=models.BooleanField(default=False, verbose_name="checked_by_teacher"),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="duration_seconds",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="duration_seconds"),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("in_progress", "in_progress"),
                    ("submitted", "submitted"),
                    ("expired", "expired"),
                ],
                default="in_progress",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="teacher_checked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="teacher_checked_at"),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="teacher_feedback",
            field=models.TextField(blank=True, verbose_name="teacher_feedback"),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="teacher_score",
            field=models.PositiveIntegerField(
                blank=True, help_text="teacher_score", null=True, verbose_name="teacher_score"
            ),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="answer_mode",
            field=models.CharField(
                choices=[("single", "single"), ("multiple", "multiple")],
                default="single",
                help_text="answer_mode",
                max_length=20,
                verbose_name="answer_mode",
            ),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                help_text="bank",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_questions",
                to="exams.questionbank",
                verbose_name="bank",
            ),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="exams.questionblock",
                verbose_name="block",
            ),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="correct_answer",
            field=models.TextField(blank=True, verbose_name="correct_answer"),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "easy"), ("medium", "medium"), ("hard", "hard")],
                default="medium",
                max_length=20,
                verbose_name="difficulty",
            ),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="enable_paint",
            field=models.BooleanField(default=False, help_text="enable_paint"),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="exams.exam",
                verbose_name="exam",
            ),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="explanation",
            field=models.TextField(blank=True, help_text="explanation", verbose_name="explanation"),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.exams.models.question_media_path, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="order",
            field=models.PositiveIntegerField(default=1, verbose_name="order"),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="tags",
            field=models.JSONField(blank=True, default=list, help_text="tags", verbose_name="tags"),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="text",
            field=models.TextField(verbose_name="text"),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="time_limit_seconds",
            field=models.PositiveIntegerField(
                blank=True, help_text="time_limit_seconds", null=True, verbose_name="time_limit_seconds"
            ),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="usage_count",
            field=models.PositiveIntegerField(default=0, help_text="usage_count", verbose_name="usage_count"),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.exams.models.question_media_path,
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["mp4", "webm", "mov"]),
                    apps.exams.models.validate_video_size,
                ],
                verbose_name="video",
            ),
        ),
        migrations.AlterField(
            model_name="examquestionoption",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="is_correct"),
        ),
        migrations.AlterField(
            model_name="examquestionoption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="exams.examquestion",
                verbose_name="question",
            ),
        ),
        migrations.AlterField(
            model_name="examquestionoption",
            name="text",
            field=models.CharField(max_length=255, verbose_name="text"),
        ),
        migrations.AlterField(
            model_name="proctoringlog",
            name="details",
            field=models.JSONField(blank=True, default=dict, help_text="details", verbose_name="details"),
        ),
        migrations.AlterField(
            model_name="proctoringlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("tab_switch", "tab_switch"),
                    ("copy_paste", "copy_paste"),
                    ("right_click", "right_click"),
                    ("fullscreen_exit", "fullscreen_exit"),
                    ("focus_loss", "focus_loss"),
                    ("browser_console", "browser_console"),
                    ("screenshot_attempt", "screenshot_attempt"),
                    ("multiple_windows", "multiple_windows"),
                    ("suspicious_activity", "suspicious_activity"),
                    ("network_disconnect", "network_disconnect"),
                    ("other", "other"),
                ],
                max_length=50,
                verbose_name="event_type",
            ),
        ),
        migrations.AlterField(
            model_name="proctoringlog",
            name="exam_attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proctoring_logs",
                to="exams.examattempt",
                verbose_name="exam_attempt",
            ),
        ),
        migrations.AlterField(
            model_name="proctoringlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="timestamp"),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_banks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created_by",
            ),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="is_active"),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="is_shared",
            field=models.BooleanField(default=False, help_text="is_shared", verbose_name="is_shared"),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("university", "university"),
                    ("school", "school"),
                    ("course_center", "course_center"),
                    ("individual", "individual"),
                ],
                default="individual",
                max_length=50,
                verbose_name="organization_type",
            ),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="subject",
            field=models.CharField(blank=True, help_text="subject", max_length=100, verbose_name="subject"),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated_at"),
        ),
        migrations.AlterField(
            model_name="questionblock",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_blocks",
                to="exams.exam",
                verbose_name="exam",
            ),
        ),
        migrations.AlterField(
            model_name="questionblock",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="questionblock",
            name="order",
            field=models.PositiveIntegerField(default=1, verbose_name="order"),
        ),
        migrations.AlterField(
            model_name="questionblock",
            name="time_limit_minutes",
            field=models.PositiveIntegerField(
                blank=True, help_text="time_limit_minutes", null=True, verbose_name="time_limit_minutes"
            ),
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="name",
            field=models.CharField(max_length=50, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_groups",
                to="organizations.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="student_groups_as_student",
                to=settings.AUTH_USER_MODEL,
                verbose_name="students",
            ),
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="teacher",
            ),
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="teachers",
            field=models.ManyToManyField(
                blank=True,
                related_name="student_groups_as_teacher",
                to=settings.AUTH_USER_MODEL,
                verbose_name="teachers",
            ),
        ),
    ]
