# Generated by Django 5.2.13 on 2026-05-05 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_add_supervision_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="exam_type",
            field=models.CharField(
                choices=[("test", "test"), ("written", "written"), ("coding", "Practical Coding Exam")],
                default="test",
                max_length=20,
                verbose_name="exam_type",
            ),
        ),
        migrations.CreateModel(
            name="CodingExamQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("javascript", "JavaScript"),
                            ("python", "Python"),
                            ("cpp", "C++"),
                            ("java", "Java"),
                            ("html", "HTML/CSS/JS"),
                        ],
                        default="python",
                        max_length=30,
                        verbose_name="language",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("problem_statement", models.TextField(verbose_name="problem_statement")),
                ("input_description", models.TextField(blank=True, verbose_name="input_description")),
                ("output_description", models.TextField(blank=True, verbose_name="output_description")),
                ("example_input", models.TextField(blank=True, verbose_name="example_input")),
                ("example_output", models.TextField(blank=True, verbose_name="example_output")),
                ("time_limit_seconds", models.PositiveIntegerField(default=2, verbose_name="time_limit_seconds")),
                ("memory_limit_mb", models.PositiveIntegerField(default=128, verbose_name="memory_limit_mb")),
                ("max_score", models.PositiveIntegerField(default=100, verbose_name="max_score")),
                ("starter_code", models.TextField(blank=True, verbose_name="starter_code")),
                ("allow_file_creation", models.BooleanField(default=False, verbose_name="allow_file_creation")),
                ("allow_multiple_files", models.BooleanField(default=False, verbose_name="allow_multiple_files")),
                (
                    "enable_code_execution",
                    models.BooleanField(
                        default=False, help_text="enable_code_execution", verbose_name="enable_code_execution"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_details",
                        to="exams.examquestion",
                        verbose_name="question",
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["question__order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CodingSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "selected_language",
                    models.CharField(
                        choices=[
                            ("javascript", "JavaScript"),
                            ("python", "Python"),
                            ("cpp", "C++"),
                            ("java", "Java"),
                            ("html", "HTML/CSS/JS"),
                        ],
                        max_length=30,
                        verbose_name="selected_language",
                    ),
                ),
                ("submitted_code", models.TextField(blank=True, verbose_name="submitted_code")),
                ("files", models.JSONField(blank=True, default=list, verbose_name="files")),
                ("output", models.TextField(blank=True, verbose_name="output")),
                ("error_message", models.TextField(blank=True, verbose_name="error_message")),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("success", "success"),
                            ("runtime_error", "runtime_error"),
                            ("compile_error", "compile_error"),
                            ("timeout", "timeout"),
                            ("execution_disabled", "execution_disabled"),
                            ("sandbox_unavailable", "sandbox_unavailable"),
                            ("submitted", "submitted"),
                        ],
                        default="draft",
                        max_length=30,
                        verbose_name="execution_status",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="score"),
                ),
                ("test_results", models.JSONField(blank=True, default=list, verbose_name="test_results")),
                (
                    "execution_time_ms",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="execution_time_ms"),
                ),
                ("memory_usage_kb", models.PositiveIntegerField(blank=True, null=True, verbose_name="memory_usage_kb")),
                ("is_final", models.BooleanField(default=False, verbose_name="is_final")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_submissions",
                        to="exams.examattempt",
                        verbose_name="attempt",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_submissions",
                        to="exams.exam",
                        verbose_name="exam",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="exams.codingexamquestion",
                        verbose_name="question",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="student",
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="CodingFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=180, verbose_name="name")),
                ("content", models.TextField(blank=True, verbose_name="content")),
                ("language", models.CharField(blank=True, max_length=30, verbose_name="language")),
                ("is_main", models.BooleanField(default=False, verbose_name="is_main")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_files",
                        to="exams.codingsubmission",
                        verbose_name="submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["-is_main", "name"],
            },
        ),
        migrations.CreateModel(
            name="CodingTestCase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("input_data", models.TextField(blank=True, verbose_name="input_data")),
                ("expected_output", models.TextField(blank=True, verbose_name="expected_output")),
                (
                    "visibility",
                    models.CharField(
                        choices=[("visible", "visible"), ("hidden", "hidden")],
                        default="visible",
                        max_length=12,
                        verbose_name="visibility",
                    ),
                ),
                ("point_value", models.PositiveIntegerField(default=1, verbose_name="point_value")),
                ("order", models.PositiveIntegerField(default=1, verbose_name="order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coding_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="exams.codingexamquestion",
                        verbose_name="coding_question",
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="codingsubmission",
            index=models.Index(fields=["student", "exam", "-submitted_at"], name="exams_codin_student_2a03b5_idx"),
        ),
        migrations.AddIndex(
            model_name="codingsubmission",
            index=models.Index(fields=["attempt", "question", "is_final"], name="exams_codin_attempt_ba27be_idx"),
        ),
        migrations.AddIndex(
            model_name="codingsubmission",
            index=models.Index(fields=["execution_status"], name="exams_codin_executi_9bb611_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="codingfile",
            unique_together={("submission", "name")},
        ),
        migrations.AddIndex(
            model_name="codingtestcase",
            index=models.Index(
                fields=["coding_question", "visibility", "order"], name="exams_codin_coding__d6c308_idx"
            ),
        ),
    ]
