# Generated by Django 5.2.8 on 2026-03-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0008_exam_organization_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examquestion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
        ),
    ]
