# Generated by Django 5.2.14 on 2026-05-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_aiconfiguration_assistant_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='supervision_resumed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='supervision_resumed_at'),
        ),
        migrations.AddField(
            model_name='examsupervisionconfig',
            name='resume_window_seconds',
            field=models.PositiveIntegerField(default=600, help_text='resume_window_seconds', verbose_name='resume_window_seconds'),
        ),
        migrations.AlterField(
            model_name='supervisionincident',
            name='event_type',
            field=models.CharField(choices=[('fullscreen_exited', 'fullscreen_exited'), ('fullscreen_restored', 'fullscreen_restored'), ('tab_switched', 'tab_switched'), ('window_blurred', 'window_blurred'), ('window_focused', 'window_focused'), ('copy_attempt', 'copy_attempt'), ('paste_attempt', 'paste_attempt'), ('cut_attempt', 'cut_attempt'), ('right_click_attempt', 'right_click_attempt'), ('keyboard_shortcut', 'keyboard_shortcut'), ('text_select_attempt', 'text_select_attempt'), ('suspicious_repeated', 'suspicious_repeated'), ('grace_period_expired', 'grace_period_expired'), ('auto_locked', 'auto_locked'), ('auto_submitted', 'auto_submitted'), ('resume_window_expired', 'resume_window_expired'), ('teacher_resumed', 'teacher_resumed'), ('teacher_granted_chance', 'teacher_granted_chance'), ('exam_started_supervised', 'exam_started_supervised'), ('student_acknowledged', 'student_acknowledged')], max_length=30, verbose_name='event_type'),
        ),
    ]
