# Generated by Django 5.2.14 on 2026-05-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_examattempt_supervision_resumed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='supervision_locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='supervision_locked_at'),
        ),
    ]
