# Generated by Django 5.2.14 on 2026-06-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0018_questionbank_default_question_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionbank",
            name="default_question_type",
            field=models.CharField(
                choices=[("test", "test"), ("written", "written")],
                default="test",
                max_length=20,
                verbose_name="default_question_type",
            ),
        ),
    ]
