# Generated by Django 5.2.15 on 2026-07-02 19:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.exams.domain.import_jobs


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0023_option_image"),
        ("organizations", "0011_backfill_teacher_course_create"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TextExtractionJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_name", models.CharField(blank=True, default="", max_length=255)),
                ("file", models.FileField(upload_to=apps.exams.domain.import_jobs.extraction_job_upload_path)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("processing", "İcra olunur"),
                            ("success", "Hazır"),
                            ("failed", "Xəta"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_extraction_jobs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_extraction_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["user", "-created_at"], name="exams_extjob_user_created")],
            },
        ),
    ]
