# Generated by Django 5.2.15 on 2026-07-02 20:16

from django.db import migrations, models

import apps.exams.domain.import_jobs


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0024_textextractionjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="textextractionjob",
            name="kind",
            field=models.CharField(
                choices=[("extract", "Mətn çıxarma"), ("ai_generate", "AI sual generasiyası")],
                default="extract",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="textextractionjob",
            name="payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="textextractionjob",
            name="result_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="textextractionjob",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=apps.exams.domain.import_jobs.extraction_job_upload_path
            ),
        ),
    ]
