# Generated by Django 5.2.15 on 2026-07-05 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0026_textextractionjob_result_file_and_more"),
        ("organizations", "0014_academicperiod_exam_session_end_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="title", max_length=200, verbose_name="title")),
                (
                    "language",
                    models.CharField(
                        choices=[("az", "Azərbaycan dili"), ("en", "English"), ("ru", "Русский"), ("tr", "Türkçe")],
                        default="az",
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                ("raw_text", models.TextField(verbose_name="raw_text")),
                ("parsed_snapshot", models.JSONField(blank=True, default=list)),
                ("question_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "pending"), ("accepted", "accepted"), ("rejected", "rejected")],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("resubmission_count", models.PositiveIntegerField(default=0)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_note", models.TextField(blank=True, verbose_name="reviewer_note")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_submissions",
                        to="exams.questionbank",
                        verbose_name="accepted_bank",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_submissions",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_question_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reviewer",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["organization", "status", "-created_at"], name="qsub_org_status_idx"),
                    models.Index(fields=["teacher", "-created_at"], name="qsub_teacher_created_idx"),
                ],
            },
        ),
    ]
