# Generated by Django 5.2.15 on 2026-07-05 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0027_questionsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionsubmission",
            name="group_label",
            field=models.CharField(default="", max_length=200, verbose_name="group_label"),
        ),
        migrations.AddField(
            model_name="questionsubmission",
            name="student_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="question_submissions",
                to="exams.studentgroup",
                verbose_name="student_group",
            ),
        ),
        migrations.AddField(
            model_name="questionsubmission",
            name="subject",
            field=models.CharField(default="", max_length=200, verbose_name="subject"),
        ),
    ]
