# Generated by Django 5.2.15 on 2026-07-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0028_questionsubmission_group_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionsubmission",
            name="teacher_note",
            field=models.TextField(blank=True, default="", verbose_name="teacher_note"),
        ),
    ]
