# Generated by Django 5.2.15 on 2026-07-06 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0029_questionsubmission_teacher_note"),
        ("organizations", "0014_academicperiod_exam_session_end_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamRoom",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("code", models.CharField(help_text="code", max_length=32, verbose_name="code")),
                ("building", models.CharField(blank=True, max_length=120, verbose_name="building")),
                ("floor", models.CharField(blank=True, max_length=32, verbose_name="floor")),
                ("capacity", models.PositiveIntegerField(default=0, help_text="capacity", verbose_name="capacity")),
                ("computer_count", models.PositiveIntegerField(default=0, verbose_name="computer_count")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="is_active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exam_rooms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created_by",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_rooms",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExamRoomSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scheduled_start", models.DateTimeField(verbose_name="scheduled_start")),
                ("scheduled_end", models.DateTimeField(verbose_name="scheduled_end")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("prepared", "prepared"),
                            ("entry_open", "entry_open"),
                            ("active", "active"),
                            ("ended", "ended"),
                            ("cancelled", "cancelled"),
                        ],
                        default="prepared",
                        max_length=20,
                        verbose_name="state",
                    ),
                ),
                ("entry_opened_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="started_at")),
                ("start_connected_count", models.PositiveIntegerField(default=0)),
                ("ended_at", models.DateTimeField(blank=True, null=True, verbose_name="ended_at")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_room_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ended_room_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ended_by",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_sessions",
                        to="exams.exam",
                        verbose_name="exam",
                    ),
                ),
                (
                    "invigilator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invigilated_room_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="invigilator",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_room_sessions",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="exams.examroom",
                        verbose_name="room",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        help_text="staff",
                        related_name="staffed_room_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="staff",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_room_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="started_by",
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["-scheduled_start", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FinalExamTicket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("seat_number", models.PositiveIntegerField(blank=True, null=True, verbose_name="seat_number")),
                (
                    "language",
                    models.CharField(
                        blank=True, default="", help_text="language", max_length=10, verbose_name="language"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "assigned"),
                            ("waiting", "waiting"),
                            ("ready", "ready"),
                            ("active", "active"),
                            ("completed", "completed"),
                            ("removed", "removed"),
                            ("absent", "absent"),
                        ],
                        default="assigned",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("pin_hash", models.CharField(blank=True, default="", max_length=192)),
                ("pin_cipher", models.TextField(blank=True, default="")),
                ("pin_issued_at", models.DateTimeField(blank=True, null=True)),
                ("pin_expires_at", models.DateTimeField(blank=True, null=True)),
                ("pin_revoked_at", models.DateTimeField(blank=True, null=True)),
                ("pin_failed_attempts", models.PositiveIntegerField(default=0)),
                ("pin_locked_until", models.DateTimeField(blank=True, null=True)),
                ("entry_validated_at", models.DateTimeField(blank=True, null=True)),
                ("rules_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("waiting_since", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "removal_action",
                    models.CharField(
                        blank=True,
                        choices=[("removed", "removed"), ("suspended", "suspended"), ("technical", "technical")],
                        default="",
                        max_length=20,
                    ),
                ),
                ("removal_reason", models.TextField(blank=True, default="")),
                ("reconnect_count", models.PositiveIntegerField(default=0)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="final_tickets",
                        to="exams.examattempt",
                        verbose_name="attempt",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_tickets",
                        to="exams.exam",
                        verbose_name="exam",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_exam_tickets",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "pin_generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_final_pins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="removed_final_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="exams.examroomsession",
                        verbose_name="session",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_exam_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="student",
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["seat_number", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="examroom",
            index=models.Index(fields=["organization", "is_active", "name"], name="examroom_org_active_name_idx"),
        ),
        migrations.AddConstraint(
            model_name="examroom",
            constraint=models.UniqueConstraint(fields=("organization", "code"), name="uniq_exam_room_code_per_org"),
        ),
        migrations.AddIndex(
            model_name="examroomsession",
            index=models.Index(
                fields=["organization", "state", "-scheduled_start"], name="roomsess_org_state_sched_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examroomsession",
            index=models.Index(fields=["exam", "-scheduled_start"], name="roomsess_exam_sched_idx"),
        ),
        migrations.AddIndex(
            model_name="examroomsession",
            index=models.Index(fields=["room", "-scheduled_start"], name="roomsess_room_sched_idx"),
        ),
        migrations.AddIndex(
            model_name="examroomsession",
            index=models.Index(fields=["invigilator", "state"], name="roomsess_invig_state_idx"),
        ),
        migrations.AddConstraint(
            model_name="examroomsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "active")), fields=("room",), name="uniq_active_session_per_room"
            ),
        ),
        migrations.AddConstraint(
            model_name="examroomsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("scheduled_end__gt", models.F("scheduled_start"))),
                name="room_session_end_after_start",
            ),
        ),
        migrations.AddIndex(
            model_name="finalexamticket",
            index=models.Index(fields=["session", "status"], name="finticket_session_status_idx"),
        ),
        migrations.AddIndex(
            model_name="finalexamticket",
            index=models.Index(fields=["student", "status"], name="finticket_student_status_idx"),
        ),
        migrations.AddIndex(
            model_name="finalexamticket",
            index=models.Index(fields=["organization", "-created_at"], name="finticket_org_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="finalexamticket",
            constraint=models.UniqueConstraint(fields=("session", "student"), name="uniq_ticket_per_session_student"),
        ),
        migrations.AddConstraint(
            model_name="finalexamticket",
            constraint=models.UniqueConstraint(fields=("exam", "student"), name="uniq_ticket_per_exam_student"),
        ),
        migrations.AddConstraint(
            model_name="finalexamticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(("seat_number__isnull", False)),
                fields=("session", "seat_number"),
                name="uniq_seat_per_session",
            ),
        ),
    ]
