# Generated by Django 5.2.15 on 2026-07-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0030_examroom_examroomsession_finalexamticket_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finalexamticket",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("az", "Azərbaycan dili"), ("en", "English"), ("ru", "Русский"), ("tr", "Türkçe")],
                default="",
                help_text="language",
                max_length=10,
                verbose_name="language",
            ),
        ),
    ]
