# Generated by Django 5.2.15 on 2026-07-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0031_alter_finalexamticket_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalexamticket",
            name="reminder_stage",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
