# Generated by Django 5.2.15 on 2026-07-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0032_finalexamticket_reminder_stage"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="examroomsession",
            name="uniq_active_session_per_room",
        ),
    ]
