# Generated by Django 5.2.15 on 2026-07-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0033_remove_examroomsession_uniq_active_session_per_room"),
        ("registrar", "0020_rls_rubrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroup",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="student_groups", to="registrar.subject", verbose_name="subjects"
            ),
        ),
    ]
