# Generated by Django 5.2.15 on 2026-07-07 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0034_studentgroup_subjects"),
        ("organizations", "0015_rls_final_center"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroup",
            name="org_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_groups",
                to="organizations.orgunit",
                verbose_name="org_unit",
            ),
        ),
    ]
