# Generated by Django 5.2.15 on 2026-07-07 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0035_studentgroup_org_unit"),
        ("registrar", "0020_rls_rubrics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exams",
                to="registrar.subject",
                verbose_name="subject",
            ),
        ),
        migrations.CreateModel(
            name="ExamStudentPin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pin_hash", models.CharField(max_length=255)),
                ("pin_cipher", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_pins",
                        to="exams.exam",
                        verbose_name="exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_student_pins",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="student",
                    ),
                ),
            ],
            options={
                "verbose_name": "student exam PIN",
                "verbose_name_plural": "student exam PINs",
                "indexes": [models.Index(fields=["exam", "student"], name="exam_student_pin_idx")],
                "constraints": [models.UniqueConstraint(fields=("exam", "student"), name="uniq_exam_student_pin")],
            },
        ),
        migrations.CreateModel(
            name="StudentExamAttemptGrant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("extra_attempts", models.PositiveIntegerField(default=1, verbose_name="extra_attempts")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempt_grants",
                        to="exams.exam",
                        verbose_name="exam",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="granted_by",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempt_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="student",
                    ),
                ),
            ],
            options={
                "verbose_name": "extra attempt grant",
                "verbose_name_plural": "extra attempt grants",
                "constraints": [
                    models.UniqueConstraint(fields=("exam", "student"), name="uniq_exam_student_attempt_grant")
                ],
            },
        ),
    ]
