# Generated by Django 5.2.15 on 2026-07-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0036_exam_subject_examstudentpin_studentexamattemptgrant"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="is_trial",
            field=models.BooleanField(db_index=True, default=False, verbose_name="is_trial"),
        ),
    ]
