# Generated by Django 5.2.15 on 2026-07-07 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0037_examattempt_is_trial"),
        ("organizations", "0015_rls_final_center"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="examroom",
            name="invigilators",
            field=models.ManyToManyField(
                blank=True,
                help_text="invigilators",
                related_name="invigilated_rooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="invigilators",
            ),
        ),
        migrations.CreateModel(
            name="ExamRoomComputer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(help_text="label", max_length=64, verbose_name="label")),
                (
                    "seat_number",
                    models.PositiveIntegerField(
                        blank=True, help_text="seat_number", null=True, verbose_name="seat_number"
                    ),
                ),
                ("mac_address", models.CharField(help_text="mac_address", max_length=17, verbose_name="mac_address")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="ip_address", null=True, verbose_name="ip_address"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="is_active")),
                ("notes", models.CharField(blank=True, max_length=255, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_room_computers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_room_computers",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="computers",
                        to="exams.examroom",
                        verbose_name="room",
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["seat_number", "label", "id"],
                "indexes": [models.Index(fields=["room", "is_active"], name="roomcomp_room_active_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("room", "mac_address"), name="uniq_room_computer_mac"),
                    models.UniqueConstraint(fields=("room", "label"), name="uniq_room_computer_label"),
                    models.UniqueConstraint(
                        condition=models.Q(("seat_number__isnull", False)),
                        fields=("room", "seat_number"),
                        name="uniq_room_computer_seat",
                    ),
                ],
            },
        ),
    ]
