# Generated by Django 5.2.15 on 2026-07-08 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0038_examroom_invigilators_examroomcomputer"),
        ("organizations", "0016_rls_exam_room_computer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="finalexamticket",
            name="uniq_ticket_per_session_student",
        ),
        migrations.RemoveConstraint(
            model_name="finalexamticket",
            name="uniq_seat_per_session",
        ),
        migrations.RemoveIndex(
            model_name="examroomsession",
            name="roomsess_exam_sched_idx",
        ),
        migrations.RemoveField(
            model_name="examroomsession",
            name="exam",
        ),
        migrations.AlterField(
            model_name="finalexamticket",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="exams.examroomsession",
                verbose_name="session",
            ),
        ),
        migrations.AddConstraint(
            model_name="finalexamticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(("seat_number__isnull", False), ("session__isnull", False)),
                fields=("session", "seat_number"),
                name="uniq_seat_per_session",
            ),
        ),
    ]
