# Generated by Django 5.2.15 on 2026-07-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0039_decouple_exam_from_room_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionsubmission",
            name="student_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="question_submissions_multi",
                to="exams.studentgroup",
                verbose_name="student_groups",
            ),
        ),
    ]
