# Generated by Django 5.2.13 on 2026-07-08 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0040_qsubmission_multi_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="excluded_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="excluded_users",
                related_name="excluded_exams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="excluded_users",
            ),
        ),
    ]
