# Generated by Django 5.2.15 on 2026-07-10 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0041_exam_excluded_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attempts",
                to="exams.examroom",
                verbose_name="room",
            ),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="room_computer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attempts",
                to="exams.examroomcomputer",
                verbose_name="room_computer",
            ),
        ),
    ]
