# Generated by Django 5.2.15 on 2026-07-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0042_examattempt_room_examattempt_room_computer"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="deleted_at",
            field=models.DateTimeField(blank=True, help_text="deleted_at", null=True, verbose_name="deleted_at"),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, help_text="is_deleted", verbose_name="is_deleted"),
        ),
    ]
