# Generated by Django 5.2.13 on 2026-07-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0044_examanswer_question_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="examanswer",
            name="selected_option_ids_snapshot",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
