# Generated by Django 5.2.13 on 2026-07-11 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0045_examanswer_selected_option_ids_snapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="codingsubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("attempt__isnull", False), ("is_final", True)),
                fields=("attempt", "question"),
                name="uniq_final_coding_submission_per_attempt_question",
            ),
        ),
    ]
