# Generated by Django 5.2.13 on 2026-07-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0046_codingsubmission_final_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="examstudentpin",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="expires_at"),
        ),
        migrations.AddField(
            model_name="examstudentpin",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="revoked_at"),
        ),
    ]
