# Generated by Django 5.2.13 on 2026-07-11 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0047_examstudentpin_lifecycle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_exam_attempts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="graded_by",
            ),
        ),
        migrations.CreateModel(
            name="ExamGradeEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("old_score", models.IntegerField(blank=True, null=True)),
                ("new_score", models.IntegerField(blank=True, null=True)),
                ("max_points", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_events",
                        to="exams.examattempt",
                        verbose_name="attempt",
                    ),
                ),
                (
                    "grader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_grade_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="grader",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grade_events",
                        to="exams.examquestion",
                        verbose_name="question",
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["-created_at", "-id"],
                "indexes": [models.Index(fields=["attempt", "-created_at"], name="exams_examg_attempt_4bebfd_idx")],
            },
        ),
    ]
