# Generated by Django 5.2.13 on 2026-07-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0048_attempt_graded_by_grade_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="autosave_revision",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
