# Generated by Django 5.2.13 on 2026-07-11 21:11
# EXAM-P1-09: access_code artıq bazada Fernet-şifrli saxlanır (şəffaf sahə).

from django.db import migrations

import apps.exams.domain.fields


def encrypt_existing_access_codes(apps, schema_editor):
    """Mövcud xam mətn giriş kodlarını yerində şifrələ.

    Sahə şəffafdır: yükləyəndə köhnə xam mətn ``from_db_value``-dən olduğu kimi
    keçir (açıla bilmir → xam qalır), yenidən saxlayanda ``get_prep_value``
    onu şifrələyir. Yalnız boş olmayan kodlar toxunulur.

    Exam RLS-qorunandır — FORCE RLS altında org konteksti olmadan sətir görünməz;
    bütün tenant-lərin kodlarını şifrələmək üçün bypass edirik.
    """
    from core.rls import bypass_rls

    Exam = apps.get_model("exams", "Exam")
    with bypass_rls():
        for exam in Exam.objects.exclude(access_code="").iterator():
            # access_code yaddaşda xam mətndir; save şifrələmiş nüsxəni yazır.
            exam.save(update_fields=["access_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0049_attempt_autosave_revision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="access_code",
            field=apps.exams.domain.fields.EncryptedAccessCodeField(
                blank=True, help_text="access_code", max_length=255, verbose_name="access_code"
            ),
        ),
        migrations.RunPython(encrypt_existing_access_codes, migrations.RunPython.noop),
    ]
