# Generated by Django 5.2.13 on 2026-07-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0050_access_code_encrypted_at_rest"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="question_timing",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
