# Generated by Django 5.2.13 on 2026-07-11 22:55

import apps.exams.question_timer_protocol
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0052_active_exam_question_invariant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examattempt",
            name="question_timing",
            field=models.JSONField(blank=True, default=apps.exams.question_timer_protocol.default_question_timing),
        ),
    ]
