# Generated by Django 5.2.13 on 2026-07-17 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0056_retire_exam_archive"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(fields=["exam", "started_at"], name="examattempt_exam_started_idx"),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(fields=["exam", "-supervision_violation_count"], name="examattempt_exam_violation_idx"),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                condition=models.Q(("is_trial", False), ("status__in", ["draft", "in_progress"])),
                fields=["status"],
                name="examattempt_active_sweep_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                condition=models.Q(("supervision_status", "locked")),
                fields=["supervision_status"],
                name="examattempt_locked_sweep_idx",
            ),
        ),
    ]
