# Generated by Django 5.2.13 on 2026-07-17 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0057_examattempt_examattempt_exam_started_idx_and_more"),
        ("organizations", "0024_membership_membership_user_org_active_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="examroomcomputer",
            index=models.Index(fields=["organization", "mac_address"], name="roomcomp_org_mac_idx"),
        ),
        migrations.AddIndex(
            model_name="examroomcomputer",
            index=models.Index(fields=["organization", "is_active"], name="roomcomp_org_active_idx"),
        ),
    ]
