# Generated by Django 5.2.13 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0058_examroomcomputer_roomcomp_org_mac_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankquestion",
            name="image_replaces_text",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bankquestionoption",
            name="image_replaces_text",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="image_replaces_text",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examquestionoption",
            name="image_replaces_text",
            field=models.BooleanField(default=False),
        ),
    ]
