# Generated by Django 5.2.15 on 2026-07-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0060_questionsubmission_import_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="total_duration_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                default=60,
                help_text="total_duration_minutes",
                null=True,
                verbose_name="total_duration_minutes",
            ),
        ),
    ]
