# Generated by Django 5.2.15 on 2026-07-30 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0061_alter_exam_total_duration_minutes"),
        ("registrar", "0038_journalcorrection_created_mark"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbank",
            name="exam_kind",
            field=models.CharField(
                blank=True,
                choices=[("final", "Final"), ("midterm", "Midterm"), ("quiz", "Quiz")],
                db_index=True,
                default="",
                max_length=20,
                verbose_name="exam_kind",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="source_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sourced_question_banks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="source_teacher",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="subject_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="question_banks",
                to="registrar.subject",
                verbose_name="subject_ref",
            ),
        ),
        migrations.AddField(
            model_name="questionsubmission",
            name="exam_kind",
            field=models.CharField(
                blank=True,
                choices=[("final", "Final"), ("midterm", "Midterm"), ("quiz", "Quiz")],
                default="",
                max_length=20,
                verbose_name="exam_kind",
            ),
        ),
        migrations.AddField(
            model_name="questionsubmission",
            name="subject_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="question_submissions",
                to="registrar.subject",
                verbose_name="subject_ref",
            ),
        ),
    ]
