# Generated by Django 5.2.17 on 2026-09-03 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0062_question_bank_subject_kind_teacher"),
        ("organizations", "0035_dean_syllabus_review_only"),
        ("registrar", "0063_selfwork_enrollment_done_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionSubmissionEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("actor_label", models.CharField(blank=True, default="", max_length=200)),
                ("actor_role", models.CharField(blank=True, default="", max_length=64)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submitted_to_chair", "submitted"),
                            ("resubmitted_to_chair", "resubmitted"),
                            ("chair_approved", "chair_approved"),
                            ("chair_revision", "chair_revision"),
                            ("chair_rejected", "chair_rejected"),
                            ("center_opened", "center_opened"),
                            ("center_accepted", "center_accepted"),
                            ("center_revision", "center_revision"),
                            ("center_rejected", "center_rejected"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("from_status", models.CharField(blank=True, default="", max_length=20)),
                ("to_status", models.CharField(blank=True, default="", max_length=20)),
                ("reason", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="questionsubmission",
            name="chair_decision",
            field=models.CharField(
                blank=True,
                choices=[("approved", "approved"), ("revision", "revision"), ("rejected", "rejected")],
                default="",
                max_length=20,
                verbose_name="chair_decision",
            ),
        ),
        migrations.AddField(
            model_name="questionsubmission",
            name="chair_note",
            field=models.TextField(blank=True, default="", verbose_name="chair_note"),
        ),
        migrations.AddField(
            model_name="questionsubmission",
            name="chair_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionsubmission",
            name="chair_reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chair_reviewed_question_submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="chair_reviewer",
            ),
        ),
        migrations.AddField(
            model_name="questionsubmission",
            name="chair_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="question_submissions",
                to="organizations.orgunit",
                verbose_name="chair_unit",
            ),
        ),
        migrations.AddField(
            model_name="questionsubmission",
            name="reached_center_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionsubmission",
            name="routed_to_dean",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="questionsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("submitted_to_chair", "submitted_to_chair"),
                    ("chair_revision", "chair_revision"),
                    ("chair_approved", "chair_approved"),
                    ("center_review", "center_review"),
                    ("center_revision", "center_revision"),
                    ("accepted", "accepted"),
                    ("rejected", "rejected"),
                ],
                db_index=True,
                default="submitted_to_chair",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AddIndex(
            model_name="questionsubmission",
            index=models.Index(fields=["chair_unit", "status", "-created_at"], name="qsub_chair_status_idx"),
        ),
        migrations.AddField(
            model_name="questionsubmissionevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="question_submission_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="actor",
            ),
        ),
        migrations.AddField(
            model_name="questionsubmissionevent",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_submission_events",
                to="organizations.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AddField(
            model_name="questionsubmissionevent",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="exams.questionsubmission",
                verbose_name="submission",
            ),
        ),
        migrations.AddIndex(
            model_name="questionsubmissionevent",
            index=models.Index(fields=["submission", "id"], name="qsubev_submission_idx"),
        ),
        migrations.AddIndex(
            model_name="questionsubmissionevent",
            index=models.Index(fields=["organization", "-created_at"], name="qsubev_org_created_idx"),
        ),
    ]
