# Generated by Django 5.2.17 on 2026-10-05 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_drop_duplicate_indexes"),
        ("exams", "0070_examroom_is_exam_hall"),
        ("organizations", "0057_capacity_drop_unused_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Tutum testi 2026-10-05: yalnız indekslər silinir (FK məhdudiyyətinə toxunulmur) —
    # bax accounts/0030_capacity_drop_unused_indexes.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "exams_exam_author_id_67f92c07";\nDROP INDEX IF EXISTS "exams_exam_course_id_67ded634";\nDROP INDEX IF EXISTS "exams_exam_is_archived_c35ba1c6";\nDROP INDEX IF EXISTS "exams_exam_is_deleted_2a956a7b";\nDROP INDEX IF EXISTS "exams_exam_organization_id_13f3dd43";\nDROP INDEX IF EXISTS "exams_examattempt_exam_id_a836ae5c";\nDROP INDEX IF EXISTS "exams_examattempt_graded_by_id_ed9cce49";\nDROP INDEX IF EXISTS "exams_examattempt_is_trial_d7589d92";\nDROP INDEX IF EXISTS "exams_examattempt_user_id_7e278f56";',
                    reverse_sql="CREATE INDEX IF NOT EXISTS exams_exam_author_id_67f92c07 ON public.exams_exam USING btree (author_id);\nCREATE INDEX IF NOT EXISTS exams_exam_course_id_67ded634 ON public.exams_exam USING btree (course_id);\nCREATE INDEX IF NOT EXISTS exams_exam_is_archived_c35ba1c6 ON public.exams_exam USING btree (is_archived);\nCREATE INDEX IF NOT EXISTS exams_exam_is_deleted_2a956a7b ON public.exams_exam USING btree (is_deleted);\nCREATE INDEX IF NOT EXISTS exams_exam_organization_id_13f3dd43 ON public.exams_exam USING btree (organization_id);\nCREATE INDEX IF NOT EXISTS exams_examattempt_exam_id_a836ae5c ON public.exams_examattempt USING btree (exam_id);\nCREATE INDEX IF NOT EXISTS exams_examattempt_graded_by_id_ed9cce49 ON public.exams_examattempt USING btree (graded_by_id);\nCREATE INDEX IF NOT EXISTS exams_examattempt_is_trial_d7589d92 ON public.exams_examattempt USING btree (is_trial);\nCREATE INDEX IF NOT EXISTS exams_examattempt_user_id_7e278f56 ON public.exams_examattempt USING btree (user_id);",
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="exam",
                    name="author",
                    field=models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                migrations.AlterField(
                    model_name="exam",
                    name="course",
                    field=models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exams",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
                migrations.AlterField(
                    model_name="exam",
                    name="is_archived",
                    field=models.BooleanField(default=False, help_text="is_archived", verbose_name="is_archived"),
                ),
                migrations.AlterField(
                    model_name="exam",
                    name="is_deleted",
                    field=models.BooleanField(default=False, help_text="is_deleted", verbose_name="is_deleted"),
                ),
                migrations.AlterField(
                    model_name="exam",
                    name="organization",
                    field=models.ForeignKey(
                        db_index=False,
                        help_text="organization",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
                migrations.AlterField(
                    model_name="examattempt",
                    name="exam",
                    field=models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="exams.exam",
                    ),
                ),
                migrations.AlterField(
                    model_name="examattempt",
                    name="graded_by",
                    field=models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="graded_by",
                    ),
                ),
                migrations.AlterField(
                    model_name="examattempt",
                    name="is_trial",
                    field=models.BooleanField(default=False, verbose_name="is_trial"),
                ),
                migrations.AlterField(
                    model_name="examattempt",
                    name="user",
                    field=models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
