# Generated by Django 5.2.12 on 2026-03-24 09:11

import apps.live_exam.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "pin",
                    models.CharField(
                        db_index=True, default=apps.live_exam.models.generate_pin, max_length=10, unique=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("lobby", "lobby"),
                            ("question", "question"),
                            ("reveal", "reveal"),
                            ("finished", "finished"),
                        ],
                        default="lobby",
                        max_length=12,
                    ),
                ),
                ("is_locked", models.BooleanField(default=False)),
                ("current_index", models.PositiveIntegerField(default=0)),
                ("question_started_at", models.DateTimeField(blank=True, null=True)),
                ("question_ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("current_question_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("question_seconds", models.PositiveIntegerField(default=15)),
                ("question_limit", models.PositiveIntegerField(default=10)),
                ("selected_question_ids", models.JSONField(blank=True, default=list)),
                ("host_settings", models.JSONField(blank=True, default=dict)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="live_sessions", to="exams.exam"
                    ),
                ),
                (
                    "host_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_live_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LivePlayer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nickname", models.CharField(max_length=32)),
                ("avatar_key", models.CharField(default="avatar_1", max_length=32)),
                ("accessory_key", models.CharField(default="accessory_none", max_length=32)),
                ("client_id", models.CharField(db_index=True, max_length=64)),
                ("score", models.IntegerField(default=0)),
                ("streak", models.PositiveIntegerField(default=0)),
                ("is_connected", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="players", to="live_exam.livesession"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiveAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question_id", models.IntegerField()),
                ("choice_id", models.IntegerField(blank=True, null=True)),
                ("choice_ids", models.JSONField(blank=True, default=list)),
                ("is_correct", models.BooleanField(default=False)),
                ("answer_ms", models.IntegerField(default=0)),
                ("awarded_points", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="live_exam.liveplayer"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="live_exam.livesession"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="liveplayer",
            constraint=models.UniqueConstraint(fields=("session", "client_id"), name="uniq_player_per_session_client"),
        ),
        migrations.AddConstraint(
            model_name="liveanswer",
            constraint=models.UniqueConstraint(
                fields=("session", "player", "question_id"), name="uniq_answer_per_player_question"
            ),
        ),
    ]
