# Generated by Django 5.2.15 on 2026-06-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_exam', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='liveanswer',
            index=models.Index(fields=['session', 'question_id'], name='liveans_session_question_idx'),
        ),
    ]
