# Generated by Django 5.2.8 on 2026-03-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_exam", "0002_alter_liveanswer_player_alter_liveanswer_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livesession",
            name="state",
            field=models.CharField(
                choices=[("lobby", "lobby"), ("question", "question"), ("reveal", "reveal"), ("finished", "finished")],
                default="lobby",
                max_length=12,
            ),
        ),
    ]
