# Generated by Django 5.2.8 on 2026-03-20 00:26

import apps.live_exam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_exam', '0006_alter_livesession_pin_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesession',
            name='pin',
            field=models.CharField(db_index=True, default=apps.live_exam.models.generate_pin, max_length=10, unique=True),
        ),
    ]
