# Generated by Django 5.2.8 on 2026-03-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_exam', '0007_increase_pin_length'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liveanswer',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='liveanswer',
            constraint=models.UniqueConstraint(fields=('session', 'player', 'question_id'), name='uniq_answer_per_player_question'),
        ),
    ]
