# Generated by Django 5.2.17 on 2026-09-02 00:42

import apps.workload.models.amendment
import core.upload_security
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0032_seed_alumni_role"),
        ("registrar", "0062_legacy_grade_review_category_snapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeachingTask",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "academic_year",
                    models.CharField(
                        help_text="Tədris ili — «2026/2027» (AcademicPeriod.academic_year konvensiyası).", max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qaralama"),
                            ("submitted", "Dekanlığa göndərilib"),
                            ("returned", "Qaytarılıb"),
                            ("pending_final_approval", "Yekun təsdiq gözləyir"),
                            ("approved", "Təsdiqlənib"),
                            ("distributing", "Bölüşdürülür"),
                            ("distributed", "Bölüşdürülüb"),
                            ("amended", "Düzəliş edilib"),
                            ("cancelled", "Ləğv edilib"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(default=0, help_text="Hər qaytarma-göndərmə dövrü artırır (F2)."),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("distributed_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "chair",
                    models.ForeignKey(
                        help_text="Kafedra (OrgUnit: chair/department).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teaching_tasks",
                        to="organizations.orgunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_teaching_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "distributed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="distributed_teaching_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_tasks",
                        to="organizations.organization",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_teaching_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "tədris tapşırığı",
                "verbose_name_plural": "tədris tapşırıqları",
                "ordering": ["-academic_year", "chair__name"],
            },
        ),
        migrations.CreateModel(
            name="TeachingTaskRow",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "season",
                    models.CharField(
                        choices=[("fall", "Payız"), ("spring", "Yaz"), ("summer", "Yay")],
                        db_index=True,
                        default="fall",
                        max_length=16,
                    ),
                ),
                (
                    "subject_text",
                    models.CharField(
                        blank=True, help_text="Kataloqda olmayan fənn / xüsusi sətir adı.", max_length=255
                    ),
                ),
                (
                    "row_kind",
                    models.CharField(
                        choices=[
                            ("teaching", "Dərs"),
                            ("practice", "Təcrübə"),
                            ("thesis", "Buraxılış/dissertasiya işi"),
                            ("postgrad", "Dissertant/doktorant"),
                            ("other", "Digər"),
                        ],
                        db_index=True,
                        default="teaching",
                        max_length=16,
                    ),
                ),
                ("specialty_text", models.CharField(blank=True, max_length=255)),
                (
                    "groups_text",
                    models.CharField(blank=True, help_text="Birləşmə yazılışı: «036 / 336 F».", max_length=255),
                ),
                (
                    "education_form",
                    models.CharField(
                        choices=[
                            ("eyani", "Əyani"),
                            ("qiyabi", "Qiyabi"),
                            ("intensiv", "İntensiv"),
                            ("distant", "Distant"),
                        ],
                        db_index=True,
                        default="eyani",
                        max_length=16,
                    ),
                ),
                (
                    "degree_level",
                    models.CharField(
                        choices=[("bachelor", "Bakalavr"), ("master", "Magistr"), ("phd", "Doktorantura")],
                        db_index=True,
                        default="bachelor",
                        max_length=16,
                    ),
                ),
                ("student_count", models.PositiveIntegerField(default=0)),
                ("student_count_text", models.CharField(blank=True, help_text="Birləşmədə «30 / 50».", max_length=100)),
                (
                    "union_count",
                    models.PositiveSmallIntegerField(default=1, help_text="Mühazirə axını (birləşmə) sayı."),
                ),
                (
                    "subgroup_count",
                    models.PositiveSmallIntegerField(default=1, help_text="Qrup və yarımqrupların sayı."),
                ),
                ("lecture_plan", models.PositiveIntegerField(default=0)),
                ("lecture_total", models.PositiveIntegerField(default=0)),
                ("seminar_plan", models.PositiveIntegerField(default=0)),
                ("seminar_total", models.PositiveIntegerField(default=0)),
                ("lab_plan", models.PositiveIntegerField(default=0)),
                ("lab_total", models.PositiveIntegerField(default=0)),
                ("consult_hours", models.PositiveIntegerField(default=0)),
                ("exam_hours", models.PositiveIntegerField(default=0)),
                ("thesis_hours", models.PositiveIntegerField(default=0)),
                ("postgrad_hours", models.PositiveIntegerField(default=0)),
                ("practice_research_hours", models.PositiveIntegerField(default=0)),
                ("practice_production_hours", models.PositiveIntegerField(default=0)),
                (
                    "total_hours",
                    models.PositiveIntegerField(default=0, help_text="Sətir üzrə yekun (servisdə yoxlanılır)."),
                ),
                ("credits", models.CharField(blank=True, help_text="Birləşmədə «6 / 7» ola bilər.", max_length=20)),
                (
                    "credits_value",
                    models.PositiveSmallIntegerField(default=0, help_text="Əsas kredit dəyəri (aqreqat üçün)."),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("reviewed", "Baxılıb"),
                            ("flagged", "İradlı"),
                            ("returned", "Qaytarılıb"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        help_text="Denormalizə — dilim marşrutu (F2); specialty.path-dan törədilir.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workload_rows_as_faculty",
                        to="organizations.orgunit",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="workload_rows_as_group", to="organizations.orgunit"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_task_rows",
                        to="organizations.organization",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        help_text="Semestrə lövbər — offering sinxronu üçün MƏCBURİDİR.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workload_rows",
                        to="organizations.academicperiod",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workload_rows_as_specialty",
                        to="organizations.orgunit",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workload_rows",
                        to="registrar.subject",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rows", to="workload.teachingtask"
                    ),
                ),
            ],
            options={
                "verbose_name": "tapşırıq sətri",
                "verbose_name_plural": "tapşırıq sətirləri",
                "ordering": ["task", "season", "order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeacherAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("lecture", "Mühazirə"),
                            ("seminar", "Seminar/təcrübi"),
                            ("lab", "Laboratoriya"),
                            ("consult", "Məsləhət"),
                            ("exam", "İmtahan"),
                            ("thesis", "Buraxılış işinə rəhbərlik"),
                            ("postgrad", "Dissertant rəhbərliyi"),
                            ("practice_research", "Elmi-tədqiqat təcrübəsi"),
                            ("practice_production", "İstehsalat təcrübəsi"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("hours", models.PositiveIntegerField(help_text="Bu müəllimə düşən saat (>0).")),
                (
                    "groups_note",
                    models.CharField(
                        blank=True, help_text="Hansı qrup/yarımqrup — «236 İ ing, 2-ci yarımqrup».", max_length=255
                    ),
                ),
                ("is_hourly_paid", models.BooleanField(default=False, help_text="Saathesabı fondundan ödənilir.")),
                ("note", models.TextField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="made_workload_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_assignments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        help_text="Boşdursa — VAKANT (saathesabı fondu / işə qəbul ehtiyacı).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workload_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="workload.teachingtaskrow",
                    ),
                ),
            ],
            options={
                "verbose_name": "bölgü sətri",
                "verbose_name_plural": "bölgü sətirləri",
                "ordering": ["row", "activity", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkloadAmendment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "target_kind",
                    models.CharField(choices=[("row", "Tapşırıq sətri"), ("assignment", "Bölgü sətri")], max_length=16),
                ),
                (
                    "target_id",
                    models.UUIDField(help_text="Hədəf sətrin/bölgünün id-si (FK YOX — hədəf silinsə də qeyd qalır)."),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("correction", "Texniki səhvin düzəlişi"),
                            ("staff_change", "Kadr dəyişikliyi"),
                            ("student_count", "Tələbə sayının dəyişməsi"),
                            ("official", "Rəsmi sərəncam/əmr"),
                            ("other", "Digər"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(help_text="Səbəbin açıqlaması — MƏCBURİ.")),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="Rəsmi sənəd (PDF) — org siyasəti ilə məcburi ola bilər.",
                        null=True,
                        upload_to=apps.workload.models.amendment.amendment_document_path,
                        validators=[
                            core.upload_security.FileUploadValidator(allowed_extensions={".pdf"}, max_size_mb=10)
                        ],
                    ),
                ),
                (
                    "made_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workload_amendments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_amendments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendments",
                        to="workload.teachingtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "yük düzəlişi",
                "verbose_name_plural": "yük düzəlişləri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeacherWorkloadProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("academic_year", models.CharField(db_index=True, max_length=20)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("professor", "Professor"),
                            ("dosent", "Dosent"),
                            ("bas_muellim", "Baş müəllim"),
                            ("muellim", "Müəllim"),
                            ("assistent", "Assistent"),
                        ],
                        default="muellim",
                        max_length=32,
                    ),
                ),
                (
                    "staff_fraction",
                    models.DecimalField(
                        decimal_places=2, default=1, help_text="Ştat payı: 0.25 … 1.50 (KQ-12: max 1,5).", max_digits=4
                    ),
                ),
                ("annual_norm_hours", models.PositiveIntegerField(default=500)),
                ("is_external", models.BooleanField(default=False, help_text="Kənar (saathesabı) müəllim.")),
                ("note", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_profiles",
                        to="organizations.organization",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "müəllim yük profili",
                "verbose_name_plural": "müəllim yük profilləri",
                "ordering": ["-academic_year"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "teacher", "academic_year"), name="uniq_workload_profile_teacher_year"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="teachingtask",
            index=models.Index(fields=["organization", "academic_year"], name="workload_te_organiz_969a9c_idx"),
        ),
        migrations.AddIndex(
            model_name="teachingtask",
            index=models.Index(fields=["organization", "status"], name="workload_te_organiz_e36240_idx"),
        ),
        migrations.AddConstraint(
            model_name="teachingtask",
            constraint=models.UniqueConstraint(
                fields=("organization", "academic_year", "chair"), name="uniq_teaching_task_year_chair"
            ),
        ),
        migrations.AddIndex(
            model_name="teachingtaskrow",
            index=models.Index(fields=["task", "season"], name="workload_te_task_id_f24804_idx"),
        ),
        migrations.AddIndex(
            model_name="teachingtaskrow",
            index=models.Index(fields=["organization", "subject"], name="workload_te_organiz_79ec48_idx"),
        ),
        migrations.AddIndex(
            model_name="teacherassignment",
            index=models.Index(fields=["row", "activity"], name="workload_te_row_id_213bad_idx"),
        ),
        migrations.AddIndex(
            model_name="teacherassignment",
            index=models.Index(fields=["organization", "teacher"], name="workload_te_organiz_cb3482_idx"),
        ),
        migrations.AddConstraint(
            model_name="teacherassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(("hours__gt", 0)), name="workload_assignment_hours_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="workloadamendment",
            index=models.Index(fields=["task", "-created_at"], name="workload_wo_task_id_d1932a_idx"),
        ),
        migrations.AddIndex(
            model_name="workloadamendment",
            index=models.Index(
                fields=["organization", "target_kind", "target_id"], name="workload_wo_organiz_8f526e_idx"
            ),
        ),
    ]
