# Generated by Django 5.2.17 on 2026-09-03 06:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0041_seed_stage2_permissions"),
        ("workload", "0003_seed_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherworkloadprofile",
            name="load_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="LoadObjection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "reason_key",
                    models.CharField(
                        choices=[
                            ("hours", "Saat sayı düz deyil"),
                            ("students", "Qrup/tələbə sayı səhvdir"),
                            ("subject", "Fənn ixtisasım deyil"),
                            ("norm", "Norma həddindən artıqdır"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("text", models.TextField(help_text="İzah (≥20 simvol).")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Baxılır"), ("accepted", "Qəbul edildi"), ("rejected", "Rədd edildi")],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Konkret bölgü sətri (varsa) — müəllim hansı təyinata etiraz edir.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="objections",
                        to="workload.teacherassignment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_objections",
                        to="organizations.organization",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_workload_objections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objections",
                        to="workload.teachingtaskrow",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_objections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "yük etirazı",
                "verbose_name_plural": "yük etirazları",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["organization", "status"], name="workload_lo_organiz_ccf678_idx"),
                    models.Index(fields=["row", "teacher"], name="workload_lo_row_id_c31270_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskFacultySlice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "revision",
                    models.PositiveIntegerField(default=0, help_text="Tapşırığın göndərmə dövrü (task.revision)."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Göndərilib"), ("approved", "Təsdiqlənib"), ("returned", "Qaytarılıb")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "comment",
                    models.TextField(blank=True, help_text="Qaytarma səbəbi / təsdiq qeydi (≥20 simvol, auditli)."),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_workload_slices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        help_text="Fakültə (OrgUnit: faculty) — sətrin ixtisasının path-ından törəyir.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workload_slices",
                        to="organizations.orgunit",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_slices",
                        to="organizations.organization",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="slices", to="workload.teachingtask"
                    ),
                ),
            ],
            options={
                "verbose_name": "fakültə təsdiq dilimi",
                "verbose_name_plural": "fakültə təsdiq dilimləri",
                "ordering": ["task", "faculty__name"],
                "indexes": [
                    models.Index(fields=["organization", "status"], name="workload_ta_organiz_df598a_idx"),
                    models.Index(fields=["faculty", "status"], name="workload_ta_faculty_6d0b01_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "faculty", "revision"), name="uniq_workload_slice_task_faculty_revision"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskRowReview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("reviewed", "Baxılıb"), ("flagged", "İradlı")], db_index=True, max_length=16
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="İradda MƏCBURİ (≥20 simvol); vizada boş ola bilər."),
                ),
                (
                    "coordinator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_row_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_row_reviews",
                        to="organizations.organization",
                    ),
                ),
                (
                    "row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="workload.teachingtaskrow",
                    ),
                ),
            ],
            options={
                "verbose_name": "sətir vizası",
                "verbose_name_plural": "sətir vizaları",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["organization", "status"], name="workload_ta_organiz_19c4f0_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("row", "coordinator"), name="uniq_workload_row_review")
                ],
            },
        ),
    ]
