# Generated by Django 5.2.17 on 2026-10-05 08:16

import apps.workload.models.amendment
import core.upload_security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workload", "0006_seed_stage4_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workloadamendment",
            name="document",
            field=models.FileField(
                blank=True,
                help_text="Rəsmi sənəd (PDF) — org siyasəti ilə məcburi ola bilər.",
                max_length=255,
                null=True,
                upload_to=apps.workload.models.amendment.amendment_document_path,
                validators=[core.upload_security.FileUploadValidator(allowed_extensions={".pdf"}, max_size_mb=10)],
            ),
        ),
    ]
