# Generated by Django 5.2.14 on 2026-05-18 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aiassistantlog",
            new_name="ai_assistan_user_id_59dc22_idx",
            old_name="ai_assistant_user_cr_idx",
        ),
        migrations.RenameIndex(
            model_name="aiassistantlog",
            new_name="ai_assistan_organiz_d8356b_idx",
            old_name="ai_assistant_org_cr_idx",
        ),
        migrations.RenameIndex(
            model_name="aiassistantlog",
            new_name="ai_assistan_status_ee0029_idx",
            old_name="ai_assistant_status_cr_idx",
        ),
    ]
