# Generated by Django 5.2.13 on 2026-08-30 06:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0032_seed_alumni_role"),
        ("registrar", "0054_legacy_grade_attempts_and_artifacts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Syllabus",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sillabusu yazan müəllim.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_syllabi",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chair_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Təsdiq edən kafedra (OrgUnit). Kafedra müdirinin scope filtri bu sahəyə söykənir.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="syllabi",
                        to="organizations.orgunit",
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fənn açılışı (qrup + müəllim). Köçürülmüş tarixi qeydlərdə boş ola bilər.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="syllabi",
                        to="registrar.courseoffering",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabi",
                        to="organizations.organization",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        help_text="Semestr. Köçürülmüş «baza sillabus»da BOŞDUR — uydurma tarix yazılmır.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="syllabi",
                        to="organizations.academicperiod",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        help_text="İxtisas — siyahıda fənn adının altında göstərilir.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="syllabi",
                        to="registrar.program",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="syllabi", to="registrar.subject"
                    ),
                ),
            ],
            options={
                "verbose_name": "sillabus",
                "verbose_name_plural": "sillabuslar",
                "ordering": ["subject__code"],
            },
        ),
        migrations.CreateModel(
            name="SyllabusVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("major", models.PositiveSmallIntegerField(default=1)),
                ("minor", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qaralama"),
                            ("submitted", "Təqdim edilib"),
                            ("review", "Baxışdadır"),
                            ("revision", "Düzəliş tələb olunur"),
                            ("approved", "Təsdiqlənib"),
                            ("rejected", "Rədd edilib"),
                            ("archived", "Arxivlənib"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "change_kind",
                    models.CharField(
                        choices=[
                            ("initial", "İlk versiya"),
                            ("minor", "Kiçik dəyişiklik (cari semestr)"),
                            ("major", "Böyük dəyişiklik (növbəti semestr)"),
                            ("copied", "Keçən ildən köçürülüb"),
                            ("imported", "Köhnə sistemdən köçürülüb"),
                        ],
                        default="initial",
                        max_length=16,
                    ),
                ),
                (
                    "plan_hours",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Tədris planından gələn auditoriya saatı bölgüsü: {'lecture': .., 'seminar': .., 'lab': ..}.",
                    ),
                ),
                (
                    "completion_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Biznes qaydalarına uyğun bölmələrin faizi — servis qatı hesablayır (input sayı DEYİL).",
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("review_started_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_reason",
                    models.TextField(
                        blank=True, help_text="Düzəliş/rədd səbəbi — bu iki status üçün MƏCBURİDİR (DB check)."
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approval_source",
                    models.CharField(
                        choices=[("human", "İnsan qərarı"), ("migration", "Sistem / köçürmə")],
                        default="human",
                        help_text="Təsdiqin mənbəyi: insan qərarı və ya köçürmə damğası.",
                        max_length=16,
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Versiyanın redaktəyə bağlandığı an (təsdiqə göndərmə və ya təsdiq).",
                        null=True,
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applies_to_period",
                    models.ForeignKey(
                        blank=True,
                        help_text="Versiyanın tətbiq olunduğu semestr (böyük versiya növbəti semestrə göstərir).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="syllabus_versions",
                        to="organizations.academicperiod",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Təsdiqləyən şəxs. Köçürülmüş qeydlərdə NULL — saxta insan təsdiqi yazılmır.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_syllabus_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabus_versions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Versiyanı baxışa götürmüş kafedra müdiri.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bu versiyanın köçürüldüyü mənbə versiya (diff üçün baza).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_versions",
                        to="syllabus.syllabusversion",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "syllabus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="syllabus.syllabus"
                    ),
                ),
            ],
            options={
                "verbose_name": "sillabus versiyası",
                "verbose_name_plural": "sillabus versiyaları",
                "ordering": ["-major", "-minor"],
            },
        ),
        migrations.CreateModel(
            name="SyllabusSection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "section_id",
                    models.CharField(
                        choices=[
                            ("info", "Ümumi məlumat"),
                            ("desc", "Fənnin təsviri və məqsədi"),
                            ("out", "Təlim nəticələri"),
                            ("week", "Həftəlik mövzular"),
                            ("method", "Tədris metodları"),
                            ("assess", "Qiymətləndirmə strukturu"),
                            ("self", "Sərbəst iş strukturu"),
                            ("lit", "Əsas və əlavə ədəbiyyat"),
                            ("prev", "Yekun görünüş"),
                            ("send", "Təsdiqə göndərmə"),
                        ],
                        help_text="Bölmə açarı — dizayn paketindəki `id` ilə eyni (info/desc/out/…).",
                        max_length=16,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "is_complete",
                    models.BooleanField(
                        default=False,
                        help_text="Biznes qaydası ödənilibmi (servis hesablayır; doldurulmuş input sayı DEYİL).",
                    ),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(
                        default=0, help_text="Optimistik kilid sayğacı — hər uğurlu autosave-də 1 artır."
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabus_sections",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="syllabus.syllabusversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "sillabus bölməsi",
                "verbose_name_plural": "sillabus bölmələri",
                "ordering": ["version", "section_id"],
            },
        ),
        migrations.CreateModel(
            name="SyllabusReview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("submitted", "Təsdiqə göndərildi"),
                            ("withdrawn", "Geri çağırıldı"),
                            ("opened", "Baxışa götürüldü"),
                            ("approved", "Təsdiqləndi"),
                            ("revision", "Düzəliş üçün geri qaytarıldı"),
                            ("rejected", "Rədd edildi"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Geri çağırma / düzəliş / rədd səbəbi — bu üç qərar üçün MƏCBURİDİR (DB check).",
                    ),
                ),
                ("comment", models.TextField(blank=True, help_text="Ümumi şərh (səbəbdən ayrı, opsional).")),
                (
                    "section_comments",
                    models.JSONField(
                        blank=True, default=dict, help_text="Bölmə-bölmə şərhlər: {'week': 'saatlar uyğun deyil', …}."
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Qərarı verən şəxs (köçürmə qeydlərində NULL).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="syllabus_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabus_reviews",
                        to="organizations.organization",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="syllabus.syllabusversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "sillabus baxışı",
                "verbose_name_plural": "sillabus baxışları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="syllabus",
            name="approved_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Hazırda QÜVVƏDƏ olan təsdiqlənmiş versiya — tələbənin gördüyü.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="syllabus.syllabusversion",
            ),
        ),
        migrations.AddField(
            model_name="syllabus",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Üzərində işlənən / ən son versiya (siyahıda göstərilən).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="syllabus.syllabusversion",
            ),
        ),
        migrations.AddIndex(
            model_name="syllabusversion",
            index=models.Index(fields=["organization", "status"], name="syllabus_sy_organiz_68bd54_idx"),
        ),
        migrations.AddIndex(
            model_name="syllabusversion",
            index=models.Index(fields=["syllabus", "-major", "-minor"], name="syllabus_sy_syllabu_124028_idx"),
        ),
        migrations.AddIndex(
            model_name="syllabusversion",
            index=models.Index(fields=["organization", "submitted_at"], name="syllabus_sy_organiz_45cd2c_idx"),
        ),
        migrations.AddConstraint(
            model_name="syllabusversion",
            constraint=models.UniqueConstraint(
                fields=("organization", "syllabus", "major", "minor"), name="uniq_syllabus_version_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="syllabusversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["draft", "review", "revision", "submitted"])),
                fields=("syllabus",),
                name="uniq_syllabus_open_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="syllabusversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "approved")), fields=("syllabus",), name="uniq_syllabus_approved_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="syllabusversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status__in", ["rejected", "revision"]), _negated=True),
                    models.Q(("decision_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="syllabus_version_reason_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="syllabusversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "approved"), _negated=True), ("locked_at__isnull", False), _connector="OR"
                ),
                name="syllabus_version_approved_is_locked",
            ),
        ),
        migrations.AddConstraint(
            model_name="syllabusversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "approved"), _negated=True),
                    models.Q(("approval_source", "human"), _negated=True),
                    ("approved_by__isnull", False),
                    _connector="OR",
                ),
                name="syllabus_version_human_approval_has_approver",
            ),
        ),
        migrations.AddConstraint(
            model_name="syllabusversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("major__gte", 1)), name="syllabus_version_major_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="syllabusversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("completion_percent__lte", 100)), name="syllabus_version_completion_percent_range"
            ),
        ),
        migrations.AddIndex(
            model_name="syllabussection",
            index=models.Index(fields=["organization", "version"], name="syllabus_sy_organiz_a084bb_idx"),
        ),
        migrations.AddConstraint(
            model_name="syllabussection",
            constraint=models.UniqueConstraint(
                fields=("organization", "version", "section_id"), name="uniq_syllabus_section_per_version"
            ),
        ),
        migrations.AddIndex(
            model_name="syllabusreview",
            index=models.Index(fields=["organization", "version"], name="syllabus_sy_organiz_5a5c69_idx"),
        ),
        migrations.AddIndex(
            model_name="syllabusreview",
            index=models.Index(fields=["organization", "-created_at"], name="syllabus_sy_organiz_fe2315_idx"),
        ),
        migrations.AddConstraint(
            model_name="syllabusreview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("decision__in", ("withdrawn", "revision", "rejected")), _negated=True),
                    models.Q(("reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="syllabus_review_reason_required",
            ),
        ),
        migrations.AddIndex(
            model_name="syllabus",
            index=models.Index(fields=["organization", "period"], name="syllabus_sy_organiz_189403_idx"),
        ),
        migrations.AddIndex(
            model_name="syllabus",
            index=models.Index(fields=["organization", "chair_unit"], name="syllabus_sy_organiz_7455f7_idx"),
        ),
        migrations.AddIndex(
            model_name="syllabus",
            index=models.Index(fields=["organization", "author"], name="syllabus_sy_organiz_b5a518_idx"),
        ),
        migrations.AddConstraint(
            model_name="syllabus",
            constraint=models.UniqueConstraint(
                condition=models.Q(("offering__isnull", False)),
                fields=("organization", "offering"),
                name="uniq_syllabus_per_offering",
            ),
        ),
        migrations.AddConstraint(
            model_name="syllabus",
            constraint=models.UniqueConstraint(
                condition=models.Q(("offering__isnull", True), ("period__isnull", False)),
                fields=("organization", "subject", "period"),
                name="uniq_syllabus_per_subject_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="syllabus",
            constraint=models.UniqueConstraint(
                condition=models.Q(("offering__isnull", True), ("period__isnull", True)),
                fields=("organization", "subject", "author"),
                name="uniq_syllabus_base_per_subject_author",
            ),
        ),
    ]
