# Generated by Django 5.2.13 on 2026-08-22 22:19

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
_TOKEN_VALIDATOR = django.core.validators.RegexValidator(
    message="Yalnız kiçik hərf, rəqəm, nöqtə, alt xətt və defis istifadə edilə bilər.", regex="^[a-z0-9][a-z0-9._-]*$"
)
_SHA256_VALIDATOR = django.core.validators.RegexValidator(
    message="Dəyər kiçik hərfli 64 simvolluq SHA-256 hex digest olmalıdır.", regex="^[0-9a-f]{64}$"
)
_OPAQUE_KEY_VALIDATOR = django.core.validators.RegexValidator(
    message="Açar yalnız opaque identifikator simvollarından ibarət olmalıdır.", regex="^[A-Za-z0-9][A-Za-z0-9._:-]{0,254}$"
)
_MODEL_LABEL_VALIDATOR = django.core.validators.RegexValidator(
    message="Target model etiketi app_label.model_name formatında olmalıdır.", regex="^[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*$"
)

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0026_seed_ikt_rehber_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyEntityMap",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "source_system",
                    models.CharField(
                        max_length=64,
                        validators=[_TOKEN_VALIDATOR],
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        max_length=64,
                        validators=[_TOKEN_VALIDATOR],
                    ),
                ),
                (
                    "legacy_pk",
                    models.CharField(
                        max_length=255,
                        validators=[_OPAQUE_KEY_VALIDATOR],
                    ),
                ),
                (
                    "source_row_hash",
                    models.CharField(
                        max_length=64,
                        validators=[_SHA256_VALIDATOR],
                    ),
                ),
                (
                    "transform_version",
                    models.CharField(
                        max_length=64,
                        validators=[_TOKEN_VALIDATOR],
                    ),
                ),
                (
                    "target_model_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        validators=[_MODEL_LABEL_VALIDATOR],
                    ),
                ),
                (
                    "target_pk",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        validators=[_OPAQUE_KEY_VALIDATOR],
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("migrated", "Miqrasiya edilib"),
                            ("skipped", "Buraxılıb"),
                            ("quarantined", "Quarantine"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reconciliation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("verified", "Təsdiqlənib"),
                            ("mismatch", "Uyğunsuzluq"),
                            ("not_applicable", "Tətbiq edilmir"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_entity_maps",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={"ordering": ["source_system", "entity_type", "legacy_pk"]},
        ),
        migrations.CreateModel(
            name="LegacyMigrationRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "source_system",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Yalnız kiçik hərf, rəqəm, nöqtə, alt xətt və defis istifadə edilə bilər."
                                ),
                                regex="^[a-z0-9][a-z0-9._-]*$",
                            )
                        ],
                    ),
                ),
                (
                    "snapshot_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Dəyər kiçik hərfli 64 simvolluq SHA-256 hex digest olmalıdır.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("snapshot_size_bytes", models.PositiveBigIntegerField()),
                ("source_row_count", models.PositiveBigIntegerField(default=0)),
                (
                    "schema_version",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Yalnız kiçik hərf, rəqəm, nöqtə, alt xətt və defis istifadə edilə bilər."
                                ),
                                regex="^[a-z0-9][a-z0-9._-]*$",
                            )
                        ],
                    ),
                ),
                (
                    "transform_version",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Yalnız kiçik hərf, rəqəm, nöqtə, alt xətt və defis istifadə edilə bilər."
                                ),
                                regex="^[a-z0-9][a-z0-9._-]*$",
                            )
                        ],
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("profile", "Profiling"), ("rehearsal", "Rehearsal"), ("cutover", "Cutover")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("running", "İcra olunur"),
                            ("succeeded", "Uğurlu"),
                            ("failed", "Uğursuz"),
                            ("cancelled", "Dayandırılıb"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("manual", "Manual"), ("command", "Management command")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("migrated_count", models.PositiveBigIntegerField(default=0)),
                ("skipped_count", models.PositiveBigIntegerField(default=0)),
                ("quarantined_count", models.PositiveBigIntegerField(default=0)),
                (
                    "failure_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Yalnız kiçik hərf, rəqəm, nöqtə, alt xətt və defis istifadə edilə bilər."
                                ),
                                regex="^[a-z0-9][a-z0-9._-]*$",
                            )
                        ],
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legacy_migration_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_migration_runs",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="LegacyMigrationIssue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "source_table",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Yalnız kiçik hərf, rəqəm, nöqtə, alt xətt və defis istifadə edilə bilər."
                                ),
                                regex="^[a-z0-9][a-z0-9._-]*$",
                            )
                        ],
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Yalnız kiçik hərf, rəqəm, nöqtə, alt xətt və defis istifadə edilə bilər."
                                ),
                                regex="^[a-z0-9][a-z0-9._-]*$",
                            )
                        ],
                    ),
                ),
                (
                    "legacy_pk",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Açar yalnız opaque identifikator simvollarından ibarət olmalıdır.",
                                regex="^[A-Za-z0-9][A-Za-z0-9._:-]{0,254}$",
                            )
                        ],
                    ),
                ),
                (
                    "rule_code",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Yalnız kiçik hərf, rəqəm, nöqtə, alt xətt və defis istifadə edilə bilər."
                                ),
                                regex="^[a-z0-9][a-z0-9._-]*$",
                            )
                        ],
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Məlumat"),
                            ("warning", "Xəbərdarlıq"),
                            ("error", "Xəta"),
                            ("critical", "Kritik"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("open", "Açıq"),
                            ("acknowledged", "Qəbul edilib"),
                            ("resolved", "Həll edilib"),
                            ("waived", "İstisna təsdiqlənib"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "payload_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Dəyər kiçik hərfli 64 simvolluq SHA-256 hex digest olmalıdır.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "entity_map",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues",
                        to="legacy_import.legacyentitymap",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_migration_issues",
                        to="organizations.organization",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues",
                        to="legacy_import.legacymigrationrun",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="legacyentitymap",
            name="created_run",
            field=models.ForeignKey(
                help_text="Canonical mapping-in ilk yaradıldığı run; sonrakı run-lar observation kimi saxlanır.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_entity_maps",
                to="legacy_import.legacymigrationrun",
            ),
        ),
        migrations.AddIndex(
            model_name="legacymigrationrun",
            index=models.Index(
                fields=["organization", "source_system", "status"], name="legacy_run_org_src_status"
            ),
        ),
        migrations.AddIndex(
            model_name="legacymigrationrun",
            index=models.Index(fields=["organization", "snapshot_sha256"], name="legacy_run_org_snapshot"),
        ),
        migrations.AddConstraint(
            model_name="legacymigrationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("snapshot_sha256__regex", "^[0-9a-f]{64}$")),
                name="legacy_run_snapshot_sha_hex",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacymigrationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_system__regex", "^[a-z0-9][a-z0-9._-]*$")),
                name="legacy_run_source_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacymigrationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_version__regex", "^[a-z0-9][a-z0-9._-]*$")),
                name="legacy_run_schema_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacymigrationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("transform_version__regex", "^[a-z0-9][a-z0-9._-]*$")),
                name="legacy_run_transform_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacymigrationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("failure_code", ""),
                    ("failure_code__regex", "^[a-z0-9][a-z0-9._-]*$"),
                    _connector="OR",
                ),
                name="legacy_run_failure_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacymigrationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "migrated_count__lte",
                        models.F("source_row_count")
                        - models.F("skipped_count")
                        - models.F("quarantined_count"),
                    )
                ),
                name="legacy_run_counts_within_total",
            ),
        ),
        migrations.AddIndex(
            model_name="legacymigrationissue",
            index=models.Index(
                fields=["organization", "review_status", "severity"], name="legacy_issue_org_review"
            ),
        ),
        migrations.AddIndex(
            model_name="legacymigrationissue",
            index=models.Index(fields=["run", "entity_type"], name="legacy_issue_run_entity"),
        ),
        migrations.AddConstraint(
            model_name="legacymigrationissue",
            constraint=models.UniqueConstraint(
                fields=("run", "source_table", "legacy_pk", "rule_code"),
                name="legacy_issue_row_rule_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacymigrationissue",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_table__regex", "^[a-z0-9][a-z0-9._-]*$")),
                name="legacy_issue_table_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacymigrationissue",
            constraint=models.CheckConstraint(
                condition=models.Q(("entity_type__regex", "^[a-z0-9][a-z0-9._-]*$")),
                name="legacy_issue_entity_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacymigrationissue",
            constraint=models.CheckConstraint(
                condition=models.Q(("rule_code__regex", "^[a-z0-9][a-z0-9._-]*$")),
                name="legacy_issue_rule_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacymigrationissue",
            constraint=models.CheckConstraint(
                condition=models.Q(("payload_digest__regex", "^[0-9a-f]{64}$")),
                name="legacy_issue_digest_hex",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacymigrationissue",
            constraint=models.CheckConstraint(
                condition=models.Q(("legacy_pk__regex", "^[A-Za-z0-9][A-Za-z0-9._:-]{0,254}$")),
                name="legacy_issue_pk_token",
            ),
        ),
        migrations.AddIndex(
            model_name="legacyentitymap",
            index=models.Index(
                fields=["organization", "created_run", "state"], name="legacy_map_org_created_state"
            ),
        ),
        migrations.AddIndex(
            model_name="legacyentitymap",
            index=models.Index(fields=["target_model_label", "target_pk"], name="legacy_map_target"),
        ),
        migrations.AddConstraint(
            model_name="legacyentitymap",
            constraint=models.UniqueConstraint(
                fields=("organization", "source_system", "entity_type", "legacy_pk"),
                name="legacy_map_source_key_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacyentitymap",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_system__regex", "^[a-z0-9][a-z0-9._-]*$")),
                name="legacy_map_source_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacyentitymap",
            constraint=models.CheckConstraint(
                condition=models.Q(("entity_type__regex", "^[a-z0-9][a-z0-9._-]*$")),
                name="legacy_map_entity_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacyentitymap",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_row_hash__regex", "^[0-9a-f]{64}$")),
                name="legacy_map_row_sha_hex",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacyentitymap",
            constraint=models.CheckConstraint(
                condition=models.Q(("transform_version__regex", "^[a-z0-9][a-z0-9._-]*$")),
                name="legacy_map_transform_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacyentitymap",
            constraint=models.CheckConstraint(
                condition=models.Q(("legacy_pk__regex", "^[A-Za-z0-9][A-Za-z0-9._:-]{0,254}$")),
                name="legacy_map_pk_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacyentitymap",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("target_model_label", ""),
                    ("target_model_label__regex", "^[a-z][a-z0-9_]*\\.[a-z][a-z0-9_]*$"),
                    _connector="OR",
                ),
                name="legacy_map_model_label",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacyentitymap",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("target_pk", ""),
                    ("target_pk__regex", "^[A-Za-z0-9][A-Za-z0-9._:-]{0,254}$"),
                    _connector="OR",
                ),
                name="legacy_map_target_pk_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacyentitymap",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("state", "migrated"),
                        models.Q(("target_model_label", ""), _negated=True),
                        models.Q(("target_pk", ""), _negated=True),
                    ),
                    models.Q(
                        ("state__in", ["skipped", "quarantined"]),
                        ("target_model_label", ""),
                        ("target_pk", ""),
                    ),
                    _connector="OR",
                ),
                name="legacy_map_target_by_state",
            ),
        ),
    ]
