# Generated by Django 5.2.16 on 2026-08-24 09:47

import uuid
from contextlib import contextmanager

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


@contextmanager
def _migration_rls_bypass(schema_editor):
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        yield
        return
    with connection.cursor() as cursor:
        cursor.execute("SELECT set_config('app.bypass_rls', 'on', true)")
    try:
        yield
    finally:
        if not connection.needs_rollback:
            with connection.cursor() as cursor:
                cursor.execute("SELECT set_config('app.bypass_rls', 'off', true)")


def _drop_v4_observation_guard(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "DROP TRIGGER IF EXISTS legacy_import_observation_integrity "
            "ON public.legacy_import_legacyentityobservation"
        )


_RESTORE_V4_OBSERVATION_SQL = r"""
CREATE OR REPLACE FUNCTION legacy_import_observation_integrity_guard()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    run_row record;
    map_row record;
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'legacy entity observation dəyişdirilə bilməz';
    END IF;
    SELECT run.organization_id, run.source_system, run.transform_version, run.status
      INTO run_row
      FROM public.legacy_import_legacymigrationrun AS run
     WHERE run.id = NEW.run_id FOR UPDATE;
    SELECT entity_map.organization_id, entity_map.source_system,
           entity_map.source_row_hash, entity_map.transform_version,
           entity_map.target_model_label, entity_map.target_pk,
           entity_map.state, entity_map.reconciliation_status
      INTO map_row
      FROM public.legacy_import_legacyentitymap AS entity_map
     WHERE entity_map.id = NEW.entity_map_id FOR UPDATE;
    IF NOT FOUND
       OR run_row.status <> 'running'
       OR run_row.organization_id <> NEW.organization_id
       OR run_row.source_system <> map_row.source_system
       OR run_row.transform_version <> NEW.transform_version
       OR map_row.organization_id <> NEW.organization_id
       OR map_row.source_row_hash <> NEW.source_row_hash
       OR map_row.transform_version <> NEW.transform_version
       OR map_row.target_model_label <> NEW.target_model_label
       OR map_row.target_pk <> NEW.target_pk
       OR map_row.state <> NEW.state
       OR map_row.reconciliation_status <> NEW.reconciliation_status
    THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'legacy observation run və canonical mapping ilə uyğun deyil';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER legacy_import_observation_integrity
BEFORE INSERT OR UPDATE ON public.legacy_import_legacyentityobservation
FOR EACH ROW EXECUTE FUNCTION legacy_import_observation_integrity_guard();
REVOKE ALL ON FUNCTION legacy_import_observation_integrity_guard() FROM PUBLIC;
"""


def _restore_v4_observation_guard(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(_RESTORE_V4_OBSERVATION_SQL)


def _precheck_existing_issue_reviews(apps, schema_editor):
    Issue = apps.get_model("legacy_import", "LegacyMigrationIssue")
    alias = schema_editor.connection.alias
    with _migration_rls_bypass(schema_editor):
        if Issue.objects.using(alias).exclude(review_status="open").exists():
            raise RuntimeError("legacy_import_0005_existing_reviews_require_audit_reconciliation")


def _backfill_initial_versions(apps, schema_editor):
    EntityMap = apps.get_model("legacy_import", "LegacyEntityMap")
    Version = apps.get_model("legacy_import", "LegacyEntityMapVersion")
    Observation = apps.get_model("legacy_import", "LegacyEntityObservation")
    alias = schema_editor.connection.alias
    fields = (
        "source_row_hash",
        "transform_version",
        "target_model_label",
        "target_pk",
        "state",
        "reconciliation_status",
    )
    with _migration_rls_bypass(schema_editor):
        drift_filter = {
            "organization_id": models.F("entity_map__organization_id"),
            "source_row_hash": models.F("entity_map__source_row_hash"),
            "transform_version": models.F("entity_map__transform_version"),
            "target_model_label": models.F("entity_map__target_model_label"),
            "target_pk": models.F("entity_map__target_pk"),
            "state": models.F("entity_map__state"),
            "reconciliation_status": models.F("entity_map__reconciliation_status"),
        }
        matching_scope = models.Q(**drift_filter) & models.Q(
            organization_id=models.F("run__organization_id"),
            entity_map__source_system=models.F("run__source_system"),
            transform_version=models.F("run__transform_version"),
        )
        if Observation.objects.using(alias).exclude(matching_scope).exists():
            raise RuntimeError("legacy_import_0005_observation_backfill_drift")
        pending = []
        for entity_map in EntityMap.objects.using(alias).all().iterator(chunk_size=1000):
            pending.append(
                Version(
                    organization_id=entity_map.organization_id,
                    entity_map_id=entity_map.pk,
                    version_number=1,
                    recorded_run_id=entity_map.created_run_id,
                    **{field: getattr(entity_map, field) for field in fields},
                )
            )
            if len(pending) == 1000:
                Version.objects.using(alias).bulk_create(pending, batch_size=1000)
                pending = []
        if pending:
            Version.objects.using(alias).bulk_create(pending, batch_size=1000)
        observation_table = schema_editor.quote_name(Observation._meta.db_table)
        version_table = schema_editor.quote_name(Version._meta.db_table)
        schema_editor.execute(
            f"UPDATE {observation_table} SET map_version_id = ("
            f"SELECT id FROM {version_table} WHERE {version_table}.entity_map_id = "
            f"{observation_table}.entity_map_id AND {version_table}.version_number = 1) "
            "WHERE map_version_id IS NULL"
        )


def _remove_backfilled_versions(apps, schema_editor):
    Observation = apps.get_model("legacy_import", "LegacyEntityObservation")
    Version = apps.get_model("legacy_import", "LegacyEntityMapVersion")
    alias = schema_editor.connection.alias
    with _migration_rls_bypass(schema_editor):
        _assert_no_reviewed_remaps_unscoped(apps, alias)
        Observation.objects.using(alias).update(map_version=None)
        version_table = schema_editor.quote_name(Version._meta.db_table)
        schema_editor.execute(f"DELETE FROM {version_table}")
        if schema_editor.connection.vendor == "postgresql":
            schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


def _assert_no_reviewed_remaps(apps, schema_editor):
    with _migration_rls_bypass(schema_editor):
        _assert_no_reviewed_remaps_unscoped(apps, schema_editor.connection.alias)


def _assert_no_reviewed_remaps_unscoped(apps, alias):
    Version = apps.get_model("legacy_import", "LegacyEntityMapVersion")
    Issue = apps.get_model("legacy_import", "LegacyMigrationIssue")
    has_review_history = Issue.objects.using(alias).exclude(
        review_status="open",
        reviewed_by__isnull=True,
        reviewed_at__isnull=True,
        review_reason_code="",
        review_evidence_digest="",
    ).exists()
    if Version.objects.using(alias).filter(version_number__gt=1).exists() or has_review_history:
        raise RuntimeError("legacy_import_0005_reverse_blocked_by_review_history")


_FORWARD_GUARDS_SQL = r"""
CREATE OR REPLACE FUNCTION legacy_import_issue_integrity_guard()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    run_row record;
    old_rank integer;
    new_rank integer;
    review_changed boolean;
BEGIN
    IF TG_OP = 'UPDATE' AND (
        NEW.id IS DISTINCT FROM OLD.id
        OR NEW.created_at IS DISTINCT FROM OLD.created_at
        OR NEW.organization_id IS DISTINCT FROM OLD.organization_id
        OR NEW.run_id IS DISTINCT FROM OLD.run_id
        OR NEW.source_table IS DISTINCT FROM OLD.source_table
        OR NEW.entity_type IS DISTINCT FROM OLD.entity_type
        OR NEW.legacy_pk IS DISTINCT FROM OLD.legacy_pk
        OR NEW.rule_code IS DISTINCT FROM OLD.rule_code
        OR NEW.payload_digest IS DISTINCT FROM OLD.payload_digest
    ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'legacy migration issue identity dəyişdirilə bilməz';
    END IF;
    SELECT run.organization_id, run.source_system, run.transform_version, run.status
      INTO run_row
      FROM public.legacy_import_legacymigrationrun AS run
     WHERE run.id = NEW.run_id FOR UPDATE;
    IF NOT FOUND OR run_row.organization_id <> NEW.organization_id THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'legacy migration issue run scope ilə uyğun deyil';
    END IF;
    IF NEW.entity_map_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
          FROM public.legacy_import_legacyentitymap AS entity_map
         WHERE entity_map.id = NEW.entity_map_id
           AND entity_map.organization_id = NEW.organization_id
           AND entity_map.source_system = run_row.source_system
           AND entity_map.entity_type = NEW.entity_type
           AND entity_map.legacy_pk = NEW.legacy_pk
           AND (
               NEW.rule_code = 'legacy_entity_identity_conflict'
               OR EXISTS (
                   SELECT 1
                     FROM public.legacy_import_legacyentityobservation AS observation
                    WHERE observation.entity_map_id = entity_map.id
                      AND observation.run_id = NEW.run_id
                      AND observation.transform_version = run_row.transform_version
               )
           )
    ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'legacy issue canonical source identity ilə uyğun deyil';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF run_row.status <> 'running'
           OR NEW.review_status <> 'open'
           OR NEW.reviewed_by_id IS NOT NULL
           OR NEW.reviewed_at IS NOT NULL
           OR NEW.review_reason_code <> ''
           OR NEW.review_evidence_digest <> ''
        THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'legacy issue open və review evidence-siz yaradılmalıdır';
        END IF;
        RETURN NEW;
    END IF;

    review_changed :=
        NEW.reviewed_by_id IS DISTINCT FROM OLD.reviewed_by_id
        OR NEW.reviewed_at IS DISTINCT FROM OLD.reviewed_at
        OR NEW.review_reason_code IS DISTINCT FROM OLD.review_reason_code
        OR NEW.review_evidence_digest IS DISTINCT FROM OLD.review_evidence_digest;
    old_rank := CASE OLD.severity
        WHEN 'info' THEN 0 WHEN 'warning' THEN 1
        WHEN 'error' THEN 2 WHEN 'critical' THEN 3 ELSE -1 END;
    new_rank := CASE NEW.severity
        WHEN 'info' THEN 0 WHEN 'warning' THEN 1
        WHEN 'error' THEN 2 WHEN 'critical' THEN 3 ELSE -1 END;

    IF NEW.severity IS DISTINCT FROM OLD.severity THEN
        IF run_row.status <> 'running'
           OR new_rank <= old_rank
           OR NEW.review_status <> 'open'
           OR review_changed
        THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'legacy issue severity yalnız evidence-i saxlayan open escalation ola bilər';
        END IF;
    ELSIF NEW.review_status IS DISTINCT FROM OLD.review_status THEN
        IF NEW.review_status NOT IN ('acknowledged', 'resolved', 'waived')
           OR OLD.review_status IN ('resolved', 'waived')
           OR (OLD.review_status = 'acknowledged' AND NEW.review_status = 'acknowledged')
           OR NOT review_changed
           OR NEW.reviewed_by_id IS NULL
           OR NEW.reviewed_at IS NULL
           OR NEW.review_reason_code = ''
           OR NEW.review_evidence_digest = ''
           OR NEW.reviewed_at < NEW.created_at
           OR (OLD.reviewed_at IS NOT NULL AND NEW.reviewed_at <= OLD.reviewed_at)
        THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'legacy issue review keçidi explicit yeni evidence tələb edir';
        END IF;
    ELSIF review_changed THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'legacy issue review evidence status keçidi olmadan dəyişə bilməz';
    END IF;
    IF NEW.entity_map_id IS DISTINCT FROM OLD.entity_map_id AND (
        run_row.status <> 'running'
        OR OLD.entity_map_id IS NOT NULL
        OR NEW.entity_map_id IS NULL
        OR NEW.review_status <> 'open'
    ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'legacy issue entity map yalnız open running issue-a bağlana bilər';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION legacy_import_version_integrity_guard()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    map_row record;
    run_row record;
    predecessor_row record;
    issue_row record;
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'legacy canonical mapping version dəyişdirilə bilməz';
    END IF;
    SELECT entity_map.organization_id, entity_map.source_system,
           entity_map.entity_type, entity_map.legacy_pk,
           entity_map.created_run_id, entity_map.source_row_hash,
           entity_map.transform_version, entity_map.target_model_label,
           entity_map.target_pk, entity_map.state,
           entity_map.reconciliation_status
      INTO map_row
      FROM public.legacy_import_legacyentitymap AS entity_map
     WHERE entity_map.id = NEW.entity_map_id FOR UPDATE;
    SELECT run.organization_id, run.source_system, run.transform_version, run.status
      INTO run_row
      FROM public.legacy_import_legacymigrationrun AS run
     WHERE run.id = NEW.recorded_run_id FOR UPDATE;
    IF map_row.organization_id IS NULL
       OR run_row.organization_id IS NULL
       OR NEW.organization_id <> map_row.organization_id
       OR run_row.organization_id <> NEW.organization_id
       OR run_row.source_system <> map_row.source_system
       OR run_row.transform_version <> NEW.transform_version
       OR run_row.status <> 'running'
    THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'legacy mapping version run/source scope ilə uyğun deyil';
    END IF;
    IF NEW.version_number = 1 THEN
        IF NEW.supersedes_id IS NOT NULL
           OR NEW.approved_issue_id IS NOT NULL
           OR NEW.reviewed_by_id IS NOT NULL
           OR NEW.reviewed_at IS NOT NULL
           OR NEW.review_reason_code <> ''
           OR NEW.review_evidence_digest <> ''
           OR NEW.applied_by_id IS NOT NULL
           OR NEW.recorded_run_id <> map_row.created_run_id
           OR NEW.source_row_hash <> map_row.source_row_hash
           OR NEW.transform_version <> map_row.transform_version
           OR NEW.target_model_label <> map_row.target_model_label
           OR NEW.target_pk <> map_row.target_pk
           OR NEW.state <> map_row.state
           OR NEW.reconciliation_status <> map_row.reconciliation_status
        THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'legacy initial mapping version base snapshot ilə eyni olmalıdır';
        END IF;
        RETURN NEW;
    END IF;
    SELECT version.entity_map_id, version.version_number,
           version.source_row_hash, version.transform_version,
           version.target_model_label, version.target_pk,
           version.state, version.reconciliation_status
      INTO predecessor_row
      FROM public.legacy_import_legacyentitymapversion AS version
     WHERE version.id = NEW.supersedes_id FOR UPDATE;
    IF predecessor_row.entity_map_id IS NULL
       OR predecessor_row.entity_map_id <> NEW.entity_map_id
       OR predecessor_row.version_number + 1 <> NEW.version_number
       OR EXISTS (
           SELECT 1 FROM public.legacy_import_legacyentitymapversion AS later
            WHERE later.entity_map_id = NEW.entity_map_id
              AND later.version_number > predecessor_row.version_number
       )
       OR (
           predecessor_row.source_row_hash,
           predecessor_row.transform_version,
           predecessor_row.target_model_label,
           predecessor_row.target_pk,
           predecessor_row.state,
           predecessor_row.reconciliation_status
       ) IS NOT DISTINCT FROM (
           NEW.source_row_hash,
           NEW.transform_version,
           NEW.target_model_label,
           NEW.target_pk,
           NEW.state,
           NEW.reconciliation_status
       )
    THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'legacy remap version lineage etibarsızdır';
    END IF;
    SELECT issue.organization_id, issue.run_id, issue.entity_map_id,
           issue.entity_type, issue.legacy_pk, issue.rule_code,
           issue.review_status, issue.reviewed_by_id, issue.reviewed_at,
           issue.review_reason_code, issue.review_evidence_digest
      INTO issue_row
      FROM public.legacy_import_legacymigrationissue AS issue
     WHERE issue.id = NEW.approved_issue_id FOR UPDATE;
    IF issue_row.organization_id IS NULL
       OR issue_row.organization_id <> NEW.organization_id
       OR issue_row.run_id <> NEW.recorded_run_id
       OR issue_row.entity_map_id <> NEW.entity_map_id
       OR issue_row.entity_type <> map_row.entity_type
       OR issue_row.legacy_pk <> map_row.legacy_pk
       OR issue_row.rule_code <> 'legacy_entity_identity_conflict'
       OR issue_row.review_status <> 'resolved'
       OR issue_row.reviewed_by_id <> NEW.reviewed_by_id
       OR issue_row.reviewed_at IS DISTINCT FROM NEW.reviewed_at
       OR issue_row.review_reason_code <> NEW.review_reason_code
       OR issue_row.review_evidence_digest <> NEW.review_evidence_digest
       OR NEW.applied_by_id IS NULL
    THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'legacy remap matching resolved review evidence tələb edir';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION legacy_import_initial_version_create()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
    INSERT INTO public.legacy_import_legacyentitymapversion (
        id, created_at, updated_at, organization_id, entity_map_id,
        version_number, supersedes_id, recorded_run_id, source_row_hash,
        transform_version, target_model_label, target_pk, state,
        reconciliation_status, approved_issue_id, reviewed_by_id,
        reviewed_at, review_reason_code, review_evidence_digest, applied_by_id
    ) VALUES (
        gen_random_uuid(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
        NEW.organization_id, NEW.id, 1, NULL, NEW.created_run_id,
        NEW.source_row_hash, NEW.transform_version, NEW.target_model_label,
        NEW.target_pk, NEW.state, NEW.reconciliation_status,
        NULL, NULL, NULL, '', '', NULL
    );
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION legacy_import_observation_integrity_guard()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    run_row record;
    version_row record;
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'legacy entity observation dəyişdirilə bilməz';
    END IF;
    SELECT run.organization_id, run.source_system, run.transform_version, run.status
      INTO run_row FROM public.legacy_import_legacymigrationrun AS run
     WHERE run.id = NEW.run_id FOR UPDATE;
    SELECT version.organization_id, version.entity_map_id,
           entity_map.source_system, version.source_row_hash,
           version.transform_version, version.target_model_label,
           version.target_pk, version.state, version.reconciliation_status
      INTO version_row
      FROM public.legacy_import_legacyentitymapversion AS version
      JOIN public.legacy_import_legacyentitymap AS entity_map
        ON entity_map.id = version.entity_map_id
     WHERE version.id = NEW.map_version_id FOR UPDATE OF version;
    IF run_row.organization_id IS NULL
       OR version_row.organization_id IS NULL
       OR run_row.status <> 'running'
       OR run_row.organization_id <> NEW.organization_id
       OR run_row.source_system <> version_row.source_system
       OR run_row.transform_version <> NEW.transform_version
       OR version_row.organization_id <> NEW.organization_id
       OR version_row.entity_map_id <> NEW.entity_map_id
       OR version_row.source_row_hash <> NEW.source_row_hash
       OR version_row.transform_version <> NEW.transform_version
       OR version_row.target_model_label <> NEW.target_model_label
       OR version_row.target_pk <> NEW.target_pk
       OR version_row.state <> NEW.state
       OR version_row.reconciliation_status <> NEW.reconciliation_status
    THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'legacy observation run və canonical version ilə uyğun deyil';
    END IF;
    RETURN NEW;
END;
$$;

ALTER TABLE public.legacy_import_legacyentitymapversion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.legacy_import_legacyentitymapversion FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_tenant_isolation ON public.legacy_import_legacyentitymapversion;
CREATE POLICY rls_tenant_isolation ON public.legacy_import_legacyentitymapversion
    USING (
        current_setting('app.bypass_rls', true) = 'on'
        OR organization_id::text = NULLIF(current_setting('app.current_org_id', true), '')
    )
    WITH CHECK (
        current_setting('app.bypass_rls', true) = 'on'
        OR organization_id::text = NULLIF(current_setting('app.current_org_id', true), '')
    );

CREATE TRIGGER legacy_import_version_integrity
BEFORE INSERT OR UPDATE ON public.legacy_import_legacyentitymapversion
FOR EACH ROW EXECUTE FUNCTION legacy_import_version_integrity_guard();
CREATE TRIGGER legacy_import_version_no_delete
BEFORE DELETE ON public.legacy_import_legacyentitymapversion
FOR EACH ROW EXECUTE FUNCTION legacy_import_delete_guard();
CREATE TRIGGER legacy_import_version_no_truncate
BEFORE TRUNCATE ON public.legacy_import_legacyentitymapversion
FOR EACH STATEMENT EXECUTE FUNCTION legacy_import_truncate_guard();
CREATE TRIGGER legacy_import_map_initial_version
AFTER INSERT ON public.legacy_import_legacyentitymap
FOR EACH ROW EXECUTE FUNCTION legacy_import_initial_version_create();
CREATE TRIGGER legacy_import_observation_integrity
BEFORE INSERT OR UPDATE ON public.legacy_import_legacyentityobservation
FOR EACH ROW EXECUTE FUNCTION legacy_import_observation_integrity_guard();

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'rls_app_role') THEN
        REVOKE TRUNCATE, REFERENCES, TRIGGER
          ON TABLE public.legacy_import_legacyentitymapversion FROM rls_app_role;
        GRANT SELECT, INSERT, UPDATE, DELETE
          ON TABLE public.legacy_import_legacyentitymapversion TO rls_app_role;
    END IF;
END;
$$;

REVOKE ALL ON FUNCTION legacy_import_issue_integrity_guard() FROM PUBLIC;
REVOKE ALL ON FUNCTION legacy_import_version_integrity_guard() FROM PUBLIC;
REVOKE ALL ON FUNCTION legacy_import_initial_version_create() FROM PUBLIC;
REVOKE ALL ON FUNCTION legacy_import_observation_integrity_guard() FROM PUBLIC;
"""


_REVERSE_GUARDS_SQL = r"""
DROP TRIGGER IF EXISTS legacy_import_observation_integrity
    ON public.legacy_import_legacyentityobservation;
DROP TRIGGER IF EXISTS legacy_import_map_initial_version
    ON public.legacy_import_legacyentitymap;
DROP TRIGGER IF EXISTS legacy_import_version_no_truncate
    ON public.legacy_import_legacyentitymapversion;
DROP TRIGGER IF EXISTS legacy_import_version_no_delete
    ON public.legacy_import_legacyentitymapversion;
DROP TRIGGER IF EXISTS legacy_import_version_integrity
    ON public.legacy_import_legacyentitymapversion;
DROP POLICY IF EXISTS rls_tenant_isolation
    ON public.legacy_import_legacyentitymapversion;
ALTER TABLE public.legacy_import_legacyentitymapversion NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.legacy_import_legacyentitymapversion DISABLE ROW LEVEL SECURITY;
DROP FUNCTION IF EXISTS legacy_import_observation_integrity_guard();
DROP FUNCTION IF EXISTS legacy_import_initial_version_create();
DROP FUNCTION IF EXISTS legacy_import_version_integrity_guard();

CREATE OR REPLACE FUNCTION legacy_import_issue_integrity_guard()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    run_row record;
    old_rank integer;
    new_rank integer;
BEGIN
    IF TG_OP = 'UPDATE' AND (
        NEW.id IS DISTINCT FROM OLD.id
        OR NEW.created_at IS DISTINCT FROM OLD.created_at
        OR NEW.organization_id IS DISTINCT FROM OLD.organization_id
        OR NEW.run_id IS DISTINCT FROM OLD.run_id
        OR NEW.source_table IS DISTINCT FROM OLD.source_table
        OR NEW.entity_type IS DISTINCT FROM OLD.entity_type
        OR NEW.legacy_pk IS DISTINCT FROM OLD.legacy_pk
        OR NEW.rule_code IS DISTINCT FROM OLD.rule_code
        OR NEW.payload_digest IS DISTINCT FROM OLD.payload_digest
    ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'legacy migration issue identity dəyişdirilə bilməz';
    END IF;
    SELECT run.organization_id, run.source_system, run.transform_version, run.status
      INTO run_row FROM public.legacy_import_legacymigrationrun AS run
     WHERE run.id = NEW.run_id FOR UPDATE;
    IF NOT FOUND OR run_row.organization_id <> NEW.organization_id THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'legacy migration issue run scope ilə uyğun deyil';
    END IF;
    IF TG_OP = 'INSERT' AND run_row.status <> 'running' THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'legacy migration issue yalnız running run-a yazıla bilər';
    END IF;
    IF NEW.entity_map_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM public.legacy_import_legacyentitymap AS entity_map
        JOIN public.legacy_import_legacyentityobservation AS observation
          ON observation.entity_map_id = entity_map.id AND observation.run_id = NEW.run_id
        WHERE entity_map.id = NEW.entity_map_id
          AND entity_map.organization_id = NEW.organization_id
          AND entity_map.source_system = run_row.source_system
          AND entity_map.transform_version = run_row.transform_version
          AND entity_map.entity_type = NEW.entity_type
          AND entity_map.legacy_pk = NEW.legacy_pk
    ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'legacy issue canonical entity observation ilə uyğun deyil';
    END IF;
    IF TG_OP = 'UPDATE' AND run_row.status <> 'running' AND (
        NEW.entity_map_id IS DISTINCT FROM OLD.entity_map_id
        OR NEW.severity IS DISTINCT FROM OLD.severity
        OR NEW.review_status IS NOT DISTINCT FROM OLD.review_status
    ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'terminal run issue-sunda yalnız review status dəyişə bilər';
    END IF;
    IF TG_OP = 'UPDATE' AND run_row.status = 'running'
       AND NEW.severity IS DISTINCT FROM OLD.severity THEN
        old_rank := CASE OLD.severity
            WHEN 'info' THEN 0 WHEN 'warning' THEN 1
            WHEN 'error' THEN 2 WHEN 'critical' THEN 3 ELSE -1 END;
        new_rank := CASE NEW.severity
            WHEN 'info' THEN 0 WHEN 'warning' THEN 1
            WHEN 'error' THEN 2 WHEN 'critical' THEN 3 ELSE -1 END;
        IF new_rank < old_rank OR NEW.review_status <> 'open' THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'legacy issue severity yalnız open escalation ola bilər';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION legacy_import_issue_integrity_guard() FROM PUBLIC;
"""


def _apply_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(_FORWARD_GUARDS_SQL)


def _revert_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(_REVERSE_GUARDS_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ("legacy_import", "0004_lifecycle_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_drop_v4_observation_guard, _restore_v4_observation_guard),
        migrations.CreateModel(
            name="LegacyEntityMapVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version_number", models.PositiveIntegerField()),
                (
                    "source_row_hash",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Dəyər kiçik hərfli 64 simvolluq SHA-256 hex digest olmalıdır.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "transform_version",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Yalnız kiçik hərf, rəqəm, nöqtə, alt xətt və defis istifadə edilə bilər.",
                                regex="^[a-z0-9][a-z0-9._-]*$",
                            )
                        ],
                    ),
                ),
                (
                    "target_model_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Target model etiketi app_label.model_name formatında olmalıdır.",
                                regex="^[a-z][a-z0-9_]*\\.[a-z][a-z0-9_]*$",
                            )
                        ],
                    ),
                ),
                (
                    "target_pk",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Açar yalnız opaque identifikator simvollarından ibarət olmalıdır.",
                                regex="^[A-Za-z0-9][A-Za-z0-9._:-]{0,254}$",
                            )
                        ],
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("migrated", "Miqrasiya edilib"),
                            ("skipped", "Buraxılıb"),
                            ("quarantined", "Quarantine"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reconciliation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("verified", "Təsdiqlənib"),
                            ("mismatch", "Uyğunsuzluq"),
                            ("not_applicable", "Tətbiq edilmir"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_reason_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Yalnız kiçik hərf, rəqəm, nöqtə, alt xətt və defis istifadə edilə bilər.",
                                regex="^[a-z0-9][a-z0-9._-]*$",
                            )
                        ],
                    ),
                ),
                (
                    "review_evidence_digest",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Dəyər kiçik hərfli 64 simvolluq SHA-256 hex digest olmalıdır.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["entity_map_id", "version_number"],
            },
        ),
        migrations.AddField(
            model_name="legacymigrationissue",
            name="review_evidence_digest",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Dəyər kiçik hərfli 64 simvolluq SHA-256 hex digest olmalıdır.", regex="^[0-9a-f]{64}$"
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="legacymigrationissue",
            name="review_reason_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Yalnız kiçik hərf, rəqəm, nöqtə, alt xətt və defis istifadə edilə bilər.",
                        regex="^[a-z0-9][a-z0-9._-]*$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="legacymigrationissue",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="legacymigrationissue",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_legacy_migration_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(_precheck_existing_issue_reviews, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="legacymigrationissue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("review_evidence_digest", ""),
                        ("review_reason_code", ""),
                        ("reviewed_at__isnull", True),
                        ("reviewed_by__isnull", True),
                    ),
                    models.Q(
                        ("review_evidence_digest__regex", "^[0-9a-f]{64}$"),
                        ("review_reason_code__regex", "^[a-z0-9][a-z0-9._-]*$"),
                        ("reviewed_at__isnull", False),
                        ("reviewed_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="legacy_issue_review_evidence_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacymigrationissue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("review_status", "open"),
                    models.Q(
                        ("review_evidence_digest__regex", "^[0-9a-f]{64}$"),
                        ("review_reason_code__regex", "^[a-z0-9][a-z0-9._-]*$"),
                        ("reviewed_at__isnull", False),
                        ("reviewed_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="legacy_issue_decision_has_review",
            ),
        ),
        migrations.AddField(
            model_name="legacyentitymapversion",
            name="applied_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applied_legacy_entity_remaps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="legacyentitymapversion",
            name="approved_issue",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_map_version",
                to="legacy_import.legacymigrationissue",
            ),
        ),
        migrations.AddField(
            model_name="legacyentitymapversion",
            name="entity_map",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="versions", to="legacy_import.legacyentitymap"
            ),
        ),
        migrations.AddField(
            model_name="legacyentitymapversion",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="legacy_entity_map_versions",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="legacyentitymapversion",
            name="recorded_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recorded_map_versions",
                to="legacy_import.legacymigrationrun",
            ),
        ),
        migrations.AddField(
            model_name="legacyentitymapversion",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_legacy_entity_map_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="legacyentitymapversion",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement_versions",
                to="legacy_import.legacyentitymapversion",
            ),
        ),
        migrations.AddField(
            model_name="legacyentityobservation",
            name="map_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="observations",
                to="legacy_import.legacyentitymapversion",
            ),
        ),
        migrations.AddIndex(
            model_name="legacyentitymapversion",
            index=models.Index(fields=["organization", "recorded_run"], name="legacy_ver_org_run"),
        ),
        migrations.AddConstraint(
            model_name="legacyentitymapversion",
            constraint=models.UniqueConstraint(fields=("entity_map", "version_number"), name="legacy_ver_map_no_uniq"),
        ),
        migrations.AddConstraint(
            model_name="legacyentitymapversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version_number__gte", 1)), name="legacy_ver_number_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="legacyentitymapversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_row_hash__regex", "^[0-9a-f]{64}$")), name="legacy_ver_row_sha_hex"
            ),
        ),
        migrations.AddConstraint(
            model_name="legacyentitymapversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("transform_version__regex", "^[a-z0-9][a-z0-9._-]*$")),
                name="legacy_ver_transform_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacyentitymapversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("target_model_label", ""),
                    ("target_model_label__regex", "^[a-z][a-z0-9_]*\\.[a-z][a-z0-9_]*$"),
                    _connector="OR",
                ),
                name="legacy_ver_model_label",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacyentitymapversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("target_pk", ""), ("target_pk__regex", "^[A-Za-z0-9][A-Za-z0-9._:-]{0,254}$"), _connector="OR"
                ),
                name="legacy_ver_target_pk_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacyentitymapversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("state", "migrated"),
                        models.Q(("target_model_label", ""), _negated=True),
                        models.Q(("target_pk", ""), _negated=True),
                    ),
                    models.Q(("state__in", ["skipped", "quarantined"]), ("target_model_label", ""), ("target_pk", "")),
                    _connector="OR",
                ),
                name="legacy_ver_target_by_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacyentitymapversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["migrated", "skipped", "quarantined"])),
                name="legacy_ver_state_choice",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacyentitymapversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reconciliation_status__in", ["pending", "verified", "mismatch", "not_applicable"])
                ),
                name="legacy_ver_recon_choice",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacyentitymapversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("applied_by__isnull", True),
                        ("approved_issue__isnull", True),
                        ("review_evidence_digest", ""),
                        ("review_reason_code", ""),
                        ("reviewed_at__isnull", True),
                        ("reviewed_by__isnull", True),
                        ("supersedes__isnull", True),
                        ("version_number", 1),
                    ),
                    models.Q(
                        ("applied_by__isnull", False),
                        ("approved_issue__isnull", False),
                        ("review_evidence_digest__regex", "^[0-9a-f]{64}$"),
                        ("review_reason_code__regex", "^[a-z0-9][a-z0-9._-]*$"),
                        ("reviewed_at__isnull", False),
                        ("reviewed_by__isnull", False),
                        ("supersedes__isnull", False),
                        ("version_number__gt", 1),
                    ),
                    _connector="OR",
                ),
                name="legacy_ver_review_shape",
            ),
        ),
        migrations.RunPython(_backfill_initial_versions, _remove_backfilled_versions),
        migrations.AlterField(
            model_name="legacyentityobservation",
            name="map_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="observations",
                to="legacy_import.legacyentitymapversion",
            ),
        ),
        migrations.RunPython(_apply_guards, _revert_guards),
        migrations.RunPython(migrations.RunPython.noop, _assert_no_reviewed_remaps),
    ]
