# Generated by Django 5.2.8 on 2026-02-13 20:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("university", "University"),
                            ("school", "School"),
                            ("course_center", "Course Center"),
                            ("individual", "Individual"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="org_logos/"),
                ),
                ("description", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("enabled_apps", models.JSONField(blank=True, default=list)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrgUnit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("rectorate", "Rectorate"),
                            ("vice_rectorate", "Vice Rectorate"),
                            ("faculty", "Faculty"),
                            ("deanery", "Deanery"),
                            ("chair", "Chair"),
                            ("department", "Department"),
                            ("lab", "Laboratory"),
                            ("institute", "Institute"),
                            ("center", "Center"),
                            ("directorate", "Directorate"),
                            ("section", "Section"),
                            ("parallel", "Parallel"),
                            ("class", "Class"),
                            ("grade_level", "Grade Level"),
                            ("branch", "Branch"),
                            ("division", "Division"),
                            ("group", "Group"),
                            ("classroom", "Classroom"),
                            ("unit", "Unit"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=50)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("level", models.PositiveIntegerField(db_index=True, default=0)),
                ("path", models.CharField(blank=True, db_index=True, max_length=1000)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="organizations.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="organizations.orgunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizational Unit",
                "verbose_name_plural": "Organizational Units",
                "ordering": ["organization", "path", "order"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("level", models.PositiveIntegerField(db_index=True, default=50)),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("organization", "Organization-wide"),
                            ("unit", "Unit-specific"),
                            ("course", "Course-specific"),
                        ],
                        max_length=50,
                    ),
                ),
                ("permissions", models.JSONField(blank=True, default=list)),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["-level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("employee_id", models.CharField(blank=True, max_length=50)),
                ("is_primary", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organizations.organization",
                    ),
                ),
                (
                    "scope_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organizations.orgunit",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organizations.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
                "ordering": ["-is_primary", "role__level"],
            },
        ),
        migrations.CreateModel(
            name="AcademicPeriod",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("semester", "Semester"),
                            ("trimester", "Trimester"),
                            ("quarter", "Quarter"),
                            ("year", "Year"),
                            ("term", "Term"),
                        ],
                        max_length=20,
                    ),
                ),
                ("academic_year", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_periods",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Period",
                "verbose_name_plural": "Academic Periods",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-start_date"],
                        name="organizatio_organiz_655adc_idx",
                    ),
                    models.Index(
                        fields=["organization", "is_current"],
                        name="organizatio_organiz_a61403_idx",
                    ),
                ],
                "unique_together": {("organization", "name", "academic_year")},
            },
        ),
        migrations.AddIndex(
            model_name="orgunit",
            index=models.Index(
                fields=["organization", "unit_type"],
                name="organizatio_organiz_c7fd85_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orgunit",
            index=models.Index(
                fields=["organization", "parent"], name="organizatio_organiz_5303a2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orgunit",
            unique_together={("organization", "slug")},
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["organization", "-level"], name="organizatio_organiz_4831d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["organization", "is_active"],
                name="organizatio_organiz_e166c4_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["user", "organization"], name="organizatio_user_id_a85932_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["organization", "role"], name="organizatio_organiz_130fbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["user", "is_primary"], name="organizatio_user_id_3055f4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("user", "organization", "role", "scope_unit")},
        ),
    ]
