# Generated by Django 5.2.12 on 2026-03-24 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=2, unique=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("university", "university"),
                            ("school", "school"),
                            ("course_center", "course_center"),
                            ("individual", "individual"),
                        ],
                        max_length=50,
                    ),
                ),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                (
                    "organization_identifier",
                    models.CharField(blank=True, default="", help_text="organization_identifier", max_length=120),
                ),
                (
                    "license_identifier",
                    models.CharField(blank=True, default="", help_text="license_identifier", max_length=120),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="org_logos/")),
                ("description", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("enabled_apps", models.JSONField(blank=True, default=list)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("pending", "pending"), ("suspended", "suspended")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("suspension_reason", models.TextField(blank=True, default="")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrgUnit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("rectorate", "rectorate"),
                            ("vice_rectorate", "vice_rectorate"),
                            ("faculty", "faculty"),
                            ("deanery", "deanery"),
                            ("chair", "chair"),
                            ("department", "department"),
                            ("lab", "laboratory"),
                            ("institute", "institute"),
                            ("center", "center"),
                            ("directorate", "directorate"),
                            ("section", "section"),
                            ("parallel", "parallel"),
                            ("class", "class"),
                            ("grade_level", "grade_level"),
                            ("branch", "branch"),
                            ("division", "division"),
                            ("group", "group"),
                            ("classroom", "classroom"),
                            ("unit", "unit"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=50)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("level", models.PositiveIntegerField(db_index=True, default=0)),
                ("path", models.CharField(blank=True, db_index=True, max_length=1000)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="organizations.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="organizations.orgunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["organization", "path", "order"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("level", models.PositiveIntegerField(db_index=True, default=50)),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("organization", "Organization-wide"),
                            ("unit", "Unit-specific"),
                            ("course", "Course-specific"),
                        ],
                        max_length=50,
                    ),
                ),
                ("permissions", models.JSONField(blank=True, default=list)),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["-level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=100)),
                ("employee_id", models.CharField(blank=True, max_length=50)),
                ("is_primary", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organizations.organization",
                    ),
                ),
                (
                    "scope_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organizations.orgunit",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="organizations.role"
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["-is_primary", "role__level"],
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("school", "school"),
                            ("university", "university"),
                            ("course_center", "course_center"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, default="", max_length=120)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institutions",
                        to="organizations.country",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["country", "institution_type", "is_active"], name="org_inst_country_type_idx")
                ],
                "unique_together": {("country", "institution_type", "name")},
            },
        ),
        migrations.CreateModel(
            name="AcademicPeriod",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("semester", "Semester"),
                            ("trimester", "Trimester"),
                            ("quarter", "Quarter"),
                            ("year", "Year"),
                            ("term", "Term"),
                        ],
                        max_length=20,
                    ),
                ),
                ("academic_year", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_periods",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(fields=["organization", "-start_date"], name="organizatio_organiz_655adc_idx"),
                    models.Index(fields=["organization", "is_current"], name="organizatio_organiz_a61403_idx"),
                ],
                "unique_together": {("organization", "name", "academic_year")},
            },
        ),
        migrations.AddIndex(
            model_name="orgunit",
            index=models.Index(fields=["organization", "unit_type"], name="organizatio_organiz_c7fd85_idx"),
        ),
        migrations.AddIndex(
            model_name="orgunit",
            index=models.Index(fields=["organization", "parent"], name="organizatio_organiz_5303a2_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="orgunit",
            unique_together={("organization", "slug")},
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["organization", "-level"], name="organizatio_organiz_4831d9_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["organization", "is_active"], name="organizatio_organiz_e166c4_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["user", "organization"], name="organizatio_user_id_a85932_idx"),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["organization", "role"], name="organizatio_organiz_130fbf_idx"),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["user", "is_primary"], name="organizatio_user_id_3055f4_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("user", "organization", "role", "scope_unit")},
        ),
    ]
