# Generated by Django 5.2.8 on 2026-02-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="organization",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("pending", "Pending"), ("suspended", "Suspended")],
                default="active",
                max_length=20,
            ),
        ),
    ]
