# Generated by Django 5.2.8 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_country_organization_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="license_identifier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Lisenziya/VÖEN və ya əlavə identifikator",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="organization_identifier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Rəsmi təşkilat kodu/nömrəsi (məktəb və universitet üçün)",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="suspension_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
