# Generated by Django 5.2.8 on 2026-02-19

import django.db.models.deletion
from django.db import migrations, models


def seed_azerbaijan_institutions(apps, schema_editor):
    Country = apps.get_model("organizations", "Country")
    Institution = apps.get_model("organizations", "Institution")

    az, _ = Country.objects.get_or_create(code="AZ", defaults={"name": "Azerbaijan", "is_active": True})

    institutions = [
        ("school", "School No. 20", "SCH-020"),
        ("school", "School No. 132", "SCH-132"),
        ("school", "School-Lyceum No. 6", "SCH-006"),
        ("university", "Baku State University", "UNI-BSU"),
        ("university", "ADA University", "UNI-ADA"),
        ("university", "Azerbaijan Technical University", "UNI-AZTU"),
        ("course_center", "Code Academy", "CC-CODE"),
        ("course_center", "Step IT Academy Baku", "CC-STEP"),
    ]

    for institution_type, name, code in institutions:
        Institution.objects.get_or_create(
            country=az,
            institution_type=institution_type,
            name=name,
            defaults={"code": code, "is_active": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_organization_identifiers_and_suspension"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=2, unique=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("school", "School"),
                            ("university", "University"),
                            ("course_center", "Course Center"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, default="", max_length=120)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institutions",
                        to="organizations.country",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("country", "institution_type", "name")},
            },
        ),
        migrations.AddIndex(
            model_name="institution",
            index=models.Index(fields=["country", "institution_type", "is_active"], name="org_inst_country_type_idx"),
        ),
        migrations.RunPython(seed_azerbaijan_institutions, migrations.RunPython.noop),
    ]
