# Generated by Django 5.2.8 on 2026-03-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_seed_additional_azerbaijan_universities"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academicperiod",
            options={"ordering": ["-start_date"], "verbose_name": "singular", "verbose_name_plural": "plural"},
        ),
        migrations.AlterModelOptions(
            name="membership",
            options={
                "ordering": ["-is_primary", "role__level"],
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={"ordering": ["name"], "verbose_name": "singular", "verbose_name_plural": "plural"},
        ),
        migrations.AlterModelOptions(
            name="orgunit",
            options={
                "ordering": ["organization", "path", "order"],
                "verbose_name": "singular",
                "verbose_name_plural": "plural",
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ["-level", "name"], "verbose_name": "singular", "verbose_name_plural": "plural"},
        ),
        migrations.AlterField(
            model_name="institution",
            name="institution_type",
            field=models.CharField(
                choices=[("school", "school"), ("university", "university"), ("course_center", "course_center")],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="license_identifier",
            field=models.CharField(blank=True, default="", help_text="license_identifier", max_length=120),
        ),
        migrations.AlterField(
            model_name="organization",
            name="org_type",
            field=models.CharField(
                choices=[
                    ("university", "university"),
                    ("school", "school"),
                    ("course_center", "course_center"),
                    ("individual", "individual"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="organization_identifier",
            field=models.CharField(blank=True, default="", help_text="organization_identifier", max_length=120),
        ),
        migrations.AlterField(
            model_name="organization",
            name="status",
            field=models.CharField(
                choices=[("active", "active"), ("pending", "pending"), ("suspended", "suspended")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orgunit",
            name="unit_type",
            field=models.CharField(
                choices=[
                    ("rectorate", "rectorate"),
                    ("vice_rectorate", "vice_rectorate"),
                    ("faculty", "faculty"),
                    ("deanery", "deanery"),
                    ("chair", "chair"),
                    ("department", "department"),
                    ("lab", "laboratory"),
                    ("institute", "institute"),
                    ("center", "center"),
                    ("directorate", "directorate"),
                    ("section", "section"),
                    ("parallel", "parallel"),
                    ("class", "class"),
                    ("grade_level", "grade_level"),
                    ("branch", "branch"),
                    ("division", "division"),
                    ("group", "group"),
                    ("classroom", "classroom"),
                    ("unit", "unit"),
                ],
                max_length=50,
            ),
        ),
    ]
