# Generated by Django 5.2.15 on 2026-07-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0012_rls_text_extraction_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgunit",
            name="unit_type",
            field=models.CharField(
                choices=[
                    ("rectorate", "rectorate"),
                    ("vice_rectorate", "vice_rectorate"),
                    ("faculty", "faculty"),
                    ("deanery", "deanery"),
                    ("chair", "chair"),
                    ("department", "department"),
                    ("specialty", "specialty"),
                    ("lab", "laboratory"),
                    ("institute", "institute"),
                    ("center", "center"),
                    ("directorate", "directorate"),
                    ("section", "section"),
                    ("parallel", "parallel"),
                    ("class", "class"),
                    ("grade_level", "grade_level"),
                    ("branch", "branch"),
                    ("division", "division"),
                    ("group", "group"),
                    ("classroom", "classroom"),
                    ("unit", "unit"),
                ],
                max_length=50,
            ),
        ),
    ]
