# Generated by Django 5.2.15 on 2026-07-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0013_alter_orgunit_unit_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicperiod",
            name="exam_session_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="academicperiod",
            name="exam_session_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="academicperiod",
            name="registration_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="academicperiod",
            name="registration_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
