# Generated by Django 5.2.17 on 2026-09-03 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0039_seed_student_services_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="academicperiod",
            name="lock_reason",
            field=models.TextField(blank=True, help_text="Kilid / kilidin açılması səbəbi (≥20 simvol)."),
        ),
        migrations.AddField(
            model_name="academicperiod",
            name="locked_at",
            field=models.DateTimeField(blank=True, help_text="Semestrin kilidləndiyi an.", null=True),
        ),
        migrations.AddField(
            model_name="academicperiod",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_periods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="academicperiod",
            name="opening_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Başlanmayıb"),
                    ("generated", "Plandan açılış yaradıldı"),
                    ("sent", "Kafedraya göndərildi"),
                    ("locked", "Semestr kilidləndi"),
                ],
                db_index=True,
                default="not_started",
                help_text="Semestr açılışının mərhələsi (plandan yaradıldı → kafedraya göndərildi → kilidləndi).",
                max_length=16,
            ),
        ),
    ]
