# Generated by Django 5.2.17 on 2026-09-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0042_seed_rim_staff_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunit",
            name="is_service_unit",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
