# Generated by Django 5.2.17 on 2026-10-05 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0056_system_monitoring_view_permission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Tutum testi 2026-10-05: yalnız indekslər silinir. Django-nun FK `db_index`
    # dəyişikliyi FK məhdudiyyətini silib yenidən əlavə edir (bütün cədvəl yoxlaması) —
    # bu lazımsızdır, ona görə DB tərəfi xam DROP INDEX, state tərəfi isə avtomatik
    # əməliyyatlardır.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "organizatio_user_id_a85932_idx";\nDROP INDEX IF EXISTS "organizations_membership_assigned_by_id_839ca3bc";\nDROP INDEX IF EXISTS "organizations_membership_is_active_2be0c227";\nDROP INDEX IF EXISTS "organizations_membership_is_primary_6aa61fb0";\nDROP INDEX IF EXISTS "organizations_membership_organization_id_6889aa64";\nDROP INDEX IF EXISTS "organizations_membership_user_id_a8e72055";',
                    reverse_sql="CREATE INDEX IF NOT EXISTS organizatio_user_id_a85932_idx ON public.organizations_membership USING btree (user_id, organization_id);\nCREATE INDEX IF NOT EXISTS organizations_membership_assigned_by_id_839ca3bc ON public.organizations_membership USING btree (assigned_by_id);\nCREATE INDEX IF NOT EXISTS organizations_membership_is_active_2be0c227 ON public.organizations_membership USING btree (is_active);\nCREATE INDEX IF NOT EXISTS organizations_membership_is_primary_6aa61fb0 ON public.organizations_membership USING btree (is_primary);\nCREATE INDEX IF NOT EXISTS organizations_membership_organization_id_6889aa64 ON public.organizations_membership USING btree (organization_id);\nCREATE INDEX IF NOT EXISTS organizations_membership_user_id_a8e72055 ON public.organizations_membership USING btree (user_id);",
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name="membership",
                    name="organizatio_user_id_a85932_idx",
                ),
                migrations.AlterField(
                    model_name="membership",
                    name="assigned_by",
                    field=models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.AlterField(
                    model_name="membership",
                    name="is_active",
                    field=models.BooleanField(default=True),
                ),
                migrations.AlterField(
                    model_name="membership",
                    name="is_primary",
                    field=models.BooleanField(default=False),
                ),
                migrations.AlterField(
                    model_name="membership",
                    name="organization",
                    field=models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organizations.organization",
                    ),
                ),
                migrations.AlterField(
                    model_name="membership",
                    name="user",
                    field=models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
