# Generated by Django 5.2.14 on 2026-06-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appeals", "0002_scoreadjustment_previous_answer_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appeal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Gözləyir"),
                    ("under_review", "Baxılır"),
                    ("accepted", "Qəbul edildi"),
                    ("rejected", "Rədd edildi"),
                    ("partially_accepted", "Qismən qəbul edildi"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="appealitem",
            name="appeal_type",
            field=models.CharField(
                choices=[
                    ("wrong_question", "Sual səhvdir"),
                    ("wrong_answer_key", "Cavab açarı səhvdir"),
                    ("unclear_question", "Sual aydın deyil"),
                    ("out_of_syllabus", "Proqramdan kənardır"),
                    ("technical_issue", "Texniki problem"),
                    ("grading_issue", "Qiymətləndirmə səhvi"),
                    ("other", "Digər"),
                ],
                max_length=30,
                verbose_name="appeal_type",
            ),
        ),
        migrations.AlterField(
            model_name="appealitem",
            name="status",
            field=models.CharField(
                choices=[("pending", "Gözləyir"), ("accepted", "Qəbul edildi"), ("rejected", "Rədd edildi")],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
