name: 🚀 CI Pipeline

on:
  pull_request:
    branches:
      - main
      - Staging
      - Develop
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
      - Staging
      - Develop
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/_lint.yml
    with:
      python-version: "3.11.6"

  build:
    needs: lint
    uses: ./.github/workflows/_build.yml
    with:
      python-version: "3.11.6"

  security:
    needs: lint
    uses: ./.github/workflows/_security.yml
    with:
      python-version: "3.11.6"
