# Generated by Django 5.2.12 on 2026-03-24 23:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentorganizationrequest",
            name="role_type",
            field=models.CharField(
                choices=[("student", "Student"), ("teacher", "Teacher"), ("staff", "Staff")],
                db_index=True,
                default="student",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="inappnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("assignment", "Assignment"),
                    ("exam", "Exam"),
                    ("grade", "Grade / Feedback"),
                    ("system", "System / Admin"),
                    ("course", "Course"),
                    ("live_exam", "Live Exam / Session"),
                    ("approval", "Membership / Approval Request"),
                ],
                db_index=True,
                default="system",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="studentorganizationrequest",
            index=models.Index(fields=["organization", "role_type", "status"], name="notificatio_organiz_278c6d_idx"),
        ),
    ]
