# Generated by Django 5.2.17 on 2026-09-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_inappnotification_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inappnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("assignment", "Assignment"),
                    ("exam", "Exam"),
                    ("grade", "Grade / Feedback"),
                    ("system", "System / Admin"),
                    ("course", "Course"),
                    ("live_exam", "Live Exam / Session"),
                    ("approval", "Membership / Approval Request"),
                    ("application", "Application / Request"),
                ],
                db_index=True,
                default="system",
                max_length=20,
            ),
        ),
    ]
