# Generated by Django 5.2.8 on 2026-01-27 22:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0004_remove_course_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Lab Adı")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Lab işinin təsviri, tələblər və s.",
                        verbose_name="Təsvir",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        help_text="Bu tarixdən sonra tələbələr labı görə bilər",
                        verbose_name="Başlanğıc tarixi",
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        help_text="Bu tarixdən sonra göndəriş qəbul olunmur",
                        verbose_name="Son tarix (Deadline)",
                    ),
                ),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Maksimum bal"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Yayımlandı"),
                            ("archived", "Arxivləndi"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "allow_late_submission",
                    models.BooleanField(
                        default=False, verbose_name="Gecikmiş göndərişə icazə ver"
                    ),
                ),
                (
                    "late_penalty_percent",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Hər gün üçün neçə % çıxılsın",
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Gecikmə cəzası (%)",
                    ),
                ),
                (
                    "teacher_files",
                    models.FileField(
                        blank=True,
                        help_text="PDF, ZIP, DOC və s.",
                        null=True,
                        upload_to="labs/teacher_files/%Y/%m/",
                        verbose_name="Müəllim faylı",
                    ),
                ),
                (
                    "teacher_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Tələbələr üçün əlavə təlimat (text formatında)",
                        verbose_name="Müəllim təlimatları",
                    ),
                ),
                (
                    "allow_file_upload",
                    models.BooleanField(
                        default=True, verbose_name="Fayl yükləməyə icazə"
                    ),
                ),
                (
                    "allow_link_submission",
                    models.BooleanField(
                        default=True, verbose_name="Link göndərməyə icazə"
                    ),
                ),
                (
                    "allowed_extensions",
                    models.CharField(
                        default="zip,pdf,docx,png,jpg,txt,py,java,cpp",
                        help_text="Vergüllə ayırın: zip,pdf,docx",
                        max_length=255,
                        verbose_name="İcazə verilən fayl tipləri",
                    ),
                ),
                (
                    "max_file_size_mb",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Maks fayl ölçüsü (MB)"
                    ),
                ),
                (
                    "questions_per_student",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 = bütün suallar, >0 = random seçim",
                        verbose_name="Hər tələbəyə düşən sual sayı",
                    ),
                ),
                (
                    "allowed_groups",
                    models.TextField(
                        blank=True,
                        help_text="Vergüllə ayırın: 850,860. Boş = bütün kurs",
                        verbose_name="İcazəli qruplar",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labs",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_labs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab İşi",
                "verbose_name_plural": "Lab İşləri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='Məs: "Asan suallar", "Orta", "Çətin"',
                        max_length=255,
                        verbose_name="Blok adı",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Blok təsviri"),
                ),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Sıra")),
                (
                    "questions_to_pick",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 = bütün suallar",
                        verbose_name="Bu blokdan seçiləcək sual sayı",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="labs.lab",
                        verbose_name="Lab",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sual Bloku",
                "verbose_name_plural": "Sual Blokları",
                "ordering": ["lab", "order"],
            },
        ),
        migrations.CreateModel(
            name="LabQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_number",
                    models.PositiveIntegerField(default=1, verbose_name="Sual nömrəsi"),
                ),
                ("question_text", models.TextField(verbose_name="Sual mətni")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="labs/questions/%Y/%m/",
                        verbose_name="Əlavə fayl",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 = bərabər paylanacaq",
                        verbose_name="Bal",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="labs.labblock",
                        verbose_name="Blok",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Sualı",
                "verbose_name_plural": "Lab Sualları",
                "ordering": ["block", "question_number"],
            },
        ),
        migrations.CreateModel(
            name="LabAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="labs.lab",
                        verbose_name="Lab",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tələbə",
                    ),
                ),
                (
                    "assigned_questions",
                    models.ManyToManyField(
                        related_name="assignments",
                        to="labs.labquestion",
                        verbose_name="Təyin olunan suallar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Təyinatı",
                "verbose_name_plural": "Lab Təyinatları",
                "unique_together": {("lab", "student")},
            },
        ),
        migrations.CreateModel(
            name="LabSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_text",
                    models.TextField(
                        blank=True,
                        help_text="Əlavə qeyd, izahat",
                        verbose_name="Cavab mətni",
                    ),
                ),
                (
                    "submission_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="labs/submissions/%Y/%m/",
                        verbose_name="Fayl",
                    ),
                ),
                (
                    "submission_link",
                    models.URLField(
                        blank=True,
                        help_text="GitHub, Google Drive, Figma və s.",
                        verbose_name="Link",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Göndərilib"),
                            ("late", "Gecikmiş"),
                            ("graded", "Qiymətləndirilib"),
                            ("returned", "Qaytarıldı"),
                        ],
                        default="submitted",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Qiymət",
                    ),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="Müəllim rəyi")),
                (
                    "graded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Qiymətləndirmə tarixi"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt_number",
                    models.PositiveIntegerField(default=1, verbose_name="Cəhd nömrəsi"),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="labs.labassignment",
                        verbose_name="Təyinat",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_lab_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Qiymətləndirən",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Cavabı",
                "verbose_name_plural": "Lab Cavabları",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
