# Generated by Django 5.2.8 on 2026-01-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="allowed_students",
            field=models.TextField(
                blank=True,
                help_text="Vergüllə ayrılmış tələbə ID-ləri. Boş = qrup filtri istifadə olunur",
                verbose_name="İcazəli tələbələr (ID)",
            ),
        ),
    ]
