# Generated by Django 5.2.8 on 2026-01-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0003_labanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="max_attempts",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Tələbə neçə dəfə göndərə bilər",
                verbose_name="Maksimum cəhd sayı",
            ),
        ),
    ]
