# Generated by Django 5.2.8 on 2026-01-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0004_lab_max_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="labanswer",
            name="answer_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="labs/answers/%Y/%m/",
                verbose_name="Cavab faylı",
            ),
        ),
    ]
