# Generated by Django 5.2.8 on 2026-01-29 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0005_labanswer_answer_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="labanswer",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="labanswer",
            name="attempt_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="labanswer",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="labs.labsubmission",
            ),
        ),
        migrations.AlterField(
            model_name="labanswer",
            name="answer_file",
            field=models.FileField(
                blank=True, null=True, upload_to="labs/answers/%Y/%m/"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="labanswer",
            unique_together={("lab", "question", "student", "attempt_number")},
        ),
    ]
